- connect-widget/app/package-lock.json
- connect-widget/app/package.json
Add missing env-cmd to connect widget's `package.json`
> Add missing `env-cmd`

- api/app/src/shared/constants.ts
Fix build by enabling Garmin
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1672177347287219
> Fix compilation by enabling Garmin on the API

- api/app/src/command/webhook/count-failed.ts
- api/app/src/command/webhook/retry-failed.ts
- api/app/src/command/webhook/webhook.ts
- api/app/src/routes/settings.ts
Ticket: #43
- Downstream: https://github.com/metriport/metriport-internal/pull/157
Add webhook request info and retry.
> Add webhook request info and retry

- api/app/src/routes/settings.ts
- docs/mint.json
- docs/settings/get-settings.mdx
- docs/settings/get-webhook.mdx
- docs/settings/post-settings.mdx
- docs/settings/retry-webhook.mdx
Ticket: #43
- Upstream: https://github.com/metriport/metriport-internal/pull/157
- Downstream: https://github.com/metriport/metriport/pull/17
Remove unused `SettingsDTO`` properties that were left there for the release
> Remove unused properties from `SettingsDTO`

- deploy.sh
- package.json
Ticket: #167
N/A
Update build script to consider first-time checkout + deploy
N/A
> Update build script to consider first-time checkout + deploy #167

- api/app/src/mappings/garmin/body-composition.ts
- api/app/src/mappings/garmin/hrv.ts
- api/app/src/mappings/garmin/index.ts
- api/app/src/mappings/garmin/user.ts
- api/app/src/routes/webhook/garmin.ts
- pkgs/packages/api/src/models/biometrics.ts
- Upstream: https://github.com/metriport/metriport/pull/18
- Add Garmin Biometrics and HRV
- Fixes bug/leftover that added non-existing property to Garmin > Body
- anytime
> Garmin Biometrics and HRV

- api/app/src/mappings/garmin/bloodPressure.ts
- api/app/src/mappings/garmin/index.ts
- api/app/src/routes/webhook/garmin.ts
- Upstream: https://github.com/metriport/metriport/pull/19
- Downstream: https://github.com/metriport/metriport/pull/23
Adds Garmin BloodPressure
- anytime
> Adds Garmin BloodPressure

- pkgs/packages/api/src/models/common/respiration.ts
- pkgs/packages/api/src/models/user.ts
- Upstream: https://github.com/metriport/metriport/pull/20
- Downstream: https://github.com/metriport/metriport/pull/24
Add `samples` to SDK's `Respiration`
> Add samples to SDK Respiration

- docs/more-info/our-integrations.mdx
- Upstream: https://github.com/metriport/metriport/pull/24
Add basic info about Garmin integration
- anytime
> Add basic Garmin info on docs

- api/lambdas/garmin/index.js
Ticket: #118
N/A
Update default response to Garmin to 200 - Garmin will ping us periodically to check if our endpoints work with no UAT, need to not 401 in these cases.
ASAP to staging
> Update default response to Garmin to 200 #118

- .github/workflows/_reusable_deploy.yml
- .github/workflows/api_deploy-prod.yml
- .github/workflows/api_deploy-staging.yml
- README.md
- deploy.sh
- infra/config/.gitignore
- infra/config/example.ts
- infra/lib/api-stack.ts
- infra/lib/env-type.ts
Ticket: https://github.com/metriport/metriport-internal/issues/92
- Add infra env config file
- Rename `prod` to `production` config name
- Update README
Upcoming: update README about CI/CD
asap
> Add infra env config file

- api/app/src/default-error-handler.ts
- api/app/src/providers/withings.ts
- api/app/src/routes/user.ts
- docs/more-info/our-integrations.mdx
- docs/user/revoke-provider-access.mdx
Ticket: #249
N/A
Provider revoke fixes, Garmin is TODO
ASAP
> Provider revoke fixes #249

- docs/settings/get-settings.mdx
- docs/settings/get-webhook.mdx
- docs/settings/post-settings.mdx
- docs/settings/retry-webhook.mdx
- docs/user/create-user.mdx
- docs/user/revoke-provider-access.mdx
- pkgs/lerna.json
- pkgs/package-lock.json
- pkgs/packages/api/package.json
- pkgs/packages/api/src/client/metriport.ts
- pkgs/packages/api/src/client/models/settings-response.ts
- pkgs/packages/api/src/client/models/webhook-status-response.ts
- pkgs/packages/api/src/index.ts
Ticket: #250
N/A
Update sdk & docs to be in sync with the OSS API 
ASAP
> Update sdk & docs to be in sync with the OSS API #250

- connect-widget/app/src/pages/connect/components/connect-button.tsx
Ticket: 252
Add checkmark on mobile when connected to provider
ASAP
> 252 add checkmark when connected mobile

- README.md
- docs/getting-started/connect-quickstart.mdx
- docs/getting-started/connect-widget.mdx
Ticket: #258
N/A
Update docs for mobile Connect Widget implementation examples
ASAP
> Update docs for mobile implementation examples #258

- pkgs/package-lock.json
- pkgs/packages/api/README.md
- pkgs/packages/commonwell-jwt-maker/README.md
- pkgs/packages/commonwell-jwt-maker/__tests__/commonwell-sdk.test.js
- pkgs/packages/commonwell-jwt-maker/package.json
- pkgs/packages/commonwell-jwt-maker/src/index.ts
- pkgs/packages/commonwell-jwt-maker/tsconfig.json
- pkgs/packages/commonwell-sdk/README.md
- pkgs/packages/commonwell-sdk/src/index.ts
Ticket: metriport/metriport-internal#222
N/A
Add cw jwt maker tool
Anytime
> Add cw jwt maker tool #222

- pkgs/packages/api/src/models/common/provider-source.ts
Ticket: #176
- Upstream: The apple OSS change on branch 176_add_apple_health
Add apple to provider source (Minor change)
ASAP
> 176 add apple to provider source

- docs/getting-started/connect-quickstart.mdx
- docs/mint.json
- docs/more-info/api-keys.mdx
- docs/more-info/iOS.mdx
- infra/lib/api-stack.ts
Ticket: metriport/metriport-internal#274
N/A
add api key docs for client/secret keys + apple webhooks route fix
anytime
> docs: add api key docs for client/secret keys

- packages/packages/api/src/models/common/provider-source.ts
Ticket: 176
add google to provider source
ASAP
> fix(google): add google to provider source

- api/app/src/providers/apple.ts
- api/app/src/routes/user.ts
- docs/user/revoke-provider-access.mdx
Ticket: [#305](https://github.com/metriport/metriport-internal/issues/305)
Add apple to revoke token route
ASAP
> fix(apple): add revoke route for token

- infra/.eslintignore
- infra/.eslintrc.js
- infra/.gitignore
- infra/bin/infrastructure.ts
- infra/lib/api-stack.ts
- infra/lib/connect-widget-stack.ts
- infra/lib/env-config.ts
- infra/package-lock.json
- infra/package.json
Ref https://github.com/metriport/metriport-internal/issues/143
- Upstream: https://github.com/metriport/metriport/pull/59
- Downstream: https://github.com/metriport/metriport/pull/61
Add ESLint to infra
- anytime
> Add ESLint to infra

- infra/lib/api-stack.ts
Ticket: metriport/metriport-internal#310
N/A
Add performance alarming to DBs.
Anytime.
> chore(infra): add alarming to dbs

- api/app/src/providers/fitbit.ts
- api/app/src/providers/oauth2.ts
- api/app/src/providers/oura.ts
- api/app/src/providers/whoop.ts
- api/app/src/providers/withings.ts
Ticket: #[313](https://github.com/metriport/metriport-internal/issues/313)
Refresh token error withings
ASAP
> fix(api): fix refresh token withings

- api/app/src/mappings/oura/sleep.ts
- api/app/src/mappings/whoop/models/sleep.ts
- api/app/src/mappings/whoop/sleep.ts
- api/app/src/mappings/withings/models/activity.ts
- api/app/src/mappings/withings/models/heart-rate.ts
- api/app/src/mappings/withings/models/workouts.ts
- api/app/src/providers/withings.ts
- api/app/src/routes/index.ts
Ticket: #[313](https://github.com/metriport/metriport-internal/issues/313)
Sanity check withings
ASAP
> 313 fix withings

- packages/packages/commonwell-cert-runner/src/index.ts
- packages/packages/commonwell-cert-runner/src/patient-management.ts
- packages/packages/commonwell-cert-runner/src/payloads.ts
- packages/packages/commonwell-cert-runner/src/person-management.ts
- packages/packages/commonwell-cert-runner/src/util.ts
- packages/packages/commonwell-sdk/package.json
- packages/packages/commonwell-sdk/src/client/commonwell.ts
- packages/packages/commonwell-sdk/src/common/util.ts
- packages/packages/commonwell-sdk/src/index.ts
- packages/packages/commonwell-sdk/src/models/facility.ts
- packages/packages/commonwell-sdk/src/models/link.ts
- packages/packages/commonwell-sdk/src/models/organization.ts
- packages/packages/commonwell-sdk/src/models/patient.ts
- packages/packages/commonwell-sdk/src/models/person.ts
Ticket: #[225](https://github.com/metriport/metriport-internal/issues/225)
Add patient management to commonwell packages
> 225 commonwell patient management

- packages/package-lock.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-cert-runner/src/index.ts
- packages/packages/commonwell-cert-runner/src/link-management.ts
- packages/packages/commonwell-cert-runner/src/patient-management.ts
- packages/packages/commonwell-cert-runner/src/payloads.ts
- packages/packages/commonwell-cert-runner/src/person-management.ts
- packages/packages/commonwell-sdk/src/client/commonwell.ts
- packages/packages/commonwell-sdk/src/common/util.ts
- packages/packages/commonwell-sdk/src/index.ts
- packages/packages/commonwell-sdk/src/models/link.ts
- packages/packages/commonwell-sdk/src/models/person.ts
Ticket: #[226](https://github.com/metriport/metriport-internal/issues/226)
Add link management to the cert runner
> feat(packages): link management

- packages/package-lock.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-cert-runner/src/index.ts
- packages/packages/commonwell-cert-runner/src/link-management.ts
- packages/packages/commonwell-cert-runner/src/org-management.ts
- packages/packages/commonwell-cert-runner/src/patient-management.ts
- packages/packages/commonwell-cert-runner/src/payloads.ts
- packages/packages/commonwell-cert-runner/src/person-management.ts
- packages/packages/commonwell-sdk/src/client/commonwell.ts
- packages/packages/commonwell-sdk/src/common/util.ts
- packages/packages/commonwell-sdk/src/index.ts
- packages/packages/commonwell-sdk/src/models/certificates.ts
- packages/packages/commonwell-sdk/src/models/organization.ts
- packages/packages/commonwell-sdk/src/models/patient.ts
Ticket: #[202](https://github.com/metriport/metriport-internal/issues/220)
Add org management 
Once approved it will be merged
> feat(packages): add org management

- packages/package-lock.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
- packages/packages/commonwell-sdk/src/common/validate-npi.ts
Ticket: metriport/metriport-internal#323
N/A
Fix npi validation as per https://www.cms.gov/Regulations-and-Guidance/Administrative-Simplification/NationalProvIdentStand/Downloads/NPIcheckdigit.pdf
ASAP
> fix(packages): implement proper NPI validation

- api/app/src/mappings/withings/activity.ts
Ticket: NA
Withings datetime issue needed to be in unix
ASAP
> fix(api): withings date issue

- .github/workflows/pull-request_packages.yml
- packages/package.json
- packages/packages/api/package.json
- packages/packages/api/src/client/metriport.ts
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-cert-runner/src/link-management.ts
- packages/packages/commonwell-cert-runner/src/org-management.ts
- packages/packages/commonwell-cert-runner/src/patient-management.ts
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
- packages/packages/commonwell-sdk/src/common/make-jwt.ts
Ref #92
- Adjust packages scripts to build, lint, prettier
- Add CI (check PRs when there's updates to `/packages`)
- Fix compilation issues
- anytime
> Adjust packages scripts + add CI

- packages/package-lock.json
- packages/packages/commonwell-cert-runner/README.md
- packages/packages/commonwell-cert-runner/src/document-consumption.ts
- packages/packages/commonwell-cert-runner/src/index.ts
- packages/packages/commonwell-cert-runner/src/payloads.ts
- packages/packages/commonwell-jwt-maker/README.md
- packages/packages/commonwell-sdk/src/client/commonwell.ts
- packages/packages/commonwell-sdk/src/common/util.ts
- packages/packages/commonwell-sdk/src/index.ts
- packages/packages/commonwell-sdk/src/models/demographics.ts
- packages/packages/commonwell-sdk/src/models/document.ts
- packages/packages/commonwell-sdk/src/models/identifier.ts
- packages/packages/commonwell-sdk/src/models/link.ts
- packages/packages/commonwell-sdk/src/models/patient.ts
Ref: https://github.com/metriport/metriport-internal/issues/227
- Downstream: https://github.com/metriport/metriport/pull/91
WIP of Commonwell Document Consumption, includes only the first part: doc query
Also fixes other issues with compilation, lint, prettier.
A couple of adjustments on existing models.
- ⚠️ "Squash & merge" as we have some temporary commits on the history
> 1/2 - Commonwell Document Query

- .gitignore
- .husky/pre-commit
- .vscode/launch.json
- .vscode/settings.json
- README.md
- api/app/src/command/medical/facility/create-facility.ts
- api/app/src/command/medical/organization/create-organization.ts
- api/app/src/models/db.ts
- api/app/src/models/medical/facility.ts
- api/app/src/models/medical/organization.ts
- api/app/src/sequelize/migrations/20230104000000-create-org-facility.ts
- api/app/src/shared/config.ts
- api/app/src/shared/oid.ts
- infra/config/example.ts
- infra/lib/api-stack.ts
- infra/lib/env-config.ts
Ticket: metriport/metriport-internal#331
Upstream: https://github.com/metriport/metriport-internal/pull/333
add OID generation scheme, start with orgs + facs as a baseline
- upstream deps are met
- merge this PR
> 331 oid scheme

- .github/pull_request_template.md
- infra/lib/api-stack.ts
Ticket:  metriport/metriport-internal#335
N/A
add support for OSS API us-east-1 deployments
anytime
> Infra use1 deploy fix

- docs/medical-api-reference/coming-soon.mdx
Ref. metriport/metriport-internal#332
Ticket: 322
- Upstream: https://github.com/metriport/metriport-internal/pull/347#issuecomment-1426331425
Update medical api request docs
Once approved
> feat(docs): add request medical api docs

- api/app/src/mappings/withings/biometrics.ts
- api/app/src/mappings/withings/body.ts
- api/app/src/mappings/withings/models/measurements.ts
- api/app/src/providers/withings.ts
- docs/more-info/our-integrations.mdx
Ref. metriport/metriport-internal#345
Ticket: 345
None
Add body data to withings
> feat(api): add measurement data to withings provider

- api/app/src/routes/user.ts
- api/app/src/routes/util.ts
- docs/mint.json
- docs/user/get-connected-providers.mdx
- packages/packages/api/src/client/metriport.ts
Ref. metriport/metriport-internal#346
Ticket: 346
None
End point for connected providers
> feat(api): get user's connected providers

- api/app/src/routes/fhir-proxy.ts
- packages/package-lock.json
- packages/packages/commonwell-cert-runner/README.md
- packages/packages/commonwell-cert-runner/src/document-consumption.ts
- packages/packages/commonwell-cert-runner/src/document-contribution.ts
- packages/packages/commonwell-cert-runner/src/index.ts
- packages/packages/commonwell-cert-runner/src/link-management.ts
- packages/packages/commonwell-cert-runner/src/org-management.ts
- packages/packages/commonwell-cert-runner/src/patient-management.ts
- packages/packages/commonwell-cert-runner/src/payloads.ts
- packages/packages/commonwell-cert-runner/src/person-management.ts
- packages/packages/commonwell-cert-runner/src/shared-person.ts
- packages/packages/commonwell-sdk/package.json
- packages/packages/commonwell-sdk/src/client/commonwell.ts
- packages/packages/commonwell-sdk/src/common/fileDownload.ts
- packages/packages/commonwell-sdk/src/common/metriport-error.ts
- packages/packages/commonwell-sdk/src/models/document.ts
- creates/gets patient/person on main org
- creates new org w/ certificates
- creates new patient on new org
- links stuff
- queries docs from main org (to hit new one)
- anytime, no release
> refactor: doc contrib create org w/ cert and more

- infra/lib/api-stack.ts
Create private zone on R53 and make it available for the default VPC.
anytime
> build: create private zone on R53

- api/app/src/models/db.ts
- api/app/src/models/medical/mapi-access.ts
- api/app/src/routes/index.ts
- api/app/src/routes/middlewares/auth.ts
- api/app/src/sequelize/migrations/20230222000000-create-mapi-access.ts
refs. #370
N/A
Add whitelist support + MW for MAPI access, and update Notion doc accordingly. We can use the following DML to grant a cx access:
`insert into mapi_access values ('<CUSTOMER_ID>');`
ASAP
> feat(api): add MAPI access whitelist

- api/app/src/providers/google.ts
- api/app/src/providers/oauth2.ts
Ref: [Google revoke token](https://github.com/metriport/metriport/pull/114)
None
This is a patch for revoke google token
Deploy to prod once approved
> Patch google revoke

- infra/lib/api-stack.ts
- Upstream: https://github.com/metriport/metriport/pull/121
- Downstream: https://github.com/metriport/metriport/pull/122
Fixes the logic to create custom cognito domain from the PR https://github.com/metriport/metriport/pull/121
Had to use a certificate from `us-east-1` as stated [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-add-custom-domain.html).
It was not working to refer to the one created on the Widget (it was not a wildcard based one), as well as would still need to move the creation of the Widget one to outside that stack. Because certs are free, we're just creating a new one for the user pool.
> fix: add dedicated cert for custom cognito domain

- infra/lib/api-stack.ts
- Upstream: https://github.com/metriport/metriport/pull/123
- Downstream: https://github.com/metriport/metriport/pull/122
Add missing config for the new cognito user pool.
Follow this PR's https://github.com/metriport/metriport/pull/121
> fix: add missing config to new cognito authorizer

- .husky/post-merge
- api/app/package.json
Add git hook for updates on packages.json and DB migrations.
When there's an update in one of these files/folders, we should be notified on the output of `git merge`.
- anytime, nothing specific
> build: add git hook for updates on packages.json and DB migrations

- api/app/src/command/medical/patient/get-patient.ts
- api/app/src/routes/medical/document.ts
- api/app/src/routes/medical/index.ts
- api/app/src/routes/medical/link.ts
- api/app/src/routes/util.ts
- packages/packages/commonwell-cert-runner/src/document-consumption.ts
- packages/packages/commonwell-cert-runner/src/document-contribution.ts
- packages/packages/commonwell-cert-runner/src/patient-management.ts
- packages/packages/commonwell-sdk/src/client/commonwell.ts
Ref: metriport/metriport-internal#372
- Downstream: https://github.com/metriport/metriport-internal/pull/392
See downstream PR
> 372 link mgmt 1

- api/app/src/command/usage/report-usage.ts
- api/app/src/command/webhook/webhook.ts
- api/app/src/routes/index.ts
- api/app/src/routes/middlewares/usage.ts
Ref. metriport/metriport-internal#376
Ref: 376
- Downstream: https://github.com/metriport/metriport-internal/pull/417
Report usage for multiple apis
> feat(api): report usage for separate apis

- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
- packages/packages/react-native-sdk/package.json
Ref. metriport/metriport-internal#369
update release versions on packages' `package.json` files
- publication done
- simple merge
> chore(packages): update versions

- api/app/src/providers/google.ts
Ref. metriport/metriport-internal#365
Ref: 365
Remove Google data source id
> fix(api): google data source bug

- api/app/src/providers/google.ts
> fix(api): google data source bug (#142)

- api/app/package.json
refs. no issue
fix master metriport api version
> chore(api): fix master metriport api version

- api/app/package.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
refs. metriport/metriport-internal#378
bump package vers for release
> chore: release 2023-03-16

- api/app/src/external/commonwell/api.ts
- api/app/src/external/commonwell/organization.ts
Ref. metriport/metriport-internal#406
Ref: 406
Update dates with the cert date
> fix(api): add correct cert date

- infra/bin/infrastructure.ts
refs. metriport/metriport-internal#378
> fix(infra): provide region prop to connect widget stack

- infra/bin/infrastructure.ts
Ref: metriport/metriport-internal#378
- Downstream: https://github.com/metriport/metriport-internal/pull/444/
> Release 2023-03-16 Round 2

- api/app/src/routes/medical/organization.ts
Ref. metriport/metriport-internal#421
Ref: Quick fix
Fix return bug
> fix(api): return something

- api/app/src/external/commonwell/patient-shared.ts
Ref. metriport/metriport-internal#411
Ref: 411
None
Send slack notification for demographics as well
> fix(api): send slack notification for demo as well

- api/app/package.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
- packages/packages/react-native-sdk/package.json
Ref. metriport/metriport-internal#458
Ref: 458
None
Update package versions
> fix(packages): update versions for release

- api/app/package.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
- packages/packages/react-native-sdk/package.json
Ref. metriport/metriport-internal#378
- Downstream: https://github.com/metriport/metriport-internal/pull/465
Equalize zod versions on patch level.
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1679362975527769
- asap
> chore: equalize zod versions on patch level

- api/app/src/mappings/google/sleep.ts
Ref. metriport/metriport-internal#423
Ref: 423
None
Update the sleep to handle stream of samples
> fix(api): update sleep to handle samples

- api/app/src/command/connected-user/get-connected-user.ts
- api/app/src/mappings/google/models/sleep.ts
- api/app/src/mappings/google/sleep.ts
- api/app/src/providers/google.ts
Ref. metriport/metriport-internal#423
Ref: 423
Fix google sleep response issue
> Fix google sleep

- api/app/src/providers/withings.ts
Ref. metriport/metriport-internal#480
Ref: 480
When the response is an error make sure to error out
> fix(api): error when no token

- api/app/src/routes/util.ts
- api/app/src/shared/analytics.ts
Ref. metriport/metriport-internal#468
Ref: 468
Add logs for visibility
> feat(api): add logs visiblity

- api/app/src/routes/util.ts
- api/app/src/shared/analytics.ts
Ref. metriport/metriport-internal#468
Ref: 468
Remove visibility logs
> feat(api): remove logs visiblity

- packages/packages/api/package.json
Ref. metriport/metriport-internal#405
Ref: 405
Add the correct version
> feat(api): add correct version for api

- api/app/src/external/commonwell/link/create.ts
- api/app/src/external/commonwell/link/shared.ts
- api/app/src/external/commonwell/patient.ts
refs. metriport/metriport-internal#415
N/A
Auto-upgrade patient network LOLA 1 links to LOLA 2
asap
> fix(api): add missing network link upgrade on patient create

- docs/devices-api/more-info/apple-health.mdx
- docs/devices-api/more-info/our-integrations.mdx
- docs/devices-api/more-info/react-native.mdx
refs. metriport/metriport-internal#517
Ref: #517
- None
Fix broken links in docs under /devices-api/more-info
- merge to master
> docs: fix typos

- docs/devices-api/api-reference/get-activity-data.mdx
- docs/devices-api/api-reference/get-biometrics-data.mdx
- docs/devices-api/api-reference/get-body-data.mdx
- docs/devices-api/api-reference/get-nutrition-data.mdx
- docs/devices-api/api-reference/get-sleep-data.mdx
- docs/devices-api/api-reference/get-user-data.mdx
- docs/devices-api/api-reference/settings/get-settings.mdx
- docs/devices-api/api-reference/settings/get-webhook.mdx
- docs/devices-api/api-reference/settings/post-settings.mdx
- docs/devices-api/api-reference/settings/retry-webhook.mdx
- docs/devices-api/api-reference/user/create-connect-token.mdx
- docs/devices-api/api-reference/user/create-user.mdx
- docs/devices-api/api-reference/user/get-connected-providers.mdx
- docs/devices-api/api-reference/user/revoke-provider-access.mdx
- docs/devices-api/more-info/apple-health.mdx
- docs/devices-api/more-info/our-integrations.mdx
- docs/devices-api/more-info/react-native.mdx
- docs/medical-api/api-reference/document/get-document.mdx
- docs/medical-api/api-reference/document/list-documents.mdx
- docs/medical-api/api-reference/facility/get-facility.mdx
- docs/medical-api/api-reference/facility/list-facilities.mdx
- docs/medical-api/api-reference/link/create-link.mdx
- docs/medical-api/api-reference/link/get-links.mdx
- docs/medical-api/api-reference/link/remove-link.mdx
- docs/medical-api/api-reference/organization/get-organization.mdx
- docs/medical-api/api-reference/patient/get-patient.mdx
- docs/medical-api/api-reference/patient/list-patients.mdx
Ref: #metriport/metriport-internal#517
N/A
fix typos & broken links in docs
ASAP - cxs have ran into issues b/c of this
> 517 doc typos 2 release

- api/app/src/mappings/google/activity.ts
- api/app/src/mappings/google/body.ts
- api/app/src/mappings/google/models/activity.ts
- api/app/src/mappings/google/models/index.ts
- api/app/src/mappings/google/models/sleep.ts
- api/app/src/mappings/google/sleep.ts
- api/app/src/providers/google.ts
Ref. #196
Ref: #196
None
Add more data coverage for Google Fit
> fix(api): add more data coverage for google fit

- docs/medical-api/getting-started/quickstart.mdx
Ref. metriport/metriport-internal#522
none
Add info about async docs at quickstart
- nothing special, merging to `master` will generate a new deployment of our docs
> refactor(docs): add info on async docs at quickstart

- infra/cdk.context.json
Ref. metriport/metriport-internal#547
- Upstream: https://github.com/metriport/metriport/pull/218
- Downstream: https://github.com/metriport/metriport-internal/pull/548
Update `cdk.context` so ci/cd can deploy it
- go this content by running `./deploy.sh -e production -s APIInfrastructureStack -d` (`-d` runs `cdk diff`)
> build: update cdk.context so ci/cd can deploy it

- api/app/src/app.ts
- api/app/src/command/account-init.ts
- api/app/src/command/medical/mapi-access.ts
- api/app/src/routes/internal.ts
- api/app/src/routes/util.ts
- api/app/src/sentry.ts
Ref. metriport/metriport-internal#553
- Downstream: https://github.com/metriport/metriport-internal/pull/588
- Add mapi-access endpoint
> 553 add mapi-access endpoint

- api/app/src/providers/google.ts
- api/app/src/routes/helpers/provider-route-helper.ts
refs. metriport/metriport#228
Ref: #228 
N/A
see issue
asap
> fix(api): google fit sleep schema issue

- api/app/tsconfig.json
- connect-widget/app/src/index.tsx
- infra/bin/infrastructure.ts
- infra/lib/secrets.ts
- infra/lib/util.ts
- infra/package.json
- infra/tsconfig.json
- package-lock.json
Ref. metriport/metriport-internal#340
- Upstream: https://github.com/metriport/metriport/pull/231
Review tsconfig on infra (missed this folder on the first PR).
- nothing special, but it will generate a new deploy
> 340 review tsconfig on infra

- packages/package-lock.json
- packages/packages/commonwell-sdk/src/client/commonwell.ts
- packages/packages/commonwell-sdk/src/client/document.ts
- packages/packages/commonwell-sdk/src/models/document.ts
refs. metriport/metriport-internal#585
add func to expose CW operation outcomes to doc queries - updating API to use this will be done in another issue
> chore(packages): add func to expose CW operation outcomes to doc queries

- infra/lib/api-service.ts
- infra/lib/api-stack.ts
- infra/lib/util.ts
do not alert when miss data from CW
- nothing special, asap so we can include this on the release
> 135 do not alert when miss data from CW

- packages/package-lock.json
- packages/packages/api/package.json
Ref. metriport/metriport-internal#262
Ref: RELEASE
- downstream: https://github.com/metriport/metriport-internal/pull/630
Update package version for release
> feat(packages): update package versions

- infra/lib/api-stack.ts
- infra/lib/env-config.ts
Ref: https://github.com/metriport/metriport-internal/issues/135
Ref: https://github.com/metriport/metriport-internal/issues/627
https://github.com/metriport/metriport/pull/266
Reuse prod's slack SNS topic on sandbox
> RELEASE PATCH Reuse prod's slack SNS topic on sandbox

- api/app/src/routes/medical/document.ts
Ref. metriport/metriport-internal#0
Ref: Patch
remove check for download
> feat(api): remove check for downlaod

- api/app/src/command/medical/patient/get-patient.ts
Ref. metriport/metriport-internal#644
none
Check personal id in-memory
- nothing special, tested locally
> 644 check personal id in-memory

- infra/lib/api-stack.ts
Ref. metriport/metriport-internal#0
Ref: Patch
Remove sandbox check for medical bucket
> feat(api): remove sandbox check

- api/app/src/command/connected-user/get-connected-user.ts
- api/app/src/command/cx-user/get-user-token.ts
- api/app/src/command/medical/mapi-access.ts
- api/app/src/default-error-handler.ts
- api/app/src/errors/bad-request.ts
- api/app/src/errors/forbidden.ts
- api/app/src/errors/not-found.ts
- api/app/src/errors/unauthorized.ts
- api/app/src/errors/version-mismatch.ts
- api/app/src/errors/webhook.ts
- api/app/src/external/commonwell/link/get.ts
- api/app/src/external/commonwell/link/reset.ts
- api/app/src/providers/google.ts
- api/app/src/providers/oauth2.ts
- api/app/src/routes/medical/document.ts
- api/app/src/sequelize/cli.ts
- docs/home/api-info/error-responses.mdx
- docs/mint.json
refs. metriport/metriport#259
N/A
standardize & document error responses to rfc7807 - docs preview:
ASAP, nothing special
> feat(api): standardize & document error responses to rfc7807

- api/app/package.json
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/commonwell/mock.ts
- package-lock.json
- packages/package-lock.json
- packages/packages/commonwell-sdk/README.md
- packages/packages/commonwell-sdk/package.json
- packages/packages/commonwell-sdk/src/client/commonwell-api.ts
- packages/packages/commonwell-sdk/src/client/document.ts
- packages/packages/commonwell-sdk/src/index.ts
- packages/packages/commonwell-sdk/src/models/document.ts
refs. metriport/metriport-internal#566
N/A
expose cw errors when querying docs & send corresponding warning to sentry
the USUAL
> feat(api): expose cw errors & send to sentry

- api/app/src/command/medical/document/document-query.ts
Ref. metriport/metriport-internal#607
none
Make sure we always commit the DB tx when updating doc query progress
Context: https://metriport.slack.com/archives/C04T256DQPQ/p1682965822011749
- ASAP
- Replicate to `develop` after released
> RELEASE PATCH always finalize DB tx on updateDocQuery

- api/app/src/external/fhir/api.ts
- api/app/src/external/fhir/document/get-documents.ts
refs. metriport/metriport#287
N/A
paginate queries to fhir server for doc refs
asap
> fix(api): paginate queries to fhir server for doc refs

- api/app/package.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
Ref. metriport/metriport-internal#294
Ref: 294
Update packages for release
> feat(api): update packages for release

- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/medical/models/link.ts
refs. metriport/metriport#269
fix link schema in api pkg
> feat(api): patient demographic input sanitization & schema updates

- api/app/src/providers/withings.ts
- packages/package-lock.json
- packages/packages/api/package.json
Ref: #290 
- Downstream: tbd
patch release 2023-05-06
> patch release 2023-05-06

- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/fhir/document/get-documents.ts
refs. metriport/metriport#299
N/A
handle sandbox properly when querying mapi docs:
- send wh payload
- update query status
ASAP
> fix(api): handle sandbox properly when querying mapi docs

- api/app/src/providers/withings.ts
Ref: #299
N/A
handle sandbox properly when querying mapi docs:
• send wh payload
• update query status
ASAP
> Patch Release 2022-05-07

- docs/medical-api/api-reference/document/start-document-query.mdx
refs. metriport/metriport#302
N/A
update doc query endpoint wording
> docs: update doc query endpoint wording

- api/app/src/providers/withings.ts
- docs/medical-api/api-reference/document/get-document.mdx
> Docs Release

- api/app/src/external/commonwell/document/document-query.ts
refs. metriport/metriport#314
N/A
stringify cw errs when reporing Sentry err
asap
> feat(api): stringify cw errs when reporing Sentry err

- docs/_snippets/address.mdx
- docs/_snippets/patient.mdx
N/A
update patient properties to include address/contact arrays
asap
> docs: update patient properties to include address/contact arrays

- api/app/package.json
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/fhir/document/index.ts
- api/app/src/external/fhir/document/save-document-reference.ts
- api/app/src/routes/medical/dtos/documentDTO.ts
- api/app/src/shared/external.ts
- package-lock.json
Ref. metriport/metriport-internal#673
Ref: 673
Replace up arrow with period
> feat(api): replace up arrow with period

- infra/lib/api-stack.ts
Ref. metriport/metriport-internal#285
Ref: 285
Patch remove line for infra
> feat(api): remove withings extra resourve

- api/app/src/external/commonwell/cw-fhir-proxy.ts
Ref. metriport/metriport-internal#691
none
update the query param used for patientId
> 691 update the query param used for patientId

- api/app/package.json
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/routes/medical/document.ts
- api/app/src/shared/types.ts
- package-lock.json
- packages/package-lock.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
- packages/packages/commonwell-sdk/src/models/demographics.ts
Ref. metriport/metriport-internal#691
none
- fix`override` doc query route param
- add more logs to understand what's going on with file download
> 691 fix `override` doc query route param

- api/app/src/external/commonwell/cw-fhir-proxy.ts
Ref. metriport/metriport-internal#696
none
Filter out CW originated data on `cw-fhir-proxy`, so we don't include CW-originated DocRefs when responding to CW. :)
> 696 filter out CW originated data

- api/app/src/external/fhir-converter/converter.ts
- fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
- fhir-converter/src/lib/workers/worker.js
- fhir-converter/src/routes.js
N/A
remove fhir converter logging spam, fix bug in converter resp
asap
> feat(api): remove fhir converter logging spam, fix bug in converter resp

- fhir-converter/src/templates/cda/Resources/Immunization.hbs
- fhir-converter/src/templates/cda/Resources/Procedure.hbs
N/A
update fhir mappings for immunization/procedure status
asap
> 428 cda fhir engine 3

- fhir-converter/src/templates/cda/ValueSet/MedicationStatementStatus.hbs
N/A
update fhir mappings for medication status as per http://hl7.org/fhir/R4/valueset-medicationrequest-status.html
asap
> feat(api): update fhir mappings for medication status

- fhir-converter/src/index.js
N/A
increase max num event listeners for workers
asap
> fix(api): increase max num event listeners for workers

- fhir-converter/src/templates/cda/Resources/Patient.hbs
- fhir-converter/src/templates/cda/Resources/RelatedPerson.hbs
- fhir-converter/src/templates/cda/ValueSet/AdministrativeGender.hbs
- fhir-converter/src/templates/cda/ValueSet/MedicationStatementStatus.hbs
N/A
update templates for adminsitrative gender + med status
asap
> fix(api): update templates for adminsitrative gender + med status

- api/app/src/command/medical/admin-populate-fhir.ts
- api/app/src/command/medical/document/document-query.ts
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/shared/util.ts
Ref. metriport/metriport-internal#692
Add more time during cx populate
Context: https://metriport.slack.com/archives/C04T256DQPQ/p1684295242643449?thread_ts=1684295006.817009&cid=C04T256DQPQ
- ⚠️ this is pointing to `master`, deploy in `prod`
- merge in to develop once this is done
> 692 add more time during cx populate

- docs/mint.json
Remove the deprecated configuration components from `mint.json` docs settings
> [Docs] Remove unneeded color components

- api/app/src/default-error-handler.ts
- api/app/src/errors/conversion-error.ts
- api/app/src/external/commonwell/__tests__/error-categories.test.ts
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/commonwell/error-categories.ts
- api/app/src/external/commonwell/organization.ts
- api/app/src/external/commonwell/patient-shared.ts
- api/app/src/external/fhir/shared/__tests__/error-mapping.test.ts
- api/app/src/external/fhir/shared/error-mapping.ts
- api/app/src/external/fhir/shared/index.ts
- api/app/src/shared/log.ts
Ref. metriport/metriport-internal#701
none
Do some processing while dealing with errors mid FHIR processing, so we're better equipped to deal with them.
Both from FHIR server and FHIR converter.
> 701 make reported errors more useful

- api/app/src/mappings/oura/sleep.ts
Ref. metriport/metriport-internal#709
Ref: 709
Add samples for sleep in Oura
Patch release once done
> feat(api): add samples for sleep in oura

- api/app/src/default-error-handler.ts
- api/app/src/errors/conversion-error.ts
- api/app/src/external/commonwell/__tests__/error-categories.test.ts
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/commonwell/error-categories.ts
- api/app/src/external/commonwell/organization.ts
- api/app/src/external/commonwell/patient-shared.ts
- api/app/src/external/fhir/shared/__tests__/error-mapping.test.ts
- api/app/src/external/fhir/shared/error-mapping.ts
- api/app/src/external/fhir/shared/index.ts
- api/app/src/mappings/oura/sleep.ts
- api/app/src/shared/log.ts
- docs/medical-api/fhir/resources/adverseevent.mdx
- fhir-converter/src/templates/cda/Resources/AllergyIntolerance.hbs
- fhir-converter/src/templates/cda/Resources/Immunization.hbs
- fhir-converter/src/templates/cda/Resources/MedicationRequest.hbs
- fhir-converter/src/templates/cda/Resources/Procedure.hbs
- fhir-converter/src/templates/cda/ValueSet/AllergySeverity.hbs
- fhir-converter/src/templates/cda/ValueSet/EventStatus.hbs
- fhir-converter/src/templates/cda/ValueSet/ImmunizationStatus.hbs
- fhir-converter/src/templates/cda/ValueSet/MedicationRequestStatus.hbs
- infra/lib/api-service.ts
- infra/lib/api-stack.ts
- infra/lib/fhir-converter-service.ts
Ref
- https://github.com/metriport/metriport/pull/364
- https://github.com/metriport/metriport/pull/362
- https://github.com/metriport/metriport/pull/360
- https://github.com/metriport/metriport/pull/361
> RELEASE 2023-05-18

- infra/lib/fhir-converter-service.ts
Ref. metriport/metriport-internal#706
Fix prod cpu/mem combination
Context https://metriport.slack.com/archives/C04DBBJSKGB/p1684444612981999
- asap
> PATCH 706 fix prod cpu/mem combination

- api/app/.env.test
- api/app/src/command/medical/__tests__/mapi-access.test.ts
- api/app/src/command/medical/mapi-access.ts
- api/app/src/command/medical/organization/__tests__/create-organization.test.ts
- api/app/src/command/medical/organization/create-organization.ts
- api/app/src/models/__tests__/base-model.ts
- api/app/src/models/medical/__tests__/organization.ts
Ref. metriport/metriport-internal#705
- Upstream: https://github.com/metriport/metriport/pull/369
Init FHIR server for cx on org create
> 705 init FHIR server for cx on org create

- fhir-converter/src/templates/cda/ValueSet/ImmunizationStatus.hbs
N/A
update hbs template typo
asap
> fix(api): update hbs template typo

- api/app/src/command/medical/patient/consolidate-data.ts
- api/app/src/external/fhir/mocks/consolidated.ts
Ref. metriport/metriport-internal#686
none
Mock consolidated patient endpoint on `sandbox`
Context: https://metriport.slack.com/archives/C0553DYC95L/p1684857800106979
- deploy in `production` asap
> 686 mock consolidated patient endpoint on sandbox

- api/app/src/command/medical/patient/consolidate-data.ts
- docs/medical-api/api-reference/patient/get-patient-consolidated.mdx
Ref. metriport/metriport#375
none
Add missing FHIR resources to `/consolidated` endpoint
> 375 add missing FHIR resources to consolidated

- infra/lib/api-service.ts
- Fix access to metrics
- asap
> PATCH RELEASE allow API to send metrics to cloudwatch

- api/app/src/external/commonwell/document/document-query.ts
- api/lambdas/cda-to-visualization/index.js
- infra/lib/api-stack.ts
Ref. metriport/metriport-internal#726
Ref: 726
Patch release bugs 
- Lambda timeout
- Lambda es5
- Default content type
> fix(api): patch release bugs

- fhir-converter/src/templates/cda/ValueSet/EncounterStatus.hbs
N/A
normalize encounter status template & add completed mapping
asap
> feat(api): normalize encounter status template & add completed mapping

- api/lambdas/sqs-to-converter/index.js
refs. metriport/metriport-internal#741
N/A
ensure doc id extension is set on the resrouce
asap
> fix(api): ensure doc id extension is set on the resrouce

- infra/lib/api-stack.ts
Ref: 726
Grant access to invoke lambda
> Patch infra access

- infra/dashboards/cw-dashboard-prod.json
- infra/dashboards/cw-dashboard-staging.json
Ref: https://github.com/metriport/metriport-internal/issues/724
none
Add dashboards to git
- no release/deploy
> 724 Add dashboards to git

- api/app/src/command/medical/document/document-download.ts
- api/lambdas/cda-to-visualization/index.js
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/medical/client/metriport.ts
Ref. 726
Ref: 726
Lambda import
> fix(infra): fix import

- api/app/src/external/commonwell/document/document-query.ts
Ref. metriport/metriport-internal#744
none
Only convert CCDA>FHIR when new file
- bugfix, asap
> 744 only convert CCDA>FHIR when new file

- api/app/package.json
- api/app/src/mappings/fitbit/body.ts
- api/app/src/mappings/fitbit/models/weight.ts
- api/app/src/mappings/withings/body.ts
- api/app/src/mappings/withings/models/user.ts
- api/app/src/providers/fitbit.ts
- api/app/src/providers/withings.ts
- docs/devices-api/api-reference/get-body-data.mdx
- docs/devices-api/more-info/models.mdx
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/devices/models/body.ts
- packages/packages/api/src/devices/models/common/metadata.ts
- packages/packages/api/src/devices/models/common/sample.ts
- packages/packages/api/src/devices/models/common/source-info.ts
Ref: [308](https://github.com/metriport/metriport/issues/308) & [380](https://github.com/metriport/metriport/issues/380)
Add withings weight samples and device source
Deploy updated packages
> 308 expose data source

- api/lambdas/cda-to-visualization/index.js
Ref. metriport/metriport-internal#726
Ref: 726
Update lambda to setContent instead opening page
> feat(api): setcontent lambda pdf

- api/app/package.json
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/mappings/fitbit/body.ts
- api/app/src/mappings/fitbit/models/weight.ts
- api/app/src/mappings/withings/body.ts
- api/app/src/mappings/withings/models/user.ts
- api/app/src/providers/fitbit.ts
- api/app/src/providers/withings.ts
- api/lambdas/cda-to-visualization/index.js
- docs/devices-api/api-reference/get-body-data.mdx
- docs/devices-api/more-info/models.mdx
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/devices/models/body.ts
- packages/packages/api/src/devices/models/common/metadata.ts
- packages/packages/api/src/devices/models/common/sample.ts
- packages/packages/api/src/devices/models/common/source-info.ts
- https://github.com/metriport/metriport/pull/409
- https://github.com/metriport/metriport/pull/401
- https://github.com/metriport/metriport/pull/411
- Deployed packages 
- nothing special, just a deploy to production
> RELEASE 2023-06-01

- api/lambdas/withings/index.js
Ref. metriport/metriport-internal#751
Ref: 751
Fix url params as string in lambda
> feat(api): withings patch

- api/app/src/models/db-dev.ts
- api/app/src/models/db.ts
- api/app/src/shared/config.ts
refs. metriport/metriport#412
N/A
Changed the createTokenTable method to first check if the table exists. Also, added a couple methods in the Config class to avoid using getEnvVarOrFail method in other places.
ASAP
> feat(api): createTokenTable if not exists

- api/app/src/routes/webhook/withings.ts
- api/lambdas/withings/index.js
Ref. metriport/metriport-internal#751
Ref: 751
Add logs for visiblity
> feat(api): add visibility

- api/app/src/models/db-dev.ts
- api/app/src/models/db.ts
- api/app/src/shared/config.ts
refs. metriport/metriport#412
N/A
Changed the createTokenTable method to first check if the table exists. Also, added a couple methods in the Config class to avoid using getEnvVarOrFail method in other places.
ASAP
> feat(api): createTokenTable if not exists 

- connect-widget/app/src/shared/localStorage/agreement.ts
- connect-widget/app/src/shared/localStorage/color-mode.ts
- connect-widget/app/src/shared/localStorage/custom-color.ts
- connect-widget/app/src/shared/localStorage/providers.ts
refs. metriport/metriport#425
_[Document your changes, give context for reviewers, add images/videos of UI changes]_
> fix(widget): localStorage null check

- api/app/src/mappings/withings/models/measurements.ts
- api/app/src/mappings/withings/models/user.ts
- docs/devices-api/getting-started/connect-quickstart.mdx
- docs/devices-api/more-info/our-integrations.mdx
Ref. metriport/metriport-internal#753
Ref: 753
Fix withings zof errors and update docs to mention no multiple acc per provider
> fix(api): fix zof bugs and update docs

- docs/devices-api/more-info/our-integrations.mdx
> docs: fix typo

- api/app/src/routes/medical/dtos/documentDTO.ts
Ref. metriport/metriport#745
none
Return Metriport content on document reference's `toDTO()`
- nothing special, but asap as we're randomly returning CommonWell URL's for our customers
> 745 return Metriport content on doc's toDTO

- api/app/src/routes/webhook/apple.ts
Ref. metriport/metriport-internal#763
Ref: 763
- Downstream: https://github.com/metriport/metriport-ios-sdk/pull/6
Consume apple error and send to sentry
> feat(package): add error logs to apple health

- api/app/src/mappings/fitbit/activity.ts
refs. metriport/metriport#462
N/A
see issue
asap
> 462 fitbit activity units

- connect-widget/app/src/pages/connect/index.tsx
- connect-widget/app/src/shared/api.ts
I changed everything involved in the token verification into asynchronous functions. 
I hope this works 😩
> fix(widget): token verification

- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/fhir-converter/converter.ts
- api/app/src/external/sidechain-fhir-converter/connector-factory.ts
- api/app/src/external/sidechain-fhir-converter/connector-sqs.ts
- api/app/src/external/sidechain-fhir-converter/connector.ts
- api/app/src/external/sidechain-fhir-converter/converter.ts
- api/app/src/shared/config.ts
- api/lambdas/sqs-to-converter/index.js
- api/lambdas/sqs-to-converter/package-lock.json
- api/lambdas/sqs-to-converter/package.json
- infra/lib/api-service.ts
- infra/lib/api-stack.ts
- infra/lib/api-stack/sidechain-fhir-converter-connector.ts
- infra/lib/env-config.ts
- infra/lib/secrets-stack.ts
- infra/lib/shared/lambda.ts
- infra/lib/shared/secrets.ts
refs. metriport/metriport-internal#770
N/A
add sidechain fhir conversion
asap, nothing special
> feat(api): add sidechain fhir conversion

- connect-widget/app/src/pages/connect/components/agreement-footer.tsx
- connect-widget/app/src/pages/connect/components/agreement.tsx
- connect-widget/app/src/pages/connect/index.tsx
- connect-widget/app/src/shared/components/WidgetContainer.tsx
refs. metriport/metriport#378
- Obvious scrolling on the agreement and provider list. 
- Sticky "Continue" button with the text that explains what the user is agreeing to. 
- Sticky "Arrow Down" icon at the bottom of the provider list to indicate available scrolling. 
https://imgur.com/a/ZU9SSdt
> feat(widget): obvious widget scrolling

- api/app/src/routes/medical/patient.ts
- api/app/src/shared/config.ts
Ref. metriport/metriport-internal#764
Ref: 764
Limit patient create in sandbox mode
> feat(api): limit patient create sandbox

- api/app/src/external/commonwell/document/document-query-sandbox.ts
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/commonwell/sandbox-payloads.ts
- api/app/src/external/fhir-converter/converter.ts
- api/app/src/external/fhir/connector/connector-factory.ts
- api/app/src/external/fhir/connector/connector-http.ts
- api/app/src/external/fhir/connector/connector-sqs.ts
- api/app/src/external/fhir/connector/connector.ts
- api/app/src/external/fhir/organization/upsert-organization.ts
- api/app/src/external/fhir/patient/upsert-patient.ts
- api/app/src/routes/medical/patient.ts
- api/app/src/shared/config.ts
- api/app/src/shared/sandbox/sandbox-seed-data-defaults.ts
- api/app/src/shared/sandbox/sandbox-seed-data-heather.ts
- api/app/src/shared/sandbox/sandbox-seed-data-jane.ts
- api/app/src/shared/sandbox/sandbox-seed-data.ts
- api/lambdas/sqs-to-converter/index.js
- api/lambdas/sqs-to-fhir/index.js
- infra/lib/api-service.ts
- infra/lib/api-stack.ts
- infra/lib/env-config.ts
none
- create org and patient on FHIR server while on sandbox
- validate patient demographics against seed data on sandbox
- doc query on sandbox returns seed doc refs
- create FHIR connector on sandbox
- CCDA>FHIR conversion on sandbox skips converter, straight to FHIR server
- asap
> 760 sandbox w/ seed and fhir server

- api/app/src/routes/medical/patient.ts
- api/app/src/shared/sandbox/sandbox-seed-data-ollie.ts
- api/app/src/shared/sandbox/sandbox-seed-data.ts
sandbox seed only on doc query
- after deploy, merge master into develop
> PATCH RELEASE 760 sandbox seed only on doc query

- docs/medical-api/more-info/sandbox.mdx
Ref: #304
n/a
add mapi sandbox seed data to docs
> 304 docs patch 4

- api/app/src/command/medical/patient/consolidate-data.ts
- api/app/src/external/fhir/admin.ts
- api/app/src/external/fhir/document/get-documents.ts
- api/app/src/routes/medical/patient.ts
- api/app/src/shared/sandbox/sandbox-seed-data-andreas.ts
- api/app/src/shared/sandbox/sandbox-seed-data-hajra.ts
- api/app/src/shared/sandbox/sandbox-seed-data-kyla.ts
- api/app/src/shared/sandbox/sandbox-seed-data-rory.ts
- api/app/src/shared/sandbox/sandbox-seed-data.ts
- infra/lib/api-stack.ts
none
Add more seed data
- asap
> 760 more seed data

- api/app/src/command/medical/patient/consolidate-data.ts
- api/app/src/external/fhir/admin.ts
- api/app/src/external/fhir/document/get-documents.ts
- api/app/src/routes/medical/patient.ts
- api/app/src/shared/sandbox/sandbox-seed-data-andreas.ts
- api/app/src/shared/sandbox/sandbox-seed-data-hajra.ts
- api/app/src/shared/sandbox/sandbox-seed-data-kyla.ts
- api/app/src/shared/sandbox/sandbox-seed-data-rory.ts
- api/app/src/shared/sandbox/sandbox-seed-data.ts
- docs/medical-api/more-info/sandbox.mdx
- infra/lib/api-stack.ts
Ref. https://github.com/metriport/metriport-internal/issues/760
- asap
> RELEASE 2023-06-09_2

- api/app/src/external/commonwell/document/document-query-sandbox.ts
none
Generate new seed doc IDs
> 760 generate new seed doc IDs

- api/app/src/shared/sandbox/sandbox-seed-data-aamina.ts
- api/app/src/shared/sandbox/sandbox-seed-data-damien.ts
- api/app/src/shared/sandbox/sandbox-seed-data-emilia.ts
- api/app/src/shared/sandbox/sandbox-seed-data-gavin.ts
- api/app/src/shared/sandbox/sandbox-seed-data-lexi.ts
- api/app/src/shared/sandbox/sandbox-seed-data-wanda.ts
- api/app/src/shared/sandbox/sandbox-seed-data-william.ts
- api/app/src/shared/sandbox/sandbox-seed-data.ts
- api/lambdas/sqs-to-fhir/index.js
- docs/medical-api/more-info/sandbox.mdx
Ref: https://github.com/metriport/metriport-internal/issues/760
- Add Lexi, Aamina, Gavin, William, Wanda, Emilia, Damien, and Heather seed data.
- Fix FHIR server logic (payload processing and metrics)
- Add retry on FHIR bundle upsert
- update `develop` after this is merged
> RELEASE add more seed data

- api/app/src/command/medical/patient/delete-patient.ts
- api/app/src/routes/internal.ts
Ref. metriport/metriport-internal#765
Ref: 765
Delete patient fully in sandbox
> feat(api): delete patient from sandbox

- packages/package-lock.json
- packages/packages/react-native-sdk/android/build.gradle
- packages/packages/react-native-sdk/package.json
Ref. patch
Ref: #patch
Add plus sign
> fix(packages): add plus sign

- api/app/src/command/medical/document/document-download.ts
- api/app/src/external/commonwell/document/document-query-sandbox.ts
- infra/lib/api-stack.ts
Ref: #476 
Add patient to docref + access to s3 bucket 
> RELEASE add patient to docref + access to s3 bucket 

- api/app/src/external/commonwell/document/document-query-sandbox.ts
Ref: #760
Add Patient to docRef contained
> fix: add Patient to docRef contained

- api/app/src/external/commonwell/document/document-query-sandbox.ts
Add Patient subject to docRef contained
> RELEASE add Patient subject to docRef contained

- api/lambdas/sqs-to-fhir/index.js
replace IDs on FHIR server lambda
> 760 replace IDs on FHIR server lambda

- api/app/src/mappings/cronometer/nutrition.ts
- api/app/src/mappings/fitbit/models/food.ts
- api/app/src/mappings/fitbit/nutrition.ts
- api/app/src/providers/cronometer.ts
- docs/devices-api/api-reference/get-nutrition-data.mdx
- docs/devices-api/more-info/models.mdx
- packages/packages/api/src/devices/models/common/food-item.ts
- packages/packages/api/src/devices/models/common/food.ts
- packages/packages/api/src/devices/models/nutrition.ts
- packages/packages/api/src/index.ts
refs. metriport/metriport#430
- Fixed the Nutrition interface to include food logs.
- Added a FoodItem interface to support the food logs.
- Fixed the fitbit nutrition model to include the defined food log entries. 
- Updated the docs to reflect the changes.
- Added support for Cronometer food logs.
https://imgur.com/a/TFAnGpP
> feat(api): package nutrition and fitbit food logs

- api/app/src/command/medical/document/document-query.ts
- api/app/src/command/webhook/medical.ts
- api/app/src/external/commonwell/document/document-query.ts
- docs/home/api-info/webhooks.mdx
- docs/medical-api/more-info/webhooks.mdx
refs. metriport/metriport#503
N/A
add more robust webhook status updates for mapi doc queries
asap
> feat(api): add more robust webhook status updates for mapi doc queries

- api/lambdas/sqs-to-converter/index.js
- api/lambdas/sqs-to-fhir/index.js
- infra/lib/api-stack/sidechain-fhir-converter-connector.ts
- upstream: https://github.com/metriport/metriport/pull/500
Limit urls length on FHIR conversion/server lambdas
- asap
> 785 limit URLs length on FHIR lambdas

- api/lambdas/sqs-to-converter/index.js
- api/lambdas/sqs-to-fhir/index.js
- infra/lib/api-stack/sidechain-fhir-converter-connector.ts
refs. metriport/metriport-internal#770
N/A
update sqs converter lambda sidechain post process logic
asap
> fix(api): update sqs converter lambda sidechain post process logic

- api/lambdas/sqs-to-converter/index.js
- infra/lib/api-stack/sidechain-fhir-converter-connector.ts
- infra/lib/env-config.ts
- Downstream: internal https://github.com/metriport/metriport-internal/pull/788
Remove words from conversion lambda
- asap
> 785 remove words from conversion lambda

- api/lambdas/sqs-to-fhir/index.js
- api/lambdas/sqs-to-fhir/package-lock.json
- api/lambdas/sqs-to-fhir/package.json
Ref. metriport/metriport-internal#725
Add axios to FHIR server lambda
- This is pointing to `master`
> PATCH RELEASE 725 add axios to FHIR server lambda

- api/app/package.json
- api/app/src/routes/helpers/provider-route-helper.ts
- package-lock.json
- packages/package-lock.json
- packages/packages/commonwell-cert-runner/package.json
- packages/packages/commonwell-jwt-maker/package.json
- packages/packages/commonwell-sdk/package.json
- packages/packages/commonwell-sdk/src/client/commonwell.ts
Longer timeout for CommonWell client
> PATCH RELEASE longer timeout for cw client

- api/app/src/routes/internal.ts
- api/lambdas/sqs-to-converter/index.js
- api/lambdas/sqs-to-fhir/index.js
Ref. metriport/metriport-internal#725
Ref: 725
Need to add the payload as params
> fix(api): add payload as params

- api/lambdas/sqs-to-converter/index.js
- api/lambdas/sqs-to-fhir/index.js
none
Doc Ref's meta might be empty - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1686625592143689)
> 785 meta might be empty

- api/app/src/command/medical/document/document-query.ts
Ref. metriport/metriport-internal#725
Ref: 725
Need to check if doc progress convert is true before sending webhook
> Patch doc progress bug

- api/app/src/command/medical/document/document-query.ts
- api/lambdas/sqs-to-converter/index.js
- api/lambdas/sqs-to-fhir/index.js
Ref: https://github.com/metriport/metriport/pull/517
Ref: https://github.com/metriport/metriport/pull/518
> RELEASE - 06-13-23

- api/lambdas/sqs-to-converter/index.js
N/A
fix typo in post-processing & resource null check
asap
> 785 patch release 2

- api/lambdas/sqs-to-converter/index.js
N/A
fix typo in post-processing
asap
> fix(api): fix typo in post-processing

- api/lambdas/sqs-to-converter/index.js
N/A
fix typo in post-processing
asap
> 785 patch release 4

- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/fhir-converter/converter.ts
- api/app/src/routes/internal.ts
- api/lambdas/sqs-to-converter/index.js
Only consider CCDA files when counting for conversion progress
- This is pointing to `master`
- Update develop after this gets merged
> PATCH RELEASE conversion progress to only consider CCDA

- docs/devices-api/more-info/faq.mdx
- docs/medical-api/more-info/faq.mdx
- docs/mint.json
refs. metriport/metriport#516
-Added FAQ docs under DAPI and MAPI More Info sections.
> feat(docs): added faq sections

- connect-widget/app/src/pages/connect/components/agreement-footer.tsx
refs. metriport/metriport#532
The connect button container background is set dynamically
> fix(widget): background bug for continue button

- api/app/src/command/medical/document/__tests__/document-query.test.ts
- api/app/src/command/medical/document/document-query.ts
- package.json
Force new object to Sequelize update
Context: https://metriport.slack.com/archives/C04GEQ1GH9D/p1686779321526119?thread_ts=1686762542.746299&cid=C04GEQ1GH9D
- Update develop after this is merged
> PATCH RELEASE force new object to Sequelize update

- api/app/src/command/medical/document/document-query.ts
- api/app/src/command/medical/patient/delete-patient.ts
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/routes/internal.ts
- api/lambdas/sqs-to-converter/index.js
- Return latest doc query status on new post 
- Add log on doc-query after downloading from HIE and upserting on FHIR server
- Don't log the whole payload on FHIR converter lambda
> PATCH RELEASE return latest doc query status on new post

- api/app/package.json
- api/app/src/mappings/fitbit/body.ts
- api/app/src/mappings/fitbit/constants.ts
- api/app/src/mappings/fitbit/models/weight.ts
- api/app/src/mappings/withings/body.ts
- docs/devices-api/api-reference/get-body-data.mdx
- docs/devices-api/more-info/models.mdx
- package-lock.json
- packages/package-lock.json
- packages/packages/api/src/devices/models/common/source-info.ts
- packages/packages/api/src/devices/models/common/source-type.ts
- packages/packages/api/src/index.ts
refs. https://github.com/metriport/metriport/issues/541
- Added a standardized_type attribute to the data_source for weight returns for Fitbit and Withings.
- Fixed the faulty logic for unit conversion for Fitbit
- Truncated the weight and height returns to 2 decimal places
> 541 standard device source

- api/app/package.json
- api/app/src/command/medical/admin-populate-fhir.ts
- api/app/src/command/medical/document/__tests__/document-query.test.ts
- api/app/src/command/medical/document/__tests__/document-query_calculateAndUpdateDocQuery.test.ts
- api/app/src/command/medical/document/document-query.ts
- api/app/src/command/medical/document/document-redownload.ts
- api/app/src/command/medical/patient/__tests__/append-doc-query-progress.test.ts
- api/app/src/command/medical/patient/append-doc-query-progress.ts
- api/app/src/command/medical/patient/get-patient.ts
- api/app/src/command/medical/patient/update-patient.ts
- api/app/src/domain/medical/__tests__/document-reference.ts
- api/app/src/domain/medical/document-reference.ts
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/models/__tests__/transaction.ts
- api/app/src/models/medical/__tests__/patient.ts
- api/app/src/routes/internal.ts
- api/app/src/routes/schemas/internal.ts
- api/app/src/shared/__tests__/utils.ts
- package-lock.json
- Adj doc query progress
- FHIR populate w/ option to not query docs
> PATCH RELEASE adj progress and fhir populate

- api/app/src/command/medical/document/document-query.ts
- api/app/src/routes/internal.ts
Additional log for doc query progress 
- ⚠️ Deploy in `production`
> PATCH RELEASE additional log for doc query progress 

- api/app/src/command/medical/document/__tests__/document-query_calculateAndUpdateDocQuery.test.ts
- api/app/src/command/medical/document/document-query.ts
- api/app/src/domain/medical/__tests__/document-reference.ts
- api/app/src/routes/user.ts
Refactor DB tx commit & add couple of tests
Context: https://metriport.slack.com/archives/C04GEQ1GH9D/p1686888717767589?thread_ts=1686885618.985399&cid=C04GEQ1GH9D
> PATCH RELEASE refactor DB tx commit & add couple of tests

- api/app/src/command/medical/document/document-redownload.ts
- api/app/src/command/medical/patient/delete-patient.ts
- api/app/src/command/settings/updateSettings.ts
- api/app/src/command/usage/report-usage.ts
- api/app/src/command/webhook/apple.ts
- api/app/src/command/webhook/garmin.ts
- api/app/src/command/webhook/medical.ts
- api/app/src/default-error-handler.ts
- api/app/src/errors/bad-request.ts
- api/app/src/shared/notifications.ts
- Upstream: https://github.com/metriport/metriport/pull/563
Minimize noise from errors on logs.
I had this stashed on my computer from the weekend, pushing so we can test along other changes in staging.
> 785 minimize noise from errors on logs

- api/app/src/command/medical/document/document-download.ts
Ref. metriport/metriport#558
Ref: 558
Remove quotes from string
> fix(api): remove quotes from url

- api/app/src/command/medical/document/document-query.ts
- api/app/src/routes/internal.ts
- package-lock.json
N/A
add retry to doc query status update in/outside of the txn
asap
> fix(api): add retry to doc query status update in/outside of the txn

- api/app/src/command/medical/patient/append-doc-query-progress.ts
Fix: pass DB tx to update within DB tx
- ASAP
> PATCH RELEASE pass DB tx to update

- api/app/src/mappings/fitbit/body.ts
- api/app/src/providers/fitbit.ts
- api/app/src/providers/oauth2.ts
Ref: #_[565]_https://github.com/metriport/metriport/issues/565
- Fitbit weight is now obtained in a standard manner (in stones) and is properly converted to kg with 2 decimal place precision.
> fix(api): weight decimal places

- api/app/package.json
- api/app/src/external/commonwell/link/create.ts
- api/app/src/external/commonwell/link/get.ts
- api/app/src/external/commonwell/patient-external-data.ts
- api/app/src/external/commonwell/patient-shared.ts
- api/app/src/external/commonwell/patient.ts
- api/app/src/external/patient-link.ts
- docs/_snippets/patient-response-json.mdx
- docs/_snippets/patient-response.mdx
- docs/mint.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/index.ts
- packages/packages/api/src/medical/models/link.ts
Ref. metriport/metriport#483
Ref: 483
- Downstream: https://github.com/metriport/metriport-internal/pull/803
Add status for patient linking during create
update packages
> fix(api): add patient linking status

- api/app/src/command/medical/document/__tests__/document-query.test.ts
- api/app/src/command/medical/document/__tests__/document-query_calculateAndUpdateDocQuery.test.ts
- api/app/src/command/medical/document/document-query.ts
- api/app/src/command/medical/patient/append-doc-query-progress.ts
- api/app/src/domain/medical/document-reference.ts
- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/routes/internal.ts
Split WH trigger from table update
Context: https://metriport.slack.com/archives/C04GEQ1GH9D/p1687283911197099?thread_ts=1687283103.397309&cid=C04GEQ1GH9D
> PATCH RELEASE split WH trigger from table update

- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/fhir-converter/converter.ts
- api/app/src/external/sidechain-fhir-converter/converter.ts
- api/app/src/routes/internal.ts
none
- WH trigger for convert (fixes [this](https://metriport.slack.com/archives/C04GEQ1GH9D/p1687293284416449?thread_ts=1687292327.753799&cid=C04GEQ1GH9D))
- update counter on error to trigger conversion
> 785 wh trigger for convert + counter on error

- api/app/package.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/medical/models/document.ts
Ref. metriport/metriport-internal#808
Ref:808
Update doc ref schema to make type optional
- warning: Pointing to master
> fix(packages): update schema to match api

- api/app/src/command/medical/patient/__tests__/append-doc-query-progress.test.ts
- api/app/src/external/commonwell/document/document-query.ts
> PATCH RELEASE double check convert status

- api/app/src/sequelize/migrations/20230620184500-create-change-log.ts
- api/app/src/sequelize/migrations/20230620185500-alter-patient-add-change-log.ts
Ref. metriport/metriport-internal#54
none
- Create change log plumbing
- Add change log to patient table
Working local:
- ⚠️ Has a DB migration
- nothing more
> 54 add change log to patient table

- api/app/src/sequelize/migrations/20230620212500-alter-change-log.ts
Ref. metriport/metriport-internal#54
change log values columns optional
context: https://metriport.slack.com/archives/C04DMKE9DME/p1687313634418659?thread_ts=1687310433.847549&cid=C04DMKE9DME
- ⚠️ This is pointing to `master
> PATCH RELEASE change log values columns optional

- connect-widget/app/src/pages/connect/components/error-dialog.tsx
- connect-widget/app/src/pages/connect/index.tsx
- connect-widget/app/src/shared/token-errors.ts
refs. metriport/metriport#531
- No sentry error with a demo token on the widget
> fix(widget): no sentry error with demo token

- api/app/src/external/commonwell/document/document-query.ts
- api/app/src/external/fhir-converter/converter.ts
- api/app/src/external/sidechain-fhir-converter/converter.ts
- api/app/src/routes/internal.ts
- Upstream: https://github.com/metriport/metriport/pull/587
Reapply the changes from the PR https://github.com/metriport/metriport/pull/587, somehow were lost on some merge.
Context: https://metriport.slack.com/archives/C04GEQ1GH9D/p1687316199405879?thread_ts=1687312875.442429&cid=C04GEQ1GH9D
- merge into develop after this is merged
> PATCH RELEASE wh trigger for convert + counter on error

- api/app/src/external/fhir/api/api-hapi.ts
Ref: 799
Remove cache from medplum
> 799 remove cache medplum search

- api/app/package.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/medical/models/document.ts
Ref: 799
Add failed to status schema
> fix(api): add failed to status schema

- api/app/src/command/medical/document/check-doc-queries.ts
Ref. metriport/metriport-internal#798
none
Add updatedAt to doc query check result so we have this information on Sentry when analyzing the doc queries that need update.
> 798 add updatedAt to doc query check result

- api/app/src/mappings/fitbit/body.ts
refs. metriport/metriport#605
- Added "Web" as a potential manual data source for weight data
> feat(api): fitbit mapping web data source

- api/app/src/routes/webhook/apple.ts
- api/app/src/shared/analytics.ts
Ref: 799
Add webhook logs for apple
> fix(api): add logs for apple health

- api/app/package.json
- package-lock.json
- packages/package-lock.json
- packages/packages/api/package.json
Ref. https://github.com/metriport/metriport/pull/611
Fix packages with updated link logic removed
> PATCH PACKAGES - 06-26-23

- api/app/src/external/commonwell/document/document-query-sandbox.ts
refs. metriport/metriport-internal#815
N/A
set doc query progress correctly for sandbox
merge to develop after master release
> fix(api): set doc query progress correctly for sandbox

- api/app/src/mappings/fitbit/models/activity-log.ts
Ref: #626 
N/A
patch fitbit activity data model
asap
> 626 fitbit zod schema patch

- api/app/package.json
- package-lock.json
- package.json
- packages/package-lock.json
- packages/packages/api/package.json
- packages/packages/api/src/medical/models/facility.ts
refs. metriport/metriport#502
- Downstream: _[848]_https://github.com/metriport/metriport-internal/pull/848
- Updated the pkg to match the NPI validation in the OSS src code
> fix(dash): pkg updated to allow npi validation

- api/app/src/command/medical/patient/shared.ts
- api/app/src/external/commonwell/patient-conversion.ts
- api/app/src/external/fhir/patient/index.ts
- api/app/src/models/medical/patient.ts
- api/app/src/routes/medical/dtos/demographicsDTO.ts
- api/app/src/routes/medical/dtos/linkDTO.ts
- api/app/src/routes/medical/schemas/patient.ts
- docs/_snippets/patient-response-no-facilities-or-links.mdx
- docs/_snippets/patient.mdx
- docs/medical-api/api-reference/patient/list-patients.mdx
refs. metriport/metriport#570
- Made the personal identifiers array nullish in the schema 
- Made all the required downstream changes
> feat(mapi): personalIdentifiers is now nullish

- docs/devices-api/more-info/apple-health.mdx
- docs/devices-api/more-info/react-native.mdx
- examples/ios/HealthKitExample/Metriport mobile/WebViewController.swift
- examples/ios/HealthKitExample/Metriport mobile/WidgetView.swift
- examples/react-native/ios/MetriportReactNative.xcodeproj/project.pbxproj
- examples/react-native/ios/MetriportReactNative/AppDelegate.mm
- examples/react-native/package-lock.json
- examples/react-native/package.json
- examples/react-native/yarn.lock
- packages/package-lock.json
- packages/packages/react-native-sdk/ios/MetriportConfiguration.h
- packages/packages/react-native-sdk/ios/MetriportConfiguration.m
- packages/packages/react-native-sdk/metriport-react-native.podspec
- packages/packages/react-native-sdk/package.json
Ref:799
Simple update to react native dev setup and updated package
> fix(packages): update react native setup

- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
Ref. metriport/metriport-internal#715
Fix CICD script for connect-widget
- merge into `develop` once this is merged
> PATCH RELEASE fix CICD script for connect-widget

- package-lock.json
- package.json
refs. metriport/metriport#502
- In a recent PR, I accidentally introduced unnecessary dependencies into the package.lock in the root folder. This PR reverses that.
> fix(api): removed unnecessary dependency from the package.json in root

- api/app/src/mappings/apple/activity.ts
- api/app/src/mappings/apple/index.ts
- api/app/src/mappings/apple/sleep.ts
Ref: 799
Sleep and workout data for apple needs source to prevent duplicates
> fix(api): update apple to accept source

- .vscode/settings.json
- api/lambdas/src/cda-to-visualization.ts
Ref. metriport/metriport-internal#307
none
- add log on CDA conversion lambda
- ignore develop PRs
context: https://metriport.slack.com/archives/C0553DYC95L/p1688591944748239?thread_ts=1688590892.391769&cid=C0553DYC95L
> 307 add log on CDA conversion lambda

- .github/workflows/branch-to-staging.yml
Ref. metriport/metriport-internal#714
none
Fix branch-to-staging vars
- asap
> 714 fix branch-to-staging vars

- packages/infra/lib/api-stack.ts
refs. metriport/metriport-internal#879
N/A
specify correct bucket for cda to vis lambda in sandbox mode
asap
> fix(infra): specify correct bucket for cda to vis lambda in sandbox

- .vscode/launch.json
- packages/api/src/mappings/google/models/index.ts
- packages/api/src/providers/google.ts
Ref: #667 
N/A
update google fit activity data zod schema
also fix vscode docker attach
ASAP
> fix(api): update google fit activity data zod schema

- packages/react-native-sdk/metriport-react-native.podspec
> fix(package): add useragent to be able to access webview

- docs/devices-api/more-info/cordova.mdx
- docs/devices-api/more-info/flutter.mdx
- docs/devices-api/more-info/react-native.mdx
- docs/mint.json
- examples/react-native/package-lock.json
- examples/react-native/package.json
- examples/react-native/yarn.lock
- packages/react-native-sdk/metriport-react-native.podspec
- packages/react-native-sdk/package.json
Ref. metriport/metriport#202
Ref: 202
Add flutter docs sdk (some react native changes)
> feat(package): add flutter docs

- packages/api/src/sequelize/index.ts
none
Update DB migration logic to find files.
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1689876463894999
- asap
> 704 update DB migration logic to find files

- packages/infra/lib/api-stack.ts
refs. metriport/metriport#363
- Used a different way to grant read access to the fitbit lambdas
> feat(dapi): Alternative method to grant secrets read access

- .github/workflows/_release.yml
- packages/api/src/sequelize/index.ts
- Upstream: https://github.com/metriport/metriport/pull/687
Fix path to DB migrations
- asap
> 704 fix path to DB migrations

- packages/infra/lib/api-stack.ts
- packages/lambdas/src/fitbit-auth.ts
- packages/lambdas/src/fitbit-subscriber-verification.ts
Ref: #363 
N/A
use correct secrets on CDK for fitbit, update req param type on fitbit lambda
ignore my commit messages, I accidentally used the wrong history.
asap
> 363 fix fitbit lambdas

- packages/lambdas/src/fitbit-subscriber-verification.ts
refs. metriport/metriport#363
N/A
update fitbit sub lambda
asap
> fix(api): update fitbit sub lambda

- packages/api/src/command/connected-user/save-connected-user.ts
- packages/api/src/command/webhook/devices.ts
refs. metriport/metriport#695
- Adding the newly-connected provider into the array before constructing the wh payload
> fix(dapi): fixed adding newly-connected providers into the array of all connected providers

- packages/lambdas/src/fitbit-auth.ts
- packages/lambdas/src/fitbit-subscriber-verification.ts
refs. metriport/metriport#697
- Changed the header key to properly fetch the fitbit signature
- Removed JSON.stringify since the requests coming in have already been stringified
> fix(dapi): fixed fitbitAuthLambda

- packages/api/src/mappings/google/models/index.ts
refs. metriport/metriport-internal#905
N/A
patch google fit activity session zod schema
asap
> fix(api): patch google fit activity session zod schema

- packages/api/src/routes/medical/internal-patient.ts
- packages/api/tsconfig.json
refs. metriport/metriport-internal#843
N/A
- add internal enpoint to update all of a cx's patients
asap
> 843 update all patients internal endpoint

- packages/api/src/routes/internal.ts
refs. metriport/metriport-internal#897
N/A
add user internal routing
asap
> feat(api): add user internal route

- examples/react-native/App.tsx
- package-lock.json
- packages/api/package.json
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/react-native-sdk/src/index.tsx
Ref: 799
PATCH: Add user agent for android webview
> 799 add user agent

- packages/api/src/mappings/google/activity.ts
- packages/api/src/mappings/google/models/index.ts
Ref: #_[710]_(https://github.com/metriport/metriport/issues/710)
- Added the following details to each activity: active_seconds, active_kcal, distance_meters, avg_km_h
- Fixed the calculation for the avg speed for each activity
> [DAPI]: Google fit - activity details

- packages/api/src/command/medical/admin/upload-doc.ts
Ref. metriport/metriport#672
Ref: 672
Quick fix needed to stringify the doc content ref
> fix(api): stringify the doc ref content

- packages/api/src/command/medical/admin/upload-doc.ts
- packages/api/src/shared/config.ts
Ref. metriport/metriport#672
Ref: 672
Remove the doc contribution url env and then use the api url
> fix(api): add api url with doc contribution route

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/api/src/external/commonwell/patient-duplicates.ts
- packages/api/src/routes/medical/internal-patient.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/commonwell-sdk/src/models/human-name.ts
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
Ref: https://github.com/metriport/metriport-internal/issues/704
none
Update CW demographics/name suffix to accept array
Context: https://metriport.slack.com/archives/C04T256DQPQ/p1690921538295009
> PATCH RELEASE check duplicated persons at cw master 2

- packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
- packages/api/src/external/commonwell/patient-shared.ts
- packages/api/src/external/commonwell/patient.ts
- packages/api/src/routes/medical/internal-patient.ts
- Upstream: https://github.com/metriport/metriport/pull/738
Add `POST /internal/patient/recreate-at-hies`
> build: add POST /internal/patient/recreate-at-hies

- packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
- packages/api/src/external/commonwell/patient-shared.ts
- packages/api/src/external/commonwell/patient.ts
- packages/api/src/routes/internal.ts
- packages/api/src/routes/medical/internal-docs.ts
- packages/api/src/routes/medical/internal-patient.ts
Ref: https://github.com/metriport/metriport-internal/issues/704
none
Move `POST /internal/upload-doc` to `POST /internal/docs/upload`.
> 704 move /upload-doc to /internal/docs

- packages/api/src/mappings/fitbit/activity.ts
- packages/api/src/mappings/fitbit/models/activity-log.ts
- packages/api/src/mappings/fitbit/models/heart-rate.ts
Ref. metriport/metriport-internal#932
Ref: 932
Fix fitbit heart rate schema because certain fields were coming back null
> fix(api): update fitbit heart rate schema to nullish

- packages/api/src/external/commonwell/admin/find-patient-duplicates.ts
- packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
- packages/api/src/external/commonwell/document/document-download.ts
- packages/api/src/external/commonwell/document/document-query.ts
- packages/api/src/external/commonwell/link/create.ts
- packages/api/src/external/commonwell/link/get.ts
- packages/api/src/external/commonwell/link/reset.ts
- packages/api/src/external/commonwell/organization.ts
- packages/api/src/external/commonwell/patient-conversion.ts
- packages/api/src/external/commonwell/patient-duplicates.ts
- packages/api/src/external/commonwell/patient.ts
- packages/api/src/routes/medical/internal-patient.ts
- packages/connect-widget/package.json
Ref: https://github.com/metriport/metriport-internal/issues/704
none
Improve the `GET /internal/patient/duplicated` to provide better/more actionable data
> 704 fix find duplicated persons auth @ CW

- docs/devices-api/getting-started/connect-quickstart.mdx
refs. metriport/metriport#914
N/A
add DAPI demo vid
asap
> docs: add DAPI demo vid

- .gitignore
- docs/_snippets/devices-api-query-params.mdx
- docs/devices-api/api-reference/get-activity-data.mdx
- docs/devices-api/api-reference/get-biometrics-data.mdx
- docs/devices-api/api-reference/get-body-data.mdx
- docs/devices-api/api-reference/get-nutrition-data.mdx
- docs/devices-api/api-reference/get-sleep-data.mdx
- docs/devices-api/api-reference/get-user-data.mdx
- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/devices/client/metriport.ts
- packages/api-sdk/src/devices/client/util/timezone-util.ts
- packages/api/package.json
- packages/api/src/command/webhook/fitbit.ts
- packages/api/src/command/webhook/withings.ts
- packages/api/src/providers/google.ts
- packages/api/src/providers/provider.ts
- packages/api/src/routes/helpers/provider-route-helper.ts
- packages/api/src/routes/schemas/timezone-id.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
refs. metriport/metriport#733
N/A
first cut at tz support for dapi for google fit
> fix(api): first cut at tz support for dapi for google fit

- .gitignore
- docs/_snippets/devices-api-query-params.mdx
- docs/devices-api/api-reference/get-activity-data.mdx
- docs/devices-api/api-reference/get-biometrics-data.mdx
- docs/devices-api/api-reference/get-body-data.mdx
- docs/devices-api/api-reference/get-nutrition-data.mdx
- docs/devices-api/api-reference/get-sleep-data.mdx
- docs/devices-api/api-reference/get-user-data.mdx
- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/devices/client/metriport.ts
- packages/api-sdk/src/devices/client/util/timezone-util.ts
- packages/api/package.json
- packages/api/src/command/webhook/fitbit.ts
- packages/api/src/command/webhook/withings.ts
- packages/api/src/providers/google.ts
- packages/api/src/providers/provider.ts
- packages/api/src/routes/helpers/provider-route-helper.ts
- packages/api/src/routes/schemas/timezone-id.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
N/A
releases #733
nothing special, already released release pkgs
> Patch release 2023 08 07

- packages/api/src/providers/google.ts
Ref. metriport/metriport-internal#941
none
Do not duplicate issues with Google provider by removing intermediary error handling code.
Make `fetchGoogleData` private.
> 941 do not duplicate issues with Google provider

- packages/api/src/providers/oauth1.ts
Ref. metriport/metriport#763
none
Encode callback url sent to Garmin
- test on `staging`
- cherry-pick the commit and create a patch to `master`/production
> 763 encode callback url sent to Garmin

- packages/api/src/providers/oauth1.ts
Ref. metriport/metriport#763
Encode callback url sent to Garmin
> PATCH RELEASE 763 encode callback url sent to Garmin

- package-lock.json
- package.json
- packages/api/package.json
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/utils/package.json
Ref. metriport/metriport#944
none
Get all packages to same TS version except react-native.
Add TS as dev dependency on API.
> 944 get all packages to same TS version except react-native

- packages/api/src/mappings/fitbit/index.ts
- packages/api/src/providers/fitbit.ts
- packages/api/src/providers/oauth2.ts
- packages/api/src/routes/devices/internal-user.ts
Ref: [#_[ticket-number]_](https://github.com/metriport/metriport/issues/735)
- Error handling allows the subscriptions to proceed even if old subscriptions aren't deleted
- We will be informed on Sentry about issues like this
- Strong typing for Fitbit token
- Merge this
- Test on staging 
- Cherry-pick to prod and hit both internal/user endpoints
> Improved error handling and strong typing

- packages/api/src/routes/webhook/apple.ts
Ref: 799
- Downstream:  https://github.com/metriport/metriport-ios-sdk/pull/14
Add extra fields for sentry apple
> fix(packages): add extra to sentry

- docs/mint.json
Ref: #304
n/a
fix caps on fhir section
asap
> docs: fix caps on fhir section

- package-lock.json
- package.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/api/src/external/commonwell/admin/find-patient-duplicates.ts
- packages/api/src/external/commonwell/admin/patch-patient-duplicates.ts
- packages/api/src/external/commonwell/admin/shared.ts
- packages/api/src/external/commonwell/person-shared.ts
- packages/api/src/routes/medical/internal-patient.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/commonwell-sdk/src/common/util.ts
- packages/commonwell-sdk/src/index.ts
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
Ref: https://github.com/metriport/metriport/pull/704
none
Add patch /duplicated to dedup persons @ CW
> 704 fix duplicated persons

- package-lock.json
- package.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
- packages/api/src/external/commonwell/patient-shared.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/commonwell-sdk/src/index.ts
- packages/commonwell-sdk/src/models/person.ts
- packages/connect-widget/package.json
- packages/utils/package.json
Ref: metriport/metriport#953
- Upstream: https://github.com/metriport/metriport/pull/780
- findOrCreate @ CW to reenrol person if unenrolled
- return earliest enrolled person instead of latest
- keep recreating at HIEs when 1 patient fails
- asap
> 953 fix patient recreate at HIEs

- packages/api/src/command/webhook/fitbit.ts
refs. metriport/metriport#774
- Fixed `capture.extra.context` based on PR comments
- Added more information on what webhook is being processed
> fix(dapi): fixed a couple nits

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/utils/package.json
Ref. metriport/metriport#953
- Upstream: https://github.com/metriport/metriport/pull/783
Recreate @ HIEs to create when no CW info.
Context: https://metriport.slack.com/archives/C04T256DQPQ/p1691961978832499
- asap
> 953 recreate @ HIEs to create when no CW info

- packages/connect-widget/src/pages/connect/components/connect-providers.tsx
- packages/connect-widget/src/shared/localStorage/apple.ts
- packages/connect-widget/src/shared/localStorage/providers.ts
Ref. metriport/metriport#776
Ref: 776
Persist is apple in local storage
> fix(widget): set apple in local storage

- .github/workflows/_e2e-tests.yml
Ref. metriport/metriport-internal#672
Ref: 672
Install playwright dependencies similar to build script
> fix(ops): need to install playwright dependencies

- packages/api/src/mappings/fitbit/activity.ts
refs. metriport/metriport#803
- Fitbit activity mapping updated to include energy expenditure
> feat(dapi): added energy expenditure to fitbit mapping

- packages/api/src/mappings/google/activity.ts
- packages/api/src/providers/google.ts
Ref. metriport/metriport-internal#977
- Upstream: https://github.com/metriport/metriport/pull/814
- filter on google sessions ISO based
- data mapping on google more efficient
> 977 filter on google sessions ISO based

- packages/api/src/mappings/google/activity.ts
- packages/api/src/providers/google.ts
Ref: https://github.com/metriport/metriport-internal/issues/977
https://github.com/metriport/metriport/pull/816
Add missing commit from cherry-pick
- asap
> PATCH RELEASE patch google 2

- docs/_snippets/patient-address-response.mdx
- docs/_snippets/patient-address.mdx
- docs/_snippets/patient-response-no-facilities-or-links.mdx
- docs/_snippets/patient.mdx
n/a
update patient address required props
asap
> docs: update patient address required props

- packages/api/src/mappings/whoop/models/sleep.ts
Ref: 799
Cherry pick zod whoop error
Warning: POINTING TO MASTER
> fix(api): PATCH - make values nullable for whoop 

- packages/api/src/mappings/fitbit/body.ts
- packages/api/src/providers/fitbit.ts
Ref. metriport/metriport-internal#967
Ref: 967
Handle profile not being present in the scope
To expand on the work in this PR: https://github.com/metriport/metriport-internal/issues/991
> fix(api): handle profile scope not present

- docs/devices-api/more-info/models.mdx
- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/devices/models/sleep.ts
- packages/api/package.json
- packages/api/src/mappings/apple/sleep.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
Ref: 799
Create one sample per session and add wakeup frequency
> fix(api): handle sleep per session and add wakeup frequency

- docs/medical-api/api-reference/fhir/consolidated-data-count.mdx
- docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx
- docs/medical-api/getting-started/quickstart.mdx
- docs/medical-api/more-info/webhooks.mdx
- docs/mint.json
- package-lock.json
- package.json
- packages/api-sdk/package.json
- packages/api-sdk/src/index.ts
- packages/api-sdk/src/medical/client/metriport.ts
- packages/api-sdk/src/medical/models/fhir.ts
- packages/api/package.json
- packages/api/src/command/medical/patient/consolidated-get.ts
- packages/api/src/external/fhir/api/api-hapi.ts
- packages/api/src/external/fhir/patient/count-resources.ts
- packages/api/src/external/fhir/patient/resource-filter.ts
- packages/api/src/routes/medical/patient.ts
- packages/api/src/routes/medical/schemas/fhir.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
- packages/utils/src/api-sdk-tester/mapi/consolidated-query.ts
Ref. metriport/metriport-internal#895
- Upstream: https://github.com/metriport/metriport/pull/824
Add consolidated resource count endpoint, SDK and docs
- NPM release, `minor`
- nothing special other than that
> 895 add consolidated resource count endpoint

- packages/api/src/command/medical/patient/consolidated-webhook.ts
- packages/api/src/command/webhook/webhook.ts
Ref. metriport/metriport-internal#870
- Upstream: https://github.com/metriport/metriport/pull/824
Include bundle size on consolidated WH analytics
> 870 include bundle size on consolidated WH analytics

- docs/medical-api/api-reference/fhir/create-patient-consolidated.mdx
- package-lock.json
- package.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/client/metriport.ts
- packages/api/src/providers/fitbit.ts
- packages/api/src/providers/shared/oauth2.ts
- packages/api/src/routes/medical/patient.ts
- packages/connect-widget/package.json
Ref: https://github.com/metriport/metriport-internal/issues/407
- Downstream: https://github.com/metriport/metriport/pull/837
- move post consolidated to put
- improve error logging for Fitbit auth
- also cherry-picked [this commit](https://github.com/metriport/metriport/commit/cdde627a553c27c8ac7dd9053595d25ac04dcf7f) to bring the update on `package.json` to release individual NPM packages
- staging
- production
> 407 move POST consolidated to PUT

- packages/infra/lib/api-stack.ts
Ref. metriport/metriport-internal#981
none
Increase timeout of cda to vis from 1 to 5min
- infra update, nothing special other than that
> 981 increase timeout of cda to vis from 1 to 5min

- packages/api/src/external/commonwell/document/document-query.ts
Ref.
- metriport/metriport-internal#566
- metriport/metriport-internal#1001
none
Don't notify sentry/slack on 0 bytes doc
Context: https://metriport.slack.com/archives/C04T256DQPQ/p1693250979692219?thread_ts=1693248545.311379&cid=C04T256DQPQ
> 566 don't notify sentry/slack on 0 bytes doc

- packages/api/src/command/webhook/webhook.ts
Ref. metriport/metriport-internal#870
none
Fail MAPI WH when no WH config.
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1693326273845709?thread_ts=1692731043.166889&cid=C04DMKE9DME
```sql
update webhook_request
set status = 'failed'
where status = 'processing'
and type like 'medical%';
```
> 870 fail MAPI WH when no WH config

- packages/api/src/external/commonwell/document/document-query.ts
- packages/api/src/external/commonwell/document/shared.ts
- packages/api/src/external/fhir/document/index.ts
- packages/api/src/external/fhir/organization/index.ts
- packages/api/src/external/fhir/patient/index.ts
- packages/api/src/external/fhir/shared/index.ts
refs. metriport/metriport#846
- Created a CW-to-FHIR converter for the following resource types: Organization, Patient, Practitioner
- Nothing special?
> feat(mapi): included more metadata to doc refs

- packages/api/src/command/webhook/apple.ts
- packages/api/src/command/webhook/devices.ts
- packages/api/src/command/webhook/fitbit.ts
- packages/api/src/command/webhook/garmin.ts
- packages/api/src/command/webhook/retry-failed.ts
- packages/api/src/command/webhook/tenovi.ts
- packages/api/src/command/webhook/webhook.ts
Ref. metriport/metriport-internal#774
none
Adjust WH related log and error reporting.
Contex: https://metriport.slack.com/archives/C04T256DQPQ/p1693562489557599
> 774 adjust wh related log and error reporting

- packages/api/jest.config.ts
- packages/api/src/__tests__/env-setup.ts
- packages/api/src/command/medical/docref-mapping/__tests__/get-docref-mapping.test.ts
- packages/api/src/command/medical/document/__tests__/document-query.test.ts
- packages/api/src/command/medical/document/__tests__/document-query_calculateAndUpdateDocQuery.test.ts
- packages/api/src/command/medical/organization/__tests__/create-organization.test.ts
- packages/api/src/command/medical/patient/__tests__/append-doc-query-progress.test.ts
- packages/api/src/command/medical/patient/__tests__/consolidated-get.test.ts
- packages/api/src/command/usage/report-usage.ts
- packages/api/src/external/commonwell/__tests__/cw-fhir-proxy.test.ts
- packages/api/src/external/fhir/document/save-document-reference.ts
- packages/api/src/external/fhir/shared/__tests__/error-mapping.test.ts
- packages/api/src/providers/__tests__/oauth1-deregister.test.ts
- packages/api/src/routes/medical/__tests__/fhir-r4/e2e/binary.ts
Ref. metriport/metriport-internal#669
none
- Fix jest setup for `dotenv`
- Small adjustments other parts of the code (from the stashed code for doc contribution)
> 669 fix jest setup for .env

- docs/devices-api/getting-started/tenovi.mdx
refs. metriport/metriport#865
- Fixed a couple docs typos 
> fix(dapi): fixed a couple of typos in the docs

- packages/utils/src/.gitignore
- packages/utils/src/bulk-insert-patients.ts
refs. metriport/metriport-internal#690
n/a
update bulk insert csv tool to new format and more normalizing
asap, nothing special
> chore: update bulk insert csv tool to new format and more normalizing

- packages/utils/src/bulk-insert-patients.ts
refs. metriport/metriport-internal#690
n/a
update bulk insert csv tool to add more normalizing
asap
> chore: update bulk insert csv tool to add more normalizing

- packages/api/jest.config.ts
- packages/api/src/command/medical/admin/upload-doc.ts
- packages/api/src/external/fhir/document/__tests__/cw-payloads.ts
- packages/api/src/external/fhir/document/__tests__/index-convert-to-fhir-resource.test.ts
- packages/api/src/external/fhir/document/__tests__/index-get-authors.test.ts
- packages/api/src/external/fhir/document/__tests__/index-to-fhir.test.ts
- packages/api/src/external/fhir/document/index.ts
- packages/api/src/external/fhir/shared/__tests__/date.ts
- packages/api/tsconfig.dev.json
- packages/commonwell-sdk/src/models/__tests__/document.ts
Ref: https://github.com/metriport/metriport-internal/issues/1033
none
- cw doc ref toFHIR() to return a single author for a given reference
- cw doc ref toFHIR() not to include custodian
- add format to FHIR content upon doc query 
- consider content.period.end to get doc ref date 
- add practitioner role on doc ref contained
- make jest less strict while developing
> 1033 fix doc ref conversion

- packages/api/src/command/medical/document/document-redownload.ts
Ref: metriport/metriport-internal#1033
Doc reprocess consider paginated results when querying FHIR server.
Context: https://metriport.slack.com/archives/C04DBBJSKGB/p1694289742096979?thread_ts=1694288623.375039&cid=C04DBBJSKGB
> PATCH RELEASE fix doc reprocess pagination

- packages/api/src/command/medical/document/document-redownload.ts
Ref:
- metriport/metriport-internal#1033
- https://github.com/metriport/metriport-internal/issues/1038
Doc reprocess resets progress upon start
> PATCH RELEASE doc reprocess resets progress upon start

- packages/api/src/command/medical/admin/upload-doc.ts
- packages/api/src/command/medical/document/document-redownload.ts
- packages/api/src/external/commonwell/document/document-query.ts
- packages/api/src/external/fhir/document/index.ts
- packages/api/src/shared/__tests__/log.test.ts
- packages/api/src/shared/log.ts
- packages/api/src/shared/numbers.ts
- packages/api/src/shared/util.ts
Ref: https://github.com/metriport/metriport/issues/846
none
- make /upload to match toFHIR logic 
- doc ref status now matches what we get from CW - [link](https://github.com/metriport/metriport/pull/889/files#diff-ca68a1648769cbb4448dba2cab721fd02d62e511904af21aba6e0e7829aa9ee0R117)
- improve error handling
> 846 make /upload to match toFHIR logic 

- packages/api/src/routes/user.ts
refs. metriport/metriport#1041
- This release contains a bug fix to decrease DB load on List Connected Users.
> PATCH RELEASE 2023-09-13

- packages/lambdas/package-lock.json
Release
ref: https://github.com/metriport/metriport/pull/896
Once approved
> RELEASE - 2023-09-15

- README.md
refs. metriport/metriport-internal#1050
n/a
update readme to include MAPI demo
asap
> chore: update readme to include MAPI demo

- packages/api/src/routes/medical/internal-patient.ts
refs. metriport/metriport#1040
n/a
run patient update in parallel on update-all
asap
> chore: run patient update in parallel on update-all

- docs/medical-api/api-reference/patient/update-patient.mdx
- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/models/common/address.ts
- packages/api/package.json
- packages/api/src/routes/medical/patient.ts
- packages/api/src/routes/medical/schemas/patient.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
- packages/utils/src/initialize-cw-test-env/index.ts
Ref: #[_[ticket-number]_](https://github.com/metriport/metriport/issues/922)
- Downstream: https://github.com/metriport/metriport-internal/pull/1078
- Made the following address fields required for `POST /patient`: city, addressLine1, state
- Release pkg
- Merge this
- Update downstream PR
- Merge downstream PR
> 922 required address properties

- packages/api/src/command/medical/document/check-doc-queries.ts
Ref: metriport/metriport-internal#1090
none
Make sure native sql query returns correct value
Context: https://metriport.slack.com/archives/C04T5Q9JHFX/p1696115260259599?thread_ts=1696113621.578759&cid=C04T5Q9JHFX
> 1090 make sure native sql query returns correct value

- packages/infra/config/env-config.ts
- packages/infra/lib/api-stack.ts
- packages/infra/lib/api-stack/sidechain-fhir-converter-connector.ts
- packages/infra/lib/secrets-stack.ts
- packages/lambdas/package-lock.json
- packages/lambdas/package.json
- packages/lambdas/src/sqs-to-converter.ts
Ref: metriport/metriport-internal#1089
- Upstream: TBD
track sidechain rate limit
> 1089 track sidechain rate limit

- packages/lambdas/src/sqs-to-converter.ts
refs. metriport/metriport-internal#1089
n/a
change sidechain keys table col name
need to make sure we don't use reserved words: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html
asap
> fix(api): change sidechain keys table col name

- packages/api/src/routes/settings.ts
refs. metriport/metriport-internal#1100
n/a
allow webhook url with 0 in it
asap
> feat(api): allow webhook url with 0 in it

- packages/api/src/routes/settings.ts
refs. metriport/metriport-internal#1100
- Fixes the issue where 0's were not allowed in the url for webhook settings on the dashboard
> PATCH RELEASE 2023-10-03

- packages/infra/lib/api-stack.ts
- packages/lambdas/src/cda-to-visualization.ts
Ref: #https://github.com/metriport/metriport-internal/issues/1102
Ref: #https://github.com/metriport/metriport-internal/issues/1103
- A couple of minor fixes to CDA-to-Visualization lambda
> Patch release 2022 10 04

- packages/infra/lib/shared/open-search-construct.ts
- packages/lambdas/src/sqs-to-opensearch-xml.ts
https://github.com/metriport/metriport-internal/pull/1105
- Fix lambda url to OpenSearch
- add VPC cidr to OpenSearch SecurityGroup
- asap
> 1050 fix lambda url to OS + add VPC cidr to OS SG

- packages/api/src/external/opensearch/file-search-connector-factory.ts
none
Fix search URL on API
- asap
> 1050 fix search URL on API

- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/index.ts
- packages/api-sdk/src/medical/client/metriport.ts
- packages/api-sdk/src/medical/models/common/address.ts
- packages/api-sdk/src/medical/models/patientDTO.ts
- packages/api/package.json
- packages/api/src/routes/medical/__tests__/mapi/e2e/mapi.test.e2e.ts
- packages/api/src/routes/medical/__tests__/mapi/e2e/patient.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
- packages/utils/src/api-sdk-tester/mapi/patient-list.ts
- packages/utils/src/bulk-query-patients.ts
- packages/utils/src/initialize-cw-test-env/index.ts
refs. metriport/metriport-internal#1088
- getPatient and listPatients on sdk will now return PatientDTOs which have optional address parameters, allowing us to properly process existing patients who don't have all of the address attributes listed
- merge this
- release NPM package update
> feat(sdk): patientDTO for sdk

- packages/api/src/external/commonwell/document/document-query-sandbox.ts
Ref: metriport/metriport-internal#1134
- Upstream: https://github.com/metriport/metriport/pull/964
Check files before conversion on sandbox
- asap
> 1134 check files before conversion on sandbox

- packages/infra/lib/shared/open-search-construct.ts
Ref: https://github.com/metriport/metriport-internal/issues/1050
- Upstream: https://github.com/metriport/metriport/pull/964
Fix OpenSearch AvailabilityZone for `prod`.
Context: https://metriport.slack.com/archives/C04DBBJSKGB/p1696717607549059?thread_ts=1696716284.957409&cid=C04DBBJSKGB
Tested w/ `cdk synth` for all envs.
- nothing special beyond that
> 1050 fix OS AZ for prod

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/utils/package.json
Ref: #https://github.com/metriport/metriport-internal/issues/1088
- Updating the NPM package with a prod release version. Doing this because I can't make a release straight from develop (no permissions)
- Merge this. 
- Release the changes from develop
- Release the internal
> NPM package update

- packages/api/src/mappings/tenovi/body.ts
Ref: https://github.com/metriport/metriport/pull/976
Add timeout to printing pdf and navigation in conversion lambda
> RELEASE - Conversion lambda timeout - 2023-10-09

- packages/lambdas/src/sqs-to-converter.ts
Ref: #799 
Check to see if xml doc is empty before processing
> fix(api): check to see if xml doc is empty

- packages/infra/lib/api-stack/ccda-search-connector.ts
none
Tune down search infra on staging. Use same mount of data nodes to simulate better the prod env, just use smaller instances.
- This has infra changes, but it shouldn't change anything on prod/sandbox
- Anytime
> 1050 tune down search infra on staging

- package-lock.json
- packages/utils/.gitignore
- packages/utils/src/bulk-query-patients.ts
refs. metriport/metriport-internal#1040
n/a
patch bulk query tool, add whitelist, only kick off query, don't wait for completion
asap
> chore: patch bulk query tool

- packages/lambdas/src/sqs-to-converter.ts
refs. metriport/metriport-internal#1161
n/a
validate fhir bundle resp in sidechain lambda, pick random key
asap
> fix(api): validate fhir bundle resp in sidechain lambda, pick random key

- README.md
refs. metriport/metriport-internal#91
n/a
update checkly badge
asap
> chore: update checkly badge

- packages/lambdas/src/fhir-to-medical-record.ts
- packages/lambdas/src/shared/converter.ts
- packages/lambdas/src/sqs-to-converter.ts
Ref: 1158
Add conversion type to post to converter
> fix(api): add conversion type to post to converter

- .github/workflows/deploy-production.yml
Ref. metriport/metriport-internal#1149
Ref: #1149
- https://github.com/metriport/metriport-internal/pull/1176
Works in staging so applying same changes to production
> fix(api): add lambda deploy for prod

- packages/api/src/command/medical/patient/get-patient.ts
- packages/api/src/routes/medical/internal-patient.ts
- packages/utils/src/bulk-insert-patients.ts
Ref: metriport/metriport-internal#1181
- Downstream:
- https://github.com/metriport/metriport-internal/pull/1183
- https://github.com/metriport/metriport/pull/1019
- POST /update-all filtered by patientId
- bulk-insert better phone normalization
> 1081 `POST /update-all` filtered by patientId

- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
Ref: metriport/metriport-internal#1188
none
CI/CD to run w/ changes to `core` and `api-sdk`
- nothing special, no release expected
> 1188 cicd to run w/ code and sdk changes

- packages/api/src/command/medical/document/document-download.ts
Ref: #1158
Error with build issue with xml mime type
ASAP
> fix(api): remove ismimexml from repo causing build

- docs/medical-api/more-info/sandbox.mdx
- packages/api/src/command/medical/patient/convert-fhir-bundle.ts
- packages/api/src/shared/config.ts
- packages/infra/lib/api-stack.ts
- packages/infra/lib/api-stack/api-service.ts
Ref: #1033 
- Update patient matching
- FHIR To MR shouldnt be in sandbox
- Fix seed patients
> fix(api): no fhirtomr in sandbox and fix seed patients

- docs/medical-api/api-reference/document/post-upload-url.mdx
- package-lock.json
- packages/api/package.json
- packages/api/src/command/medical/admin/upload-doc.ts
- packages/api/src/routes/medical/document.ts
- packages/core/package.json
- packages/core/src/external/aws/lambda-logic/document-uploader.ts
- packages/core/src/external/aws/s3.ts
- packages/lambdas/package-lock.json
- packages/lambdas/package.json
- packages/lambdas/src/document-uploader.ts
refs. metriport/metriport#960
- Removed the size restriction on file upload
- Added alert if file is too large
- To test the file upload, use the `/src/document/document-upload.ts`
- Merge this
- Test on develop
- Release
> fix(sdk): removed the content-length restriction on file upload

- packages/api/src/command/medical/admin/upload-doc.ts
- packages/api/src/external/fhir/document/draft-update-document-reference.ts
refs. metriport/metriport#960
- DocRef.extension update is now being updated properly
> fix(docs): fixed a bug with extension not being updated on docref

- package-lock.json
- packages/core/package.json
- packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
Ref: #1033 
Add reports for the MR documetn
> fix(api): update code to include encounters from reports

- packages/lambdas/package-lock.json
- packages/lambdas/package.json
Ref: #1033 
Update package 
ASAP
> fix(api): update package almdab core

- package-lock.json
- packages/core/package.json
- packages/lambdas/src/fhir-to-medical-record.ts
Ref: #1158
Update core package ref and add lodash to core package
> fix(api): add lodash to core and update lambda referecne

- packages/lambdas/package-lock.json
- packages/lambdas/package.json
Ref: #1033 
Update core package in lambda
> fix(api): update core package

- packages/infra/lib/api-stack.ts
Ref: #1033 
Add chromium to the lambda
> fix(api): add chromium to the lambda

- packages/infra/lib/api-stack.ts
> fix(api): change layer name

- packages/infra/lib/api-stack.ts
Update layer node version
ASAP
> fix(api): update layer node version

- packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
> fix(api): dont parse bundle

- packages/api/src/routes/medical/document.ts
Ref: #https://github.com/metriport/metriport-internal/issues/1216
- awaiting respoinse on downloadUrl 
- ⚠️ POINTING TO MASTER
> fix(mapi): fixed issue with getDocument not returning url

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/api/src/command/medical/document/document-query.ts
- packages/api/src/external/aws/appConfig.ts
- packages/api/src/shared/config.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/core/src/external/aws/appConfig.ts
- packages/infra/lib/api-stack.ts
- packages/infra/lib/api-stack/api-service.ts
- packages/infra/lib/app-config-stack.ts
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/tester-node/package.json
- packages/utils/package.json
refs. metriport/metriport#1058
n/a
add feature flag support for enhanced coverage
> feat(api): add feature flag support for enhanced coverage

- packages/infra/lib/api-stack.ts
Ref: #1033 
Update lambda node version
> fix(api): update lambda node version

- packages/api/src/routes/medical/document.ts
- packages/api/src/routes/medical/schemas/documents.ts
Ref: #https://github.com/metriport/metriport-internal/issues/1217
- DownloadUrl bug fix 
- ASAP
> PATCH RELEASE 2023-10-30

- packages/infra/lib/api-stack.ts
Ref. [metriport/metriport-internal#1158](https://github.com/metriport/metriport/pull/1068)
Update node version for lambda fhir-mr
asap
> RELEASE - Update lambda node version - 2023/10/30

- packages/infra/lib/api-stack/api-service.ts
refs. metriport/metriport#1058
fix permissions for OSS API app config on CDK
asap
> feat(api): fix permissions for OSS API app config on CDK

- packages/api/src/external/aws/appConfig.ts
refs. metriport/metriport#1058
n/a
fix parsing of feature flag
asap
> feat(api): fix parsing of feature flag

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
- packages/infra/package.json
- packages/lambdas/package-lock.json
- packages/lambdas/package.json
- packages/react-native-sdk/package.json
- packages/tester-node/package.json
- packages/utils/package.json
Ref: https://github.com/metriport/metriport/pull/1077
Update logic for filtering encounters in core
ASAP
> Patch release core

- .github/workflows/_check-commits.yml
- https://github.com/metriport/metriport/pull/1081
Fix which PR ref branch we validate on check commit msg
- asap
> 1040 fix PR ref branch on check commit msg

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
- packages/infra/package.json
- packages/lambdas/package-lock.json
- packages/lambdas/package.json
- packages/react-native-sdk/package.json
- packages/tester-node/package.json
- packages/utils/package.json
Ref: #1033 
Update MR by making AWE its own section, and adding earliest and latests for conditions
POINTING TO MASTER
> RELEASE - MR updates

- packages/api/src/external/commonwell/document/document-query-sandbox.ts
Ref: #799
Issue in sandbox when querying docs that the convert stalls.
For reference https://metriport.slack.com/archives/C0627AB65AB/p1698842626026559
asap
> fix(api): update count if dont convert

- packages/infra/config/env-config.ts
- packages/infra/lib/api-stack.ts
- packages/infra/lib/ihe-stack.ts
- packages/lambdas/src/ihe.ts
refs. metriport/metriport-internal#1222
- Upstream: https://github.com/metriport/metriport-internal/pull/1224
add ihe api in staging env - see ticket for details (this will be available at `ihe.staging.metriport.com`)
> feat(api): add ihe api in staging env

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
- packages/lambdas/package-lock.json
- packages/lambdas/package.json
- packages/utils/package.json
Ref: #1158
Update packages for core
asap
> 1158 fhir to mr updates

- docs/_snippets/address.mdx
- docs/_snippets/patient-address.mdx
- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/models/common/address.ts
- packages/api/package.json
- packages/api/src/routes/medical/schemas/address.ts
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/commonwell-sdk/src/models/address.ts
- packages/connect-widget/package.json
- packages/core/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/tester-node/package.json
- packages/utils/package.json
- packages/utils/src/initialize-cw-test-env/index.ts
Ref: #799
Only accept USA as an option for schema
POINTING TO MASTER
> fix(api): patch the country to only accept usa

- packages/api/src/routes/medical/internal-docs.ts
- packages/core/src/util/__tests__/concurrency.test.ts
- packages/core/src/util/concurrency.ts
- packages/infra/dashboards/cw-dashboard-prod.json
- packages/lambdas/src/cw-link-patients.ts
- packages/lambdas/src/cw-patients-grouping.ts
- packages/utils/src/bulk-query-patients.ts
- packages/utils/src/commonwell/doc-query-shared.ts
- packages/utils/src/commonwell/enhance-coverage.ts
- packages/utils/src/lambda/execute-lambda.ts
none
- enhanced coverage util also triggers doc query
- adds script to run lambda from local/utils
- improve executeAsynchronously()
- add OS search time to prod's dash
- nothing special, mostly utils
> 1195 enhanced coverage util also triggers doc query

- packages/lambdas/package-lock.json
- packages/lambdas/package.json
Ref: https://github.com/metriport/metriport-internal/issues/1148
Fix lambda layer
> PATCH RELEASE 1148

- packages/core/src/external/commonwell/management/api.ts
- packages/utils/src/commonwell/enhance-coverage.ts
none
- increase timeout to include list
- sleep before doc query
> 1195 increase timeout to include list + sleep before doc query

- packages/api/src/domain/medical/patient-facility.ts
> PATCH RELEASE #1195

- packages/api/src/command/medical/patient/consolidated-get.ts
refs. metriport/metriport-internal#1234
n/a
map binary data to diagnostic report - see issue for context
asap
> fix(api): map binary data to diagnostic report

- packages/core/src/external/commonwell/management/link-patients.ts
none
Increase timeout to `POST /update-all`
> 1195 increase timeout to /update-all

- packages/api/src/command/medical/patient/consolidated-get.ts
Ref. metriport/metriport#1130
Check bundle for resources before creating MR
asap
> fix(api): check bundle for resources

- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/client/metriport.ts
- packages/api/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/utils/package.json
Ref: #1087 #1106 
- NPM changes
> 1087 1221 npm release

- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/client/metriport.ts
- packages/api/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/utils/package.json
Ref: #1105 #1087 
- NPM changes to develop
> 1087 1221 npm prod release

- packages/commonwell-sdk/__tests__/commonwell-sdk.test.js
- packages/commonwell-sdk/jest.config.ts
- packages/commonwell-sdk/src/__tests__/env-setup.ts
- packages/commonwell-sdk/src/common/__tests__/validate-npi.test.ts
- packages/commonwell-sdk/src/common/validate-npi.ts
Refs: #1129
- fixing edge case of the sum of the digits being a 10
> feat(npi): validation error fixed

- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/client/metriport.ts
- packages/api/package.json
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/utils/package.json
Ref: https://github.com/metriport/metriport-internal/issues/1129
- upstream: none
- downstream: https://github.com/metriport/metriport-internal/pull/1239
PR: https://github.com/metriport/metriport/pull/1137
> RELEASE #1129

- package-lock.json
- packages/api/package.json
- packages/core/package.json
- packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
refs. metriport/metriport-internal#1234
n/a
put meds under awes for mr summary rendering
> feat(api): put meds under awes for mr summary rendering

- packages/core/src/external/commonwell/management/link-patients.ts
- packages/core/src/util/log.ts
- packages/lambdas/package-lock.json
- packages/lambdas/package.json
- packages/utils/src/bulk-insert-patients.ts
- packages/utils/src/commonwell/enhance-coverage.ts
Ref: metriport/metriport-internal#1129
none
- update lambda dependency to CW SDK - fixes [this](https://metriport.slack.com/archives/C04T256DQPQ/p1699474853587999)
- time between CQ include list and /update-all
- don't revert CQ org list if original was empty
- adjust bulk-insert minimum column requirements
- nothing special, just asap
> 1129 update lambda dependency to CW SDK

- packages/api/src/routes/helpers/request-analytics.ts
- packages/utils/src/bulk-insert-patients.ts
none
Bulk insert accepts both address and addressLine
> 1195 bulk insert accepts both address and addressLine

- docs/_snippets/devices-api-init.mdx
refs. metriport/metriport#1154
- Fixed a typo in the DAPI Getting Started page
> fix(docs): fixed a typo in dapi docs

- packages/core/src/external/aws/lambda-logic/document-uploader.ts
refs. metriport/metriport-internal#1242
- Fixed the file naming for the file relocation during document upload
- Merge this
> fix(core): fixed the destination key for uploaded files

- docs/_snippets/webhook-metadata-post-example.mdx
- docs/_snippets/webhook-request-metadata.mdx
- docs/medical-api/api-reference/document/start-document-query.mdx
- docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx
Ref: metriport/metriport-internal#517
n/a
fix docs metadata bugs and typos
asap
> docs: fix metadata bugs and typos

- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/models/common/address.ts
- packages/api/package.json
- packages/api/src/command/medical/patient/__tests__/test_data.ts
- packages/api/src/domain/medical/__tests__/location-address.ts
- packages/api/src/domain/medical/address.ts
- packages/api/src/shared/sandbox/sandbox-seed-data.ts
- packages/connect-widget/package.json
- packages/core/package.json
- packages/infra/package.json
- packages/utils/package.json
- packages/utils/src/bulk-insert-patients.ts
- packages/utils/src/initialize-cw-test-env/index.ts
Ref: #https://github.com/metriport/metriport/issues/1158
- Updated the address state to be limited to 2-letter valid US state codes
- ✅ Update existing patients to conform to this new standard: No prod patients affected.
> 1158 address state fix

- packages/api/src/routes/medical/internal-patient.ts
- packages/infra/lib/api-stack/cw-enhanced-coverage-connector.ts
- packages/utils/session-manager-daemon.sh
none
- run EC every day/hour
- add daemon script for EC
> 1195 run EC every day/hour

- packages/api/src/routes/medical/internal-patient.ts
- packages/infra/lib/api-stack/cw-enhanced-coverage-connector.ts
- packages/utils/session-manager-daemon.sh
Ref: https://github.com/metriport/metriport-internal/issues/1195
PR: https://github.com/metriport/metriport/pull/1166
- ⚠️ this is pointing to master
> RELEASE 1195 run EC at all times

- packages/api/src/external/commonwell/cq-bridge/coverage-enhancement-check-stale.ts
- packages/api/src/external/commonwell/cq-bridge/coverage-enhancement-complete.ts
- packages/api/src/routes/medical/internal-patient.ts
- packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
- packages/infra/lib/api-stack/cw-enhanced-coverage-connector.ts
Ref: https://github.com/metriport/metriport-internal/issues/1195
Add more time for EC
> PATCH RELEASE 1195 more time for EC

- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/client/metriport.ts
- packages/api/package.json
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/tester-node/package.json
- packages/utils/package.json
Ref: #1104
- https://github.com/metriport/metriport/pull/1113
- NPM prod release for hmac changes
> 1104 npm release prod

- docs/home/api-info/webhooks.mdx
Ref: #1104
- fix docs visual issue 
> PATCH RELEASE 1104 docs update

- docs/home/api-info/webhooks.mdx
Ref: #1178 
- fix mistaken python docs example
> PATCH RELEASE 1104 python docs update

- package-lock.json
- packages/api-sdk/package.json
- packages/connect-widget/package.json
- packages/tester-node/package.json
Ref: https://github.com/metriport/metriport-internal/issues/1195
PR: https://github.com/metriport/metriport/pull/1191
- ⚠️ pointing to `master`
> RELEASE 1195

- .github/workflows/_build.yml
- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/pull-request_core.yml
- .github/workflows/pull-request_ihe-gateway-sdk.yml
- .github/workflows/pull-request_shared.yml
refs. metriport/metriport-internal#1251
- Updated the Github workflows to include the new packages
> feat(cicd): upd github workflows

- packages/scripts/deploy-api.sh
refs. metriport/metriport-internal#1251
- Updated the scripts for api deploy with references to 2 new pkgs
> fix(scripts): updated deploy-api scripts

- packages/api/src/command/medical/patient/get-patient.ts
- packages/api/src/command/medical/patient/query-init.ts
- packages/api/src/command/medical/patient/update-patient.ts
- packages/api/src/external/commonwell/cq-bridge/cq-link-status.ts
- packages/api/src/external/commonwell/patient-external-data.ts
- packages/api/src/models/transaction-wrapper.ts
Ref: https://github.com/metriport/metriport-internal/issues/1267
none
Make all patients updates to happen within a DB tx.
> PATCH RELEASE all updates to patient within DB tx

- packages/api/src/external/commonwell/document/document-query.ts
- packages/core/src/external/aws/lambda.ts
- packages/core/src/external/commonwell/document/document-downloader-local.ts
refs. metriport/metriport-internal#1205
- Sentry reporting was done before the condition that should prevent it for CW 404
> fix(mapi): fixed sentry reporting on cw 404

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/carequality-sdk/package.json
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
- packages/ihe-gateway-sdk/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/shared/package.json
- packages/tester-node/package.json
- packages/utils/package.json
refs. metriport/metriport-internal#11589
n/a
remove AWE confirmation from MR summary
> fix(packages): remove AWE confirmation from MR

- fern/definition/medical/patient.yml
Update the `contacts` property that is typed as `optional<List<Contact>>`. 
To update the SDKs, run the release SDKs github workflow and the SDKs will update.
> Update `contact` property in `BasePatient`

- packages/api/.gitignore
- packages/api/src/external/commonwell/organization.ts
- packages/api/src/routes/internal.ts
- packages/utils/src/commonwell/enhance-coverage.ts
none
- improved EC script
- improve reset CQ include list endpoint
> 1195 improved EC script + reset CQ include list endpoint

- packages/ihe-gateway/.gitignore
- packages/ihe-gateway/Dockerfile
- packages/ihe-gateway/docker-compose.yml
- packages/ihe-gateway/entrypoint.sh
refs. metriport/metriport-internal#1261
n/a
update mirth SSL setup
asap
> feat(gateway): update mirth SSL setup

- packages/api/src/external/carequality/organization.ts
- packages/api/src/shared/config.ts
refs. metriport/metriport-internal#1265
- Fixes the issue with the CQ ORG DETAILS treated like a required field when it's actually optional
- Nothing special, ASAP
> fix(mapi): fixed cq org details error

- packages/api/src/external/commonwell/cq-bridge/coverage-enhancer-api-local.ts
- packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
- packages/core/src/util/capture.ts
- packages/utils/src/commonwell/enhance-coverage.ts
Ref: metriport/metriport#1195
- Upstream: https://github.com/metriport/metriport/pull/1237
Notify us on partial EC errors.
- asap
> PATCH RELEASE 1195 notify on partial EC errors

- packages/utils/src/create-mr-for-patients.ts
- A slight improvement to the mr creation script
> feat(utils): added dir creation to the script

- packages/api/src/command/medical/admin/api.ts
- packages/api/src/routes/internal.ts
- packages/infra/lib/api-stack.ts
- packages/infra/lib/api-stack/api-quota-checker.ts
> 1154 add api quota checker

- packages/api/src/external/commonwell/patient-external-data.ts
Ref: metriport/metriport#1192
Revert CW data check on DQ
> PATCH RELEASE 1192

- packages/api/src/external/commonwell/patient-external-data.ts
Fix CW data check on DQ
- asap
> PATCH RELEASE 1154

- packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
- packages/core/src/external/commonwell/cq-bridge/coverage-enhancer.ts
Ref: metriport/metriport#1195
Restore original CQ include list @ CW when running EC - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1701232026090999)
> PATCH RELEASE 1195

- packages/ihe-gateway/ihe-gateway-setup.xml
Update the backup with the latest xcpd channel and valid xml 
> fix(packages): Update the backup with the latest xcpd channel and valid xml

- packages/api/src/command/medical/document/document-query.ts
- packages/api/src/command/medical/patient/consolidated-get.ts
- packages/api/src/shared/util.ts
- packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
- packages/core/src/external/commonwell/management/api.ts
- packages/core/src/external/commonwell/management/link-patients.ts
- packages/core/src/util/log.ts
- packages/shared/src/common/general.ts
- packages/shared/src/index.ts
Ref: metriport/metriport#1195
none
- decrease log on EC
- move emptyFunction to shared and update usages
> 1195 decrease log on EC

- packages/api/src/command/medical/patient/consolidated-get.ts
- packages/api/src/routes/medical/internal-patient.ts
- packages/api/src/routes/medical/patient.ts
- packages/utils/package.json
- packages/utils/src/bulk-insert-patients.ts
- packages/utils/src/commonwell/enhance-coverage.ts
- packages/utils/src/create-mr-for-patients.ts
- packages/utils/src/shared/get-cx-data.ts
Ref: https://github.com/metriport/metriport-internal/issues/1040
none
MR creation script
> 1040 MR creation script

- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
- package-lock.json
- package.json
- packages/lambdas/scripts/build-shared-layer.sh
- Fix lambda build
- [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1701408848673629)
> PATCH RELEASE Fix lambda build

- packages/api/src/command/webhook/tenovi.ts
- packages/api/src/mappings/tenovi/biometrics.ts
- packages/api/src/mappings/tenovi/constants.ts
- packages/api/src/mappings/tenovi/index.ts
Ref: https://github.com/metriport/metriport-internal/issues/1321
- new metric type was added, and we found out about it by chance while looking at aws logs. this fix gives it more vis
> 1321 tenovi tweaks

- packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
Update EC logs error message to have the correct length
> fix(core): update cq ec logs

- packages/api-sdk/src/medical/models/common/us-data.ts
- packages/api/src/routes/medical/schemas/address.ts
- packages/api/src/routes/medical/schemas/patient.ts
Refs: #1285 
- allowing lowercase state names as inputs and then transforming them to uppercase
> fix(caps): allowing lowercase state names

- package-lock.json
- packages/api-sdk/package.json
- packages/api-sdk/src/medical/models/common/us-data.ts
- packages/api/src/app.ts
- packages/api/src/routes/medical/schemas/address.ts
- packages/api/src/routes/medical/schemas/patient.ts
- packages/connect-widget/package.json
- packages/tester-node/package.json
Tickets:
- https://github.com/metriport/metriport-internal/issues/1323
- https://github.com/metriport/metriport/issues/1285
PRs:
- https://github.com/metriport/metriport/pull/1293
- https://github.com/metriport/metriport/pull/1286
> RELEASE 1320 1323

- packages/api/src/external/commonwell/document/document-query.ts
- packages/api/src/external/commonwell/link/get.ts
- packages/api/src/routes/medical/internal-patient.ts
- packages/commonwell-sdk/src/index.ts
- packages/commonwell-sdk/src/models/link.ts
- packages/commonwell-sdk/src/models/patient-organization.ts
- packages/commonwell-sdk/src/models/patient.ts
Include network links on internal get links. More context [here](https://metriport.slack.com/archives/C0616FCPAKZ/p1701889931390139?thread_ts=1701883477.074949&cid=C0616FCPAKZ).
> PATCH RELEASE include network links on internal get links

- .github/pull_request_template.md
none
New PR template - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1701575889071549).
> 1040 new PR template

- package-lock.json
- packages/api-sdk/package.json
- packages/api/package.json
- packages/carequality-cert-runner/package.json
- packages/carequality-sdk/package.json
- packages/commonwell-cert-runner/package.json
- packages/commonwell-jwt-maker/package.json
- packages/commonwell-sdk/package.json
- packages/connect-widget/package.json
- packages/core/package.json
- packages/ihe-gateway-sdk/package.json
- packages/infra/package.json
- packages/react-native-sdk/package.json
- packages/shared/package.json
- packages/tester-node/package.json
- packages/utils/package.json
Ticket: #799
Update the name for cq cert runner package
none
nohing special
> 799 fix certrunner name

- packages/api/src/app.ts
Ref: metriport/metriport-internal#799
Kill the API if it fails to load DB - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1702084424449759).
- Local
- Staging
- Production
> 799 kill the API if it fails to load DB

- packages/infra/lib/location-services-stack.ts
refs. metriport/metriport-internal#1302
n/a
_[Document your changes, give context for reviewers, add images/videos of UI changes]_
n/a
refer to previous PR https://github.com/metriport/metriport/pull/1314
> feat(infra): fix location services stack to point to stack

- .github/workflows/deploy-staging.yml
refs. metriport/metriport-internal#1302
n/a
temporarily don't deploy location stack in staging - to remove from original stack
n/a
refer to original PR
> feat(infra): temporarily don't deploy location stack in staging

- .github/workflows/deploy-staging.yml
refs. metriport/metriport-internal#1302
n/a
add back deploy location stack in staging
n/a
see original PR
> feat(infra): add back deploy location stack in staging

- packages/api/src/command/medical/cq-directory/rebuild-cq-directory.ts
refs. metriport/metriport-internal#1302
- Added a comment for a future TODO
> feat(infra): added a todo for cq prod release

- packages/core/src/external/carequality/iti-38-template.ts
- packages/core/src/external/carequality/iti-39-template.ts
- packages/core/src/external/carequality/iti-55-template.ts
- packages/lambdas/src/ihe.ts
Refs: #1329
- formatting patch to satisfy qvera
- Local
> feat(xcpd): removing whitespace at front of response

- packages/api/src/external/commonwell/patient-conversion.ts
- packages/api/src/external/commonwell/patient-shared.ts
- packages/commonwell-sdk/src/models/contact.ts
refs. metriport/metriport#1329
n/a
send telecom/contact info to CW
- Local
- N/A
- Staging
- Production
> fix(api): send telecom/contact info to CW

- packages/core/src/external/aws/s3.ts
- packages/core/src/external/commonwell/document/document-downloader-local.ts
- packages/core/src/util/file-type.ts
- packages/core/src/util/mime.ts
> Patch mime type xml

- packages/core/src/external/commonwell/document/document-downloader-local.ts
Refs: #000
- weird github versioning issues caused some changes to not be merged. That is unresolved but lets still ship the fix. 
- Local
> feat(mime): uncommenting out commented out mime type code

- packages/infra/dashboards/cw-dashboard-prod.json
- packages/infra/lib/api-stack.ts
none
update API DB/RDS alarms
Peak Read IOPS vs ACU in the last 6 weeks - [metrics](https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#metricsV2?graph=~(metrics~(~(~'AWS*2fRDS~'VolumeReadIOPs~'DBClusterIdentifier~'api-cluster~(id~'m2~label~'VolumeReadIOPs~region~'us-west-1~yAxis~'right))~(~'.~'VolumeWriteIOPs~'.~'.~(yAxis~'right~id~'m1~region~'us-west-1~visible~false))~(~'.~'ACUUtilization~'.~'.~(yAxis~'left~stat~'Average)))~view~'timeSeries~stacked~false~region~'us-west-1~stat~'Maximum~period~300~title~'API*20DB*20-*20IOPS~liveData~false~annotations~(horizontal~(~(visible~false~label~'VolumeWriteIOPs*20*3e*3d*2050_000*20for*201*20datapoints*20within*205*20minutes~value~50000~yAxis~'right)))~start~'2023-12-09T08*3a38*3a00.149Z~e …
> 1040 update API DB/RDS alarms

- packages/infra/dashboards/cw-dashboard-prod.json
- packages/infra/lib/shared/open-search-construct.ts
none
Add alarms to open search
- Local
- none
- Staging
- Production
> build: add alarms to open search

- fern/definition/fhir/__package__.yml
- fern/dependencies.yml
- fern/generators.yml
For visibility and review by Deep!
Bumping Fern generators which include performance enhancements to handle the FHIR specs!
> [DNM] Add back in fern deps and bump generator versions

- .github/CODEOWNERS
- packages/core/src/external/commonwell/document/document-downloader-local.ts
PRs:
- https://github.com/metriport/metriport/pull/1350
- https://github.com/metriport/metriport/pull/1352
- https://github.com/metriport/metriport/pull/1353
- Staging
- Production
> RELEASE update db alarms

- fern/dependencies.yml
- fern/generators.yml
- package-lock.json
- packages/sdks/java/tester-local/src/test/java/com.metriport/TestCreateDocumentReference.java
- packages/sdks/typescript/tester-node/package.json
Includes fixes that address to compile/build errors
> Bump Fern dependencies once more for compile fixes

- packages/core/src/external/carequality/iti-39-template.ts
Refs: #[1381](https://github.com/metriport/metriport-internal/issues/1381)
- adding a tag
- merge to develop asap
> feat(tag): patch

- packages/core/src/external/carequality/iti-39-parsing.ts
- packages/core/src/external/carequality/iti-39-template.ts
- packages/core/src/external/carequality/iti-55-template.ts
Refs: #1381
- urn::oid duplicate
- Local
> feat(urn): fix

- packages/api/src/external/carequality/mock-patient-discovery.ts
- packages/core/src/external/carequality/docs.ts
- packages/core/src/external/carequality/iti-38-parsing.ts
- packages/core/src/external/carequality/iti-55-parsing.ts
- packages/core/src/external/carequality/iti-55-template.ts
Refs: #[1381](https://github.com/metriport/metriport-internal/issues/1381)
- updating the home Community Id. 
- fixing messageId which is undefined
- qvera wants it
> feat(home): updating home community id

- packages/core/src/external/carequality/iti-39-template.ts
Refs: #1381
- missing slash
- online xml parser I was using is bad and didnt catch that
> feat(slash): added missing slash

- packages/lambdas/src/sqs-to-converter.ts
Ref. metriport/metriport-internal#1392
Ticket: 1392
Fix bug in prod with null flavor in xml
- Production
> 1392 id null flavors

- packages/core/src/external/carequality/iti-39-parsing.ts
- packages/core/src/external/carequality/iti-39-template.ts
- packages/lambdas/src/ihe.ts
- packages/utils/src/mock-ihe-gateway.ts
Refs: #1381
- adding MTOM response type for dr requests. 
- not production code. hopefully last PR before getting go ahead from testing partners.
- Local
> feat(mtom): implemented mtom response for iti39

- packages/api/src/command/medical/document/document-reconvert.ts
Reintroduce querying doc refs from the DB's doc ref mapping so we can filter by created at properly.
- Local
- Production
- execute the [release plan](https://metriport.slack.com/archives/C04GEQ1GH9D/p1704061018033979?thread_ts=1703894243.751199&cid=C04GEQ1GH9D)
> PATCH RELEASE 1392

- packages/utils/src/bulk-delete-patients.ts
refs. metriport/metriport-internal#1398
n/a
script to delete patients in bulk
- Local
> feat(utils): script to delete patients in bulk

- packages/infra/lib/ihe-stack.ts
Refs: #1356
- patch for ci/cd failing on develop due to duplicate naming on api gateway resources  
- Staging
> feat(patch): removing duplicate resources

- packages/infra/README.md
n/a
update infra/iac readme
n/a
> docs: update iac readme

- .github/pull_request_template.md
none
Update PR template, add sandbox and more
none
> 1040 update PR template, add sandbox and more

- packages/infra/lib/api-stack.ts
Ticket: #799
Minor change to api stack to check if it takes out any manual work
> PATCH: api infra change

- packages/lambdas/src/sqs-to-converter.ts
n/a
update lambda config
- Production
> PATCH: update lambda config2

- packages/infra/lib/api-stack.ts
- packages/lambdas/src/sqs-to-fhir.ts
n/a
update lambda config add access to correct bucket
- Production
> 1441 update lambda config4

- packages/lambdas/src/sqs-to-converter.ts
- packages/lambdas/src/sqs-to-fhir.ts
n/a
move id replace to converter lambda
- Production
> 1441 update lambda config5

- packages/fhir-converter/src/lib/cda/cda.js
update preprocessor to concat original text
> feat(api): update preprocessor to concat original text
