metriport/metriport

packages/fhir-converter/src/templates/cda/Resources/Condition.hbs

- Updated the Condition resource to properly render the clinicalStatus and category attributes
- Local
- Merge this

fix(fhir): upd condition resource

---

packages/fhir-converter/src/templates/cda/DataType/HumanName.hbs
packages/fhir-converter/src/templates/cda/Resources/Patient.hbs
packages/fhir-converter/src/templates/cda/Resources/Procedure.hbs
packages/fhir-converter/src/templates/cda/Utils/ResourceTypeFromSection.hbs

- procedure
- guardian/relatedPerson
- patient.maritalStatus 
tested

1441 procedure, guardian/relatedPerson, patient

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/DataType/CodeableConcept.hbs
packages/fhir-converter/src/templates/cda/Resources/Observation.hbs
packages/fhir-converter/src/templates/cda/ValueSet/SystemReference.hbs

Refs: #1441
- updating system references to have more values
- updating coding to be able to handle better multiple translation objects and also none and also singular
- there were a few oids I could not figure out what code system they were: 2.16.840.1.113883.3.88.12.3221.5.2, 2.16.840.1.113883.5.111, 
- Local
Check each PR.

feat(api): fixing translation issue in coding and system references

---

packages/fhir-converter/src/templates/cda/Resources/MedicationStatement.hbs

feat(api): finish meds mapping

---

packages/fhir-converter/src/templates/cda/ccd.hbs

add all unused sections to main ccd template

feat(api): add all unused sections to main ccd template

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

Ticket: #1441
Update the medication section in MR Summary
Ran locally

fix(api): update mr medications section

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

Ticket: #[1441](https://github.com/metriport/metriport-internal/issues/1441)
- fixing social history vitals section 
- Local

1441 mr observation vitals

---

packages/fhir-converter/src/templates/cda/Resources/Coverage.hbs
packages/fhir-converter/src/templates/cda/Sections/Payers.hbs

- coverage - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1705870984892399)
works local

1441 coverage

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Resources/Observation.hbs

Ticket: #[1441](https://github.com/metriport/metriport-internal/issues/1441)
- fixing string errors
- Local

feat(api): string error resulting in doc loss

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

Ticket: #[1441](https://github.com/metriport/metriport-internal/issues/1441)
- fixing labs observation section 
- Local

1441 observation labs other

---

packages/fhir-converter/package-lock.json
packages/fhir-converter/package.json
packages/fhir-converter/src/lib/cda/cda.js
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Resources/DiagnosticReport.hbs
packages/fhir-converter/src/templates/cda/Resources/Procedure.hbs
packages/fhir-converter/src/templates/cda/Sections/History_of_Present_Illness.hbs
packages/fhir-converter/src/templates/cda/Sections/Notes.hbs
packages/fhir-converter/src/templates/cda/ccd.hbs

feat(api): add notes in diag report v0

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/Resources/Procedure.hbs

Ticket: #1441
Update the procedures section in MR Summary
Ran locally

fix(api): update mr procedrues section

---

packages/fhir-converter/src/templates/cda/Sections/History_of_Present_Illness.hbs
packages/fhir-converter/src/templates/cda/Sections/Notes.hbs

feat(api): add performers on notes

---

packages/fhir-converter/src/lib/cda/cda.js
packages/fhir-converter/src/templates/cda/DataType/CodeableConcept.hbs

retry after minification, don't escape codable text

feat(api): retry after minification, don't escape codable text

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/DataType/Period.hbs
packages/fhir-converter/src/templates/cda/Resources/Encounter.hbs
packages/fhir-converter/src/templates/cda/Sections/Encounters.hbs

Ticket: #_[ticket-number]_1441
- Updated the `Encounter` mapping and adjusted the corresponding section in the MR summary gen code
- Local

1441 encounter upd

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Resources/Composition.hbs
packages/fhir-converter/src/templates/cda/Resources/DocumentReference.hbs
packages/fhir-converter/src/templates/cda/Resources/Immunization.hbs
packages/fhir-converter/src/templates/cda/Sections/Immunization.hbs

Ticket: #_[ticket-number]_1441
- Fixed the `Immunization` section mapping
- Local

1441 immunization upd

---

packages/fhir-converter/src/lib/cda/cda.js

- replace invalid time
- Local

1441 replace invalid time

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

Ticket: #1441
Update the medication and conditions section in MR Summary
Ran locally

fix(api): update mr conditions and medications section

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/Resources/Procedure.hbs

feat(api): fix procedure mapping

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

feat(api): fix social mapping

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/lib/cda/cda.js
packages/fhir-converter/src/templates/cda/Resources/Observation.hbs

add text if present to observation code

feat(api): add text if present to observation code

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

- Improved `Condition` name MR mapping

fix(fhir): upd condition mr section

---

packages/fhir-converter/src/lib/cda/cda.js

feat(api): fix newlines

---

packages/fhir-converter/src/lib/cda/cda.js

don't duplicate b64 notes in cda

feat(api): don't duplicate b64 notes in cda

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/References/Coverage/payor.hbs
packages/fhir-converter/src/templates/cda/Sections/Payers.hbs

Ticket: #1441
Update the coverage section in MR Summary
Ran locally

1441 update coverage

---

packages/fhir-converter/src/templates/cda/Sections/Results.hbs

fix diag report refs to org + practitioner

feat(api): fix diag report refs to org + practitioner

---

packages/fhir-converter/Dockerfile
packages/fhir-converter/package.json
packages/fhir-converter/src/index.js

move converter docker img to node 18

feat(api): move converter docker img to node 18

---

packages/fhir-converter/src/templates/cda/Resources/Patient.hbs

Ticket: #_[ticket-number]_1441
- Patient gender fix
- Local

fix(fhir): upd patient gender fix

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/Resources/DiagnosticReport.hbs

Ticket: #1441
- downstream: https://github.com/metriport/metriport/pull/1462
Update the reports section in MR Summary + whatever else gets added
Ran locally

fix(api): update converter 2

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

feat(api): dedup social history

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/Header.hbs
packages/fhir-converter/src/templates/cda/Resources/RelatedPerson.hbs

Ticket: #_[ticket-number]_1441
- Fixed the `RelatedPerson` mapping for converter and MR
- Local

fix(fhir): upd related persons

---

packages/core/src/util/__tests__/concurrency.test.ts
packages/core/src/util/concurrency.ts
packages/fhir-converter/package.json
packages/fhir-converter/src/lib/git-filesystem/git-filesystem.spec.js
packages/utils/src/fhir-converter/count-resources.ts
packages/utils/src/fhir-converter/e2e-test.ts
packages/utils/src/fhir-converter/shared.ts
packages/utils/src/shared/fs.ts

- upstream: https://github.com/metriport/metriport/pull/1484
- downstream: https://github.com/metriport/metriport/pull/1483
- e2e test for fhir converter
- runs with or without FHIR server
- count FHIR bundles' resources - from a file or directory w/ files
- 👉  improve `executeAsynchronously` to be more efficient in parallel processing
- Local

1441 e2e test for fhir converter

---

packages/fhir-converter/package.json
packages/utils/src/fhir-converter/convert-and-generate-mr.ts
packages/utils/src/fhir-converter/convert.ts
packages/utils/src/fhir-converter/e2e-test.ts
packages/utils/src/fhir-converter/shared.ts
packages/utils/src/shared/fs.ts

Ref: metriport/metriport-internal#1441
- Upstream: https://github.com/metriport/metriport/pull/1462
- script to generate MR from XML folder
- fix start cmd on package.json
- Local

build: script to generate MR from XML folder

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/utils/src/customer-requests/medical-records.ts

- Upstream: https://github.com/metriport/metriport/pull/1483
- order medication by date
- add scrip to convert single bundle to MR
- Local

1441 order medication by date

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

- Improved mapping for Family History
- Local

fix(fhir): improved mr mapping for fam history

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/Resources/Condition.hbs

Ticket: #1441
- downstream: https://github.com/metriport/metriport/pull/1462
Update the awe section and medications in MR Summary + whatever else gets added
Ran locally

fix(api): update awe and medications

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

Refs: #1441
- conditions text and dates from encounters
- local 
Check each PR.

feat(api): conditions text and dates from encounters

---

packages/fhir-converter/src/templates/cda/Resources/MedicationAdministration.hbs
packages/fhir-converter/src/templates/cda/Resources/Procedure.hbs
packages/fhir-converter/src/templates/cda/ValueSet/MedicationAdministrationStatus.hbs

add coding handling for MedicationAdministration

feat(api): add coding handling for MedicationAdministration

---

packages/fhir-converter/src/templates/cda/Resources/DiagnosticReport.hbs

set content type on diag report

feat(api): set content type on diag report

---

packages/fhir-converter/src/templates/cda/ValueSet/MedicationAdministrationStatus.hbs
packages/fhir-converter/src/templates/cda/ValueSet/MedicationStatementStatus.hbs

Ticket:  metriport/metriport-internal#1441
fix med statement status code templates

feat(api): fix med statement status code templates

---

packages/core/src/util/concurrency.ts
packages/infra/lib/api-stack/fhir-server-connector.ts
packages/utils/src/commonwell/cq-org-builder.ts
packages/utils/src/fhir-converter/convert-and-generate-mr.ts
packages/utils/src/fhir-converter/convert.ts
packages/utils/src/fhir-converter/e2e-test.ts
packages/utils/src/fhir-converter/validate-fhir-bundles.ts
packages/utils/src/s3/get-objects.ts
packages/utils/src/shared/fs.ts

Ticket: https://github.com/metriport/metriport-internal/pull/1141
- upstream: https://github.com/metriport/metriport/pull/1509
- fhir converter e2e tests results on ./runs folder 
- bump up FHIR server and lambda throughput 
- Local
- Staging
- none
- Production

1441 fhir server infra bump + fhir converter e2e tests

---

packages/utils/src/fhir-converter/count-bundle-refs.ts
samples/typescript-express/.eslintignore
samples/typescript-express/.eslintrc.js
samples/typescript-express/mock-webhook.ts

Ticket: https://github.com/metriport/metriport-internal/pull/1141
- upstream: https://github.com/metriport/metriport/pull/1509
- Downstream: https://github.com/metriport/metriport/pull/1510
- script to count resources in bundles

1441 add script to count fhir bundle resources and refs

---

packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/external/fhir/references/get-references.ts
packages/api/src/external/fhir/shared/paginated.ts
packages/api/src/routes/internal.ts
packages/core/src/external/fhir/shared/bundle.ts
packages/utils/src/fhir-converter/count-bundle-refs.ts

- Upstream: https://github.com/metriport/metriport/pull/1508
- hydrate consolidated data w/ missing refs
- Local

1441 hydrate consolidated data w/ missing refs

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Resources/Condition.hbs
packages/fhir-converter/src/templates/cda/Resources/Consent.hbs
packages/fhir-converter/src/templates/cda/Resources/FamilyMemberHistory.hbs
packages/fhir-converter/src/templates/cda/Resources/MedicationAdministration.hbs
packages/fhir-converter/src/templates/cda/Resources/MedicationDispense.hbs
packages/fhir-converter/src/templates/cda/Resources/MedicationStatement.hbs
packages/fhir-converter/src/templates/cda/Resources/Observation.hbs
packages/fhir-converter/src/templates/cda/Resources/Patient.hbs

Refs: #[1449](https://github.com/metriport/metriport-internal/issues/1449)
- patch to observation for not having string handling
- pre-emptively patch string handling everywhere else. values that are strings that are not wrapped in strings cause malformed json errors.
- patch for observation having weird chars in value._ that cause malformed json
- routeCode patch
- Local

Misc Patches for FHIR Converter

---

packages/fhir-converter/src/templates/cda/Resources/Observation.hbs
packages/fhir-converter/src/templates/cda/Utils/ObservationCategoryDisplayFromCode.hbs

Refs: #1441
- adding text and display to category objects within observation 
- Local

feat(patch): adding observation category display and text

---

packages/connect-widget/src/index.tsx

Ticket: https://github.com/metriport/metriport-internal/issues/1443
- Upstream: https://github.com/metriport/metriport/pull/1522
- Downstream:https://github.com/metriport/metriport/pull/1524
- harmless update on Widget to test CD not triggered
- Staging
- downstream has additional test
- Sandbox
- none
- Production
- none
- nothing special other than follow dependencies

1443 (2/3) harmless update on Widget

---

packages/infra/lib/api-stack.ts
packages/infra/lib/shared/backup.ts

Ticket: metriport/metriport-internal#1466
n/a
re-introduce backup config after testing on staging
- Staging
- Sandbox
- Production

PATCH RELEASE 2023-01-30

---

.husky/pre-commit
package.json
packages/fhir-converter/full-hbs-lint.sh
packages/fhir-converter/package-lock.json
packages/fhir-converter/package.json
packages/fhir-converter/postprocess-hbs-lint.js
packages/fhir-converter/src/templates/cda/Utils/GenerateId.hbs
packages/fhir-converter/src/templates/cda/Utils/GeneratePractitionerId.hbs

Refs: #[1474](https://github.com/metriport/metriport-internal/issues/1474)
- ember-lint + postprocessing since linter config file isnt working 
- basically ember-template-lint (which is the only handlebars linter that worked I found) has a known issue: https://github.com/ember-template-lint/ember-template-lint/issues/486 which doesn't let you override handlebars-partials in the config. So basically, we have to post-process the linting output for bugs that dont matter to us
- Local
Check each PR.

Linting on Handlebars :crossed_swords:

---

packages/fhir-converter/src/templates/cda/Utils/ContactRoleCode.hbs

Refs: #[1442](https://github.com/metriport/metriport-internal/issues/1442) 
- adding missing role codes 
- Local

Mapping: Missing Role Codes

---

packages/fhir-converter/src/templates/cda/ValueSet/ImmunizationStatus.hbs

Ticket: metriport/metriport#1569
n/a
add suspended immunization code handler
nothing, but this is change is 0 risk - we've patched this stuff before

PATCH RELEASE 2024-02-04: add suspended immunization code handler

---

packages/api/src/external/aws/address.ts

Ref. metriport/metriport-internal#1447
Make location service env vars optional - [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1707146418172079?thread_ts=1707144911.172289&cid=C04DBBJSKGB)

PATCH RELEASE 1447

---

packages/api/src/external/aws/appConfig.ts
packages/api/src/shared/config.ts
packages/core/src/external/aws/appConfig.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/api-service.ts
packages/infra/lib/app-config-stack.ts
packages/lambdas/src/fhir-to-medical-record.ts

Ticket: 1040
CX has specific changes needed to MR summary that we dont want to apply to the rest of the cx's.  As a quick solution added a feature flag to the specific bundle logic that will create a adhd MR.
- Local
- Staging
- Sandbox
- Production

1040 adhd mr

---

packages/fhir-converter/src/templates/cda/Sections/Encounters.hbs
packages/fhir-converter/src/templates/cda/Sections/Hospital_Discharge_Medications.hbs
packages/fhir-converter/src/templates/cda/Sections/Problems.hbs

Ticket: #[1492](https://github.com/metriport/metriport-internal/issues/1442)
- removing and altering unsupported references in different types 
- Local
Check each PR.

Patch 1492 org in practitioner slot

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/tester-node/package.json
packages/utils/package.json

Package update for prod release: https://github.com/metriport/metriport/pull/1593
- api@1.13.3
- @metriport/api-sdk@7.12.0
- @metriport/carequality-cert-runner@1.3.4
- @metriport/carequality-sdk@0.4.4
- @metriport/commonwell-cert-runner@1.13.3
- @metriport/commonwell-jwt-maker@1.10.3
- @metriport/commonwell-sdk@4.12.3
- @metriport/core@1.9.3
- @metriport/ihe-gateway-sdk@0.4.4
- infrastructure@1.8.3
- @metriport/react-native-sdk@1.8.3
- @metriport/shared@0.4.3
- tester-node@1.4.4
- utils@1.10.3

chore(release): publish

---

packages/api/src/external/aws/appConfig.ts
packages/core/src/external/aws/appConfig.ts
packages/lambdas/src/fhir-to-medical-record.ts

Ticket: #799
Add sentry logs for FF - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1707518365180789)

PATCH: Sentry Logs for FF

---

docs/medical-api/more-info/medical-record-summary.mdx

refs. metriport/metriport#1260
- docs nit fix

feat(api): added a dot at the end of a docs sentence

---

packages/infra/lib/ihe-stack/ihe-gw-construct.ts
packages/scripts/deploy-ihe-gw.sh

none
Fix IHE TG health check and CICD deployment script
none

1377 Fix IHE TG health check and CICD deployment script

---

packages/lambdas/src/cw-doc-contribution.ts

none
Adds logs and better error handling CW contrib lambda / DR.
- Local
- none
- Staging
- Sandbox
- none
- Production

1040 logs and better error handling CW contrib lambda

---

.github/workflows/release-all-sdks.yml
.github/workflows/release-java-sdk.yml
.github/workflows/release-node-sdk.yml
.github/workflows/release-python-sdk.yml
fern/generators.yml

Sets up workflows to release all, python, node, and java SDKs.

(chore): setup all and individual sdk releases

---

packages/api/src/external/commonwell/proxy/cw-process-request.ts

Fix CW inbound DQ, uniques resources before returning - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1708121423778309).
- Local
- Production

PATCH RELEASE Fix CW inbound DQ

---

fern/generators.yml

Ensure that the generated SDK does not require optional fields

:herb: Do not require optional fields

---

fern/generators.yml

Refs: #[1219](https://github.com/metriport/metriport/issues/1219)
- Forgot to comment out pr mode

feat(sdk): removing pr mode

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Interface.xml

fix(ihe): fix mirth config

---

packages/api/src/command/medical/patient/delete-patient.ts
packages/api/src/external/carequality/api.ts
packages/api/src/external/carequality/command/cq-patient-data/create-cq-data.ts
packages/api/src/external/carequality/command/cq-patient-data/get-cq-data.ts
packages/api/src/external/carequality/command/cq-patient-data/update-cq-data.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/carequality/index.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/external/hie/reset-doc-query-progress.ts
packages/api/src/external/ihe-gateway/api.ts
packages/api/src/shared/config.ts
packages/carequality-cert-runner/src/index.ts
packages/ihe-gateway-sdk/README.md
packages/ihe-gateway-sdk/src/client/ihe-gateway.ts
packages/ihe-gateway-sdk/src/index.ts
packages/infra/config/ihe-gateway-config.ts
packages/infra/lib/api-stack/api-service.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1377
- Upstream: https://github.com/metriport/metriport-internal/pull/1539
- Check CQ direct FF and IHE GW API on PD, DQ, DR
- Remove API mode from IHE SDK 
- Synchronous PD to IHE GW 
- Local

1377 IHE GW piping

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/PostprocessingScript.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/PostprocessingScript.js

n/a
pipe dq and dr errors to right channel
n/a

fix(ihe): pipe dq and dr errors to right channel

---

.vscode/launch.json
packages/api/docker-compose.dev.yml
packages/api/package.json
packages/api/tsconfig.dev.json
packages/api/tsconfig.json

none
- run app w/ `node` instead of `ts-node`
- fix local debug
- Local
- Staging

1040 Fix local env

---

packages/infra/lib/api-stack/api-service.ts

none
Fix api config for IHE GW
none

1377 Fix api config for IHE GW

---

packages/infra/dashboards/cw-dashboard-prod.json

fix(ihe): add ihe gw to prod metrics

---

packages/infra/lib/ihe-stack/ihe-gw-construct.ts

n/a
create unique VPC listeners
- Staging
Check each PR.

fix(ihe): add inbound vpc link, create unique listeners

---

packages/api/src/external/carequality/document/__tests__/create-outbound-document-retrieval-req.test.ts
packages/api/src/external/carequality/document/__tests__/make-document-reference-with-metriport-id.ts
packages/api/src/external/carequality/document/__tests__/shared.ts
packages/api/src/external/carequality/document/create-outbound-document-retrieval-req.ts
packages/ihe-gateway-sdk/src/index.ts
packages/ihe-gateway-sdk/src/models/shared.ts

none
Limit doc refs on CQ DR - [context](https://metriport.slack.com/archives/C065BLRBUDQ/p1709407440087569)
- Local
- Staging
- Sandbox
- none
- Production

1350 Limit doc refs on CQ DR

---

packages/api/src/external/carequality/document/__tests__/create-outbound-document-retrieval-req.test.ts
packages/api/src/external/carequality/document/__tests__/make-document-reference-with-metriport-id.ts
packages/api/src/external/carequality/document/__tests__/shared.ts
packages/api/src/external/carequality/document/create-outbound-document-retrieval-req.ts
packages/ihe-gateway-sdk/src/index.ts
packages/ihe-gateway-sdk/src/models/shared.ts

n/a
- https://github.com/metriport/metriport/pull/1698
Check each PR.
🏈

PATCH RELEASE 2024-03-02

---

packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts
packages/commonwell-sdk/src/models/__tests__/document.ts

none
Lowercase comparison of URLs to exclude on IHE GW
- Staging
- Production

1350 Lowercase comparison of URLs to exclude on IHE GW

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

none
Fix identifying changes on IHE GW for CICD

1350 Fix identifying changes on IHE GW for CICD

---

packages/api/src/external/carequality/command/cq-directory/cq-gateways.ts
packages/api/src/external/carequality/command/cq-directory/get-organizations-for-xcpd.ts
packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/routes/medical/internal-cq.ts

- Added XCPD prioritization 
- Local
- Production

fix(api): changed the xcpd gateway prioritization logic

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/routes/medical/document.ts
packages/api/src/routes/medical/patient.ts

Ticket: metriport/metirport-internal#1377
n/a
enable cq by default
🏈 

feat(api): enable cq by default

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/routes/medical/document.ts
packages/api/src/routes/medical/patient.ts

Reverts metriport/metriport#1710

Revert "feat(api): enable cq by default"

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-5-Case 5: Application Error.js

- Error in the iti 55 processor where we dont have reason as a value. 
- Error in the iti39 where Cannot call method "split" of undefined

fix(ihe): fix ihe log errors

---

.github/workflows/_deploy-cdk-ihe-gw.yml
.github/workflows/branch-to-staging.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
packages/infra/lib/api-stack.ts

Ref. metriport/metriport-internal#1560
none
Split the infra deploy of API and IHE GW
- Staging
- Production

1360 Split the infra deploy of API and IHE GW

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js
packages/ihe-gateway/server/CodeTemplates/Common Library/File type/File type.js

none
Refactor IHE GW dest DR connector - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1709616646851359):
- only decode document once
- check content type before parsing XML
- improve error handling
- store operationOutcome on the channelMap
- Local
- Production

1350 Refactor IHE GW dest DR connector

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts

n/a
do mock queries in sandbox
just reverting back to original behavior before disabling CW

fix(api): do mock queries in sandbox

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/routes/medical/document.ts
packages/api/src/routes/medical/patient.ts
packages/infra/lib/api-stack.ts

Enable CQ Direct and Update PD timeout

RELEASE 1350 Enable CQ Direct and Update PD timeout

---

packages/api/src/command/medical/patient/consolidated-delete.ts
packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/command/medical/patient/convert-fhir-bundle.ts

Ticket: #1733
n/a
include referenced pt in consolidated bundle
- Staging
- Production

1733 include pt in bundle

---

.github/workflows/_deploy-cdk-ihe-gw.yml
.github/workflows/branch-to-staging.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Split the infra deploy of API and IHE GW - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1709830466643969?thread_ts=1709749285.374859&cid=C04T256DQPQ)

PATCH RELEASE Split the infra deploy of API and IHE GW

---

packages/api/src/command/medical/document/process-doc-query-webhook.ts
packages/api/src/external/hie/tally-doc-query-progress.ts

Cherry pick master commit into develop

---

packages/api/src/command/medical/patient/convert-fhir-bundle.ts

refs. metriport/metriport-internal#1515
- Fixed an error in the previous fix

PATCH RELEASE 2024-03-15_01

---

packages/api/src/command/medical/patient/convert-fhir-bundle.ts

refs. metriport/metriport-internal#1515
- Reset total resource count

fix(api): resetting bundle resource count

---

packages/api/src/command/medical/patient/convert-fhir-bundle.ts

- Fixing a merge conflict between master and develop

fix(api): fixed a merge confict

---

packages/api/src/routes/helpers/request-logger.ts
packages/core/src/external/carequality/dr/get-document-download-url.ts

Refs: #[1613](https://github.com/metriport/metriport-internal/issues/1613)
- update so uniqueDocId returned by inbound is the same as the one we got
- updating blacklist to include internal/mpi/patient
- Staging

Document ID Mismatch

---

packages/ihe-gateway/package-lock.json
packages/ihe-gateway/package.json
packages/ihe-gateway/src/admin.ts
packages/ihe-gateway/tsconfig.json

Ref. metriport/metriport-internal#1592
- Upstream: https://github.com/metriport/metriport/pull/1773
- Fix IHE GW TS setup
none

1592 Fix IHE GW TS setup

---

packages/api/src/external/aws/appConfig.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/link/create.ts
packages/api/src/external/commonwell/link/get.ts
packages/api/src/external/commonwell/link/reset.ts
packages/api/src/external/commonwell/organization.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/external/hie/reset-doc-query-progress.ts
packages/core/src/external/aws/appConfig.ts

Ticket: #1350
Add FF for cw direct to ease a slow roll out for testing in prod
- Staging
- Production

fix(api): add ff for cw direct

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-38 Inbound Interface/sourceConnector-transformer-step-4-get-query-parameters.js
packages/ihe-gateway/server/CodeTemplates/XCA Library - Inbound/Process XCA ITI-38 AdhocQueryRequest/Process XCA ITI-38 AdhocQueryRequest.js

- cherry picked https://github.com/metriport/metriport/pull/1797
Check each PR.

RELEASE 2024-03-21 #1

---

packages/api/src/external/aws/appConfig.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/link/create.ts
packages/api/src/external/commonwell/link/get.ts
packages/api/src/external/commonwell/link/reset.ts
packages/api/src/external/commonwell/organization.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/external/hie/reset-doc-query-progress.ts
packages/core/src/external/aws/appConfig.ts

Ticket: #1350
ref: https://github.com/metriport/metriport/pull/1792
Check each PR.

PATCH: CW FF

---

packages/core/src/external/carequality/pd/process-inbound-pd.ts

- replacing junk id with real 

Patch home community

---

packages/core/src/external/aws/lambda-logic/document-uploader.ts
packages/core/src/external/carequality/dq/create-metadata-xml.ts
packages/core/src/external/carequality/pd/process-inbound-pd.ts
packages/core/src/external/carequality/shared.ts

- more trying to patch inbound with epic

Patch Inbound DQ Response #2

---

packages/ihe-gateway/src/admin.ts

Ref. metriport/metriport-internal#1592
none
Upgrade IHE GW's npm admin to connect to cloud instances.
- Local

1592 Upgrade IHE GW's npm admin to connect to cloud instances

---

packages/infra/lib/api-stack.ts

More time to process poll results - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1711561705214769)
none

PATCH RELEASE More time to process poll results

---

packages/api/src/providers/dexcom.ts
packages/api/src/providers/fitbit.ts
packages/api/src/providers/tenovi.ts
packages/api/src/providers/withings.ts

refs. metriport/metriport#1461
- Removed more DAPI-related console logs

fix(dapi): found more logs to delete

---

packages/connect-widget/src/pages/connect/components/connect-providers.tsx
packages/connect-widget/src/shared/util.ts

refs. metriport/metriport#1461
- Removing logs from connect widget

fix(dapi): found and removed logging on connect-widget

---

docs/medical-api/getting-started/quickstart.mdx

refs. metriport/metriport#1461
- Upstream: (https://github.com/metriport/metriport-internal/pull/1651)
- Upd the docs section to reflect the changes on the dashboard

fix(dapi): upd the mapi request access section

---

docs/medical-api/getting-started/quickstart.mdx
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-39 Inbound Interface/destinationConnector-AWS Lambda Interface-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/CodeTemplates/Common Library/Get SOAP Template or Fault message/Get SOAP Template or Fault message.js
packages/ihe-gateway/server/CodeTemplates/XCA Library - Inbound/Get XCA ITI-39 RetrieveDocumentSetResponse/Get XCA ITI-39 RetrieveDocumentSetResponse.js

- https://github.com/metriport/metriport/pull/1846
- Staging

RELEASE 2024-03-29

---

packages/api/src/external/hie/__tests__/set-doc-query-progress.test.ts
packages/api/src/external/hie/set-doc-query-progress.ts

If existing progress didnt have any values then we wouldnt aggregate those values across hie's

PATCH fix progress type

---

.github/workflows/a-wip-test-e2e.yml

Ref. metriport/metriport-internal#1512
none
WIP, temporary E2E CICD script - attempting to fix "Execute E2E tests in all CICD runs".
With this merged into develop, I expect to be able to iterate off of a feature branch, like "branch to staging".
none

1512 WIP Temporary E2E CICD script

---

packages/api/src/external/commonwell/link/shared.ts

Ref. metriport/metriport-internal#1608
none
- Disable logs for CW links
none

1608 Disable logs for CW links

---

packages/core/src/external/carequality/dq/create-metadata-xml.ts

- customer name in DQ inbound response not metriport 
- Staging

Customer Name Appears in Epic

---

packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/external/carequality/process-patient-discovery-progress.ts
packages/api/src/external/commonwell/admin/patch-patient-duplicates.ts
packages/api/src/external/commonwell/link/create.ts
packages/api/src/external/commonwell/link/get.ts
packages/api/src/external/commonwell/link/reset.ts
packages/api/src/external/commonwell/patient-external-data.ts
packages/api/src/external/commonwell/patient.ts
packages/fhir-converter/src/templates/cda/ValueSet/ImmunizationStatus.hbs

- Upstream: https://github.com/metriport/metriport/pull/1871
Follow up to the upstream PR - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1712249027831379?thread_ts=1712200252.748979&cid=C04T256DQPQ)
- Local
- Staging
- Production

fix(api): add processing to patient update

---

.github/CODEOWNERS

- Related:
- https://github.com/metriport/metriport-internal/pull/1688
- https://github.com/metriport/fhir-server/pull/48
Add Jonah to codeowners 🤘

1040 Add Jonah to codeowners 🤘

---

packages/ihe-gateway/server/CodeTemplates/XCPD Library - Inbound/Generate HL7v3 Subject from FHIR Patient /Generate HL7v3 Subject from FHIR Patient .js

- Fixing the patient's address mapping on the inbound XCPD in the ihe-gateway

fix(ihe-gateway): fixed patient addr mapping for inbound xcpd

---

packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/external/carequality/create-outbound-patient-discovery-req.ts
packages/api/src/external/carequality/patient-updater-carequality.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/external/carequality/process-outbound-patient-discovery-resps.ts
packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
packages/api/src/external/commonwell/link/shared.ts
packages/api/src/external/commonwell/patient-updater-commonwell.ts
packages/api/src/external/commonwell/patient.ts
packages/core/src/domain/patient.ts

Ticket: #1669
Add patient discovery time analytics 
- Local
- Staging
- Production

1669 v1 analytics

---

packages/api/src/routes/helpers/request-logger.ts

PATCH: fix route logging

---

packages/api/src/external/carequality/create-outbound-patient-discovery-req.ts
packages/api/src/external/carequality/patient.ts

Ticket: #799
Pass requestid to prepare PD

fix(api): fix requestid

---

packages/api/src/external/carequality/create-outbound-patient-discovery-req.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/routes/helpers/request-logger.ts

- https://github.com/metriport/metriport/pull/1899
- https://github.com/metriport/metriport/pull/1897

Backmerge Master into Develop

---

packages/api/src/command/medical/mapi-access.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/fhir/document/save-document-reference.ts
packages/core/src/external/aws/s3.ts
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js
packages/shared/src/common/retry.ts
packages/utils/package.json
packages/utils/src/customer-requests/download-docs.ts
packages/utils/src/customer-requests/folder.ts
packages/utils/src/customer-requests/get-consolidated.ts

none
- Fix GET mapi access + other small fixes
- Add download docs util script
- Add get consolidated util script
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Add download docs and other small fixes

---

packages/core/src/domain/document-query/trigger-and-query-remote.ts
packages/fhir-converter/src/lib/workers/worker.js
packages/utils/package.json
packages/utils/src/bulk-insert-patients.ts
packages/utils/src/bulk-query-patients.ts

none
- Improvements on bulk insert and query scripts
- Make logs on FHIR converter more unique (easier to diagnose when looking through logs/Sentry)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Improvements on bulk insert and query scripts

---

packages/api/src/command/medical/document/document-webhook.ts
packages/api/src/command/medical/patient/consolidated-webhook.ts

Usage is not sending docQuery - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1713185252441519)

PATCH Fix usage not sending docQuery

---

packages/api/src/command/medical/admin/hie-overview.ts

- Upstream: https://github.com/metriport/metriport/pull/1906
Return patient data even without success records
- Local
- Staging
- Sandbox
- none
- Production

1679 Return patient data even without success records

---

packages/api/src/command/medical/admin/hie-overview.ts

Patient HIE overview raw query to use index.
Before the change:
Updated query:
- Local
- Staging
- Sandbox
- none
- Production

1679 Patient HIE overview raw query to use index

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/lib/inputProcessor/dateProcessor.js
packages/fhir-converter/src/lib/workers/worker.js
packages/fhir-converter/src/templates/cda/Resources/Composition.hbs
packages/fhir-converter/src/templates/cda/Resources/MedicationAdministration.hbs
packages/fhir-converter/src/templates/cda/Resources/MedicationStatement.hbs
packages/fhir-converter/src/templates/cda/Utils/PeriodOrDefaultPeriod.hbs

- adding dates to meds without dates
- Local

Adding Encounter Date to Meds Missing Dates

---

packages/core/src/external/fhir/shared/index.ts

- add cq extension to downloadedFromHIEs so we can reconvert CQ docs too 

1350 cq extension

---

packages/api/src/command/medical/facility/create-facility.ts
packages/api/src/command/medical/organization/create-organization.ts
packages/api/src/models/medical/facility.ts
packages/api/src/models/medical/organization.ts
packages/api/src/sequelize/migrations/2024-04-18_00_update-facility-organization.ts

Refs. metriport/metriport-internal#1706
- Downstream: https://github.com/metriport/metriport/pull/1929
update org and facility models to support OBO, add migration script to backfill facility OIDs
see design doc for details

feat(api): facility and org obo model updates

---

packages/api/src/sequelize/migrations/2024-04-18_00_update-facility-organization.ts

refs. metriport/metriport-internal#1706
n/a
facility and org migration fix
already tested in previous PR

feat(api): facility and org migration fix

---

packages/fhir-converter/src/templates/cda/Resources/Condition.hbs
packages/fhir-converter/src/templates/cda/Resources/FamilyMemberHistory.hbs
packages/utils/src/fhir-converter/e2e-test.ts

- adding dates to conditions without dates
- Local

PATCH: 1442 add dates to conditions from the Encounter

---

packages/infra/lib/ihe-stack/ihe-gw-construct.ts

none
Increase ECS deregistration delay on IHE GW - [context](https://metriport.slack.com/archives/C065BLRBUDQ/p1712770953465139)
This will give IHE GW more time to finish processing in-flight PDs, DQs, and DRs.
It will also make deployments that include IHE GW to take longer, additional 5 mins.
- Local
- none
- Staging
- Sandbox
- none
- Production

1040 Increase ECS deregistration delay on IHE GW

---

packages/api/src/external/commonwell/organization.ts
packages/api/src/routes/medical/internal-facility.ts

refs. metriport/metriport-internal#1706
n/a
add support for CW OBO org creation in internal endpoint
:warning: CW integration is still down, will need to test in prod
- Production

feat(api): add cw obo org creation

---

packages/fhir-converter/src/templates/cda/DataType/Coding.hbs
packages/lambdas/src/sqs-to-converter.ts

- https://metriport.slack.com/archives/C04T256DQPQ/p1712331358298839
- Local

Mapping: Not escaping in Coding

---

package-lock.json
packages/api/src/routes/medical/internal-cq.ts
packages/carequality-cert-runner/package.json
packages/ihe-gateway-sdk/package.json
packages/ihe-gateway-sdk/src/models/shared.ts
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/sourceConnector-transformer-step-0-Set stats.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/sourceConnector-transformer-step-0-Set stats.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/sourceConnector-transformer-step-0-Set Stats.js
packages/ihe-gateway/server/CodeTemplates/Common Library/Get current date/Get current date.js
packages/ihe-gateway/server/CodeTemplates/Common Library/index.xml
packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-38 response template/Get XCA ITI-38 response template.js
packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-39 response template/Get XCA ITI-39 response template.js
packages/ihe-gateway/server/CodeTemplates/XCPD Library - Outbound/Get XCPD ITI-55 response template/Get XCPD ITI-55 response template.js

Ticket: https://github.com/metriport/metriport-internal/issues/1712
- https://github.com/metriport/metriport/pull/1945
Check each PR.

RELEASE cherry pick duration

---

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx

Ref: #304
- Typo fix
- Local
- Production

304 webook fix

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-1-Case 1: One Match.js
packages/ihe-gateway/server/CodeTemplates/Common Library/Get current date.xml
packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-38 response template/Get XCA ITI-38 response template.js
packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-39 response template/Get XCA ITI-39 response template.js
packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/index.xml
packages/ihe-gateway/server/CodeTemplates/XCPD Library - Outbound/Get XCPD ITI-55 response template/Get XCPD ITI-55 response template.js

Back merge master commit

---

packages/api/src/external/commonwell/patient.ts

Ticket: #799
Needed to add PD status completed at the end of CW
- Local
- Staging
- Production

PATCH: add updated completed cw end

---

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx
packages/api/src/routes/medical/fhir-r4-proxy.ts

Ref: #1943
Ref: #304 
- Repeat https://github.com/metriport/metriport/pull/1954
- Repeat https://github.com/metriport/metriport/pull/1960

fix(api): proxy stuff (again) / fix: webook docs type (again)

---

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx
packages/api/src/routes/medical/fhir-r4-proxy.ts
packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/index.xml

ref: https://github.com/metriport/metriport/pull/1977
ref: https://github.com/metriport/metriport/pull/1980
Check each PR.

RELEASE: 04-30-2024

---

packages/api/src/external/commonwell/document/document-query.ts

Ref. metriport/metriport-internal#1714
none
Don't report CW NotFound error
- Local
- none
- Staging
- none
- Sandbox
- none
- Production
- none

1714 Don't report CW NotFound error

---

packages/core/src/util/__tests__/concurrency.test.ts
packages/core/src/util/concurrency.ts
packages/ihe-gateway/README.md

- Upstream: https://github.com/metriport/metriport/pull/1962
- `executeAsynchronously()` to send correct index and processes elements from the start of the array
- update readme w/ env for 'npm run admin'
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Adjust executeAsynchronously()

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/api/src/external/carequality/document/create-outbound-document-retrieval-req.ts
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts
packages/ihe-gateway-sdk/package.json
packages/ihe-gateway-sdk/src/__tests__/constants.ts
packages/ihe-gateway-sdk/src/__tests__/ihe-inbound-lambdas.test.ts
packages/ihe-gateway-sdk/src/models/document-query/document-query-requests.ts
packages/ihe-gateway-sdk/src/models/document-retrieval/document-retrieval-requests.ts
packages/ihe-gateway-sdk/src/models/patient-discovery/patient-discovery-requests.ts
packages/ihe-gateway-sdk/src/models/shared.ts
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/utils/package.json

- Downstream: (https://github.com/metriport/metriport/pull/1999)
- undoing changes made to ihe-gateway-sdk and adding tests to ihe-gateway-sdk folder to try to prevent this from happening again 
- patching current code on staging 
- Local
- Staging

IHE Gateway SDK Update to Fix Inbound

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/utils/package.json

NPM Release IHE Gateway V2

---

packages/infra/config/aws/rds.ts
packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/alarm-slack-chatbot.ts
packages/infra/lib/api-stack/ccda-search-connector.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/fhir-server-connector.ts
packages/infra/lib/ihe-stack/ihe-db-construct.ts
packages/infra/lib/ihe-stack/ihe-gw-construct.ts
packages/infra/lib/shared/cloudwatch-metric.ts
packages/infra/lib/shared/rds.ts
packages/infra/lib/shared/sqs.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1743
- Upstream: https://github.com/metriport/metriport-internal/pull/1749
- https://github.com/metriport/metriport/pull/1998
Check each PR.

PATCH RELEASE 1743

---

packages/infra/lib/api-stack/fhir-converter-service.ts
packages/infra/lib/ihe-stack/ihe-gw-construct.ts
packages/infra/lib/shared/target-group.ts

Tickets:
- https://github.com/metriport/metriport-internal/issues/1743
- https://github.com/metriport/metriport/pull/2006
Check each PR.

PATCH RELEASE 1743 - 2

---

packages/infra/lib/api-stack.ts

Removing Bad Merge Changes 

---

packages/infra/lib/api-stack.ts

- dont build nested stack for sandbox

PATCH 1667 dont deploy sandbox

---

.github/pull_request_template.md

Refs: #[1750](https://github.com/metriport/metriport-internal/issues/1750)
- updating PR review template to include reminders about FFs and api/infra dependencies

Update PR Template with FF Reminder

---

packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/fhir-converter-service.ts
packages/infra/lib/ihe-stack/ihe-gw-construct.ts
packages/infra/lib/shared/target-group.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1743
- upstream: https://github.com/metriport/metriport/pull/2038
- https://github.com/metriport/metriport/pull/2024
Check each PR.

RELEASE 1743 Additional SOC2 controls

---

docs/home/welcome.mdx

n/a
remove dapi from docs home
`mintlify dev`

feat(docs): remove dapi from home

---

packages/ihe-gateway/README.md

none
- Update IHE GW readme about the administrator
none

1040 Update IHE GW readme

---

packages/fhir-converter/src/templates/cda/ValueSet/ImmunizationStatus.hbs

Issue with storing "complete" within Immunizations - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1715705503580659)
- Local
- Production

PATCH Immunizations Completed

---

packages/api/src/external/carequality/document/__tests__/create-outbound-document-retrieval-req.test.ts
packages/api/src/external/carequality/document/create-outbound-document-retrieval-req.ts

refs. metriport/metriport#1667
n/a
revert change to query diff hcids
revert

fix(api): revert change to query diff hcids

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Resources/Immunization.hbs

Ticket: #799
Unescaped characters in lotNumber
- Local
- Production

Patch: Update Immunization Template

---

packages/fhir-converter/Dockerfile
packages/fhir-converter/src/lib/constants/constants.js
packages/fhir-converter/src/routes.js

refs. metriport/metriport-internal#1803
n/a
remove leftover unused code
- Local

chore(converter): remove leftover unused code

---

packages/fhir-converter/src/routes.js

refs. metriport/metriport-internal#1803
n/a
add health check route
- Local

fix(converter): add health check route

---

packages/api/src/external/hie/shared.ts

Ticket: #2101 
Use hie oid when obo. 
- Local
- Production

PATCH query pattern patch

---

docs/_snippets/create-dev-account.mdx
docs/converter-api/api-reference/ccda/ccda-to-fhir.mdx
docs/converter-api/getting-started/quickstart.mdx
docs/converter-api/more-info/sandbox.mdx
docs/home/welcome.mdx
docs/medical-api/getting-started/quickstart.mdx
docs/mint.json

refs. metriport/metriport-internal#1808
n/a
converter api mvp docs
- Local

feat(docs): converter api mvp

---

packages/api/src/command/medical/document/document-conversion-status.ts
packages/api/src/command/webhook/webhook.ts

Ticket: #1669
Add conversion success rate to posthog
- Local
- Staging
- Production

fix(api): add conversion success rate

---

packages/core/src/external/carequality/ihe-gateway-v2/gateways.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti38-envelope.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti39-envelope.ts

- forgot to do dqs and drs in this PR: https://github.com/metriport/metriport/pull/2130
- Local

fix(ihev2): ntst patch for dqs and drs

---

README.md
packages/api/src/routes/helpers/request-analytics.ts
packages/api/src/routes/helpers/request-logger.ts
packages/core/src/util/config.ts
packages/infra/config/env-config.ts
packages/infra/lib/ihe-stack.ts
packages/lambdas/src/ihe-inbound-document-query.ts
packages/lambdas/src/ihe-inbound-document-retrieval.ts
packages/lambdas/src/ihe-inbound-patient-discovery.ts

Ticket: #1889 
- Upstream:  https://github.com/metriport/metriport-internal/pull/1814
Need to grab the correct env var for posthog key
- Staging
- Production

feat(api): posthog infra key

---

packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/constants.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/process-xcpd.test.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/xmls/xcpd_match_multi_addr_name.xml
packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/xmls/xcpd_match_no_addresses.xml
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/process/xcpd-response.ts
packages/core/src/external/carequality/ihe-gateway-v2/utils.ts
packages/ihe-gateway-sdk/src/models/patient-discovery/patient-discovery-responses.ts

- patching issues in parsing patient demographic data responses
- Local

fix(ihev2): catching case where multiple addresses and names

---

packages/lambdas/package-lock.json
packages/lambdas/package.json

Ticket: #1889 
Add posthog node to package
- Staging
- Production

feat(api): add posthog node to lambda

---

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/process/xcpd-response.ts

Ticket: #799
Update resp to abide by schema
- Local
- Production

PATCH update error v2 pd resp

---

.github/pull_request_template.md
packages/utils/src/bulk-insert-patients.ts
packages/utils/src/bulk-query-patients.ts
packages/utils/src/coverage-assessment.ts
packages/utils/src/customer-requests/download-docs.ts
packages/utils/src/customer-requests/get-consolidated.ts
packages/utils/src/customer-requests/medical-records-create.ts
packages/utils/src/shared/folder.ts

none
Make runs folder a symlink - [context](https://metriport.slack.com/archives/C041YAW030C/p1716920946693189)
Update PR template.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Make runs folder a symlink

---

packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/lib/ihe-stack.ts
packages/lambdas/src/ihe-inbound-document-query.ts
packages/lambdas/src/ihe-inbound-document-retrieval.ts
packages/lambdas/src/ihe-inbound-patient-discovery.ts

Ticket: #1889 
- Upstream: https://github.com/metriport/metriport-internal/pull/1821
Add engineering cxid to inbound analytics 
- Local
- Staging
- Production

1669 inbound stats

---

packages/core/src/fhir-to-cda/cda-generators.ts

refs. metriport/metriport#1603
- Added xml styling info at the top of the file
- Local

fix(fhir-to-cda): added xml styling line

---

packages/api/src/external/commonwell/patient.ts

none
Log reqId and CW log ID. Didn't get CW correlation ID when debugging [this](https://metriport.slack.com/archives/C04T256DQPQ/p1717444100652249?thread_ts=1717429674.723459&cid=C04T256DQPQ), so decided to add those to this file.
none

1040 Log reqId and CW log ID

---

packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/constants.ts

Refs: #799
- updating to pass test - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1717731707501189)
- passing cicd

fix(ihev2): fixed failing test

---

packages/infra/lib/ihe-gateway-v2-stack.ts

- adding back write access - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1717777606813809) 

1667 patch ihe doc retrieve write access

---

docs/mint.json

Ref: #304
- add match patient to index
- Local
- Production
_[How does the changes on this PR impact/interact with the existing environment (database, configs, secrets, FFs, api contracts, etc.)?
Consider creating 2+ PRs if we need to ship those changes in a staged way]_
_[This is the release plan for production]_
_[You should execute the exact same steps when releasing to staging to validate it works]_
_[Add and remove items below accordingly]_

feat(api): match patient docs fix

---

packages/api/src/external/hie/__tests__/register-facility.test.ts
packages/api/src/external/hie/shared.ts

Ticket: #1040
Update cq directory structure - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1717796797816469)
- Staging
- Production

fix(api): update cq dir structure

---

packages/core/README.md
packages/core/src/util/notifications.ts

- improve docs of `capture.message` and `capture.error`
- update core's readme 
none

1040 Small adjustments on capture and core's readme

---

packages/core/src/external/carequality/ihe-gateway-v2/gateways.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti39-envelope.ts

- add uuid prefix to doc unique id for certain document retrieval reqs. 
- [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1718125971824869?thread_ts=1718123135.488959&cid=C0616FCPAKZ)
- Local

PATCH add uuid back to dr request if lowercase uuid

---

packages/api/src/sentry.ts
packages/connect-widget/src/index.tsx
packages/lambdas/src/shared/capture.ts

none
Update Sentry sample rate - [context](https://metriport.slack.com/archives/C05UXMPAVS8/p1718114642376839)
none

1040 Update Sentry sample rate

---

packages/api/src/external/carequality/document/get-non-existent-doc-refs.ts
packages/core/src/external/aws/s3.ts

Ticket: #2209 
- Upstream: https://github.com/metriport/metriport/pull/2252
Use filepath to check if exists in s3
- Local
- Staging
- Production

2209 prevent docs redownload

---

packages/api/src/external/aws/app-config.ts
packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts
packages/api/src/external/carequality/gateway/__tests__/facilities-with-filter.test.ts
packages/api/src/external/carequality/gateway/index.ts
packages/core/src/external/aws/app-config.ts

Ticket: #1040
Remove epic for facilities that are not approved
- Local
- Staging
- Production

1040 filter epic

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts

Ticket: #1040 
Only send MR summaries with clinically relevant data
- Local
- Staging
- Production

fix(api): has clinical data

---

packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-logic.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/error.ts

Refs: #1667
- fix awaits/async in dq response ihe v2
- [context](https://metriport.slack.com/archives/C04CXLSAF7V/p1718728133240849?thread_ts=1718726422.930049&cid=C04CXLSAF7V)
- Local

fix(ihev2): removing async in dq response

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts

- Upstream: notes
- Downstream: notes
Update MR summary for adhd to show latest notes
- Local
- Staging
- Production
Check each PR.

fix(api): latest notes

---

packages/infra/lib/lambdas-nested-stack.ts

Set max PD duration to 5min - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1719070208715919?thread_ts=1719018618.154209&cid=C04GEQ1GH9D)
none

PATCH RELEASE 799 Set max PD duration to 5min

---

packages/infra/lib/lambdas-nested-stack.ts

Ref. metriport/metriport-internal#1827
- Upstream: https://github.com/metriport/metriport/pull/2322
Re-add buffer to the ihe gw polling lambda - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1719249696616669?thread_ts=1719018618.154209&cid=C04GEQ1GH9D)
none

PATCH RELEASE 799 Re-add buffer to the ihe gw polling lambda

---

packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/fhir-converter-service.ts
packages/infra/lib/api-stack/fhir-server-connector.ts

- increase fhir converter task count
- increase fhir converter connection concurrent messages
- increase fhir server connection concurrent message

1040 scaling fhir converter + server

---

packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/fhir-converter-service.ts
packages/infra/lib/api-stack/fhir-server-connector.ts
packages/infra/lib/shared/sqs.ts

- add msg count alarm to fhir server and converter queues
- double fhir converter task count
- double fhir converter connection concurrent messages
- double fhir server connection concurrent message

feat(alarm): add msg count alarm to fhir server and converter queues

---

packages/fhir-converter/Dockerfile.lambda

refs. metriport/metriport-internal#1808
N/A
it should work

PATCH RELEASE 2024-06-27

---

packages/api/src/command/medical/patient/handle-data-contributions.ts
packages/api/src/external/cda/generate-ccd.ts
packages/api/src/external/cda/process-ccd-request.ts
packages/core/src/domain/document/upload.ts
packages/core/src/external/aws/s3.ts
packages/core/src/external/carequality/dq/process-inbound-dq.ts

refs. metriport/metriport-internal#1905
- Better check algo to see if CCD already exists
- Better check to see if we need to generate CCD
- [context](https://metriport.slack.com/archives/C04DMKE9DME/p1719270581196869?thread_ts=1718897333.131819&cid=C04DMKE9DME)
- Local

feat(api): introducing better checks for ccd gen

---

packages/api/src/command/medical/patient/__tests__/consolidated-get.test.ts
packages/api/src/command/medical/patient/consolidated-get.ts

Ref: #2353
- loop 3 times grabbing nested references
- Local
- Staging
- Production

2353 adding 3 loops of hydration

---

packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/config/open-search-config.ts
packages/infra/dashboards/cw-dashboard-prod.json
packages/infra/lib/api-stack/ccda-search-connector.ts

Ref. metriport/metriport-internal#1824
- upstream: https://github.com/metriport/metriport-internal/pull/1927
- downstream: none
Increase the storage space of OpenSearch - see [the last comments](https://github.com/metriport/metriport-internal/issues/1824#issuecomment-2192638565) on the ticket for why this now.
- Staging
- Sandbox
- Production

1824 Beef up OpenSearch

---

packages/infra/lib/api-stack/api-service.ts

Ref: #1884 internal
- need permissions to edit configuration and deploy configuration (testing had accidentally picked up local AWS creds)
- Local
- passed already previously
- Staging
- Production

feat(api): adding permissions for appconfig edits + deployments

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

refs. metriport/metriport-internal#2302
- removing an extra space to fix e2e testing.. 🙄

fix(core): removing extra space

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/core/src/external/fhir/shared/extensions/base-64-extension.ts
packages/fhir-converter/src/templates/cda/Resources/Observation.hbs

Ticket: https://github.com/metriport/metriport/issues/2302
Reverting the following PRs: 
- https://github.com/metriport/metriport/pull/2373
- https://github.com/metriport/metriport/pull/2358
Context - [Slack discussion](https://metriport.slack.com/archives/C04DMKE9DME/p1719963544372579)

Reverting new extension for FHIR converter

---

packages/core/src/external/carequality/dq/process-inbound-dq.ts

refs. metriport/metriport-internal#1905
- Bug fix where I accidentally duplicated some code 
- Local
- Staging

fix(core): fixing duplicated code

---

packages/api/src/routes/internal.ts
packages/api/src/routes/medical/dtos/facilityDTO.ts
packages/api/src/routes/medical/internal-facility.ts

Ref: #1884
- align return payload from internal facility endpoint to align with internal /cx-data endpoint
- Staging
- Production

feat(api): fixing return from internal facility endpoint to align with /cx-data

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/api/src/external/commonwell/__tests__/patient.test.ts
packages/api/src/external/commonwell/patient-conversion.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/external/fhir/document/index.ts
packages/api/src/sentry.ts
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/commonwell-sdk/src/models/demographics.ts
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/utils/package.json

- Fix gender mapping for CW
- Disable sentry perf for CQ resp endpoints - [context](https://metriport.slack.com/archives/C05UXMPAVS8/p1720111600293189?thread_ts=1720103185.582439&cid=C05UXMPAVS8)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

PATCH RELEASE 799 Fix gender mapping for CW

---

packages/infra/lib/ihe-stack.ts
packages/infra/lib/ihe-stack/ihe-gateway.ts

_[Document your changes, give context for reviewers, add images/videos of UI changes]_
- ...
- ...
- Local
- Staging
- Sandbox
- Production
Check each PR.
_[How does the changes on this PR impact/interact with the existing environment (database, configs, secrets, FFs, api contracts, etc.)?
Consider creating 2+ PRs if we need to ship those changes in a staged way]_
_[This is the release plan for production]_
_[You should execute the exact same steps when releasing to staging to validate it works]_
_[Add and …

2223 ihev2 inbound infra 1

---

packages/api/src/command/medical/patient/handle-data-contributions.ts
packages/api/src/external/fhir/shared/json-validator.ts

Store on S3 before validation on data contribution - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1720572237478069)
- Local

PATCH RELEASE Store on S3 before validation on data contribution

---

packages/api/src/external/carequality/document/shared.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/DataType/Period.hbs
packages/fhir-converter/src/templates/cda/Resources/AllergyIntolerance.hbs
packages/fhir-converter/src/templates/cda/Resources/Composition.hbs
packages/fhir-converter/src/templates/cda/Resources/DiagnosticReport.hbs
packages/fhir-converter/src/templates/cda/Resources/Observation.hbs

Ticket: #799
Misc changes regarding MR summary and FHIR Converter
- Local
- Production

fix(api): misc converter changes

---

packages/api/src/command/medical/patient/handle-data-contributions.ts

refs. metriport/metriport-internal#1972
- No CCD/CDA gen on sandbox
- No CCD gen await on the `PUT /consolidated` route
- No CDA upload await 
- Local
- Sandbox

PATCH RELEASE 2024_07_09_2 - PUT consolidated 

---

.github/workflows/deploy-production.yml

Ticket: #799
- ihe stack var missing.

Patch deploy prod workflow

---

.github/workflows/_deploy-cdk.yml
.github/workflows/deploy-production.yml

Ticket: #799
- dont deploy ihe stack if sandbox since it doesnt have access to the IHEStack

feat(ihe): no ihe stack in sandbox env

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/__tests__/process-dq-request.test.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/__tests__/process-dr-request.test.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/__tests__/process-xcpd-request.test.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dq-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dr-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/monitor/store.ts
packages/core/src/external/carequality/ihe-gateway-v2/schema.ts
packages/core/src/util/config.ts
packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/lib/ihe-stack.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-query.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-retrieval.ts
packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts
packages/utils/src/saml/mock-ihe-gateway.ts

- upstream: https://github.com/metriport/metriport-internal/pull/1976
- storing inbound requests
- inbound schema fix
- Staging

feat(ihe): storing dq requests + inbound schema fix

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/schema.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/create/iti55-envelope.ts

- inbound xcpd schema error fix
- Local
- Staging

2223 inbound pd schema fix

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/schema.ts
packages/core/src/external/carequality/ihe-gateway-v2/utils.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-query.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-retrieval.ts
packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts

- inbound saml attributes schema fix
- Local
- Staging

feat(ihe): allow text or numbers

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/shared.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dq-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dr-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/schema.ts

Refs: #2223
- epic sends invalid requests on staging with PurposeForUse instead of PurposeOfUse
- Local

fix(inbound): support epics bug

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/create/xcpd-response.ts

- add wsa namespaces
- [context](https://metriport.slack.com/archives/C04DMKE9DME/p1720721456332019?thread_ts=1720655617.567869&cid=C04DMKE9DME)

fix(inbound): namespaces fix

---

packages/api/src/routes/middlewares/auth.ts

Ref. metriport/metriport-internal#1935
Fix determining cxId from user JWT.
- Local

PATCH RELEASE Fix cxId from JWT

---

packages/fhir-converter/src/lib/handlebars-converter/__tests__/handlebars-helpers.test.js
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js

Ref. metriport/metriport#2295
Ticket: #2295 
Remove validation so we always return a date
- Local
- Production
Check each PR.

PATCH RELEASE: Always return date

---

packages/fhir-converter/src/lib/handlebars-converter/__tests__/handlebars-helpers.test.js
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js

Ticket: #2295
- Dont throw error if not a valid date
- Local
- Production

fix(api): return false if not valid date

---

packages/fhir-converter/src/lib/handlebars-converter/__tests__/handlebars-helpers.test.js
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js

Ref. metriport/metriport#2295
Ticket: #2295
- Upstream: NONE
- Downstream: NONE
Dont iso invalid date
- Local
- Production

PATCH RELEASE: dont iso invlaid date

---

packages/fhir-converter/src/lib/cda/cda.js

Ref: #1040
- PATCHING based on the following doc https://metriport-inc.sentry.io/issues/5564360500/?environment=production&project=4505252341153792&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1
- Local
- Production

feat(api): patch converter

---

packages/fhir-converter/src/lib/cda/cda.js

Ref: #1040
- reverse https://github.com/metriport/metriport/commit/34262811af8876b35b04b27237ea5affd1af2617

feat(api): undo patch

---

packages/api/src/command/medical/patient/__tests__/get-consolidated-webhook.test.ts
packages/api/src/command/medical/patient/__tests__/store-query-cmd.ts
packages/api/src/command/medical/patient/get-consolidated-webhook.ts
packages/api/src/routes/medical/patient.ts

Ref. metriport/metriport#2485
Ticket: #2485
- Add url to get webhook url from consolidated
- Local
- Staging
- Production

fix(api): draft consolidated webhook get

---

packages/api/src/external/hie/run-or-schedule-patient-discovery.ts
packages/api/src/routes/medical/internal-patient.ts
packages/utils/src/bulk-trigger-patient-discovery.ts

refs. metriport/metriport-internal#1040
- Added internal-patient endpoint, which triggers PD
- Added a script that allows to use this endpoint for patients en-masse
- Local

feat(utils): added an internal endpoint and script for pd trigger

---

packages/infra/lib/ihe-stack.ts

Refs: #799
- rollback 
Check each PR.
- :warning: ~~Points to `master`~~ pointing to `develop`

PATCH: rollback ihe stack changes

---

packages/infra/lib/ihe-stack.ts

Reverts metriport/metriport#2508

Revert "PATCH: rollback ihe stack changes"

---

packages/core/src/domain/__tests__/filename.test.ts
packages/core/src/domain/filename.ts

Ref: #1040
- ensure hive keys are lowercase so that we can use MSCK REPAIR TABLE (https://repost.aws/knowledge-center/athena-aws-glue-msck-repair-table)
- Local
- Staging
- Production

feat(api): patch hive file path

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/shared.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/schema.ts
packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/schema.ts
packages/core/src/external/carequality/shared.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-query.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-retrieval.ts
packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts

Refs: #2223
- making error responses descriptive, removing req fields, adding support for gender values not specified in the spec
- misc schema fixes to be more flexible to implementers not following the spec
- Staging

Inbound: Better Error Responses + Misc Fixes

---

packages/api/src/routes/internal.ts
packages/api/src/routes/medical/internal-cq.ts

Ref: #1939
- Small docstring edit

feat(api): doc string edit + unnecessary undefined check

---

packages/api/src/command/medical/patient/handle-data-contributions.ts

- Upstream: https://github.com/metriport/metriport/pull/2542
Just calculate durations so they're a positive number.
none

1040 Fix calculation of handle doc contrib duration

---

packages/api/src/__tests__/e2e/mapi/parts/consolidated/consolidated-template.html

- Upstream: https://github.com/metriport/metriport/pull/2563
Update E2E test re: medical record table update
none

PATCH RELEASE Update E2E test re: medical record table update

---

packages/core/src/external/aws/bedrock.ts

refs. metriport/metriport-internal#2040
- Fixing import for Config
- Local
- Staging

fix(api): import fix

---

packages/api-sdk/src/medical/client/__tests__/metriport.test.e2e.ts
packages/lambdas/src/fhir-to-medical-record.ts

Refs. metriport/metriport-internal#2040
none
Await on S3 file upload during MR generation - [context](https://metriport.slack.com/archives/C04CXLSAF7V/p1723060869102839?thread_ts=1722980996.708309&cid=C04CXLSAF7V)
- Local
- none
- Staging
- Sandbox
- none
- Production
- none

2040 Await on S3 file upload during MR generation

---

packages/api/src/__tests__/e2e/mapi/parts/consolidated/consolidated-template.html

refs. metriport/metriport-internal#2040
Update MR html template for E2E tests - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1723067314426519?thread_ts=1723063635.375019&cid=C04FZ9859FZ)
- Local
- Staging
- Sandbox
- none
- Production
- none

2040 Update MR html template for E2E tests

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/create/xcpd-response.ts

Ticket: #[2223](https://github.com/metriport/metriport/pull/2223)
- remove extra query by parameter field in inbound response per surescripts recommendation
- Local

fix(inbound): extra query by parameter

---

packages/commonwell-sdk/src/models/__tests__/document.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/Sections/Hospital_Discharge_Medications.hbs

Ticket: #799
- Upstream: _none
Update Practitioner spelling

PATCH: Update Practitioner name

---

packages/commonwell-sdk/src/models/__tests__/document.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/templates/cda/Sections/Hospital_Discharge_Medications.hbs

- Upstream: https://github.com/metriport/metriport/pull/2597
- Downstream: https://github.com/metriport/metriport/pull/2596
Second attempt to fix the conflict between master and develop - 1st one: https://github.com/metriport/metriport/pull/2597
none

2040 Fix backmerge conflict - 2

---

packages/api/src/routes/medical/internal-patient.ts

Ref. metriport/metriport-internal#1319
- Upstream: https://github.com/metriport/metriport/pull/2561
Finish response on `POST /internal/patient/:id/consolidated` - [context](https://metriport.slack.com/archives/C04CXLSAF7V/p1723586489731819?thread_ts=1722623737.720209&cid=C04CXLSAF7V)
- Local
- Staging
- Sandbox
- none
- Production
- none

1936 Finish response on POST internal consolidated

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/create/xcpd-response.ts

Ticket: #[2223](https://github.com/metriport/metriport/pull/2223)
- make typeCode in acknowledgementDetail an attribute instead of a field
- Local

fix(inbound): surescripts type code

---

packages/api/src/command/feedback/feedback-entry.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

Ticket: #[1792](https://github.com/metriport/metriport-internal/issues/1792)
- https://github.com/metriport/metriport/pull/2638
Check each PR.

RELEASE Blacklisted Conditions Codes

---

packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/external/aws/app-config.ts
packages/core/src/command/consolidated/consolidated-connector-local.ts
packages/core/src/command/consolidated/consolidated-on-s3.ts
packages/core/src/domain/medical-record-summary.ts
packages/core/src/external/aws/app-config.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html-no-dedup.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/core/src/fhir-deduplication/__tests__/group-same-observations.test.ts
packages/core/src/fhir-deduplication/deduplicate-fhir.ts
packages/core/src/fhir-deduplication/resources/observation-shared.ts
packages/core/src/fhir-deduplication/resources/procedure.ts
packages/core/src/util/config.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/lambdas-nested-stack.ts
packages/lambdas/src/fhir-to-medical-record.ts

- move dedup to consolidated lambda 
- added new MR summary code for AB-ing, which has no dedup logic
- Local
- Staging

feat(dedup): move fhir dedup to lambda

---

packages/infra/lib/api-stack/fhir-server-connector.ts

Ref: #1040
- add fhir server lambda retries
- Staging
- Production

feat(api): retry fhir server

---

packages/infra/lib/api-stack/fhir-server-connector.ts

Ref: #1040
-  fixing this error `Error: `retryAttempts` must be between 0 and 2.`

feat(api): changing number

---

packages/core/src/external/carequality/ihe-gateway-v2/outbound/ihe-gateway-v2-logic.ts

Ref: #1040
- patientId is already in the payload, no need to write it again

feat(api): remove duplicate key

---

packages/lambdas/src/fhir-to-medical-record.ts

- fix storing of deduped bundle

PATCH store deduplicated bundle for ABing

---

packages/lambdas/src/fhir-to-medical-record.ts

2569 patch use dedup bundle for no dedup mr

---

packages/core/src/fhir-deduplication/__tests__/examples/allergy-examples.ts
packages/core/src/fhir-deduplication/__tests__/group-same-allergies.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-locations.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-observations.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-organizations.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-practitioners.test.ts
packages/core/src/fhir-deduplication/deduplicate-fhir.ts
packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts
packages/core/src/fhir-deduplication/resources/location.ts
packages/core/src/fhir-deduplication/resources/observation-shared.ts
packages/core/src/fhir-deduplication/resources/observation-social.ts
packages/core/src/fhir-deduplication/resources/observation.ts
packages/core/src/fhir-deduplication/resources/organization.ts
packages/core/src/fhir-deduplication/resources/practitioner.ts
packages/core/src/fhir-deduplication/shared.ts
packages/core/src/fhir-to-cda/cda-templates/components/__tests__/encounter-examples.ts
packages/core/src/fhir-to-cda/cda-templates/components/__tests__/make-encounter.ts
packages/core/src/fhir-to-cda/cda-templates/components/__tests__/make-organization.ts
packages/core/src/mpi/normalize-address.ts

refs. metriport/metriport-internal#2154
- Organization 
- Location
- Practitioner
- AllergyIntolerance
- Local
- https://www.loom.com/share/5a44a74308b64a02bacc4976183b8c1e?sid=8cd0b2ab-da46-448d-ae1b-666532a716c4
- DONT BE HARSH ^ I haven't watched it myself yet. 🙈

feat(core): organizations, practitioners, locations, allergies

---

packages/core/src/fhir-deduplication/__tests__/group-same-coverages.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-related-persons.test.ts
packages/core/src/fhir-deduplication/deduplicate-fhir.ts
packages/core/src/fhir-deduplication/resources/coverage.ts
packages/core/src/fhir-deduplication/resources/related-person.ts
packages/core/src/fhir-to-cda/cda-templates/components/__tests__/make-coverage.ts
packages/core/src/fhir-to-cda/cda-templates/components/__tests__/make-family-related-person.ts
packages/fhir-converter/src/templates/cda/ValueSet/IdentifierType.hbs

Ticket: https://github.com/metriport/metriport-internal/issues/2164
- Upstream: https://github.com/metriport/metriport/pull/2654
- RelatedPerson 
- Coverage 
- Local

2164 related person dedup

---

packages/core/src/fhir-deduplication/__tests__/examples/allergy-examples.ts
packages/core/src/fhir-deduplication/__tests__/group-same-allergies.test.ts
packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts

- Removed import from `_tests_`

fix(core): fixed import from _tests_

---

packages/core/src/fhir-deduplication/__tests__/combine-two-conditions.test.ts

Refs: #[2569](https://github.com/metriport/metriport/issues/2569)
- fixed erroring test

fix(dedup): fix failing test

---

packages/core/src/external/fhir/shared/bundle.ts

Refs: #[2569](https://github.com/metriport/metriport/issues/2569)
- document references missing from deduped bundle

fix(dedup): missing doc refs

---

packages/fhir-converter/src/lib/handlebars-converter/__tests__/handlebars-helpers.test.js
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js

- No printing on undefined date - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1724962180534019?thread_ts=1724914006.228799&cid=C04T256DQPQ)
- Handle the case of date being null to prevent errors
- Local

PATCH RELEASE 2024_08_29 Fhir converter - log fixes

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html-no-dedup.ts
packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/core/src/fhir-deduplication/__tests__/combine-two-conditions.test.ts
packages/core/src/fhir-deduplication/resources/diagnostic-report.ts
packages/core/src/fhir-deduplication/shared.ts
packages/utils/src/fhir-deduplication/dedup-files.ts
packages/utils/src/fhir-deduplication/validate-converted-xmls-healthlake.ts

Ref. metriport/metriport#2179
- Update extensions reference to use Related Artifacts - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725053017008029)
- Update Social history in MR to use all dates available - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1724976777096879)
- Local
- Staging
- Production
Check each PR.

fix(api): artifact extension and social history all times

---

packages/core/src/fhir-deduplication/__tests__/group-same-medications.test.ts
packages/core/src/fhir-deduplication/resources/medication.ts
packages/core/src/fhir-deduplication/shared.ts

- Upstream: https://github.com/metriport/metriport/pull/2693
- Added backup keys as per [this thread](https://github.com/metriport/metriport/pull/2693#discussion_r1741223111 )
- Local

2569 medication backup key

---

packages/core/src/fhir-deduplication/__tests__/examples/allergy-examples.ts
packages/core/src/fhir-deduplication/__tests__/group-same-allergies.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-locations.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-organizations.test.ts
packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts
packages/core/src/fhir-deduplication/resources/location.ts

- AllergyIntolerance key recognizes more unknown values 
- Location key is less stringent (allows just the name without the address)
- Local

feat(core): allergies nka + location key + tests

---

packages/core/src/fhir-deduplication/deduplicate-fhir.ts
packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts
packages/core/src/fhir-deduplication/resources/condition.ts
packages/core/src/fhir-deduplication/resources/coverage.ts
packages/core/src/fhir-deduplication/resources/diagnostic-report.ts
packages/core/src/fhir-deduplication/resources/encounter.ts
packages/core/src/fhir-deduplication/resources/family-member-history.ts
packages/core/src/fhir-deduplication/resources/immunization.ts
packages/core/src/fhir-deduplication/resources/location.ts
packages/core/src/fhir-deduplication/resources/medication-administration.ts
packages/core/src/fhir-deduplication/resources/medication-request.ts
packages/core/src/fhir-deduplication/resources/medication-statement.ts
packages/core/src/fhir-deduplication/resources/medication.ts
packages/core/src/fhir-deduplication/resources/observation-social.ts
packages/core/src/fhir-deduplication/resources/observation.ts
packages/core/src/fhir-deduplication/resources/organization.ts
packages/core/src/fhir-deduplication/resources/practitioner.ts
packages/core/src/fhir-deduplication/resources/procedure.ts
packages/core/src/fhir-deduplication/resources/related-person.ts
packages/core/src/fhir-deduplication/shared.ts

Ticket: https://github.com/metriport/metriport/issues/2569
- Improved the flow for: 
- Replacement of consumed links
- Construction of the resulting bundle
- Local

2569 dedup flow change

---

packages/core/src/external/fhir/shared/index.ts
packages/core/src/fhir-deduplication/__tests__/deduplicate-fhir.test.ts
packages/core/src/fhir-deduplication/deduplicate-fhir.ts

- removing duplicate references
- Local

feat(dedup): remove duplicate references

---

package-lock.json
packages/api-sdk/package.json
packages/api-sdk/src/medical/client/metriport.ts
packages/api-sdk/src/medical/models/fhir.ts
packages/api/package.json
packages/api/src/__tests__/e2e/mapi/parts/consolidated.test.part.ts
packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/routes/medical/patient.ts
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/utils/package.json
packages/utils/src/document/document-query.ts

Ticket: #2064
Add dedup to start consolidated and create an internal endpoint for dash
- Local
- Staging
- Production
Check each PR.

2064 dedup from dash

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/utils/package.json

Ref. metriport/metriport#2064
Ticket: #2064
- Downstream: https://github.com/metriport/metriport/pull/2723
- Prod packages for release

fix(api): add packages

---

packages/api/src/external/aws/app-config.ts
packages/api/src/external/fhir-to-cda-converter/connector-direct.ts
packages/api/src/external/fhir-to-cda-converter/connector-lambda.ts
packages/core/src/domain/conversion/fhir-to-cda.ts
packages/core/src/external/aws/app-config.ts
packages/core/src/fhir-to-cda/cda-generators.ts
packages/core/src/fhir-to-cda/cda-templates/clinical-document/custodian.ts
packages/core/src/fhir-to-cda/fhir-to-cda.ts
packages/lambdas/src/fhir-to-cda-converter.ts

- Upstream: https://github.com/metriport/metriport/pull/2684
- Introduces an FF which allows us to set the CX organization as the CDA custodian
- Local

1603 cda custodian

---

packages/utils/src/fhir-dedup/condition.ts
packages/utils/src/fhir-dedup/coverage.ts
packages/utils/src/fhir-dedup/location.ts
packages/utils/src/fhir-dedup/medication-administration.ts
packages/utils/src/fhir-dedup/medication-requests.ts
packages/utils/src/fhir-dedup/medication-statement.ts
packages/utils/src/fhir-dedup/medication.ts
packages/utils/src/fhir-dedup/related-person.ts
packages/utils/src/fhir-dedup/report-dedup.ts
packages/utils/src/fhir-dedup/resource-props.ts
packages/utils/src/fhir-dedup/shared.ts
packages/utils/src/fhir-dedup/validate-references.ts

- Upstream: https://github.com/metriport/metriport/pull/2707
- Downstream: https://github.com/metriport/metriport/pull/2720
- update "link" extension to use artifact
- add report of missing refs to the report dedup script
- add Coverage - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725481313349429)
- add Location - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725482995233629)
- add RelatedPerson - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725485141642609)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2179 Dedup report: Report missing refs, Coverage, Location, RelatedPerson

---

packages/utils/src/fhir-dedup/allergy-intolerance.ts
packages/utils/src/fhir-dedup/condition.ts
packages/utils/src/fhir-dedup/coverage.ts
packages/utils/src/fhir-dedup/diagnostic-report.ts
packages/utils/src/fhir-dedup/encounter.ts
packages/utils/src/fhir-dedup/family-member-history.ts
packages/utils/src/fhir-dedup/immunization.ts
packages/utils/src/fhir-dedup/location.ts
packages/utils/src/fhir-dedup/medication-administration.ts
packages/utils/src/fhir-dedup/medication-requests.ts
packages/utils/src/fhir-dedup/medication-statement.ts
packages/utils/src/fhir-dedup/medication.ts
packages/utils/src/fhir-dedup/observation.ts
packages/utils/src/fhir-dedup/organization.ts
packages/utils/src/fhir-dedup/practitioner.ts
packages/utils/src/fhir-dedup/procedure.ts
packages/utils/src/fhir-dedup/related-person.ts
packages/utils/src/fhir-dedup/report-dedup.ts
packages/utils/src/fhir-dedup/resource-props.ts
packages/utils/src/fhir-dedup/shared.ts
packages/utils/src/fhir-dedup/validate-references.ts

- Upstream: https://github.com/metriport/metriport/pull/2698
- Downstream: https://github.com/metriport/metriport/pull/2707
- add AllergyIntolerance to the dedup report script - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725371602362969)
- add Immunization to the dedup report script - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725391385217109)
- add more columns for Medication
- fix bugs on MedicationStatement and Condition
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2179 Dedup report: AllergyIntolerance and Immunization

---

packages/utils/src/fhir-dedup/allergy-intolerance.ts
packages/utils/src/fhir-dedup/condition.ts
packages/utils/src/fhir-dedup/coverage.ts
packages/utils/src/fhir-dedup/diagnostic-report.ts
packages/utils/src/fhir-dedup/encounter.ts
packages/utils/src/fhir-dedup/family-member-history.ts
packages/utils/src/fhir-dedup/immunization.ts
packages/utils/src/fhir-dedup/location.ts
packages/utils/src/fhir-dedup/medication-administration.ts
packages/utils/src/fhir-dedup/medication-requests.ts
packages/utils/src/fhir-dedup/medication-statement.ts
packages/utils/src/fhir-dedup/medication.ts
packages/utils/src/fhir-dedup/observation.ts
packages/utils/src/fhir-dedup/organization.ts
packages/utils/src/fhir-dedup/practitioner.ts
packages/utils/src/fhir-dedup/procedure.ts
packages/utils/src/fhir-dedup/related-person.ts
packages/utils/src/fhir-dedup/report-dedup.ts
packages/utils/src/fhir-dedup/resource-props.ts
packages/utils/src/fhir-dedup/shared.ts
packages/utils/src/fhir-dedup/validate-references.ts

- Upstream: https://github.com/metriport/metriport/pull/2696
- Downstream: https://github.com/metriport/metriport/pull/2703
- add Observation to the report dedup script - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725310901361199)
- add DiagnosticReport to the report dedup script - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725331463525339)
- add Encounters to the report dedup script - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725336409384819)
- create shared column types and functions
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2179 Dedup report: Observation, DiagnosticReport, Encounters

---

packages/utils/src/fhir-dedup/allergy-intolerance.ts
packages/utils/src/fhir-dedup/condition.ts
packages/utils/src/fhir-dedup/coverage.ts
packages/utils/src/fhir-dedup/csv.ts
packages/utils/src/fhir-dedup/diagnostic-report.ts
packages/utils/src/fhir-dedup/encounter.ts
packages/utils/src/fhir-dedup/family-member-history.ts
packages/utils/src/fhir-dedup/get-files.ts
packages/utils/src/fhir-dedup/immunization.ts
packages/utils/src/fhir-dedup/location.ts
packages/utils/src/fhir-dedup/medication-administration.ts
packages/utils/src/fhir-dedup/medication-requests.ts
packages/utils/src/fhir-dedup/medication-statement.ts
packages/utils/src/fhir-dedup/medication.ts
packages/utils/src/fhir-dedup/observation.ts
packages/utils/src/fhir-dedup/organization.ts
packages/utils/src/fhir-dedup/practitioner.ts
packages/utils/src/fhir-dedup/procedure.ts
packages/utils/src/fhir-dedup/related-person.ts
packages/utils/src/fhir-dedup/report-dedup.ts
packages/utils/src/fhir-dedup/resource-props.ts
packages/utils/src/fhir-dedup/shared.ts
packages/utils/src/fhir-dedup/validate-references.ts

Ticket: https://github.com/metriport/metriport-internal/issues/2179
- Upstream: https://github.com/metriport/metriport/pull/2695
- Downstream: https://github.com/metriport/metriport/pull/2698
Add more resources to the dedup report 
- `MedicationRequest` - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725142709213969)
- `MedicationAdministration` - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725145522943229)
- `Condition` - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725150185965369)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2179 Dedup report: MedicationRequest, MedicationAdministration, and Condition

---

packages/utils/src/customer-requests/medical-records-local-with-brief.ts

Make the local MR w/ Brief script easier to use.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Make the local MR w/ Brief script easier to use

---

packages/utils/src/customer-requests/medical-records-create-from-s3.ts
packages/utils/src/customer-requests/medical-records-create.ts
packages/utils/src/customer-requests/medical-records-local.ts
packages/utils/src/shared/duration.ts

Ticket: https://github.com/metriport/metriport-internal/issues/2172
- downstream: https://github.com/metriport/metriport/pull/2695
- Create MR from S3 - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1724878383838679?thread_ts=1724872553.420299&cid=C0616FCPAKZ)
- log the cultprit when fails to formatAsDateTime - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1724885917317999?thread_ts=1724827486.314079&cid=C04T256DQPQ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2172 Create MR from S3

---

packages/core/src/fhir-deduplication/__tests__/group-same-allergies.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-med-statements.test.ts
packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts
packages/core/src/fhir-deduplication/resources/condition.ts
packages/core/src/fhir-deduplication/resources/medication-statement.ts
packages/core/src/fhir-deduplication/resources/procedure.ts

- addressing FHIR errors related to empty arrays
- https://github.com/metriport/metriport/pull/2731 
- refactoring unit tests

feat(dedup): addressing fhir errors and allowing medication statements without dates

---

packages/core/src/fhir-deduplication/__tests__/shared.test.ts
packages/core/src/fhir-deduplication/shared.ts

- merge preference for fields with value that is not "unknown"
- unit tests

2569 merge preferences

---

packages/core/src/external/fhir/export/fhir-to-ndjson.ts
packages/utils/src/customer-requests/medical-records-create-from-s3.ts
packages/utils/src/fhir/bundle-to-ndjson.ts
packages/utils/src/shared/duration.ts

none
Script to generate NDJSON files.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2179 Script to generate NDJSON files

---

packages/api/src/routes/medical/facility.ts

refs. metriport/metriport-internal#2224
- Org creation on facility creation
- Local

feat(api): org creation on sandbox

---

.github/workflows/fern-check.yml
fern/definition/medical/facility.yml
fern/definition/medical/fhir.yml
fern/definition/medical/organization.yml
fern/definition/medical/patient.yml

Ref: #1040
- trying to fix Fern

feat(athena): fix fern?

---

packages/core/src/fhir-deduplication/__tests__/group-same-family-histories.test.ts
packages/core/src/fhir-deduplication/__tests__/process-document-references.test.ts
packages/core/src/fhir-deduplication/deduplicate-fhir.ts
packages/core/src/fhir-deduplication/resources/document-reference.ts
packages/core/src/fhir-deduplication/resources/family-member-history.ts
packages/core/src/fhir-deduplication/shared.ts

Refs: #2569
- fixes for familyMemberHistory having 0 as value for onsetAge
- fix for documentReference having a start date after its end date
- Local

fix(fhir): family member hx and invalid period in doc ref

---

packages/api/src/external/hie/__tests__/run-or-schedule-patient-discovery.test.ts
packages/api/src/external/hie/run-initial-patient-discovery.ts
packages/api/src/external/hie/run-or-schedule-patient-discovery.ts

Ticket: #2223
- remove cq org filtering on cw

2223 fix cw

---

packages/utils/src/fhir-deduplication/dedup-files.ts

none
Update dedup script - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725503160503099?thread_ts=1725490497.216659&cid=C06CQC7GQG3)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2179 Update dedup script

---

package-lock.json
packages/utils/package.json
packages/utils/src/fhir-deduplication/report/report-dedup.ts
packages/utils/src/fhir-deduplication/validate-converted-xmls-healthlake.ts
packages/utils/src/fhir/process-ndjson-output.ts
packages/utils/src/fhir/validate/bundle-to-ndjson.ts
packages/utils/src/fhir/validate/process-ndjson-output.ts
packages/utils/src/fhir/validate/process-single-output.ts
packages/utils/src/fhir/validate/validate-all-bundles.ts
packages/utils/src/fhir/validate/validate-small-bundles.ts
packages/utils/src/shared/duration.ts

none
- Update fhir validation script (that sends small payloads)
- Create a script to validate any script size using `$import`
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2179 FHIR validation script processing large bundles

---

packages/core/src/external/athenahealth/get-patient.ts

Ref: #2115
- fix possible undefined

feat(athena): response undefined

---

packages/core/src/shareback/ensure-ccd-exists.ts

refs. metriport/metriport-internal#2240
- Fixed the URL for an internal route 
- Staging

fix(infra): fix lb url getter

---

packages/infra/lib/api-stack/api-service.ts

Ref: #2170
- giving ecs access to read secrets
- Staging
- Production

feat(athena): adding access to secrets

---

.gitignore
packages/core/src/external/fhir/shared/bundle.ts
packages/core/src/fhir-deduplication/__tests__/group-same-encounters.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-locations.test.ts
packages/core/src/fhir-deduplication/__tests__/group-same-related-persons.test.ts
packages/core/src/fhir-deduplication/__tests__/remove-dangling-link.test.ts
packages/core/src/fhir-deduplication/deduplicate-fhir.ts
packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts
packages/core/src/fhir-deduplication/resources/condition.ts
packages/core/src/fhir-deduplication/resources/coverage.ts
packages/core/src/fhir-deduplication/resources/diagnostic-report.ts
packages/core/src/fhir-deduplication/resources/encounter.ts
packages/core/src/fhir-deduplication/resources/family-member-history.ts
packages/core/src/fhir-deduplication/resources/immunization.ts
packages/core/src/fhir-deduplication/resources/location.ts
packages/core/src/fhir-deduplication/resources/medication-administration.ts
packages/core/src/fhir-deduplication/resources/medication-request.ts
packages/core/src/fhir-deduplication/resources/medication-statement.ts
packages/core/src/fhir-deduplication/resources/medication.ts
packages/core/src/fhir-deduplication/resources/observation-social.ts
packages/core/src/fhir-deduplication/resources/observation.ts
packages/core/src/fhir-deduplication/resources/organization.ts
packages/core/src/fhir-deduplication/resources/practitioner.ts
packages/core/src/fhir-deduplication/resources/procedure.ts
packages/core/src/fhir-deduplication/resources/related-person.ts
packages/core/src/fhir-deduplication/shared.ts
packages/utils/src/fhir-deduplication/compare-dedups.ts
packages/utils/src/fhir-deduplication/dedup-files.ts
packages/utils/src/fhir-deduplication/report/validate-references.ts

Reverts metriport/metriport#2816
Downstream:
- https://github.com/metriport/metriport/pull/2818

Revert the Revert for Faster Deduplication

---

packages/core/src/external/fhir/shared/bundle.ts
packages/core/src/fhir-deduplication/__tests__/deduplicate-fhir.test.ts
packages/core/src/fhir-deduplication/__tests__/remove-dangling-link.test.ts
packages/core/src/fhir-deduplication/deduplicate-fhir.ts
packages/core/src/fhir-to-cda/cda-templates/components/__tests__/make-patient.ts

Refs: #2569
- https://github.com/metriport/metriport/pull/2819
- https://github.com/metriport/metriport/pull/2811
- bug fix here
- Local
Check each PR.

fix(dedup): Bug Fix of missing patient for Faster Deduplication

---

packages/api/src/external/ehr/athenahealth/command/get-patients-from-appointments.ts

Ref: #2170
- increase lookback for appointments now that the schedule it once a day

feat(athena): increase lookback

---

packages/api/src/command/medical/document/document-conversion-status.ts
packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/patient/add-coordinates.ts
packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/command/webhook/webhook.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts
packages/api/src/external/carequality/process-outbound-patient-discovery-resps.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/routes/helpers/request-analytics.ts
packages/core/src/external/analytics/posthog.ts
packages/core/src/external/fhir/consolidated/deduplicate.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-query.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-retrieval.ts
packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts

Ref. metriport/metriport#2298
- Upstream: https://github.com/metriport/metriport-internal/pull/2301
- Group analytics by company
- Local
- Staging
- Production

fix(api): company grouping

---

packages/api/src/command/medical/document/document-conversion-status.ts
packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/patient/add-coordinates.ts
packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/command/webhook/webhook.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts
packages/api/src/external/carequality/process-outbound-patient-discovery-resps.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/routes/helpers/request-analytics.ts
packages/core/src/external/analytics/posthog.ts
packages/core/src/external/fhir/consolidated/deduplicate.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-query.ts
packages/lambdas/src/ihe-gateway-v2-inbound-document-retrieval.ts
packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts

Ref. metriport/metriport#2298
- reverting to unblock staging

fix(api): revert posthog

---

package-lock.json
packages/utils/package.json
packages/utils/src/cloudwatch/fhir-to-bundle-lambda.ts
packages/utils/src/cloudwatch/fhir-to-medical-record-lambda.ts
packages/utils/src/cloudwatch/query.ts

Refs: #799
- helper script and function to filter cloudwatch logs
- Local
Check each PR.

feat(cloudwatch): helper script to parse cloudwatch logs

---

packages/utils/src/customer-requests/medical-records-trigger.ts

Refs: #799
- medical record trigger script uses wrong query params for date
- Local

fix(script): datefrom not fromdate

---

packages/fhir-converter/src/lib/handlebars-converter/__tests__/handlebars-helpers.test.js
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/DataType/Quantity.hbs
packages/fhir-converter/src/templates/cda/DataType/SimpleQuantity.hbs
packages/fhir-converter/src/templates/cda/Resources/MedicationStatement.hbs

Refs: #[2147](https://github.com/metriport/metriport-internal/issues/2147)
- quantities of 0 don't get mapped and then observations have no values in them
- Local

fix(fhir): quantity 0 results in no value in observations

---

packages/fhir-converter/src/templates/cda/Sections/Hospital_Discharge_Medications.hbs

feat(fhir): simple dumb bug

---

packages/core/src/mpi/__tests__/inbound-epic-match.test.ts
packages/core/src/mpi/match-patients.ts

Refs: #[1766](https://github.com/metriport/metriport-internal/issues/1766)
- minor bug fix for epic similarity algo
- Local
Check each PR.

feat(inbound): ssn bug fix

---

packages/core/src/external/athenahealth/index.ts
packages/shared/src/interface/external/athenahealth/appointment.ts

Ticket: https://github.com/metriport/metriport-internal/issues/2170
- filtering to only fulfilled subscriptions

PATCH athena appoitments

---

packages/core/src/external/athenahealth/index.ts
packages/shared/src/interface/external/athenahealth/medication.ts

- changing typing and throwing error if create med was not successful.

1040 patch type for athena

---

packages/infra/lib/patient-import-nested-stack.ts

feat(patient-import): fix duration

---

packages/api/src/external/fhir/patient/__tests__/count-resources-on-s3.test.ts
packages/api/src/external/fhir/patient/count-resources-on-fhir.ts
packages/api/src/external/fhir/patient/count-resources-on-s3.ts
packages/api/src/external/fhir/patient/count-resources-shared.ts
packages/api/src/external/fhir/patient/count-resources.ts
packages/api/src/models/medical/__tests__/patient.ts
packages/api/src/routes/internal.ts
packages/api/src/routes/medical/patient.ts
packages/core/src/external/fhir/__tests__/bundle.ts

none
Count resources using consolidated from S3.
- Local
- Staging
- Sandbox
- none
- Production
- none

2215 Count resources using consolidated from S3

---

packages/infra/lib/patient-import-nested-stack.ts

- Upstream: https://github.com/metriport/metriport/pull/2853
Wait time on bulk import to 1min.
none

PATCH RELEASE 2330 Wait time on bulk import to 1min

---

packages/core/src/command/patient-import/patient-import-cloud.ts

Ref: #2330
- splitting sqs into chunks and sleeping
- Staging
- Production

feat(athena): chunking sqs

---

packages/infra/lib/patient-import-nested-stack.ts

Ref: #2330
- increase patient rate to 2pt / min

feat(patient import): patch speed

---

packages/infra/lib/patient-import-nested-stack.ts

Ref: #2330
- doubling speed for patient create on patient import

PATCH patch speed for patient create

---

packages/api/src/external/carequality/document/get-non-existent-doc-refs.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts

Ticket: #2349
- Add temp logs to debug docs to download function
Check each PR.

PATCH: Add temp logs

---

packages/api/src/command/medical/patient/consolidated-get.ts
packages/core/src/command/consolidated/__tests__/consolidated-filter-by-date.test.ts
packages/core/src/command/consolidated/__tests__/consolidated-filter-shared.test.ts
packages/core/src/command/consolidated/__tests__/consolidated-filter.test.ts
packages/core/src/command/consolidated/consolidated-create.ts
packages/core/src/command/consolidated/consolidated-filter-by-date.ts
packages/core/src/command/consolidated/consolidated-filter-shared.ts
packages/core/src/command/consolidated/consolidated-filter.ts
packages/core/src/command/consolidated/consolidated-get.ts
packages/core/src/command/consolidated/snapshot-on-s3.ts
packages/core/src/external/fhir/__tests__/patient.ts
packages/core/src/external/fhir/shared/__tests__/age.test.ts
packages/core/src/external/fhir/shared/age.ts
packages/shared/src/medical/fhir/bundle.ts
packages/utils/src/customer-requests/medical-records-create-from-s3.ts
packages/utils/src/fhir/sort-bundle-resources.ts

Ticket: https://github.com/metriport/metriport-internal/issues/2215
none
- Consolidated filters by age
- Fix filter by date range to be inclusive on the end of the range
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

2215 Consolidated filters by age

---

packages/api/src/external/carequality/document/get-non-existent-doc-refs.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts

Ref. https://github.com/metriport/metriport-internal/issues/2349
- Upstream: mpme
- revert previous logs
- https://github.com/metriport/metriport/pull/2880
- https://github.com/metriport/metriport/pull/2879

PATCH REVERT LOGS

---

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/schema.ts
packages/core/src/external/carequality/ihe-gateway-v2/utils.ts

- fixing schema issue for allscripts
- Local
Check each PR.

fix(cq): allscripts schema error

---

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/schema.ts
packages/core/src/external/carequality/ihe-gateway-v2/schema.ts

- fixing schema issue for ehex
- Local
Check each PR.

fix(cq): ehex  schema error

---

packages/api/src/command/medical/patient/__tests__/consolidated-create.test.ts
packages/api/src/command/medical/patient/consolidated-create.ts
packages/core/src/command/consolidated/__tests__/remove-contained-patients.test.ts
packages/core/src/command/consolidated/consolidated-shared.ts
packages/core/src/command/consolidated/get-snapshot-local.ts
packages/core/src/command/consolidated/snapshot-on-s3.ts
packages/core/src/domain/consolidated/filename.ts

Refs: #799
- no contained included in resources on data contribution 
- filter out contained patients 
- Local

fix(contribution): filtering out contained patients

---

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts
packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/create/iti55-envelope.ts
packages/core/src/external/carequality/pd/process-inbound-pd.ts
packages/core/src/external/carequality/pd/validating-pd.ts
packages/core/src/mpi/__tests__/inbound-epic-match.test.ts
packages/core/src/mpi/inbound-patient-mpi-metriport-api.ts
packages/core/src/mpi/match-patients.ts
packages/core/src/mpi/normalize-patient.ts
packages/shared/src/domain/contact/__tests__/email.test.ts
packages/shared/src/domain/contact/__tests__/phone.test.ts
packages/utils/src/saml/mock-ihe-gateway.ts

Refs: #1667
- outbound bad bug
- inbound a bunch of bugs resulting in situations with multiple names not matching, and emails never getting processed properly
- Local
Check each PR.

feat(cq): inbound and outbound issues identified

---

packages/api/src/command/medical/patient/consolidated-get.ts

Refs: #2569 
- fixing incorrect bundle length
- [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1728903220826379) 
- Local

feat(consolidated): fix bundle length

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/shared/src/domain/address/state.ts
packages/shared/src/domain/address/territory.ts
packages/utils/package.json

Ticket: #2845
- Upstream: https://github.com/metriport/metriport-internal/pull/2366
- Release packages for states and terrirtories
Check each PR.

2845 us package

---

packages/api/src/domain/medical/__tests__/patient-demographics.test.ts
packages/api/src/domain/medical/patient-demographics.ts
packages/api/src/external/carequality/__tests__/cq-patient-data.ts
packages/api/src/external/carequality/patient-demographics.ts
packages/api/src/external/commonwell/__tests__/cw-patient-data.ts
packages/api/src/external/commonwell/patient-demographics.ts
packages/api/src/routes/medical/internal-patient.ts
packages/shared/src/domain/address/state.ts
packages/shared/src/domain/address/territory.ts
packages/shared/src/domain/contact/phone.ts

Ref: #1040
Addressing small fixes instead of waiting for larger normalization PR https://github.com/metriport/metriport/pull/2870
- making sure patient demo aug only uses valid 10 digit phone numbers
- making sure patient demo aug normalizes US states and territories
- making sure patient demo aug normalizes zips with new function 
- making sure coverage assessment uses same normalization as patient import
- Local
- Staging
- Production

feat(bug): fixing bugs related to zips, phones

---

packages/api/src/shared/sandbox/sandbox-seed-data-chris.ts
packages/api/src/shared/sandbox/sandbox-seed-data.ts

- Add chris smith
Check each PR.

fix(api): add sandbox patient

---

packages/api/src/command/medical/patient/convert-fhir-bundle.ts
packages/core/src/external/opensearch/file-searcher-direct.ts
packages/utils/src/lambda/execute-lambda.ts

Ref. metriport/metriport#2845
none
Convert-fhit-bundle and file-searcher-direct to use out.log.
none

1040 Convert-fhit-bundle and file-searcher-direct to use out.log

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/lambdas/scripts/prep-deploy.sh
packages/react-native-sdk/package.json
packages/shared/package.json
packages/shared/src/medical/fhir/resources.ts
packages/utils/package.json

Ticket: #1040
- adding Patient, Location, and Organization to general resource filtering
- Local
- Staging
- Production

feat(consolidated): new patient location organization filtering

---

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx
fern/definition/medical/fhir.yml

Ref: #1040
- docs update to mention hydration
- Staging
- Production

feat(docs): adding hydration info

---

docs/home/api-info/webhooks.mdx

Commit 0d6e991f20cbec860d1948b9cd9cbe3cdf8b44c4 moved the location of `mock-webhook.ts`. This PR adjusts sources to changes.

fix: update mock webhook reference

---

.github/workflows/branch-to-staging.yml

Refs: #799
- leftover from https://github.com/metriport/metriport/pull/2914
- works when running branch to staging now

feat(cicd): update branch to staging vars

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts

refs. metriport/metriport#2972
n/a
update adhd mr verbage
TBD

feat(api): update adhd mr verbage

---

docs/home/api-info/webhooks.mdx

Ticket: metriport/metriport-internal#1040
- Upstream: https://github.com/metriport/metriport/pull/2950
Merging the PR https://github.com/metriport/metriport/pull/2950 into `develop`.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

External 2950 - Update reference to WH sample source code

---

.github/bots/README.md
.github/bots/package-lock.json
.github/bots/package.json
.github/bots/src/check-pr-branch.js
.github/pull_request_template.md
.github/workflows/check-pr-branch.yml

none
Add check-pr-branch GH action bot - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1730234328570499?thread_ts=1730232994.500759&cid=C0616FCPAKZ). Also updates the PR template.
It sends a notification if:
- PR points to `master` but not titled as RELEASE or PATCH
- PR is titled as RELEASE or PATCH but not points to `master`
Notifications are:
- comment to the PR
- message on Slack
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Add check-pr-branch GH action bot

---

packages/api/src/external/carequality/command/cq-directory/parse-cq-directory-entry.ts
packages/api/src/external/ehr/athenahealth/shared.ts
packages/core/src/external/athenahealth/index.ts
packages/core/src/mpi/normalize-patient.ts
packages/shared/src/domain/address/__tests__/normalize-zip.test.ts
packages/shared/src/domain/address/zip.ts
packages/utils/src/bulk-insert-patients.ts

Ref: #1040
- safeParse patients and issue "info" alert if patient does not pass
- switch zip normalization to more current version
- Local
- Staging
- Production

feat(ehr): zod schema issues into info instead of error + zip normalization

---

packages/utils/src/fhir-converter/fhir-resource-counts/develop-fhir-resource-count.json

- Updated the outdated resource counts on FHIR tests
- N/A

fix(utils): upd fhir conv test resource counts

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Sections/Notes.hbs
packages/utils/src/fhir-converter/fhir-resource-counts/develop-fhir-resource-count.json

Ticket: https://github.com/metriport/metriport-internal/issues/2454
- Fixed DiagnosticReport mapping to catch more doctors notes from unstructured CDA parts
- Misc other fixes on the FHIR Converter
- Local

2454 missing notes

---

packages/infra/lib/api-stack/api-service.ts

none
Add alarms to API's ALB/TG - [context](https://metriport.slack.com/archives/C07BFHNML0P/p1730316451327339)
- Local
- none
- Staging
- Check that they're passing, since the staging monitors are by default disabled
- Sandbox
- none
- Production

1040 Add alarms to API's LB/TG

---

.cursorignore
.cursorrules
.gitignore
.vscode/settings.json

none
Add settings for Cursor - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1730040747018219).
...WIP
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Add settings for Cursor

---

packages/utils/src/bulk-insert-patients.ts

none
Bulk-insert-patient accepts duplicated patients and merges them.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Bulk-insert-patient accepts duplicated patients

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-bmi.ts

- [context](https://metriport-inc.sentry.io/issues/5687957893/?alert_rule_id=14031186&alert_type=issue&environment=production&notification_uuid=1fe63196-c7bf-4b37-a137-8d37e4406160&project=4504912884924416&referrer=slack)
- Local
- Production
Check each PR.

PATCH: Trim Error Bundle

---

packages/api/src/external/carequality/command/cq-directory/parse-cq-directory-entry.ts

- Ignoring new XDR endpoint on the CQ directory 
- N/A

PATCH RELEASE 2024-11-12 CQ Directory

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Sections/Notes.hbs

refs. metriport/metriport-internal#2454
- Refactored the code for processing Notes sections to more accurately extract text and entries
- Local

fix(api): extracting more diag reports notes

---

docs/medical-api/more-info/limits.mdx

Ref: #1040
- fixing limits table

PATCH docs limit table fix

---

docs/medical-api/more-info/limits.mdx

Ref: #1040
- small improvements

PATCH more docs stuff

---

docs/medical-api/more-info/limits.mdx

Ref: #1040
- add links to operations

PATCH link to operations in limit docs

---

docs/medical-api/api-reference/document/start-document-query.mdx
docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx
docs/medical-api/api-reference/patient/create-patient.mdx
docs/medical-api/api-reference/patient/update-patient.mdx
docs/medical-api/more-info/limits.mdx

- adding link to limiting page

PATCH adding link to limiting page for operations

---

docs/medical-api/more-info/contribution.mdx

PATCH docs shareback

---

packages/infra/config/env-config.ts

Ref: #2498
- adding config types for new elation stuff

feat(elation): patch config

---

packages/infra/lib/secrets-stack.ts

Ref: #2498
- adding athena and elation to secrets building step
- Local
- Staging
- Sandbox
- Production

feat(elation): ehr secrets

---

packages/api/src/external/ehr/elation/shared.ts
packages/shared/src/domain/secrets.ts

Ref: #2498
- adjusting secrets approach to may to key/value pairs
- Local
- Staging
- Sandbox
- Production

feat(elation): fixing secrets

---

packages/core/src/external/elation/index.ts

Ref: https://github.com/metriport/metriport-internal/issues/2498
- patch prod elation env from api to app

feat(elation): patch prod env

---

packages/core/src/external/athenahealth/index.ts
packages/core/src/external/elation/index.ts
packages/shared/src/interface/external/elation/appointment.ts

Ref: #2498
- allowing null patient / status

feat(elation): patch zod schema

---

packages/core/src/external/aws/lambda-logic/bundle-to-brief.ts

Ticket: #metriport/metriport-internal/issues/2526
- If any errors happen during AI brief gen, we report to Sentry, and fail gracefully, so as to avoid interruptions in MR summary gen
- Local
- Staging

2526 ai brief graceful failure

---

packages/api/src/external/ehr/elation/command/sync-patient.ts

Ref: #1040
- change elation link

feat(elation): patch elation link

---

packages/api/src/external/ehr/elation/shared.ts
packages/shared/src/interface/external/elation/patient.ts

Ref: #1040
- elation address line 2 can be null, so account for this

feat(ehr): patch elation address line 2

---

packages/api/src/command/jwt-token.ts
packages/api/src/sequelize/migrations/2024-12-17_00-alter-jwt_token-increase-token-length_2.ts

feat(ehr): adjust column size

---

packages/core/src/external/cda/__tests__/example.xml
packages/core/src/external/cda/__tests__/partition-payload.test.ts
packages/core/src/external/cda/partition-payload.ts
packages/lambdas/src/sqs-to-converter.ts
packages/utils/src/fhir-converter/convert.ts
packages/utils/src/patient-import/validate-file.ts

Ticket: 
- https://github.com/metriport/metriport-internal/issues/2343
- Downstream: 
- https://github.com/metriport/metriport/pull/3104
- https://github.com/metriport/metriport/pull/3102
- REVERT the revert
- reverted PR: https://github.com/metriport/metriport/pull/3097
- original PR: https://github.com/metriport/metriport/pull/3040
- Local
- Staging

Revert "Revert "Merge pull request #3040 from metriport/2343-large-file-conversion

---

packages/lambdas/src/sqs-to-converter.ts

refs. metriport/metriport-internal#2343
- Adding a Sentry warning to see how often we get super large chunks after payload partitioninig
- Local

feat(lambda): sentry warning on large chunks

---

packages/utils/src/fhir-deduplication/dedup-files.ts

fix(utils): tiny change

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/shared/package.json
packages/utils/package.json

Ref: #000
- api@1.22.11
- @metriport/api-sdk@14.0.4
- @metriport/carequality-cert-runner@1.11.11
- @metriport/carequality-sdk@0.13.11
- @metriport/commonwell-cert-runner@1.19.11
- @metriport/commonwell-jwt-maker@1.17.11
- @metriport/commonwell-sdk@5.1.11
- @metriport/core@1.17.11
- @metriport/ihe-gateway-sdk@0.12.11
- infrastructure@1.15.11
- @metriport/shared@0.14.6
- utils@1.18.11
- Downstream: _https://github.com/metriport/metriport/pull/3114
- prod packages for https://github.com/metriport/metriport/pull/3114

Prod Packages

---

packages/core/src/domain/ai-brief/modify-resources.ts
packages/core/src/external/aws/lambda-logic/bundle-to-brief.ts
packages/core/src/external/aws/lambda-logic/modify-resources.ts

refs. metriport/metriport-internal#2526
- WIP: Breaking down the `bundle-to-brief` into more manageable pieces
- WIP: Stronger types for the altered FHIR resources
- Local
- Staging

feat(core): ai brief gen stronger types

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-bmi.ts

Ticket: #1040
- Minor updats to the bmi summary
- Local
- Staging
- Production

fix(api): bmi summary updates

---

packages/core/src/command/ai-brief/shared.ts

Ticket: #3098 
- patch issue to show the ai summary in PDF
Check each PR.

PATCH: ai brief consolidated

---

packages/core/src/__tests__/ai-brief-consolidated.test.ts
packages/core/src/command/ai-brief/shared.ts
packages/core/src/external/fhir/patient/shared.ts

Ref. metriport/metriport-internal#2526
- Upstream:  none
- Patch to only return when has meta
Check each PR.

PATCH: Only if has source

---

packages/core/src/command/ai-brief/create.ts
packages/core/src/domain/ai-brief/modify-resources.ts

Ticket: #metriport/metriport-internal/issues/799
- Some bundle slimming improvements:
- removed unnecessary IDs
- cutting practitioner names for care teams
- replacing condition references with condition names for med-related resources
- fixed a bad log
- Local

799 minor fixes

---

docs/ehr-integrations/elation.mdx

n/a
add elation demo to docs
- Local

feat(docs): add elation demo

---

packages/api/src/command/medical/document/document-webhook.ts
packages/api/src/external/fhir/shared/hydrate-bundle.ts
packages/core/src/external/fhir/document/get-documents.ts
packages/utils/src/fhir/validate/validate-all-bundles.ts

Ticket: #metriport/metriport-internal/issues/799
- Reverting this PR: https://github.com/metriport/metriport/pull/3142
N/A

PATCH Revert "Merge pull request #3142 from metriport/799-patch-minor-fixes"

---

docs/ehr-apps/overview.mdx

n/a
fix ehr app wording on docs
n/a

feat(docs): fix ehr app wording

---

docs/medical-api/handling-data/filters.mdx

refs. metriport/metriport#0000

fix(docs): fix typo

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/shared/package.json
packages/utils/package.json

Ticket: https://github.com/metriport/metriport-internal/issues/2553
Publishing non-alpha packages. See changes.

2553 chore(release): publish

---

packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory-raw-sql.ts
packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts
packages/core/src/command/ai-brief/create.ts
packages/core/src/command/consolidated/consolidated-create.ts

- https://github.com/metriport/metriport-internal/issues/2553
- https://github.com/metriport/metriport-internal/issues/799
- Upstream: https://github.com/metriport/metriport/pull/3178
- https://github.com/metriport/metriport/pull/3181
- https://github.com/metriport/metriport/pull/3184
Check each PR.

RELEASE 2553 Lighter CQ dir rebuild

---

docs/medical-api/more-info/sso.mdx

- No icon on nav
- Local
- Production
Check each PR.

PATCH: SSO ICON

---

package-lock.json

refs. metriport/metriport#3135
PR #3164 
had failed e2e tests because of a bad lockfile. This fixes the lockfile.

feat(infra): fix bad lockfile

---

packages/api-sdk/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/ihe-gateway-sdk/package.json
packages/shared/package.json

refs. metriport/metriport#1772
This reverts commit 702062fab28117a348a427e2947a9c86e9d01187.

Revert "fix(infra): lerna automated bump githead"

---

package-lock.json
packages/core/package.json
packages/core/src/external/fhir/normalization/resources/observation.ts

refs. metriportmetriport-internal#2551
- Adding pkg dep for `convert-units`
- Adding mapping for ft -> cm 
- Local
- Staging
- Production

fix(core): adding pkg dep + adding ft to cm mapping

---

packages/lambdas/package-lock.json
packages/lambdas/package.json

refs. metriportmetriport-internal#2551
- Adding `convert-units` dependency on lambdas
- Staging
- Production

fix(lambda): adding pkg dep to lambdas

---

packages/core/src/external/fhir/consolidated/hydrate.ts

refs. metriport/metriport-internal#2563
- Minor fix for analytics event
- N/A

fix(core): minor fix for analytics

---

packages/artillery-tests/.gitignore
packages/artillery-tests/src/term-server/bulk-lookup-term-server.yml
packages/artillery-tests/src/term-server/healthcheck-term-server.yml
packages/artillery-tests/src/term-server/term-server.js

Ticket: metriport/metriport-internal#2599
- Adding a test for the Term Server
- Local

2599 term server artillery

---

packages/utils/src/customer-requests/resource-metrics.ts

none
Add script to calculate resource-based patient metrics - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1737691508647179?thread_ts=1737665426.905339&cid=C0616FCPAKZ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Add script to calculate resource-based patient metrics

---

packages/api/src/external/fhir/document/draft-update-document-reference.ts
packages/api/src/sentry.ts
packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts
packages/lambdas/src/shared/capture.ts

- related: https://github.com/metriport/metriport-internal/pull/2610
Adjust Sentry's trace sample rate - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1737749668071019)
none

1040 Adjust Sentry's trace sample rate

---

packages/utils/src/bulk-insert-patients.ts
packages/utils/src/bulk-query-patients.ts
packages/utils/src/coverage-assessment.ts
packages/utils/tsconfig.json

none
Nits on coverage assessment related scripts.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Nits on coverage assessment related scripts

---

packages/utils/src/coverage-assessment.ts

none
Update coverage-assessment TSDoc.
none

1040 Update coverage-assessment TSDoc

---

packages/core/src/external/fhir/codeable-concept.ts
packages/core/src/external/fhir/normalization/coding.ts
packages/core/src/external/fhir/shared/__tests__/is-useless-display.test.ts
packages/core/src/fhir-deduplication/shared.ts

refs. metriportmetriport-internal#2572
- Some minor fixes
- Local

fix(core): small follow up fixes

---

packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/external/commonwell/admin/find-patient-duplicates.ts
packages/api/src/routes/medical/internal-patient.ts
packages/commonwell-sdk/src/client/commonwell.ts
packages/utils/src/commonwell/delete-network-links.ts

none
Script to delete CW network links - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1737675748098469?thread_ts=1737663483.297829&cid=C0616FCPAKZ).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

1040 Script to delete CW network links

---

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx
docs/medical-api/handling-data/medical-record-summary.mdx
docs/medical-api/handling-data/webhooks.mdx
docs/mint.json

n/a
add koala + posthog analytics, make conversionType required
- Local

feat(docs): add analytics, make conversionType required

---

packages/core/src/external/fhir/hydration/hydrate-fhir.ts

refs. metriport/metriport-internal#2600
- Add some more stats for FHIR hydration to track improvement
- Local

fix(core): more stats for hydration

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-bmi.ts

Ref. metriport/metriport-internal#2643
Ticket: #2643
- Update summary to include recorder information
_[Patch PRs:]_
- :warning: [ ] Run E2E tests locally
_[Plan ahead how you're validating your changes work and don't break other features. Add tests to validate the happy
path and the alternative ones. Be specific.]_
- Local
- [X ] Renders correctly
- Staging
- Production
Check each PR.

fix(api): BMI MR update

---

packages/core/src/external/aws/__tests__/s3.test.ts
packages/core/src/external/aws/s3.ts

Ticket: https://github.com/metriport/metriport-internal/issues/2330
none
Fix s3 update - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1738876872761819).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

PATCH RELEASE 2330 Fix s3 update

---

packages/api/src/routes/medical/internal-patient.ts

none
Add endpoint to re-trigger consolidated - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1738880709312269).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

PATCH RELEASE 2330 Add endpoint to re-trigger consolidated

---

packages/api/src/routes/medical/internal-patient.ts

none
Retrigger consolidate awaits start consolidated - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1738945448193429?thread_ts=1738880709.312269&cid=C04GEQ1GH9D).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

PATCH RELEASE Retrigger consolidate awaits start consolidated

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/shared/package.json
packages/utils/package.json

Ref: #000
- api@1.24.3
- @metriport/api-sdk@14.11.2
- @metriport/carequality-cert-runner@1.15.3
- @metriport/carequality-sdk@1.3.3
- @metriport/commonwell-cert-runner@1.23.3
- @metriport/commonwell-jwt-maker@1.21.3
- @metriport/commonwell-sdk@5.5.3
- @metriport/core@1.21.3
- @metriport/ihe-gateway-sdk@0.16.3
- infrastructure@1.19.3
- @metriport/shared@0.19.3
- utils@1.22.3

publish packages webhook fix

---

docs/medical-api/handling-data/ai-summaries.mdx
docs/mint.json

RELEASE feat(docs): add ai summaries

---

docs/medical-api/handling-data/ai-summaries.mdx

Ticket: 1040
- Add video and icon

fix(api): ai summary video

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Resources/FamilyMemberHistory.hbs

refs. metriport/metriport-internal#2147
- Mapping date of FamilyMemberHistory condition observation 
- Local

feat(fhir-converter): mapping dates to family history observations

---

packages/fhir-converter/src/index.js
packages/utils/src/customer-requests/medical-records-local.ts
packages/utils/src/fhir-converter/convert.ts
packages/utils/src/fhir-converter/integration-test.ts

- More flexibility to FHIR conversion testing script
- Some formatting on FHIR converter index file
- Local

fix(utils): a grab bag of small improvements

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/lib/inputProcessor/dateProcessor.js
packages/utils/src/fhir-converter/convert.ts
packages/utils/src/fhir-converter/integration-test.ts

refs. metriport/metriport-internal#2178
- Not using the document's date as backup value if the date matches the patient's dob - context 
- Local
- Production

feat(fhir-converter): change date backup logic

---

packages/terminology/README.md
packages/terminology/src/app.ts

refs. metriport/metriport-internal#2599
- Docs updates for the Term Server
- Local

feat(terminology): updated the term server readme

---

packages/terminology/README.md

refs. metriport/metriport-internal#2599
- Small docs fix
- N/A

fix(terminology): readme fix

---

packages/terminology/README.md

refs. metriport/metriport-internal#2599
- Added link to Loom for TermServer setup to the readme
- N/A

fix(terminology): readme video link

---

packages/terminology/src/app.ts

Ticket: metriport/metriport-internal#2599
- Fixing Term Server Port to default to 8080
- N/A

PATCH RELEASE Term Server Port Fix

---

docs/medical-api/handling-data/data-analytics.mdx
docs/mint.json

PATCH RELEASE: Docs analytics page

---

packages/core/src/command/ai-brief/create.ts
packages/core/src/command/ai-brief/shared.ts
packages/core/src/domain/ai-brief/generate.ts

refs. metriport/metriport-internal#2526
- Slightly better tracking for different attempts during ai brief gen
- Better Binary resource creation flow
- Local

fix(code): small fixes around the ai brief gen

---

docs/medical-api/handling-data/data-analytics.mdx

embedding demo video to analytics docs

PATCH RELEASE: feat(docs): add analytics demo

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/shared/package.json
packages/utils/package.json

Ref: #000
- api@1.24.4
- @metriport/api-sdk@14.11.3
- @metriport/carequality-cert-runner@1.15.4
- @metriport/carequality-sdk@1.3.4
- @metriport/commonwell-cert-runner@1.23.4
- @metriport/commonwell-jwt-maker@1.21.4
- @metriport/commonwell-sdk@5.5.4
- @metriport/core@1.21.4
- @metriport/ihe-gateway-sdk@0.16.4
- infrastructure@1.19.4
- @metriport/shared@0.19.4
- utils@1.22.4

chore(npm): publish

---

packages/api/src/models/db.ts

PATCH adding invalid links model

---

packages/infra/config/example.ts
packages/infra/config/patient-import.ts
packages/infra/lib/patient-import-nested-stack.ts
packages/lambdas/src/patient-import-upload-notification.ts

- Upstream:
- https://github.com/metriport/metriport/pull/3315
- https://github.com/metriport/metriport-internal/pull/2672
Notifiy bulk import on sandbox - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1739470498939529?thread_ts=1738614445.582769&cid=C04DMKE9DME)
- Local
- none
- Staging
- none
- Sandbox
- Production
- none

PATCH RELEASE 2330 Notifiy bulk import on sandbox

---

packages/api/src/external/hie/__tests__/validate-patient-links.test.ts
packages/api/src/external/hie/validate-patient-links.ts
packages/core/src/mpi/__tests__/match-patient.test.ts
packages/core/src/mpi/match-patients.ts

Ref. metriport/metriport-internal#2641
- Revert back to 7.7% threshold for links
- Local
- Staging 
- Production
Check each PR.

fix(api) Strict algorithm

---

packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts
packages/core/src/fhir-deduplication/resources/composition.ts
packages/core/src/fhir-deduplication/resources/coverage.ts
packages/core/src/fhir-deduplication/resources/encounter.ts
packages/core/src/fhir-deduplication/resources/family-member-history.ts
packages/core/src/fhir-deduplication/resources/immunization.ts
packages/core/src/fhir-deduplication/resources/location.ts
packages/core/src/fhir-deduplication/resources/medication-administration.ts
packages/core/src/fhir-deduplication/resources/medication-request.ts
packages/core/src/fhir-deduplication/resources/medication-statement.ts
packages/core/src/fhir-deduplication/resources/medication.ts
packages/core/src/fhir-deduplication/resources/observation-social.ts
packages/core/src/fhir-deduplication/resources/observation.ts
packages/core/src/fhir-deduplication/resources/procedure.ts
packages/core/src/fhir-deduplication/shared.ts

refs. metriport/metriport-internal#2533
- Refactoring some of the FHIR deduplication code to improve readability and maintainability
- Local

feat(core): code refactoring for dedup

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/shared/package.json
packages/shared/src/medical/webhook/webhook-request.ts
packages/utils/package.json

Ticket: #1040
- Update webhook schemas
- Local
- Staging
- Production

1040 update bulk schems

---

packages/api/src/external/ehr/athenahealth/command/sync-patient.ts
packages/api/src/external/ehr/athenahealth/shared.ts
packages/api/src/external/ehr/elation/command/sync-patient.ts
packages/api/src/external/ehr/elation/shared.ts
packages/core/src/external/athenahealth/index.ts
packages/core/src/external/elation/index.ts
packages/shared/src/domain/contact/__tests__/email.test.ts
packages/shared/src/domain/contact/email.ts
packages/shared/src/index.ts
packages/shared/src/interface/external/athenahealth/patient.ts
packages/shared/src/interface/external/elation/index.ts
packages/shared/src/interface/external/elation/patient.ts
packages/shared/src/interface/external/elation/subscription.ts

Ref: #2498
- Downstream: https://github.com/metriport/metriport/pull/3236
- creating looser zod parsing requirements and moving the checks into API normalization
- Local
- Staging
- Sandbox
- Production

feat(ehr): looser normalization

---

third-party/ehr/canvas-plugins/metriport-app/applications/metriport-app.py

Ref: #1040
- improves canvas code to be pythonic

feat(ehr): snake case + remove comment

---

packages/core/src/command/patient-import/csv/__tests__/convert-patient.test.ts
packages/core/src/command/patient-import/csv/address.ts
packages/core/src/command/patient-import/csv/contact.ts
packages/core/src/command/patient-import/csv/convert-patient.ts
packages/core/src/command/patient-import/patient-import-shared.ts
packages/core/src/external/carequality/shared.ts
packages/shared/src/domain/patient/ssn.ts
packages/utils/src/patient-import/shared.ts

- Upstream: https://github.com/metriport/metriport/pull/3323
- validate email and phone
- remove check for arr length as code only gets first 10
upstream

2330 Validate email, phone, SSN and DL

---

packages/fhir-converter/src/lib/workers/worker.js
packages/fhir-converter/src/routes.js

Log internal processing time on FHIR Converter - [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1739718395903729?thread_ts=1739665734.719219&cid=C04DBBJSKGB)
- [discussion](https://metriport.slack.com/archives/C04T256DQPQ/p1739734808960009?thread_ts=1739725444.196009&cid=C04T256DQPQ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

PATCH RELEASE Log internal processing time on FHIR converter

---

packages/api/src/external/ehr/athenahealth/shared.ts

Ref: #1040
- patch logging for error

feat(ehr): logging original value

---

packages/api/src/external/ehr/elation/command/sync-patient.ts

Ref: #1040
- remove re-triggering dq on appointments until webhook is in place

feat(ehr): patch elation

---

packages/core/src/external/athenahealth/index.ts
packages/core/src/external/elation/index.ts

Ref: #1040
- created a 15min buffer in wrong direction

feat(ehr): patching expiration

---

packages/api/src/external/ehr/elation/command/sync-patient.ts
packages/core/src/external/athenahealth/index.ts
packages/core/src/external/elation/index.ts

- https://github.com/metriport/metriport/pull/3352

BACKMERGE Master

---

packages/utils/src/consolidated/create-consolidate-local.ts

refs. metriport/metriport-internal#1040
- Deduplicating the consolidated bundle on the local script 
- Local

fix(utils): some improvements to a local script

---

third-party/ehr/canvas-plugins/metriport-app/CANVAS_MANIFEST.json
third-party/ehr/canvas-plugins/metriport-app/applications/metriport-app.py

- updating to new modal
- pegging sdk version (not used but better than leaving as is)
- changing manifest for new sdk version
- Local
- Staging
- Sandbox
- Production

patch canvas app

---

docs/medical-api/api-reference/document/get-document.mdx
docs/medical-api/handling-data/webhooks.mdx
packages/core/src/external/cda/process-attachments.ts
packages/core/src/external/cda/remove-b64.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/fhir-converter-service.ts
packages/infra/lib/patient-import-nested-stack.ts
packages/lambdas/src/sqs-to-converter.ts

This reverts commit 61f6f71255e988b60c7af2a8bd9d23e71ee9890c, reversing changes made to eee70dccd7030fb999284a9b1908e1bbc5fd7465.
- Upstream: https://github.com/metriport/metriport/pull/3366
Reverts https://github.com/metriport/metriport/pull/3366
This reverts commit 61f6f71255e988b60c7af2a8bd9d23e71ee9890c, reversing changes made to eee70dccd7030fb999284a9b1908e1bbc5fd7465.
[context](https://metriport.slack.com/archives/C04T256DQPQ/p1740163348227789?thread_ts=1740134313.524009&cid=C04T256DQPQ)
none

PATCH RELEASE Revert Fine tune FHIRConverter

---

packages/core/src/external/aws/lambda-logic/bundle-to-html-bmi.ts

- Patch A1C
- Local
- Production
Check each PR.

PATCH A1C Values

---

packages/lambdas/src/fhir-to-medical-record2.ts

PATCH: GREYSCALE

---

packages/core/src/external/fhir/normalization/resources/__tests__/observation.test.ts
packages/core/src/external/fhir/normalization/resources/observation.ts

refs. metriport/metriport-internal#2712
- Changing weight units from g to kg
- Local
- Production

fix(core): upd weight units to kg

---

packages/api/src/command/medical/document/document-webhook.ts
packages/core/src/command/consolidated/consolidated-create.ts
packages/core/src/command/consolidated/get-snapshot-local.ts
packages/core/src/command/consolidated/get-snapshot.ts
packages/core/src/external/analytics/posthog.ts
packages/core/src/external/fhir/consolidated/deduplicate.ts
packages/core/src/external/fhir/consolidated/hydrate.ts
packages/core/src/external/fhir/consolidated/normalize.ts
packages/core/src/external/fhir/hydration/hydrate-fhir.ts
packages/core/src/external/term-server/index.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/lambdas-nested-stack.ts
packages/lambdas/src/fhir-to-bundle.ts
packages/lambdas/src/sqs-to-converter.ts
packages/utils/src/consolidated/create-consolidate-local.ts
packages/utils/src/fhir-converter/convert.ts
packages/utils/src/fhir-hydration/hydrate-files-local.ts
packages/utils/src/fhir-normalization/normalize-files-local.ts

refs. metriport/metriport-internal#2600
- Fixing the analytics from the lambdas for data quality steps:
- Normalization 
- Deduplication 
- Hydration 
- Local
- Staging
- Production

fix(core): fixing analytics for data quality

---

packages/core/src/command/consolidated/get-snapshot-local.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/lambdas-nested-stack.ts
packages/lambdas/src/sqs-to-converter.ts

Ticket: metriport/metriport-internal#2600
- Fixing the lambda permissions for the secrets
- Staging
- Production

2600 secrets read fixes

---

packages/api/src/command/medical/document/document-webhook.ts
packages/core/src/command/consolidated/consolidated-create.ts
packages/core/src/command/consolidated/get-snapshot-local.ts
packages/core/src/command/consolidated/get-snapshot.ts
packages/core/src/external/analytics/posthog.ts
packages/core/src/external/fhir/consolidated/deduplicate.ts
packages/core/src/external/fhir/consolidated/hydrate.ts
packages/core/src/external/fhir/consolidated/normalize.ts
packages/core/src/external/fhir/hydration/hydrate-fhir.ts
packages/core/src/external/term-server/index.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/lambdas-nested-stack.ts
packages/lambdas/src/fhir-to-bundle.ts
packages/lambdas/src/sqs-to-converter.ts
packages/utils/src/consolidated/create-consolidate-local.ts
packages/utils/src/fhir-converter/convert.ts
packages/utils/src/fhir-hydration/hydrate-files-local.ts
packages/utils/src/fhir-normalization/normalize-files-local.ts

Ticket: metriport/metriport-internal#2600
- Revert PR for analytics changes 
N/A

2600 revert

---

packages/api/src/app.ts
packages/core/src/command/consolidated/consolidated-create.ts
packages/core/src/command/consolidated/get-snapshot-local.ts
packages/core/src/external/analytics/posthog.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/lambdas-nested-stack.ts
packages/lambdas/src/fhir-to-bundle.ts
packages/lambdas/src/sqs-to-converter.ts

Ticket: metriport/metriport-internal#2600
- Upstream: https://github.com/metriport/metriport/pull/3393
- Added Posthog init 
- Using new Posthog functions for FHIR to Bundle and FHIR Converter lambdas
- Combining analytics for post-processing of FHIR bundles
- Local
- Staging
- Production

2600 analytics fixes

---

packages/infra/lib/api-stack/api-service.ts

Ref: #1040
- Upstream: https://github.com/metriport/metriport-internal/pull/2760/files
- increase min task count from 6 to 8
- context https://metriport.slack.com/archives/C04DMKE9DME/p1741214206869609

PATCH min task count

---

packages/infra/lib/utils-nested-stack.ts

Ref: #1040
- max batch size 10 for new s3 queue

feat(utils:): patch batch size

---

packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/routes/helpers/request-logger.ts
packages/api/src/routes/middlewares/auth.ts
packages/api/src/routes/middlewares/propelauth.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1986
- upstream: https://github.com/metriport/metriport/pull/3648
Remove cognito logic from auth MW
- Local
- Staging
- Sandbox
- none
- Production
- none

1986 Remove cognito logic from auth MW

---

.github/pull_request_template.md
README.md
commitlint.config.js

none
Update commitlint, readme.md, and PR template to support Linear.
Linear automatically adds a link to the issue as a comment, so we don't need to add it to the PR description. This is based on the branch name, so it's important to copy it from Linear - `cmd + shift + .`
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

ENG-98 Investigate linear GitHub integration

---

packages/infra/lib/surescripts/surescripts-stack.ts

Ref: ENG-306
Issues:
- https://linear.app/metriport/issue/ENG-306
- remove waititme

feat(ss): wait time

---

packages/api/src/external/carequality/process-outbound-patient-discovery-resps.ts

Ref: ENG-000
- fixing edge case bug in demo aug - [explanation thread](https://metriport.slack.com/archives/C0616FCPAKZ/p1754600727528319?thread_ts=1754580530.426099&cid=C0616FCPAKZ)
- Local
- Staging
- Sandbox
- Production

feat(dp): fix demo aug

---

docs/medical-api/getting-started/sandbox.mdx

Part of ENG-957
Issues:
- https://linear.app/metriport/issue/ENG-957
None
Add a missing period

fix(docs): add a missing period

---

packages/fhir-converter/src/ccda-to-fhir-lambda-nodelambda.js
packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js

Part of ENG-975
Issues:
- https://linear.app/metriport/issue/ENG-975
None
Code rabbit flagged:
When playingEntity.name is undefined: TypeError: Cannot use 'in' operator to search for '_' in undefined
When playingEntity.name is a string: TypeError: Cannot use 'in' operator to search for '_' in REAL NAME
[TEST CASES RAN HERE](https://www.typescriptlang.org/play/?#code/FAYw9gdgzgLgBAVwQSwCYDcDMcC8cDyARgFYCmIMAdAIZRTIDmEAFMHHMxNQLakBciCAGsIYAO4QANHAD6XXlAAO1EP0EjxEAJS4AfHADebdnGQAzDjACei0mAvzScAIQ48AIlgAnZBAbudIxMTGAALL3E4CFIxOAAVG1IAUS8Ir2Z3JDQsAUc4bgRYOEInajhvX38tAG5jdgBfOrgvUhgELwg4AAMAVR6ASQARZgASA0d6rS7ahsljAzgegCUAGQF3RlEW1Hc4RprgQ7MECApkSFNUADEI7hWwEGoYc5YAGwenl4FqCCstAQqfkMxnA0HgtgAcjwnHh3o9npAAPyURSvahWSpJCDPazIxwzUwWVjBSHQuAAMnJTWstnscFJvFwbjg7jAJHIMF2lKaRDIFBRERgYBp …

fix(core): potential runtime error fix

---

packages/core/src/command/hl7-sftp-ingestion/hl7-sftp-ingestion-factory.ts
packages/mllp-server/src/app.ts
packages/utils/src/hl7v2-ingestion/hl7-sftp-ingestion.ts

Part of ENG-968
Issues:
- https://linear.app/metriport/issue/ENG-968
None
Change function name
Move ack to after main logic is executed
Check original PR
- https://github.com/metriport/metriport/pull/4563

Bug fix for lahie sftp ingestion

---

packages/infra/lib/api-stack.ts
packages/infra/lib/hl7-notification-webhook-sender-nested-stack.ts

Part of ENG-968
Issues:
- https://linear.app/metriport/issue/ENG-968
Add hl7 notification incoming bucket env var
Run mllp script once in staging

add hl7 notification incoming bucket to the webhook sender
