packages/api/src/external/commonwell/patient.ts
When checking to see if doc progress is triggered we need to also check after create not just update.
- Production
=> PATCH add scheduled check for create

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js, packages/ihe-gateway/server/Channels/Default Group/Tester XML/destinationConnector-Destination 1.js, packages/ihe-gateway/server/CodeTemplates/Common Library/File type/File type.js, packages/ihe-gateway/server/CodeTemplates/Common Library/parseFileFromString/parseFileFromString.js
none
`parseFileFromString()` to parse non-base64 decoded content - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1712113884942059?thread_ts=1712078581.090989&cid=C0616FCPAKZ)
- Local
- Staging
- Sandbox
- none
- Production
=> 135 Parse non-base64 decoded content

packages/api/src/command/medical/document/check-doc-queries.ts, packages/api/src/command/medical/document/document-query.ts, packages/api/src/command/medical/patient/__tests__/append-doc-query-progress.test.ts, packages/api/src/command/medical/patient/append-consolidated-query-progress.ts, packages/api/src/command/medical/patient/append-doc-query-progress.ts, packages/api/src/command/medical/patient/bulk-get-doc-url-progress.ts, packages/api/src/external/hie/reset-doc-query-progress.ts, packages/api/src/external/hie/reset-scheduled-doc-query-request-id.ts, packages/api/src/external/hie/schedule-document-query.ts, packages/api/src/external/hie/set-doc-query-progress.ts, packages/api/src/external/hie/tally-doc-query-progress.ts
none
Decompose Model with `.dataValues` when preparing the update object to Sequelize.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Decompose .dataValues when prepping the update object to Sequelize

packages/core/src/external/carequality/dq/create-metadata-xml.ts
- wrong id being used for organization when constructing responses. Using their orgId instead of their OID
- On Demand Document being used instead of Stable Document, so we are changing to stable to see if it fixes anything
=> Patch Inbound DQ: Org OID and Stable Object Type

packages/api/src/sequelize/migrations/2024-04-03_00_alter-patient-discovery-result-add-index-patient-id.ts
- Upstream: https://github.com/metriport/metriport/pull/1866
- Add index to the `patient_discovery_result` table
- Remove the PK (constraint/index), keeping the `id` column
Reason being:
- it takes +20s to query that table by `patientId`, and when we're investigating we usually don't have the PD req ID easily at hand
- by adding this index it will allow us to query/join with other tables, like so:
```sql
select p.cx_id, p.id, p.data, pd.data, r.data
from patient p
join cq_patient_data pd on pd.id = p.id
join patient_discovery_result r on r.patient_id::text = p.id
where p.id = '...'
and r.data->>'patientMatch' = 'true'
order by r.created_at desc;
```
- we don't use the ID for direct access - that allows …
=> 1040 Add index to patient discovery result

packages/api/src/sequelize/migrations/2024-04-03_00_alter-patient-discovery-result-add-index-patient-id.ts
- Upstream: https://github.com/metriport/metriport/pull/1869
Follow-up to https://github.com/metriport/metriport/pull/1869, this does the removing of the table's PK (constraint, index).
Upstream PR
Upstream PR
=> 1040 Remove PK from patient_discovery_result

package-lock.json, packages/api/package.json, packages/fhir-converter/package-lock.json, packages/fhir-converter/package.json, packages/utils/package.json, samples/typescript-express/package-lock.json, samples/typescript-express/package.json
- related: https://github.com/metriport/metriport-internal/pull/1678
Update express to 4.19 - [dependabot](https://github.com/metriport/metriport/security/dependabot/194).
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Update express to 4.19

packages/api/src/routes/helpers/request-analytics.ts, packages/api/src/routes/helpers/request-logger.ts, packages/api/src/routes/index.ts, packages/api/src/routes/internal.ts, packages/api/src/routes/medical/document.ts, packages/api/src/routes/medical/facility.ts, packages/api/src/routes/medical/internal-cq.ts, packages/api/src/routes/medical/internal-docs.ts, packages/api/src/routes/medical/internal-mpi.ts, packages/api/src/routes/medical/internal-patient.ts, packages/api/src/routes/medical/organization.ts, packages/api/src/routes/medical/patient.ts, packages/api/src/routes/settings.ts, packages/api/src/shared/analytics.ts
Ticket: #1669
- Upstream: https://github.com/metriport/metriport-internal/pull/1685
Move the request logs to the individual routes in order to extract the params from the URL's
- Local
- Staging
- Production
=> fix(api): move request logger to individual routes

packages/api/src/command/medical/admin/hie-overview.ts, packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts, packages/api/src/routes/internal.ts, packages/api/src/routes/medical/internal-cq.ts, packages/api/src/routes/medical/internal-hie.ts, packages/api/src/shared/config.ts, packages/core/src/external/carequality/ihe-gateway/poll-outbound-results.ts, packages/core/src/external/carequality/pd/get-xcpd-statistics.ts, packages/core/src/util/sequelize.ts, packages/ihe-gateway-sdk/src/index.ts, packages/ihe-gateway-sdk/src/models/patient-discovery/patient-discovery-responses.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts, packages/infra/lib/ihe-stack.ts, packages/shared/src/common/numbers.ts
none
Add internal endpoint to return the patient's overview across HIEs:
- `info`: basic information about links
- `success`: includes info about patient demographics from successful links
- indicates whether the demographics on responses from external GW are the same or different from what we have on our DB
- `error`: includes "success" and errors
- groups gateways by error description
More details/examples on https://metriport.slack.com/archives/C04DMKE9DME/p1712879705213539
- Local
- Staging
- Sandbox
- none
- Production
=> 1679 Add patient overview across HIEs

packages/infra/lib/api-stack/api-service.ts
- Upstream: https://github.com/metriport/metriport/pull/1890
Fix DB replica ECS env var. It was being created w/ the port as string instead of number and failing to start the ECS task.
- Staging
- Sandbox
- none
- Production
- none
=> 1679 Fix DB replica ECS env var

packages/api/src/command/medical/admin/hie-overview.ts
none
Get the GW name from DB thru the correct property.
- Local
- Staging
- Sandbox
- none
- Production
=> 1679 Get GW name from DB thru the correct property

package-lock.json, packages/api-sdk/package.json, packages/api-sdk/src/medical/models/demographics.ts, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json, packages/utils/src/initialize-cw-test-env/index.ts
Ticket: #799
Dont allow for empty addresses on patient create - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1713268382878429)
- Local
- Production
=> PATCH empty address on patient create

packages/api/src/command/medical/patient/__tests__/validate.test.ts, packages/api/src/command/medical/patient/shared.ts, packages/api/src/domain/medical/__tests__/patient.ts
none
Add basic address validation to domain - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1713281789791799?thread_ts=1713268382.878429&cid=C04T256DQPQ)
- Local
- Staging
- Sandbox
- Production
- none
=> 1040 Add basic address validation to domain

packages/infra/lib/api-stack.ts, packages/infra/lib/shared/lambda.ts
none
Manually specify FHIRToMedicalRecord lambda node runtime - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1713389424007909?thread_ts=1713373431.617089&cid=C04GEQ1GH9D)
This is setting on CDK/infra something we already validated in `prod`.
- Local
- none
- Staging
- Sandbox
- none
- Production
=> 799 Manually specify FHIRToMedicalRecord lambda node runtime

packages/infra/bin/infrastructure.ts, packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts, packages/infra/lib/shared/util.ts
- Upstream: https://github.com/metriport/metriport-internal/pull/1703
- move FhirToLambda runtime lambda to config
- revamp EnvConfig type structure
- Local
- none
- Staging
- Sandbox
- none
- Production
=> 799 Move FhirToLambda runtime lambda to config

package-lock.json, packages/api/src/external/carequality/command/cq-directory/create-or-update-cq-organization.ts, packages/api/src/external/carequality/constants.ts, packages/api/src/external/carequality/organization-template.ts, packages/api/src/external/carequality/organization.ts, packages/api/src/external/carequality/shared.ts, packages/api/src/routes/internal.ts, packages/api/src/routes/medical/internal-facility.ts, packages/api/src/routes/medical/schemas/facility.ts, packages/api/src/routes/schemas/shared.ts, packages/api/src/sequelize/migrations/2024-04-03_00_alter-patient-discovery-result-add-index-patient-id.ts, packages/carequality-sdk/package.json, packages/carequality-sdk/src/client/carequality.ts, packages/shared/src/domain/metriport.ts, packages/shared/src/index.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1706
- Upstream: https://github.com/metriport/metriport/pull/1928
Adds internal endpoint to create (and later update) facilities enabled for OBO.
- Local
- Staging
- Sandbox
- none
- Production
=> 1706 Add internal endpoint to create OBO Facility @ CQ

packages/api/src/command/medical/document/document-conversion-status.ts, packages/api/src/command/medical/document/document-query.ts, packages/api/src/command/medical/document/document-webhook.ts, packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/command/medical/patient/consolidated-webhook.ts
Ticket: #1889 
Add requestIid to webhooks
- Local
- Staging
- Production
Check each PR.
=> fix(api): add requestid to webhooks

docs/home/api-info/webhooks.mdx, packages/lambdas/src/__tests__/sqs-to-converter.test.ts, packages/lambdas/src/sqs-to-converter.ts, packages/lambdas/src/sqs-to-converter/cleanup.ts
Ref. metriport/metriport-internal#1698
none
- fix typo on docs
- move sqs-to-converter's cleanup fn to external and add simplest test
- didn't get to fix it b/c it seems to require more time and the issue doesn't seem to be so critical
- Local
- Staging
- Sandbox
- none
- Production
- none
=> Fix typo on docs and move sqs-to-converter's cleanup fn to external

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx, docs/medical-api/more-info/webhooks.mdx, packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/command/medical/patient/convert-fhir-bundle.ts, packages/api/src/routes/medical/patient.ts, packages/core/src/domain/conversion/fhir-to-medical-record.ts, packages/core/src/domain/medical-record-summary.ts
refs. metriport/metriport#1746
- Added `json` to the `conversionType` on the `consolidated query`
- Local
- `conversionType: undefined` - unchanged behavior
- `conversionType: json` - sends signed URL to the JSON file
- `conversionType: html` - unchanged behavior
- `conversionType: json` - unchanged behavior
- Staging
- Production
Main description:
`conversionType` param:
=> feat(api): improved consolidated query to send url to json file

packages/api/src/command/medical/patient/consolidated-get.ts
refs. metriport/metriport#1746
- No more empty json files for patients with no FHIR resources
- Local
- Staging
=> fix(api): fixed uploading empty json when no fhir resources

docs/home/api-info/webhooks.mdx
Ticket: [#_1940_](https://github.com/metriport/metriport/issues/1940)
- None
- Remove extra ```
- Local
- Staging
- Sandbox
- Production
=> 1940 Fix webhooks documentation

package-lock.json, packages/api/src/routes/medical/internal-cq.ts, packages/carequality-cert-runner/package.json, packages/ihe-gateway-sdk/package.json, packages/ihe-gateway-sdk/src/models/shared.ts, packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js, packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/sourceConnector-transformer-step-0-Set stats.js, packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js, packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/sourceConnector-transformer-step-0-Set stats.js, packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-0-Process response.js, packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/sourceConnector-transformer-step-0-Set Stats.js, packages/ihe-gateway/server/CodeTemplates/Common Library/Get current date/Get current date.js, packages/ihe-gateway/server/CodeTemplates/Common Library/index.xml, packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-38 response template/Get XCA ITI-38 response template.js, packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-39 response template/Get XCA ITI-39 response template.js, packages/ihe-gateway/server/CodeTemplates/XCPD Library - Outbound/Get XCPD ITI-55 response template/Get XCPD ITI-55 response template.js
Ref. metriport/metriport-internal#1712
Ticket: metriport/metriport-internal#1712
First of 2 PRs this one is going to introduce duration to the outbound responses. Next PR will have the script to get the median times per CQ GW + success attempts. 
- Local
- Staging
- Production
=> fix(api): part 1/2 add duration to outbound responses

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-1-Case 1: One Match.js
Ticket: https://github.com/metriport/metriport-internal/issues/1725
- Patch to eliminate the 10-minute wait on PD due to inability to parse unexpectedly structured responses
- Local
=> Patch release 2024 04 26

packages/ihe-gateway/server/CodeTemplates/Common Library/Get current date.xml, packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-38 response template/Get XCA ITI-38 response template.js, packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Get XCA ITI-39 response template/Get XCA ITI-39 response template.js, packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/index.xml, packages/ihe-gateway/server/CodeTemplates/XCPD Library - Outbound/Get XCPD ITI-55 response template/Get XCPD ITI-55 response template.js
Ref. metriport/metriport-internal#1712
Ticket: #_1712
Need to add response as a default if its not present - happens if request fails and goes straight to postprocessing - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1714184700827359)
- Local
- Production
Check each PR.
=> PATCH: add respomse timestamp if not available

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
We were treating the same day as duplicates but may not be the case - also we were filtering by only the first doc and we should be filtering by each one. -[context](https://metriport.slack.com/archives/C0616FCPAKZ/p1713986004462029)
- Local
- Production
=> PATCH: patch rendering reports

packages/api/src/routes/medical/fhir-r4-proxy.ts
Ref: #1943
<p>
<del>
- For the particular case of a Bundle resourceType return object w/ type searchset (i.e. a resource type query against the FHIR server), I adjusted the `link` urls and the individual `entry` object urls (`fullUrl`) to properly reference the API server.
- Note: in the case of the initial request `/fhir/R4/{resourceType}` the `self` parameter in link will spit this back exactly, but reissuing this command *will not* produce the same result. This has been accounted for and the `self` parameter is transformed into a usable pagination link.
- Note: I removed the dependency on `server_address` on the FHIR server and rebuild the URLs with the explicit API server url.
</del>
</p>
After discussion, the more generic approach of string replace was decided.
Important notes:
1. …
=> fix(api): adjusting response URLs from FHIR server on /fhir/R4

packages/api/src/routes/medical/__tests__/fhir-r4/e2e/organization.test.e2e.ts
Disable FHIR test search org - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1714150003631489?thread_ts=1713820888.482169&cid=C04DMKE9DME)
none
=> PATCH RELEASE Disable FHIR test search org

packages/api/src/command/medical/facility/get-facility.ts, packages/api/src/command/medical/facility/update-facility.ts, packages/api/src/domain/medical/facility.ts, packages/api/src/routes/medical/facility.ts, packages/api/src/routes/medical/internal-facility.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1706
- Internal facility route now makes updates to existing facilities instead of always creating new ones
- Added support for a different facility name in CW
- Updated FacilityUpdate schemas and made the corresponding changes in relevant functions
- Added a stricter getFacility method, which depends on having both the `id` and the `npi` to avoid mistakes in manual updates
- Local
- Production
=> Patch release 2024 04 29

packages/api/src/external/commonwell/proxy/cw-fhir-proxy.ts, packages/api/src/routes/internal.ts, packages/api/src/routes/medical/internal-cq.ts, packages/api/src/routes/medical/internal-mpi.ts, packages/api/src/routes/medical/patient.ts, packages/api/src/sequelize/index.ts
- Related: https://github.com/metriport/metriport-internal/pull/1709
- Fix DB migration auto rollback 
- Add requestLogger to endpoints missing it 
- Local
- Staging
- Sandbox
- Production
=> 1040 Fix DB auto rollback

packages/api/src/command/medical/facility/__tests__/verify-access.test.ts, packages/api/src/command/medical/facility/verify-access.ts, packages/api/src/routes/medical/facility.ts
Ref. metriport/metriport-internal#1706
- Downstream: https://github.com/metriport/metriport-internal/pull/1718
Do not allow create/update facility when OBO
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1706 Do not allow create/update facility when OBO

packages/utils/package.json, packages/utils/src/bulk-insert-patients.ts, packages/utils/src/bulk-query-patients.ts, packages/utils/src/coverage-assessment.ts, packages/utils/src/customer-requests/download-docs.ts, packages/utils/src/customer-requests/folder.ts, packages/utils/src/customer-requests/get-consolidated.ts, packages/utils/src/customer-requests/medical-records-create.ts, packages/utils/src/shared/folder.ts
- Downstream: https://github.com/metriport/metriport/pull/1963
Add coverage assessment script.
We can prob add more information to it, like the HIE link count from the HIE Overview endpoint.
And should prob remove the old, CW-specific, coverage assessment script - [link](https://github.com/metriport/metriport/blob/develop/packages/utils/src/commonwell/coverage-assessment.ts).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Add coverage assessment script

packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/config/ihe-gateway-config.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/ihe-stack/ihe-db-construct.ts
Ref. https://github.com/metriport/metriport-internal/issues/1734
- Upstream: https://github.com/metriport/metriport-internal/pull/1726
- define db maintenance window
- enable db logs on API DB
- concentrate api db configs in one prop
- make slow logs optional on IHE GW
- Local
- none
- Staging
- Sandbox
- none
- Production
- ⚠️ Contains infra updates
=> 1734 Define DB maintenance window

packages/api/src/command/medical/patient/update-patient.ts
Start time is not updated when doing a patient update for pd
- Local
- Production
=> PATCH update pd start time

packages/infra/lib/ihe-stack/ihe-db-construct.ts
Ref. metriport/metriport-internal#1734
- Upstream: https://github.com/metriport/metriport/pull/1968
Set db maintenance window on IHE GW - it was added to config but not to the CDK construct.
See upstream PR
=> 1734 Set db maintenance window on IHE GW

packages/ihe-gateway/server/CodeTemplates/XCA Library - Outbound/Process RegistryObjectList response/Process RegistryObjectList response.js
refs. metriport/metriport-internal#1676
- Mapping `serviceStartTime` to the `attachment.creation` timestamp
- Local
- Production
=> feat(ihe-gateway): added timestamp for attachment creation

packages/infra/config/aws/rds.ts, packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/alarm-slack-chatbot.ts, packages/infra/lib/api-stack/ccda-search-connector.ts, packages/infra/lib/api-stack/fhir-converter-connector.ts, packages/infra/lib/api-stack/fhir-server-connector.ts, packages/infra/lib/ihe-stack/ihe-db-construct.ts, packages/infra/lib/ihe-stack/ihe-gw-construct.ts, packages/infra/lib/shared/cloudwatch-metric.ts, packages/infra/lib/shared/rds.ts, packages/infra/lib/shared/sqs.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1743
- Upstream: https://github.com/metriport/metriport-internal/pull/1744
- add deletion protection to DBs
- add alarm on SQS' maxAgeOfOldestMessage 
- add alarm on RDS' freeLocalStorage 
- add alarm IHE GW's LB/TG metrics
- increase log retention of SlackConfig
- Local
- Staging
- Sandbox
- Production
=> 1743 Additional SOC2 alarms

packages/infra/lib/api-stack/fhir-converter-service.ts, packages/infra/lib/ihe-stack/ihe-gw-construct.ts, packages/infra/lib/shared/target-group.ts
Ref. metriport/metriport-internal#1743
- Upstream: https://github.com/metriport/metriport/pull/1998
- Related
Add ALB/TG metrics/alarm to FHIR converter.
- Staging
- Sandbox
- Production
=> 1743 Add ALB/TG metrics/alarm to FHIR converter

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts
- patching urls stored on s3. 
- Local
=> Fix: IHE Gateway V2 s3 files with wrong urls

packages/core/src/fhir-to-cda/cda-generators.ts, packages/core/src/fhir-to-cda/cda-templates/clinical-document/structured-body.ts, packages/core/src/fhir-to-cda/cda-templates/commons.ts, packages/core/src/fhir-to-cda/cda-templates/components/augmented-observation.ts, packages/core/src/fhir-to-cda/cda-templates/components/augmented-resources.ts, packages/core/src/fhir-to-cda/cda-templates/components/medications.ts, packages/core/src/fhir-to-cda/cda-templates/components/mental-status.ts, packages/core/src/fhir-to-cda/cda-templates/components/social-history.ts, packages/core/src/fhir-to-cda/cda-templates/constants.ts, packages/core/src/fhir-to-cda/cda-templates/table-rows-and-entries.ts, packages/core/src/fhir-to-cda/cda-templates/types.ts
Ticket: #https://github.com/metriport/metriport-internal/issues/1603
- Upstream: https://github.com/metriport/metriport/pull/1894
- Mapped the `MedicationStatement` and `Medication` FHIR resources to the `Medications` section in CDA
- Local
=> 1603 add medications section

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts
- fixing bug in DRs in production. Calling find without ensuring value was an array
- Local
=> PATCH IHE GW V2 DQ

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ref: #[2003](https://github.com/metriport/metriport/issues/2003)
- api@1.16.0
- @metriport/api-sdk@7.15.0
- @metriport/carequality-cert-runner@1.7.0
- @metriport/carequality-sdk@0.9.0
- @metriport/commonwell-cert-runner@1.16.0
- @metriport/commonwell-jwt-maker@1.13.0
- @metriport/commonwell-sdk@4.15.0
- @metriport/core@1.12.0
- @metriport/ihe-gateway-sdk@0.8.0
- infrastructure@1.11.0
- @metriport/react-native-sdk@1.11.0
- @metriport/shared@0.7.0
- utils@1.13.0
- npm release
=> NPM Release

packages/infra/lib/api-stack.ts, packages/infra/lib/lambdas-nested-stack.ts, packages/infra/lib/shared/lambda-layers.ts, packages/infra/lib/shared/lambda.ts
- Upstream:
- https://github.com/metriport/metriport/pull/2015
- https://github.com/metriport/metriport/pull/2017
- Downstream:
- https://github.com/metriport/metriport/pull/2022
- Part 1 of 3 to reintroduce moving lambdas to a nested stack - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1715010778920459).
- Original PR: https://github.com/metriport/metriport/pull/2015
- This time renaming the lambdas to avoid conflicts
- This PR only adds the new lambda nested stack, the next one will make the API use it
- Temporarily remove these to make up space for resources
- `ScheduledAPIQuotaChecker`
- `ScheduledDBMaintenance`
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1715015443211939?thread_ts=1715010 …
=> 1040 1/3 Create new lambdas nested stack 

packages/infra/lib/api-stack.ts
- Upstream (1/3): https://github.com/metriport/metriport/pull/2018
- Downstream: https://github.com/metriport/metriport/pull/2023
- Part 1 of 3 to reintroduce moving lambdas to a nested stack - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1715010778920459).
- Original PR: https://github.com/metriport/metriport/pull/2015
- This PR makes the API to use the lambda nested stack instead of the lambdas from the APIStack
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1715015443211939?thread_ts=1715010778.920459&cid=C04DMKE9DME
- Local
`Number of resources: 477 is approaching allowed maximum of 500`
- Staging
- Sandbox
- none
- Production
- none
=> 1040 2/3 API using the lambda nested stack

packages/infra/lib/api-stack/fhir-converter-service.ts, packages/infra/lib/ihe-stack/ihe-gw-construct.ts, packages/infra/lib/shared/target-group.ts
Ref. metriport/metriport-internal#1743
- Upstream:
- https://github.com/metriport/metriport/pull/2023
- https://github.com/metriport/metriport/pull/2006
- This reintroduces "ALB/TG metrics/alarm to FHIR converter" originally created w/ this PR: https://github.com/metriport/metriport/pull/2006
- It was reverted on this PR https://github.com/metriport/metriport/pull/2021
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1715010778920459
- Local
`Number of resources: 454 is approaching allowed maximum of 500`
- Staging
- Sandbox
- Production
=> 1743 Reintroduce additional SOC2 controls

packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts, packages/api/src/external/carequality/document/shared.ts, packages/api/src/external/commonwell/document/document-query.ts, packages/api/src/external/commonwell/document/shared.ts, packages/api/src/external/hie/get-docr-content-type-counts.ts
Ticket: #1669
Add content types to analytics 
- Local
- Staging
- Production
=> fix(api): add doc content types to analytics

packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/process-dr.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts
Ref. metriport/metriport-internal#1667
Ticket: #1667
Send filepath 
- Local
- Staging
- Production
=> fix(api): send filepath in dr resp

.github/workflows/run-e2e-test-staging.yml
none
Add manual run of E2E tests against the `staging` instance.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1634 Add manual run of E2E tests against staging

packages/infra/lib/api-stack.ts
Ticket: #799
Using the wrong bucket name for bulk download url in sandbox - [context](https://metriport.slack.com/archives/C05UXMPAVS8/p1715233353044289)
- Sandbox
=> PATCH: bulk signer use seed bucket in sandbox

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/process/xcpd-response.ts
Send address field only if string
- Local
- Staging
- Production
=> fix(api): send address field if string

.github/workflows/fern-check.yml, .github/workflows/pull-request_other.yml
- Downstream: https://github.com/metriport/metriport/pull/2056
- Mark `check-pr` successful if no changes to packages
- Trigger `fern-check` on merge queue
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1715279718404439
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Mark `check-pr` successful if no changes to packages

packages/core/src/external/carequality/dq/process-inbound-dq.ts
refs. metriport/metriport-internal#1730
- Setting the content type to `application/xml` on CCD file upload
- Local
=> fix(api): specifying content type for ccd on upload

packages/fhir-converter/src/templates/cda/Resources/Observation.hbs
Ticket: [#_[ticket-number]_](https://github.com/metriport/metriport/issues/2073)
- Added another case for the `observationEntry` parsing to gather lab results from a wider variety of CDAs 
- Local
=> PATCH RELEASE 2024_05_13 FHIR Converter

packages/fhir-converter/src/lib/inputProcessor/dateProcessor.js, packages/fhir-converter/src/lib/workers/worker.js, packages/fhir-converter/src/templates/cda/Sections/History_of_Present_Illness.hbs, packages/fhir-converter/src/templates/cda/Sections/Notes.hbs, packages/fhir-converter/src/templates/cda/Sections/Results.hbs
Ticket: #[1978](https://github.com/metriport/metriport/issues/1978) 
- CDA sections `Notes` and `Results` will also reference the `encompassingEncounter` for the `DiagnosticReports`. 
- Local
=> PATCH RELEASE 2024_05_13 FHIR Converter (2)

packages/api/src/external/carequality/command/cq-directory/__tests__/get-address-fields.test.ts, packages/api/src/external/carequality/command/cq-directory/cq-gateways.ts, packages/api/src/external/carequality/command/cq-directory/create-cq-directory-entry.ts, packages/api/src/external/carequality/command/cq-directory/parse-cq-directory-entry.ts, packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts, packages/api/src/external/carequality/cq-directory.ts, packages/api/src/external/carequality/models/cq-directory.ts, packages/api/src/routes/medical/internal-cq.ts, packages/api/src/sequelize/migrations/2024-05-15_00_alter-cq-directory-add-address-fields.ts, packages/core/src/mpi/normalize-patient.ts, packages/shared/src/common/__tests__/normalize-zip.test.ts, packages/shared/src/common/normalize-zip.ts, packages/shared/src/index.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1790
- Added the following columns to `cq_directory_entry` table: 
- `address_line`
- `city`
- `zip`
- Removed the unused `gateway` column, and functions that used to set it. Note, there were no functions that currently use it for anything. 
- Moved and improved the `normalizeZipCode` function
- Local
- Staging
- Production
=> 1790 address fields cq dir

packages/core/src/fhir-to-cda/cda-templates/clinical-document/author.ts, packages/core/src/fhir-to-cda/cda-templates/clinical-document/clinical-document.ts, packages/core/src/fhir-to-cda/cda-templates/commons.ts, packages/core/src/fhir-to-cda/cda-templates/components/observations.ts, packages/core/src/fhir-to-cda/cda-templates/components/results.ts, packages/core/src/fhir-to-cda/cda-types/observation.ts, packages/core/src/fhir-to-cda/cda-types/shared-types.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1603
- Upstream: https://github.com/metriport/metriport/pull/1757
- Downstream: https://github.com/metriport/metriport/pull/1894
- Reverted a change for the removal of brackets around attribute constants
- Local
=> 1603 fhir to cda restore CDA validity

packages/core/src/shareback/cda-uploader.ts, packages/core/src/shareback/create-and-upload-extrinsic-object.ts
refs. metriport/metriport-internal#1603
- Specifying `application/xml` content type for the CDA documents resulting from data contributions
=> fix(api): specified xml content type for cda uploads

packages/api/src/command/medical/facility/__tests__/create-facility.test.ts, packages/api/src/command/medical/facility/__tests__/create-facility.ts, packages/api/src/command/medical/facility/__tests__/update-facility.test.ts, packages/api/src/command/medical/facility/__tests__/update-facility.ts, packages/api/src/command/medical/facility/create-facility.ts, packages/api/src/command/medical/facility/update-facility.ts, packages/api/src/domain/medical/__tests__/facility.ts, packages/api/src/domain/medical/facility.ts, packages/api/src/routes/medical/internal-facility.ts
Ref. metriport/metriport-internal#1706
- downstream: https://github.com/metriport/metriport/pull/2078
- add `type` to facility update
- adjust type of facility create
- add validation to facility create and update
- add unit tests
- Local
- none (done w/ downstream PR)
- Staging
- Sandbox
- none
- Production
- none
=> 1706 Add type to facility update

packages/infra/lib/api-stack/fhir-converter-connector.ts
Refs: #[1743](https://github.com/metriport/metriport-internal/issues/1743)
- bumping up alarm on alarmMaxAgeOfOldestMessage on the FHIR server queue from 2 to 5 mins
=> fix(alarm): bump alarm max oldest age from 2 to 5 mins

packages/api/src/external/carequality/command/cq-directory/cq-gateways.ts, packages/api/src/external/hie/cross-hie-ids.ts
none
Updates the code that excludes CQ orgs from CW links so its clearer what it does - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1715711377475049?thread_ts=1715704101.580579&cid=C04DMKE9DME).
- Local
- Staging
- none (CW integration env is down)
- Sandbox
- none
- Production
=> 1040 Update CW exclude list

packages/infra/lib/ihe-gateway-v2-stack.ts
- bump up pd v2 lambda memory as a safety measure for upping number of gateways 
=> 1667 pd v2 lambda mem bump

packages/api/src/external/carequality/get-obo-data.ts, packages/api/src/external/hie/__tests__/register-facility.test.ts, packages/api/src/external/hie/register-facility.ts.ts, packages/api/src/external/hie/shared.ts
Ref. metriport/metriport-internal#1785
Ticket: #2101 
Create in hie if not active - [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1716334842494709?thread_ts=1716328345.871839&cid=C04DBBJSKGB)
- Local
- Production
=> PATCH: create in hie if not active

packages/core/src/external/carequality/ihe-gateway-v2/gateways.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti39-envelope.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/create/iti55-envelope.ts, packages/utils/src/saml/bulk-saml.ts, packages/utils/src/saml/pre-prod-tester.ts
- toggle to use Metriport OID instead of Cxs for Netsmart Endpoints
- tiny refactor to put all the special logic for different gateways in a single file so we can keep track of all of it. 
- Local
=> 1667 patch ntst oid

packages/api/src/external/hie/__tests__/register-facility.test.ts, packages/api/src/external/hie/register-facility.ts.ts
Ref. metriport/metriport-internal#1785
Ticket: #2101 
Remove checks in `createFacilityDetails` so we can set active or not active regarless if obo. 
- Local
- Production
=> PATCH: remove unnecessary checks

.husky/check-signoff.sh, .husky/commit-msg
none
Add git signoff husky hook - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1716483398391339)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Add git signoff husky hook

packages/api/src/external/carequality/command/cq-directory/create-or-update-cq-organization.ts, packages/api/src/external/carequality/organization-template.ts, packages/api/src/external/carequality/organization.ts, packages/api/src/external/carequality/shared.ts, packages/api/src/external/hie/__tests__/register-facility.test.ts, packages/api/src/external/hie/shared.ts, packages/api/src/routes/medical/internal-cq.ts
Ref. metriport/metriport-internal#1785
Ticket: #2101 
Add urls to Candidate implementers in CQ. Also do not create facilities if org has not been created in directory yet. 
- Local
- Staging
- Production
=> feat(api): add urls if registering ci

packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts, packages/api/src/external/commonwell/document/document-query.ts, packages/api/src/external/commonwell/organization.ts, packages/api/src/external/commonwell/patient.ts, packages/api/src/external/hie/get-hie-initiator.ts, packages/api/src/external/ihe-gateway-v2/ihe-gateway-v2-factory.ts
none
- use log instead of debug
- only run `isFacilityEnabledToQueryCW` if needed
- return type on factory function
=> 1040 Small adjustments

.github/dco.yml, .husky/check-signoff.sh
none
Disable DCO for team members and npm publishing
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Disable DCO for team members and npm publishing

package-lock.json, packages/api/src/command/medical/facility/__tests__/delete-facility.test.ts, packages/api/src/command/medical/facility/delete-facility.ts, packages/api/tsconfig.json, packages/carequality-cert-runner/package.json, packages/carequality-cert-runner/src/index.ts, packages/core/package.json, packages/core/src/util/error/shared.ts, packages/ihe-gateway/package-lock.json, packages/ihe-gateway/package.json, packages/ihe-gateway/src/admin.ts, packages/shared/src/common/env-var.ts, packages/shared/src/error/bad-request.ts, packages/shared/src/error/metriport-error.ts, packages/shared/src/error/not-found.ts, packages/shared/src/error/shared.ts, packages/shared/src/index.ts
- Upstream: https://github.com/metriport/metriport/pull/2053
Move errors and env-var from core to shared.
This makes it so smaller packages don't rely on `core` and thus it should minimize publishing NPM packages.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Move errors and env-var from core to shared

.vscode/launch.json, packages/api/src/external/aws/app-config.ts, packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts, packages/core/src/external/aws/app-config.ts
- Upstream:
- https://github.com/metriport/metriport/pull/2158
- https://github.com/metriport/metriport-internal/pull/1820
- Downstream: https://github.com/metriport/metriport/pull/2164
- appConfig FF as zod schema
- `CQ_URLS_TO_EXCLUDE` stored as JSON
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1634 AppConfig FF as zod schema

packages/api/src/__tests__/e2e/mapi/shared.ts, packages/api/src/__tests__/e2e/shared.ts, packages/api/src/external/aws/app-config.ts, packages/api/src/external/carequality/gateway/index.ts, packages/api/src/external/carequality/organization-conversion.ts, packages/api/src/external/carequality/patient.ts, packages/api/src/routes/middlewares/__tests__/auth.test.ts, packages/api/src/routes/middlewares/auth.ts, packages/core/src/external/aws/app-config.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1634
- Upstream: https://github.com/metriport/metriport/pull/2159
- Limit XCPD on E2E to System Root's GW
- On local env, uses the same `TEST_API_KEY` env var to define the account for E2E test to run and the one on the server to check whether to use the System Root's GW
- On the cloud env, uses a newly created FF, `e2eCxIds`
- Add unit test to part of auth.ts
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1634 FF to set the XCPD GW for E2E tests

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/api/src/external/aws/app-config.ts, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
none
Don't alarm when e2eCxIds FF has 1 item or fewer.
Release non-alpha NPM packages.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1634 Don't alarm when e2eCxIds FF has 1 item or fewer

packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts
- Upstream: https://github.com/metriport/metriport/pull/2163
Accept JSON and string for `CQ_URLS_TO_EXCLUDE` - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1716942141099129)
- Local
=> PATCH RELEASE 1634

packages/api/src/external/aws/app-config.ts, packages/core/src/external/aws/app-config.ts, packages/lambdas/src/fhir-to-medical-record.ts
none
Make `getFeatureFlagValue` return strong type.
Previously
With this PR
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1634 Make getFeatureFlagValue return strong type

package-lock.json, packages/api/package.json, packages/api/src/__tests__/env-setup.ts, packages/api/src/domain/medical/__tests__/location-address.ts, packages/api/src/domain/medical/__tests__/patient.ts, packages/api/src/external/carequality/__tests__/cq-directory.ts, packages/api/src/external/carequality/command/cq-directory/__tests__/search-cq-directory.test.ts, packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts
Ref. metriport/metriport-internal#1828
none
Don't fail XCPD when no address coordinates
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1828 Dont fail XCPD when no address coordinates

packages/api/src/external/aws/app-config.ts, packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts, packages/api/src/external/carequality/document/query-documents.ts, packages/api/src/external/carequality/gateway/index.ts, packages/api/src/external/carequality/organization-conversion.ts, packages/api/src/shared/config.ts, packages/core/src/external/aws/app-config.ts
- adding FF to enabled ihe gateway v2 for all oids for certain cxs
- Local
- Staging
=> feat(ihev2): FF to enable cx to migrate fully to IHE Gateway V2

packages/api/src/external/carequality/organization-template.ts
Ticket: #1040
Only add urls to metriport imploementer 
- Local
- Staging
- Production
=> fix(api): add urls only to cq metriport

packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts, packages/api/src/external/carequality/document/query-documents.ts, packages/api/src/external/carequality/patient.ts, packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-async.ts
- batch requests to patient discovery lambda so that the request doesnt go over the max payload size for lambdas
- [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1717444037216089)
- Local
=> fix(ihev2): batch requests to lambda

packages/infra/lib/lambdas-nested-stack.ts
refs. metriport/metriport#1603
- Adding `SYSTEM_ROOT_OID` env var to the FHIR-to-CDA lambda
- Staging
=> fix(lambda): added system root oid env var

packages/api/src/command/medical/patient/consolidated-webhook.ts, packages/api/src/command/webhook/webhook-request.ts, packages/api/src/command/webhook/webhook.ts, packages/api/src/domain/__tests__/webhook.ts, packages/api/src/domain/webhook.ts, packages/api/src/errors/webhook.ts, packages/api/src/models/__tests__/webhook.ts, packages/api/src/models/webhook-request.ts, packages/api/src/sequelize/migrations/2024-05-31_00_alter-webhook-add-statusDetail.ts, packages/api/src/shared/http.ts, packages/shared/src/common/__tests__/boolean.test.ts, packages/shared/src/common/boolean.ts, packages/shared/src/common/types.ts, packages/shared/src/index.ts, packages/utils/src/mock-webhook.ts
Ref. metriport/metriport-internal#858
- Downstream: https://github.com/metriport/metriport/pull/2189
Store additional info on WH table. Implemented this to support debugging E2E tests.
- Local
- Staging
- Sandbox
- nont
- Production
- none
=> 858 Store additional info on WH table

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts, packages/core/src/util/__tests__/urn.test.ts, packages/core/src/util/urn.ts
Dont store doc unique id with urn - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1717621712277569)
- Production
Check each PR.
=> PATCH remove urn docoid

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti39-envelope.ts
- remove urn:oid prefix from repository unique id
- Local
=> fix(ihev2): remove urn:oid prefix from repository unique id

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ref: #000
- api@1.17.2
- @metriport/api-sdk@8.0.0
- @metriport/carequality-cert-runner@1.8.0
- @metriport/carequality-sdk@0.9.8
- @metriport/commonwell-cert-runner@1.16.8
- @metriport/commonwell-jwt-maker@1.13.8
- @metriport/commonwell-sdk@4.15.8
- @metriport/core@1.13.0
- @metriport/ihe-gateway-sdk@0.9.0
- infrastructure@1.12.0
- @metriport/react-native-sdk@1.11.8
- @metriport/shared@0.8.0
- utils@1.14.0
Release packages - https://github.com/metriport/metriport/pull/2219
=> chore(release): publish

packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/constants.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/process-dq.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/xmls/dq_multiple_docs.xml, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts
- fixing date parsing for non iso dates + unit tests. For dates like 20240329163146 dayJs was messing it up and returning a crazy date like Nov 16 2608
- [Context](https://metriport.slack.com/archives/C0616FCPAKZ/p1717536123628429)
- Local
Check each PR.
=> PATCH RELEASE fixing date parsing for non iso dates

packages/core/src/external/carequality/ihe-gateway-v2/monitor/__tests__/store.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/monitor/store.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/send/dq-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/send/dr-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/send/xcpd-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts, packages/core/src/util/config.ts, packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/ihe-gateway-v2-stack.ts, packages/utils/src/saml/bulk-saml.ts, packages/utils/src/saml/pre-prod-tester.ts, packages/utils/src/saml/saml-server.ts
- upstream: https://github.com/metriport/metriport-internal/pull/1845
- store all responses from ihe gateways on s3
- Local
- Staging
=> feat(ihev2): storing all ihe responses on s3

packages/api/src/__tests__/e2e/mapi/mapi.test.e2e.ts, packages/api/src/__tests__/e2e/mapi/webhook/consolidated.ts, packages/api/src/__tests__/e2e/mapi/webhook/settings.ts, packages/api/src/__tests__/e2e/mapi/webhook/webhook-handler.ts, packages/api/src/command/settings/updateSettings.ts, packages/shared/src/common/net.ts, packages/shared/src/index.ts, packages/shared/src/medical/index.ts, packages/shared/src/medical/webhook/webhook-request.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1634
- Upstream: https://github.com/metriport/metriport/pull/2227
- Downstream:https://github.com/metriport/metriport/pull/2240
- Local
- Staging
- Sandbox
- Production
=> 1634 WHs on E2E tests (3/4)

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts
- fix timestamp on dqs to always be in utc so that unit tests pass local
- Local
=> fix(test): make times in dq always utc so tests pass local

packages/infra/lib/shared/target-group.ts
none
Remove alarms on TargetGroups - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1717159090929309)
none
=> 1040 Remove alarms on TargetGroups

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ticket: https://github.com/metriport/metriport-internal/issues/1634
- upstream: https://github.com/metriport/metriport/pull/2189
- api@1.18.1
- @metriport/api-sdk@8.1.1
- @metriport/carequality-cert-runner@1.8.2
- @metriport/carequality-sdk@0.10.2
- @metriport/commonwell-cert-runner@1.16.11
- @metriport/commonwell-jwt-maker@1.14.2
- @metriport/commonwell-sdk@4.15.11
- @metriport/core@1.13.4
- @metriport/ihe-gateway-sdk@0.9.2
- infrastructure@1.12.2
- @metriport/react-native-sdk@1.11.11
- @metriport/shared@0.9.4
- utils@1.14.2
none
=> 1634 Publish NPM packages

package-lock.json, packages/api-sdk/package.json, packages/api-sdk/src/index.ts, packages/api-sdk/src/medical/client/metriport.ts, packages/api/package.json, packages/api/src/__tests__/e2e/mapi/parts/consolidated.test.part.ts, packages/api/src/__tests__/e2e/mapi/parts/document-query.test.part.ts, packages/api/src/__tests__/e2e/mapi/parts/settings.test.part.ts, packages/api/src/__tests__/e2e/mapi/webhook/consolidated.ts, packages/api/src/__tests__/e2e/mapi/webhook/settings.ts, packages/api/src/__tests__/e2e/mapi/webhook/shared.ts, packages/api/src/__tests__/e2e/mapi/webhook/webhook-handler.ts, packages/api/src/__tests__/e2e/mapi/webhook/webhook-server.ts, packages/api/src/command/webhook/webhook.ts, packages/api/src/routes/util.ts, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/shared/src/medical/webhook/webhook-request.ts, packages/utils/package.json
none
[context](https://metriport.slack.com/archives/C04DBBJSKGB/p1718060598203809?thread_ts=1718056080.495319&cid=C04DBBJSKGB)
- adjust E2E WH test for clarity - 
- improve logging to help debugging E2E tests 
- rename WH response error to failure to avoid confusion during error handling
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1634 Adjust E2E WH test for clarity

packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
Ref. metriport/metriport#2209
Ticket: #2209 
Prevent doc refs that exist in the system from being redownloaded in CQ
- Local
- Staging
- Production
=> fix(api): prevent existing docs from redownloading

packages/ihe-gateway-sdk/package.json, samples/typescript-express/index.ts, samples/typescript-express/mock-webhook.ts, samples/typescript-express/package-lock.json, samples/typescript-express/package.json
Ticket: #1040
Given this is an internal package lets remove from registry to avoid having to publish packages
=> fix(api): remove ihe gw sdk from npm

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
Ref. metriport/metriport#2254
Ticket: #2254 
MR notes sometimes had b64 images after decoding the original b64
- Local
- Staging
- Production
Check each PR.
=> fix(api): remove b64 img from mr

packages/api/src/command/medical/patient/__tests__/consolidated-get.test.ts, packages/api/src/command/medical/patient/consolidated-get.ts
Ref. metriport/metriport#1915
Ticket: #1915 
Filter out prelim doc refs from consolidated query
- Local
- Staging
- Production
=> fix(api): filter out prelim docrefs

packages/api/src/command/settings/updateSettings.ts, packages/api/src/command/webhook/webhook-request.ts, packages/api/src/domain/settings.ts, packages/api/src/domain/webhook.ts, packages/api/src/routes/settings.ts, packages/api/src/sequelize/migrations/2024-06-13_00_alter-settings-increase-columns-length.ts, packages/api/src/sequelize/migrations/2024-06-13_01_alter-webhook-request-increase-columns-length.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1030
none
Increase the limit of webhook URLs and status details to 2048 chars - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1718315046939229?thread_ts=1718311948.783149&cid=C04T256DQPQ)
- Local
- :warning: Contains a DB migration
=> PATCH RELEASE Increase limit of webhook urls - v2

packages/infra/lib/shared/sqs.ts
none
Update DLQs visibilityTimeout from 12h to 1min - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1718313072659319?thread_ts=1718283008.568789&cid=C04T256DQPQ)
none
=> 1040 Update DLQs visibilityTimeout from 12h to 1min

packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-async.ts
- patch prod. We arent chunking outboundDocumentRetrievalReqs to the lambda so its going over the lambdas payload limit 
- [context](https://metriport.slack.com/archives/C04T256DQPQ/p1718400382008829?thread_ts=1717443446.640739&cid=C04T256DQPQ)
none
=> PATCH: chunk ihe v2 document retrieval requests

packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-async.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/process/error.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts, packages/shared/src/net/error.ts
- increased DR retries to 4 attempts, added ECONNABORTED and ERR_BAD_RESPONSE
- added 1s sleep in between DR requests when making multiple DRs for a single gateway
- Local
=> PATCH Retries ihev2

packages/core/src/external/carequality/ihe-gateway-v2/monitor/__tests__/store.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/monitor/store.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/send/dr-requests.ts
- fix missing dates for some cx documents
- noticed not all DR responses were being stored during debugging - fixed that too 
- [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1718763369892949)
- Local
=> fix(ihe): catch missing dates in dq + dont overwrite stored dr response

packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/process-dr.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/xmls/dr_success.xml, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/send/dq-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/send/xcpd-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts, packages/infra/lib/ihe-gateway-v2-stack.ts
- bump up DR lambda timeout duration - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1718767347974169)
- increase dq lambda # of retries - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1718741158598569?thread_ts=1718736573.506549&cid=C04T256DQPQ)
- fix parsing nit bug where using request homeCommunityId in DR response instead of response id. Helpful for debugging in DB results
=> fix(ihev2): bump dr lambda duration, bump attempt up on dq retries

packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts, packages/infra/lib/ihe-gateway-v2-stack.ts
- bump pd lambda duration to 10 mins
- shorten http timeout to 60s
- [context](https://metriport.slack.com/archives/C04T256DQPQ/p1718817800568869)
=> Patch pd lambda timeout

packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts
- Upstream: https://github.com/metriport/metriport-internal/pull/1899
- Downstream: https://github.com/metriport/metriport/pull/2299
Create ALB version of the API - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1718755941062309).
Next PR will point things to it. The last one will remove the NLB based API.
- Local
- Staging
- `executeWithNetworkRetries` is not on base branch yet (`develop`)
- Sandbox
- none
- Production
- none
=> 1040 - 1/3 Create ALB version of the API

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ticket: https://github.com/metriport/metriport-internal/issues/1827
- Upstream: https://github.com/metriport/metriport/pull/2285
Publish NPM packages
- api@1.18.5
- @metriport/api-sdk@9.0.2
- @metriport/carequality-cert-runner@1.8.6
- @metriport/carequality-sdk@0.10.6
- @metriport/commonwell-cert-runner@1.16.15
- @metriport/commonwell-jwt-maker@1.14.6
- @metriport/commonwell-sdk@4.15.15
- @metriport/core@1.13.8
- @metriport/ihe-gateway-sdk@0.9.6
- infrastructure@1.12.6
- @metriport/react-native-sdk@1.11.15
- @metriport/shared@0.9.8
- utils@1.14.6
none
=> 1827 Publish NPM packages

packages/api/src/external/carequality/patient.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts, packages/infra/lib/api-stack/document-upload.ts, packages/infra/lib/ihe-gateway-v2-stack.ts
- Upstream: https://github.com/metriport/metriport/pull/2303
- Downstream: https://github.com/metriport/metriport/pull/2305
Point infra to use the ALB version of the API's - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1718755941062309)
- Local
- Staging
- `executeWithNetworkRetries` is not on base branch yet (`develop`)
- Sandbox
- none
- Production
- none
=> 1040 - 2/3 Add ALB behind API's NLB to avoid errors on restart

packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts
- Upstream: https://github.com/metriport/metriport/pull/2299
Remove the NLB version of the API's - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1718755941062309)
- Local
- Staging
- `executeWithNetworkRetries` is not on base branch yet (`develop`)
- Sandbox
- none
- Production
- none
=> 1040 - 3/3 Remove NLB based API

packages/api/src/external/commonwell/patient-external-data.ts, packages/core/src/external/aws/lambda-logic/document-uploader.ts, packages/core/src/external/aws/s3.ts, packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-logic.ts, packages/lambdas/src/sqs-to-converter.ts, packages/lambdas/src/sqs-to-fhir.ts, packages/lambdas/src/sqs-to-opensearch-xml.ts, packages/shared/src/net/error.ts, packages/shared/src/net/retry.ts
Ref. metriport/metriport-internal#1827
none
Add request aware log to execute with retries functions. Without sending the request aware log to `executeWithRetries` and related functions, we don't get the req ID on the logs when it fails on the first attempt, and that's important for debugging purposes.
Also, add `ENOTFOUND` to the list of network errors to retry.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1827 Add request aware log to execute with retries functions

packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-logic.ts, packages/shared/src/common/__tests__/retry.test.ts, packages/shared/src/common/retry.ts, packages/shared/src/net/__tests__/retry.test.ts, packages/shared/src/net/retry.ts
- longer initial delay on 429s 
- Local
=> feat(retry): 3x initial delay on 429s

packages/api/src/external/carequality/document/__tests__/shared.test.ts, packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts, packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts, packages/api/src/external/carequality/document/shared.ts, packages/core/src/util/__tests__/concurrency.test.ts
- deduplicate document references upstream of upsert to fhir 
- local
- Staging
=> fix(fhir): deduplicate document references upstream of fhir upsert

packages/api/src/external/carequality/document/create-outbound-document-retrieval-req.ts, packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-logic.ts, packages/core/src/external/carequality/ihe-gateway-v2/monitor/__tests__/store.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/monitor/store.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/error.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/send/dq-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/send/dr-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/send/xcpd-requests.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts, packages/ihe-gateway-sdk/src/models/shared.ts
- Upstream: https://github.com/metriport/metriport/pull/2306
- downstream: https://github.com/metriport/metriport/pull/2317
- add concept of subRequestId to improve ability to track and understand retry logic in PRs
- Staging
=> Sub request id + improve retries logging for ihe v2 + Retries for ERR_BAD_RESPONSE on DQ 

packages/api/src/external/carequality/document/__tests__/create-outbound-document-retrieval-req.test.ts, packages/api/src/external/carequality/document/create-outbound-document-retrieval-req.ts, packages/core/src/external/carequality/ihe-gateway-v2/gateways.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti39-envelope.ts
- Upstream: https://github.com/metriport/metriport/pull/2315
- fix IHE GW Results are incomplete for Document Retrieval - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1716922220738429) 
- basically we were getting more results back than expecting, and the reason was that for several gateways the logic was in the lambdas to split them up into more 1 docRef requests. So then we would expect 10 results but get back 11 and then throw this warning. This PR moves that logic into the api so that the requests are fully broken up before being sent to the lambdas 
- local
=> fix(ihe): ihe gw results are incomplete for dr

packages/core/src/external/aws/__tests__/s3.test.ts, packages/core/src/external/aws/s3.ts
Ref. metriport/metriport-internal#1827
none
Don't retry on S3 404 - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1719097324861709).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1827 Don't retry on S3 404

packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts, packages/infra/lib/api-stack/api-service.ts, packages/shared/src/common/retry.ts, packages/shared/src/net/error.ts
none
- don't network retry on outbound PD - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1719272500023269?thread_ts=1719018618.154209&cid=C04GEQ1GH9D)
- update OSS API ALB's idle timeout from 1 to 10min - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1719264089265279?thread_ts=1718882863.214939&cid=C04T256DQPQ)
- update retry default attempt from 10 to 5 - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1719269603670079?thread_ts=1719018618.154209&cid=C04GEQ1GH9D)
- Local
- none
- Staging
- Sandbox
- Production
=> 1040 Don't network retry on outbound PD and more

packages/core/src/external/aws/document-signing/document-bulk-signer-lambda.ts, packages/core/src/external/aws/lambda.ts, packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-async.ts, packages/core/src/external/carequality/ihe-gateway-v2/ihe-gateway-v2-logic.ts, packages/core/src/external/carequality/ihe-gateway/outbound-result-poller-lambda.ts, packages/core/src/external/carequality/ihe-gateway/outbound-result-poller.ts, packages/lambdas/src/sqs-to-converter.ts, packages/lambdas/src/sqs-to-fhir.ts
Ticket: 
- Upstream: https://github.com/metriport/metriport/pull/2326
[context](https://metriport.slack.com/archives/C04T5Q9JHFX/p1719331694970869?thread_ts=1719331458.061259&cid=C04T5Q9JHFX):
- get result lambda payload checks for 2xx instead of 200
- `defaultLambdaInvocationResponseHandler` has the correct lambda name
Just avoiding hitting the OSS API too much if its already failing
- response from outbound PD IHE GW lambda to try max 5 attempts to OSS API
[context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1719347777789909?thread_ts=1719338701.693029&cid=C04GEQ1GH9D):
- disable retries on FHIR converter and server lambdas
upstream PR
=> 1040 Fix error handler on lambda async invocation + Disable SQS retries

packages/infra/lib/ihe-stack.ts
Refs: #[1928](https://github.com/metriport/metriport-internal/issues/1928)
- adding metrics/dash and logs to inbound IHE gateway. First step in debugging 502s on inbound since we dont really have any visibility into the API Gateway right now.
- Used a custom construct copied from https://github.com/aws/aws-cdk/issues/11100 for enabling logging, since HTTPApi doesnt have easy logging support for some reason
- Staging
=> feat(logs): adding metrics and logs to inbound ihe

packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/security/sign.ts
- fixes for allscripts and athena
- Local
- turn on ihev2 fully for (all?) customers 
- monitor analytics: we shouldnt have an event lasting greater than 300000 ms again
=> feat(ihev2): fix for allscripts auth and athena sha1

packages/lambdas/src/fhir-to-medical-record.ts
none
Send a single alert to sentry when MR generation fails.
none
=> 1040 Send a single alert to sentry when MR generation fails

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ticket: https://github.com/metriport/metriport-internal/issues/1911
- Upstream: https://github.com/metriport/metriport/pull/2324
- api@1.18.6
- @metriport/api-sdk@10.0.0
- @metriport/carequality-cert-runner@1.8.7
- @metriport/carequality-sdk@0.10.7
- @metriport/commonwell-cert-runner@1.16.16
- @metriport/commonwell-jwt-maker@1.14.7
- @metriport/commonwell-sdk@4.15.16
- @metriport/core@1.13.9
- @metriport/ihe-gateway-sdk@0.9.7
- infrastructure@1.12.7
- @metriport/react-native-sdk@1.11.16
- @metriport/shared@0.9.9
- utils@1.14.7
none
=> 1911 Publish NPM package

packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts, packages/infra/lib/api-stack/fhir-converter-service.ts, packages/infra/lib/shared/s3.ts
Ref. metriport/metriport-internal#1936
none
- Add access log to API's ALB 
- Add access log to FHIRConverter's ALB 
- Local
- none
- Staging
- Sandbox
- none
- Production
=> 1936 Add access log to API's ALB

packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/ccda-search-connector.ts, packages/infra/lib/api-stack/fhir-converter-connector.ts, packages/infra/lib/api-stack/fhir-converter-service.ts, packages/infra/lib/api-stack/fhir-server-connector.ts, packages/lambdas/src/shared/sqs.ts, packages/lambdas/src/sqs-to-converter.ts, packages/lambdas/src/sqs-to-fhir.ts, packages/lambdas/src/sqs-to-opensearch-xml.ts
- related: https://github.com/metriport/metriport/pull/2344
- don't retry on fhir converter and server lambdas
- don't retry on open search lambdas
- single report of issue to Sentry upon error for those lambdas ^
- autoscaling CPU threshold of FHIRConverter moved from 70 to 60 
[Context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1719338701693029)
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Remove retry on lambdas

packages/infra/lib/shared/s3.ts
Ref. metriport/metriport-internal#1936
- Upstream: https://github.com/metriport/metriport/pull/2363
Remove trailing slash from ALB access log prefix - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1719872509670939?thread_ts=1719871033.675699&cid=C04FZ9859FZ).
none
=> 1936 Remove trailing slash from ALB access log prefix

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts, packages/core/src/external/fhir/shared/extensions/base-64-extension.ts, packages/core/src/external/fhir/shared/extensions/base64-extension.ts, packages/fhir-converter/src/templates/cda/Resources/Observation.hbs
refs. metriport/metriport#2302
- `DiagnosticReport` sometimes references an `Observation` resource for results. Here, I'm introducing functionality to get those results, decode them, and create new tables from them. 
- Local
=> feat(core): constucting results tables from observations ref by diagreports

packages/api/src/routes/medical/internal-cq.ts, packages/carequality-sdk/src/client/carequality-api.ts, packages/carequality-sdk/src/client/carequality.ts
- Adding the param to allow querying for inactive CQ orgs
- Context: Sometimes, we need to query for inactive orgs with the endpoint on Postman, and there was no support for it prior to this PR
- Local
=> 799 query inactive cq orgs

packages/api/src/external/cda/process-ccd-request.ts, packages/api/src/routes/medical/internal-docs.ts, packages/core/src/domain/document/upload.ts, packages/core/src/external/aws/s3.ts, packages/core/src/external/carequality/dq/process-inbound-dq.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1905
- Upstream: https://github.com/metriport/metriport/pull/2332
- Making the CCD gen on DQ async
- In the meantime, quickly generating an empty CCD
- Local
=> 1905 ccd async

packages/api/src/models/db.ts, packages/api/src/shared/config.ts, packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/lib/api-stack/api-service.ts
- Upstream: https://github.com/metriport/metriport-internal/pull/1952
Adjust db capacity and pool settings per env - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1720042146210979).
- Local
- Staging
- See upstream
- Sandbox
- See upstream
- Production
- See upstream
=> 1040 DB pool settings per environment

packages/infra/lib/api-stack.ts, packages/infra/lib/shared/lambda.ts, packages/lambdas/src/cda-to-visualization.ts
none
Add lambda insights to the MR generation lambda. This is to help identifying issues w/ the lambda that generates MRs timing out/OOM'ing.
Also:
- add execution time for the PDF generation
- isolate functions that load the file from the filesystem
- reuse the stylesheet files across lambda executions
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Add lambda insights to MR generation lambda

packages/core/src/external/aws/s3.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/lambdas-nested-stack.ts, packages/lambdas/src/tester.ts
none
- Rename polling lambdas
- s3 utils to log w/ req ID
- dynamically set tester lambda API URL 
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Rename polling lambdas

packages/api/src/external/commonwell/document/document-query.ts, packages/core/src/external/commonwell/document/document-downloader-local.ts
none
- single alert on CW 404
- pass cause to NotFoundError
- Local
- none
- Staging
- none (CW integration is down and this doesn't change any logic)
- Sandbox
- none
- Production
- none
=> 1040 Single alert on CW 404

packages/lambdas/src/tester.ts
none
Tester lambda gets protocol in front of api url.
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Tester lambda gets protocol in front of api url

packages/core/src/external/cda/remove-b64.ts, packages/core/src/util/mime.ts
refs. metriport/metriport-internal#1925
- We've ran into a file that stores B64-encoded data with the `_mediaType` indicated as an `octet-stream`.
- Added checks for an array of different mime types that may be encoded as B64
=> PATCH_RELEASE 2024_07_04 FHIR Converter fix 

packages/infra/lib/api-stack/fhir-converter-connector.ts
Fix Lambda to FHIR converter ratio - [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1720203407907099?thread_ts=1720202939.864459&cid=C04DBBJSKGB).
none
=> PATCH RELEASE Fix Lambda to FHIR converter ratio

packages/infra/lib/api-stack/ccda-search-connector.ts, packages/infra/lib/shared/open-search-construct.ts
Ref. metriport/metriport-internal#1824
none
Add action to OpenSearch alarms - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1719940278082699).
- Local
- none
- Staging
- Sandbox
- Production
=> 1824 Add action to OpenSearch alarms

packages/api/src/routes/util.ts
none
We're not logging details about 400s - [context](https://metriport.slack.com/archives/C05UXMPAVS8/p1720063851064029?thread_ts=1720060697.055119&cid=C05UXMPAVS8)
This removes new lines from error logging on the `asyncHandler`. My hypothesis is that new lines are being "cut out" from CloudWatch logs, that's why we're not logging ZodErrors ([that's how they get logged](https://zod.dev/ERROR_HANDLING)).
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Remove new lines from error logger

package-lock.json, packages/api-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json
Ref: https://github.com/metriport/metriport-internal/issues/799
- Upstream: https://github.com/metriport/metriport/pull/2401
- @metriport/api-sdk@11.1.0
- @metriport/commonwell-cert-runner@1.18.0
- @metriport/commonwell-jwt-maker@1.16.0
- @metriport/commonwell-sdk@5.0.0
none
=> PATCH RELEASE Publish non-alpha NPM packages

packages/api/src/command/webhook/webhook.ts
Ref. https://github.com/metriport/metriport/issues/1151
none
Remove the deprecated `x-webhook-key` header.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1151 Remove x-webhook-key header

packages/api/src/app.ts, packages/api/src/routes/helpers/not-found-handler.ts, packages/api/src/routes/helpers/report-client-errors.ts
Ref. metriport/metriport-internal#367
- Downstream: https://github.com/metriport/metriport/pull/2389
Proper handler for 404s (return JSON based response).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Proper handler for 404

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dq-request.ts, packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dr-request.ts, packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts
refs. metriport/metriport-internal#1766
- Logging the inbound DQ and DR requests
- Logging the errors
- Local
- Staging
=> feat(core): adding logging to inbound requests

packages/infra/lib/ihe-stack.ts
- had OOMs on both [PD](https://metriport.slack.com/archives/C04T256DQPQ/p1720651131889459) and [DQ](https://metriport.slack.com/archives/C04T256DQPQ/p1720605589145769) lambda
=> Inbound: Bump Lambda Mem to 1g

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/schema.ts, packages/lambdas/src/ihe-gateway-v2-inbound-document-query.ts, packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts
- b64 decode requests if they are b64 encoded. 
- remove part of saml schema that others dont seem to follow and doesnt matter for processing requests
- logs for [context](https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FIHEInboundPatientDiscoveryV2Lambda/log-events/2024$252F07$252F11$252F$255B$2524LATEST$255D6906ff59fe6c4dfca573e6a05036e74d$3FfilterPattern$3D$2522Failed+to+parse+ITI-55+request$253A+Error+-+$255B$2522)
=> PATCH: base64 encoded inbound reqs

packages/core/src/fhir-to-cda/cda-templates/commons.ts, packages/core/src/fhir-to-cda/cda-types/shared-types.ts
refs. metriport/metriport-internal#1913
- Placeholders for sections with no data had extra `text` tags
- Local
=> PATCH RELEASE 2024_07_11: FHIR to CDA 

packages/infra/lib/api-stack.ts, packages/infra/lib/ihe-gateway-v2-stack.ts, packages/infra/lib/lambdas-nested-stack.ts, packages/infra/lib/location-services-stack.ts, packages/infra/lib/secrets-stack.ts
While helping to look into [this issue](https://metriport.slack.com/archives/C04DMKE9DME/p1720617675479379), I noticed [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-protect-stacks.html): there's a termination protection flag on the CloudFormation stacks.
This adds termination protection so we minimize the risk of someone accidentally terminating/removing an AWS stack.
- Local
- none
- Staging
- Sandbox
- none
- Production
=> 1040 Add termination protection to infra stacks

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
Ticket: #799
Remove unknown display for labs - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1720699588902799)
- Local
- Production
=> PATCH RELEASE - Remove unknown display for labs

packages/fhir-converter/src/templates/cda/ValueSet/MedicationStatementStatus.hbs
Ref. metriport/metriport#2295
Ticket: #2295
Remove invalid status values for medication statement -[context](https://metriport.slack.com/archives/C04T256DQPQ/p1720797061650859?thread_ts=1719935155.694079&cid=C04T256DQPQ)
- Local
- Production
- reprocess docs
=> PATCH RELEASE - Correct Medication Statement Status

packages/core/src/util/mime.ts, packages/lambdas/src/sqs-to-converter.ts
none
Store pre FHIR conversion payload on s3 - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1720806786409359?thread_ts=1719940286.197409&cid=C04T256DQPQ)
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Store pre FHIR conversion payload on S3

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
Ref. metriport/metriport#2295
Ticket: #2295
Patch trim bug - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1720913080740549?thread_ts=1719940286.197409&cid=C04T256DQPQ)
- Local
- Production
=> PATCH RELEASE: Fix undefined trim

packages/infra/config/env-config.ts, packages/infra/config/example.ts
Ref. metriport/metriport-internal#1969
- Upstream: https://github.com/metriport/metriport-internal/pull/1999
Add propelauth config - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1720924058905129?thread_ts=1720911320.166369&cid=C04FZ9859FZ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1969 Add propelauth config

packages/lambdas/src/sqs-to-converter.ts
- Upstream: https://github.com/metriport/metriport/pull/2463
Don't stringify pre-convert payload when storing on S3
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Don't stringify pre-convert payload when storing on S3

packages/api/src/app.ts, packages/api/src/models/db.ts, packages/api/src/shared/config.ts, packages/infra/config/env-config.ts, packages/infra/lib/api-stack/api-service.ts
Ref. metriport/metriport-internal#1973
- Upstream: https://github.com/metriport/metriport-internal/pull/1997
Changes:
- Set server timeout and keep alive to match LB's.
- Adjust OSS api scaling 
Context: [link](https://metriport.slack.com/archives/C04DMKE9DME/p1720815510266579?thread_ts=1720657415.437769&cid=C04DMKE9DME)
- Local
```
date && time ab -c 100 -n 100000 -H ‘x-api-key: …’ $oss-api-lb/medical/v1/organization && date
```
- 1st: 6 failed requests
- 2nd: 2 failed requests
- 3rd: 0 failed requests
```
date && time ab -c 100 -n 100000 -H ‘x-api-key: …’ $oss-api-lb/medical/v1/organization && date
```
- 59 failed requests
- Staging
```
date && time ab -c 100 -n 100000 -H ‘x-api-key: …’ $oss-api-lb/medical/v1/organization && date
```
- 1st: 
- 2nd: 
- 3rd: 
```
date …
```
=> 1973 Adj server timeout and keep alive, and scaling/db pool settings

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/create/xcpd-response.ts
- remove urn from xmlns namespace
- context: surescripts says it breaks their system
=> fix(inbound): updating namespace

.github/workflows/_deploy-cdk.yml
Refs: #[2004](https://github.com/metriport/metriport-internal/issues/2004)
- install deps so fhir converter tests in cicd run: [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1721158108812649)
- Staging:
=> fix(cicd): add install deps for fhir converter

packages/api/src/command/medical/patient/get-consolidated-webhook.ts
Ref. metriport/metriport#2485
Ticket: #2485
Fix issue with getting resource from webhook
- Local
- Production
=> PATCH: Fix Webhook URL type

packages/infra/config/ihe-gateway-config.ts, packages/infra/lib/ihe-stack.ts
Refs: #799
- Upstream: https://github.com/metriport/metriport-internal/pull/2014
- trying to rebuild ihe stack from scratch without errors after a failed attempt to migrate resources out of the ihe stack
=> Fix IHE Stack Deployments 

packages/api/src/routes/helpers/request-logger.ts, packages/api/src/routes/medical/dtos/linkDTO.ts
- Request logger now prints the `cxId`, so it's easier to filter the logs
- The internal `Patient HIE Overview` endpoint now prints `addressLine2` for a more thorough pt demos comparison
- Local
Normal routes: 
Internal routes (unchanged cuz `cxId` is already often in the `query params`:
=> feat(api): request logger prints cxId, pt hie overview prints line2

packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/ihe-gateway-v2-stack.ts
Ticket: #1040
- Upstream: https://github.com/metriport/metriport-internal/pull/2016
- Downstream: https://github.com/metriport/metriport/pull/2494
- Adding xcpd responses bucket for saving failure/error responses for outbound XCPD
- Local
- Staging
- Sandbox
- Production
=> 1040 Provision S3 Bucket for Outbound Failures

packages/api/src/external/commonwell/__tests__/patient.test.ts, packages/api/src/external/commonwell/patient.ts
Ref. metriport/metriport#2253
none
Check CW enabled for patient on sandbox - [context](https://metriport.slack.com/archives/C0553DYC95L/p1721308116030269?thread_ts=1721133545.282949&cid=C0553DYC95L)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2253 Check CW enabled for patient on sandbox

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
Ticket: #799
Remove unnecessary unknowns from MR
- Local
- Production
Check each PR.
=> PATCH RELEASE: remove unnecessary unknowns

.github/workflows/_redeploy_api-gw.yml, .github/workflows/branch-to-staging.yml, .github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, packages/scripts/redeploy-api-gateway.sh
Ref. metriport/metriport-internal#1932
none
Re-deploy API GW upon CICD run.
Based on https://github.com/metriport/metriport-internal/pull/1966
- Local
- none
- Staging
- Production
=> 1932 Re-deploy API GW upon infra changes

packages/api-sdk/src/medical/models/__tests__/contact.ts, packages/api-sdk/src/medical/models/__tests__/demographics.test.ts, packages/api-sdk/src/medical/models/demographics.ts
none
Add tests for emailSchema - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1721345749355369?thread_ts=1717952771.261659&cid=C04T256DQPQ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Add tests for emailSchema

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ticket: https://github.com/metriport/metriport-internal/issues/1969
Publish NPM packages
- api@1.21.2
- @metriport/api-sdk@12.0.2
- @metriport/carequality-cert-runner@1.10.2
- @metriport/carequality-sdk@0.12.2
- @metriport/commonwell-cert-runner@1.18.2
- @metriport/commonwell-jwt-maker@1.16.2
- @metriport/commonwell-sdk@5.0.2
- @metriport/core@1.16.2
- @metriport/ihe-gateway-sdk@0.11.2
- infrastructure@1.14.2
- @metriport/react-native-sdk@1.13.2
- @metriport/shared@0.11.2
- utils@1.17.2
none
=> 1969 Publish NPM packages

packages/core/src/external/carequality/ihe-gateway-v2/gateways.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti38-envelope.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/create/iti39-envelope.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/create/iti55-envelope.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/security/sign.ts
- fixe for kno2 to revert to using sha1 (only for them) 
- Local
=> feat(sha1): sha1 if enabled

packages/api/src/command/medical/patient/handle-data-contributions.ts
Log execution time on handle-data-contributions - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1722042794190369)
none
=> PATCH RELEASE Log execution time on handle-data-contributions

packages/fhir-converter/package-lock.json, packages/fhir-converter/package.json, packages/lambdas/package-lock.json, packages/lambdas/package.json
Ref. https://github.com/metriport/metriport/security/dependabot/230
none
Update fast-xml to 4.4.1
- Local
- Staging
- Sandbox
- none
- Production
- none
=> build: update fast-xml to 4.4.1

docs/medical-api/api-reference/fhir/create-patient-consolidated.mdx, packages/api-sdk/src/medical/client/metriport.ts, packages/api/src/command/medical/patient/__tests__/consolidated-create.test.ts, packages/api/src/command/medical/patient/consolidated-create.ts, packages/api/src/command/medical/patient/handle-data-contributions.ts, packages/core/src/fhir-to-cda/upload.ts
Improve the processing of data contribution (`PUT /consolidated`) - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1722042794190369)
- store original uploaded bundle
- store the actual bundle sent to the FHIR server
- (do these in parallel)
- validate the bundle considering the conversion to CDA before inserting on the FHIR server
- update Doc/TSDoc WRT to sandbox resource limits
- Local
- Staging
- Sandbox
- none
- Production
=> 1040 Improve processing of data contribution

packages/scripts/deploy-api.sh
- related: https://github.com/metriport/metriport-internal/pull/2076
Docker buildx to a single platform linux/amd64 - [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1722441011801579?thread_ts=1722436206.997679&cid=C04DBBJSKGB)
- Local
- none
- Staging
- Production
=> 1040 Docker buildx to a single platform

packages/infra/lib/api-stack/api-service.ts
- https://github.com/metriport/metriport-internal/pull/2073
Limit the amount of images on ECR to `5,000` - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1721334532211499?thread_ts=1721311737.404189&cid=C04FZ9859FZ)
- Local
- none
- Staging
- "Expiration is always ordered by pushed_at_time, and always expires older images before newer ones." - [source](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html)
- Production
- no changes in the amount of images since we have fewer images than the limit there
=> 1040 Limit the amount of images on ECR

.github/workflows/_deploy-cdk.yml, .github/workflows/branch-to-staging.yml, .github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Ref. metriport/metriport-internal#1969
- related: https://github.com/metriport/metriport-internal/pull/2000
Deploy secrets stack w/ CICD.
- Local
- none
- Staging
- Sandbox
- Production
=> 1969 Deploy secrets stack w/ CICD

packages/core/src/fhir-to-cda/cda-templates/components/notes.ts, packages/core/src/fhir-to-cda/cda-types/sections.ts
refs. metriport/metriport-internal#1951
- Removing template IDs from Notes as per Epic's request
- Local
=> fix(api): removed templateIds from notes

packages/api/src/command/medical/patient/handle-data-contributions.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1603
- Adding `Patient` and `Organization` resource to the Bundle prior to CDA generation
- Local
- Production
=> PATCH_RELEASE 2024_07_31 Data Contributions

packages/api/src/shared/external.ts, packages/core/src/external/aws/s3.ts, packages/core/src/external/commonwell/document/document-downloader-local.ts, packages/core/src/external/fhir/shared/extensions/metriport.ts
Some things I adjusted while testing/reviewing another PR:
- Replace console.log by out.log
- mapDocRefToMetriport from const to function
Test this along side to a larger PR.
=> 1040 Replace console.log by out.log

packages/core/src/external/canvas/data.ts
Ticket: #[2062](https://github.com/metriport/metriport-internal/issues/2062)
- switching snomed codes for icd-10 codes so they show up in canvas
- Local
=> feat(canvas): adding icd 10 codes instead of snomed

packages/api/src/command/internal/update-hie-enabled-feature-flags.ts, packages/api/src/external/aws/app-config.ts, packages/api/src/external/carequality/patient.ts, packages/api/src/external/commonwell/patient.ts, packages/api/src/routes/internal.ts, packages/core/src/external/aws/app-config.ts
Ticket: #1040
- Upstream: add the new FF to the config manually?
- adding new demo augmentation ff based on CX -- note that I followed the Epic approach of an empty cxId list maps to all customers in the list -- not sure if we want this for sure, but means we need to have at least one cxId in the list before we enable the FF at the global level.
- Fixed bug where Epic / Demo Aug would be classified as true even if the global enabled flag is false.
- adding the enabled status to the PD flow (note: done at HIE level)
- adding ability to update the new flag via the ops-dash internal endpoints
- Local
- Staging
- Production
=> 1040 add demo aug ff

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
- replace invalid paragraph HTML elements by `<p>`
- remove invalid `width` HTML tag
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> PATCH RELEASE Cleanup table medical record

packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts
refs. metriport/metriport-internal#2040
- FHIR to Medical Record Summary lambda getting env vars for Bedrock
- FHIR to Medical Record Summary lambda getting access to invoke Bedrock InvokeModel method
- Staging
=> fix(api): giving lambda access to env vars

packages/fhir-converter/package-lock.json, packages/fhir-converter/package.json, packages/fhir-converter/src/index.js
Refs: #799
- adding timeouts to fhir converter server 
- see: https://github.com/metriport/metriport/pull/2464
```
date && ab -c 100 -n 10000 -H "Host: <staging_url>" <staging_url> / && date
```
- tested 3 times all with 0 failed requests
=> fix(express): updating timeouts on fhir converter server

packages/fhir-converter/src/templates/cda/ValueSet/MedicationRequestStatus.hbs
refs. metriport/metriport-internal#2093
- Fixed mapping for `MedicationRequest.statusCode`
- Local
- Production
=> PATCH RELEASE 2024_08_08 FHIR Converter

packages/infra/lib/api-stack/fhir-server-connector.ts
- Upstream: https://github.com/metriport/fhir-server/pull/69
Beef-up FHIR Server - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1723054102315689?thread_ts=1723042815.068539&cid=C04GEQ1GH9D)
none
=> PATCH RELEASE 799 Increase max concurrency FHIR server lambda

packages/api-sdk/src/medical/client/metriport.ts, packages/core/src/external/aws/s3.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/process-dr.test.ts, packages/utils/src/bulk-insert-patients.ts, packages/utils/src/bulk-query-patients.ts, packages/utils/src/coverage-assessment.ts, packages/utils/src/shared/file.ts, packages/utils/src/shared/folder.ts, packages/utils/src/shared/log.ts
- Adjustments on CA scripts
- S3 attempts from 3 to 5 - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1723076882945709?thread_ts=1723068289.686479&cid=C04T256DQPQ)
- Add additional query params to create/update patient - [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1723127363638609?thread_ts=1723082350.762469&cid=C04DBBJSKGB)
- fix unit tests of `processDrResponse`
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Adjustments on CA scripts + other goodies

packages/api/src/__tests__/e2e/mapi/parts/patient.test.part.ts, packages/infra/lib/api-stack/ccda-search-connector.ts, packages/infra/lib/api-stack/fhir-server-connector.ts, packages/infra/lib/shared/sqs.ts
none
[context](https://metriport.slack.com/archives/C04T256DQPQ/p1723302342464439?thread_ts=1723301243.898709&cid=C04T256DQPQ):
- adjust max age of oldest message for the FHIRServer queue (from 2 to 4min)
- adjust max age of oldest message for the OpenSearch queue (from 1 to 2min)
- remove custom max age of oldest message for DLQs
- increase default max age of oldest message for DLQs from 10min to 2h
[context](https://metriport.slack.com/archives/C04FZ9859FZ/p1723302719299519?thread_ts=1723300442.760389&cid=C04FZ9859FZ):
- log the patient ID on the MAPI E2E test
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Adjust max age of oldest message on queues

packages/infra/lib/api-stack.ts
none
Add API_URL to FHIR to Medical Record Lambda - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1723304177758009?thread_ts=1723300442.760389&cid=C04FZ9859FZ)
- Staging
- Sandbox
- none
- Production
- none
=> 2040 Add API_URL to fhirToMedicalRecordLambda

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ticket: https://github.com/metriport/metriport-internal/issues/2040
- Upstream: https://github.com/metriport/metriport/pull/2529
Ref: #000
- api@1.21.3
- @metriport/api-sdk@12.0.5
- @metriport/carequality-cert-runner@1.10.5
- @metriport/carequality-sdk@0.12.3
- @metriport/commonwell-cert-runner@1.18.5
- @metriport/commonwell-jwt-maker@1.16.5
- @metriport/commonwell-sdk@5.0.5
- @metriport/core@1.16.3
- @metriport/ihe-gateway-sdk@0.11.5
- infrastructure@1.14.3
- @metriport/react-native-sdk@1.13.3
- @metriport/shared@0.12.2
- utils@1.17.3
none
=> 2040 Publish NPM packages

packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/lib/api-stack.ts, packages/lambdas/src/fhir-to-medical-record.ts, packages/lambdas/src/shared/oss-api.ts
- Upstream: https://github.com/metriport/metriport-internal/pull/2102
- Add dash url to MR lambda
- Fix feedback proxy
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 2040 Add dash url to MR lambda and fix feedback proxy

packages/api/src/command/feedback/feedback-entry.ts, packages/api/src/shared/config.ts, packages/infra/lib/api-stack/api-service.ts
none
Notification url to point to the LB address of the API - [context](https://metriport.slack.com/archives/C04GJPTTL82/p1723341303960659?thread_ts=1723340527.487859&cid=C04GJPTTL82)
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 2040 Notification url to point to the LB address of the API

packages/api/src/command/medical/patient/__tests__/check-ai-brief.test.ts, packages/api/src/command/medical/patient/check-ai-brief-enabled.ts, packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/routes/medical/patient.ts, packages/lambdas/src/fhir-to-medical-record.ts
Default enable AI Brief - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1723567672825589?thread_ts=1723566145.058639&cid=C0616FCPAKZ)
- Local
- Staging
- none
- Sandbox
- none
- Production
=> PATCH RELEASE Default enable AI Brief

packages/api/src/command/medical/patient/__tests__/check-ai-brief.test.ts, packages/api/src/command/medical/patient/check-ai-brief-enabled.ts, packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/routes/medical/patient.ts, packages/lambdas/src/fhir-to-medical-record.ts
- Upstream: https://github.com/metriport/metriport/pull/2595
- Downstream: https://github.com/metriport/metriport/pull/2596
Fix conflicts from `master` into `develop` - https://github.com/metriport/metriport/pull/2596
- Cherry-picked [the commit ](https://github.com/metriport/metriport/pull/2596/commits/975ab7aad6da1dd3f3ebf4ed2ae72699bc7ef656) from [this PR](https://github.com/metriport/metriport/pull/2595) that patched `master` with defaulting AI Brief for cx's w/ that feature enabled.
- Fix conflict
none
=> 2040 Fix backmerge conflict

packages/fhir-converter/src/templates/cda/Resources/Composition.hbs
Ticket: #799
Always have text on composition section
- Local
- Production
Check each PR.
=> PATCH: Always add text to composition section

packages/core/src/command/consolidated/consolidated-connector-lambda.ts, packages/core/src/util/config.ts
Ref. metriport/metriport-internal#1319
The current version on `develop` will break the flows that use consolidated data while the release is in progress (the API gets deployed before the infra finishes updating the ECS task definition w/ the new env vars).
This makes it to rely on the local approach to get consolidated, inside the OSS API instead of the lambda.
An upcoming PR will remove this and require the lambda name again.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> refactor(api): make consolidated lambda backwards compatible

docs/medical-api/api-reference/document/download-url-bulk.mdx, packages/core/src/external/aws/document-signing/bulk-sign.ts
Refs: #[2604](https://github.com/metriport/metriport/issues/2604)
- bulk download presigned url expiry is too short, and some cxs don't have enough time to dl the docs
=> feat(bulk): bump signed doc url duration

packages/core/src/command/consolidated/consolidated-connector-lambda.ts, packages/core/src/util/config.ts
Ref. metriport/metriport-internal#1319
- Upstream: https://github.com/metriport/metriport/pull/2601
Make consolidated lambda name required - [context](https://metriport.slack.com/archives/C04CXLSAF7V/p1723589515518419?thread_ts=1722623737.720209&cid=C04CXLSAF7V)
none
=> 1319 Make consolidated lambda name required

packages/core/src/command/consolidated/consolidated-connector-lambda.ts, packages/core/src/util/config.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1319
Reverts https://github.com/metriport/metriport/pull/2603 - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1723647155250279?thread_ts=1723641742.559579&cid=C04GEQ1GH9D)
This reverts commit 130f8d4bb431f3f1a99c734564116d0e1b01d0e5, reversing changes made to 521695497b968a85a45fa909a92d2220b1e46fbc.
none
=> Revert Make consolidated lambda name required

packages/api/src/external/hie/__tests__/carequality-analytics.test.ts, packages/api/src/external/hie/carequality-analytics.ts
- analytics was counting no-documents-found as failures on DQs making success rate lower than it should be
- Local
=> fix(dq): analytics was counting no-documents-found as failures

packages/api/src/routes/medical/internal-patient.ts, packages/core/src/util/error/shared.ts
Ticket: https://github.com/metriport/metriport-internal/issues/1319
Async response from consolidated lambda - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1723758171829449?thread_ts=1717078587.717249&cid=C04T256DQPQ)
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1319 Async response from consolidated lambda

packages/api/src/routes/medical/internal-patient.ts
Ref. metriport/metriport-internal#1319
Single import of processAsyncError on internal patient routes - context.
The imports were not organized, so when we merged [this PR](https://github.com/metriport/metriport/pull/2621) into `develop` there were no conflicts and the merge was successful - even though I was expecting the merge queue to have caught this.
- Local
- none
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1319 Single import of processAsyncError

packages/infra/lib/ihe-gateway-v2-stack.ts
Ref: #2115
- the lowest level partition (gateway oid) is resulting in too many partitions and not loading in timely manner on athena -- this data is available in the raw data anyway so isn't necessary as a partition
- Staging
- Production
=> feat(api): remove lowest partition to decrease parition loading load

packages/infra/lib/ihe-gateway-v2-stack.ts
Ref: #1040
- rename table as it has to be recreated to properly properly drop partitions
- Staging
- Production
=> feat(api): rename athena+ s3 table to force CDK recreate

packages/api/src/command/feedback/feedback-entry.ts, packages/core/src/external/aws/__tests__/s3.test.ts, packages/core/src/external/aws/s3.ts, packages/core/src/util/config.ts, packages/infra/config/env-config.ts
none
Send AI Brief notif w/ full content - [context](https://metriport.slack.com/archives/C07D712SW6R/p1723818927826839?thread_ts=1723814638.453529&cid=C07D712SW6R)
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2040 Send AI Brief notif w/ full content

packages/api/src/command/feedback/feedback-entry.ts
- Upstream: https://github.com/metriport/metriport/pull/2630
Import full path of slack util from core - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1724111720107379?thread_ts=1724109436.909239&cid=C04FZ9859FZ)
It runs local
=> 2040 Import full path of slack util from core

packages/api/src/command/feedback/feedback-entry.ts
none
Update AI Brief notification format.
- Local
- Staging
- [previous PR](https://github.com/metriport/metriport/pull/2630)
- Sandbox
- none
- Production
- none
=> 2040 Update AI Brief notification format

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
Refs: #[1792](https://github.com/metriport/metriport-internal/issues/1792)
- filter out generic snomed code as part of condition blacklist, so that MR summary is empty and cx doesn't receive MR in this case
- Local
=> fix(mr): filter out blacklisted condition codes

packages/fhir-converter/src/templates/cda/Resources/MedicationRequest.hbs
refs. metriport/metriport-internal#2128
- Added `authoredOn` field mapping for the `MedicationRequest` resource
- Local
=> feat(fhir-converter): added date mapping to med req

packages/fhir-converter/src/templates/cda/Resources/Immunization.hbs, packages/fhir-converter/src/templates/cda/Resources/Procedure.hbs
refs. metriport/metriport-internal#2149
- Default date for `Procedure` and `Immunization` resources
- Local
=> feat(fhir-converter): default date for procedure and immunization

.github/workflows/_deploy-api.yml, .github/workflows/_deploy-cdk.yml, .github/workflows/_restart-ecs.yml, .github/workflows/restart_api_prod.yml, .github/workflows/restart_api_sandbox.yml, .github/workflows/restart_api_staging.yml
none
While implementing https://github.com/metriport/metriport/pull/2492, I've noticed these issues w/ the CICD workflows:
- the concurrency control is using the Job ID as part of the key, it means that we can have the same stack being attempted to be deployed by diff CICD runs, for example;
- we're not passing the deploy env to the reusable restart workflow.
So this:
- Fix concurrency prevention to not have the job id
- Pass the deploy env to the restart ecs workflow
- Local
- Staging
- Sandbox
- Production
=> 1040 Fix concurrency prevention to not have the job id

packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html-shared.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
none
- Indicate missing date for DiagnosticReport - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1724276023306869?thread_ts=1724257837.838079&cid=C0616FCPAKZ)
- Move some shared code to a shared file
- Include the resource ID (hidden) on DiagnosticReport and MedicationStatement
Note: I intentionally kept changes to a minimum. There's a lot to fix/improve, but this needs more time and prioritization.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Indicate missing date for DiagnosticReport

packages/lambdas/src/fhir-to-medical-record.ts
none
Remove Sentry handler from FHIR to MR lambda to minimize alerts.
These will become one alert:
- https://metriport.slack.com/archives/C04T256DQPQ/p1724335779939219?thread_ts=1717081003.927489&cid=C04T256DQPQ
- https://metriport.slack.com/archives/C04T256DQPQ/p1724335780223269?thread_ts=1717078585.367749&cid=C04T256DQPQ
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Remove Sentry handler from FHIR to MR lambda

packages/api/src/__tests__/e2e/mapi/parts/consolidated.test.part.ts, packages/api/src/__tests__/e2e/mapi/parts/consolidated/consolidated-template.html, packages/api/src/__tests__/e2e/mapi/parts/consolidated/consolidated.ts, packages/api/src/__tests__/e2e/mapi/parts/consolidated/validate-received-html.ts
- Upstream: https://github.com/metriport/metriport/pull/2642
E2E test w/ allergy ID on the HTML MR - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1724379010051399?thread_ts=1724371991.327449&cid=C04FZ9859FZ)
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 E2E test w/ allergy ID on the HTML MR

packages/infra/lib/api-stack/ccda-search-connector.ts, packages/infra/lib/shared/lambda.ts
- Upstream: https://github.com/metriport/metriport-internal/pull/2156
Beef-up OpenSearch - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1724689492389159)
Also added retry attempts to the CCDASearch lambda so it can auto retry a couple of times before error and drive messages to DLQ.
See upstream
- See upstream
=> PATCH RELEASE 799 Beef-up OpenSearch

packages/core/src/domain/__tests__/filename.test.ts, packages/core/src/domain/filename.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/ihe-gateway-v2-logic.ts, packages/infra/lib/ihe-gateway-v2-stack.ts
Ticket: #1040
- add date level partitioning so that the stats query can run on a subset of dates within a month without timing out
- remove requsetId partitioning to make it a bit less heavy when running
- add new columns so that we can query data without the partitions if need be
- Local
- Staging
- Production
=> 1040 date added to partition scheme

packages/core/src/fhir-deduplication/shared.ts
Refs: #[2569](https://github.com/metriport/metriport/issues/2569)
- invalid fhir bug
=> fix(dedup): invalid fhir

packages/core/src/fhir-deduplication/__tests__/examples/medication-related.ts, packages/core/src/fhir-deduplication/__tests__/remove-dangling-link.test.ts, packages/core/src/fhir-deduplication/deduplicate-fhir.ts, packages/core/src/fhir-deduplication/resources/medication.ts
- Removing resources that are crucially dependent on the resources that had been eliminated in the deduplication step (i.e. if `Medication` that's referenced by a `MedicationStatement` was eliminated, then the whole `MedicationStatement` carries no meaning, and should therefore also be removed)
- Local
=> PATCH RELEASE 2024_08_27 Fhir Dedup 

packages/core/src/fhir-deduplication/__tests__/group-same-medications.test.ts, packages/core/src/fhir-deduplication/resources/medication.ts, packages/core/src/fhir-deduplication/shared.ts
- Removing `Medication` resources that have `No known medication` for code, as well as the Medication-related resources that refer to them. 
- Local
=> PATCH RELEASE 2024-08-28 FHIR Dedup - unknown med resources

.husky/check-signoff.sh, packages/core/src/command/consolidated/consolidated-connector-local.ts, packages/core/src/command/consolidated/consolidated-on-s3.ts, packages/lambdas/src/fhir-to-medical-record.ts
Refs: #[2569](https://github.com/metriport/metriport/issues/2569)
What's being done here - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1724813010647859):
- Move dedup logic to the "get consolidated lambda";
- Always generate the dedup bundle, just the FF to just indicates whether to use the non-deduped or the deduped version;
- Used the opportunity to fix the DCO checker when we merge from develop on local.
To help reviewing the PR:
- [this commit](https://github.com/metriport/metriport/pull/2673/files/458924f2d860298af6895b4c38ded0308d362f9e) shows the code being moved to the lambda;
- [this comparison](https://github.com/metriport/metriport/pull/2673/files/b22f81026d89dd12babb6b83b4d85c239675bcc6..f72939e0d3a103f019960bc968e3f0885daf7c9e) shows the update on the dedup …
=> 2569 Dedup GO LIVE

packages/infra/lib/api-stack.ts, packages/infra/lib/lambdas-nested-stack.ts, packages/infra/lib/shared/app-config.ts
Ref. metriport/metriport-internal#2569
- upstream: https://github.com/metriport/metriport/pull/2673
Allow get consolidated lambda to access FFs - [context](https://metriport.slack.com/archives/C04T5Q9JHFX/p1724852868602349)
See upstream
=> 2569 Allow get consolidated lambda to access FFs

packages/api/src/command/medical/patient/get-patient-facility-matches.ts
Ref. metriport/metriport#2064
Return CQ links that dont have patient resource - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1723307734296789)
- Local
- Production
Check each PR.
=> PATCH RELEASE: return cq link if no patient

packages/fhir-converter/src/lib/handlebars-converter/__tests__/handlebars-helpers.test.js, packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
Don't fail when gets a non-string value - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1724885917317999?thread_ts=1724827486.314079&cid=C04T256DQPQ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> PATCH RELESE Don't fail when gets a non-string value

packages/api/src/routes/ehr/athenahealth/auth/middleware.ts, packages/api/src/routes/ehr/athenahealth/patient.ts
Ref: #2115
- obfuscating token value when throwing middleware error
- returning an object even if patient was not found (vs. undefined)
- Staging
- Production
=> feat(athena): small change to response

packages/core/src/fhir-deduplication/__tests__/combine-two-resources.test.ts, packages/core/src/fhir-deduplication/__tests__/deduplicate-fhir.test.ts, packages/core/src/fhir-deduplication/__tests__/group-same-observations.test.ts, packages/core/src/fhir-deduplication/__tests__/group-same-organizations.test.ts, packages/core/src/fhir-deduplication/__tests__/is-unknown-coding.test.ts, packages/core/src/fhir-deduplication/__tests__/remove-dangling-link.test.ts, packages/core/src/fhir-deduplication/deduplicate-fhir.ts, packages/core/src/fhir-deduplication/resources/allergy-intolerance.ts, packages/core/src/fhir-deduplication/resources/condition.ts, packages/core/src/fhir-deduplication/resources/coverage.ts, packages/core/src/fhir-deduplication/resources/diagnostic-report.ts, packages/core/src/fhir-deduplication/resources/encounter.ts, packages/core/src/fhir-deduplication/resources/family-member-history.ts, packages/core/src/fhir-deduplication/resources/immunization.ts, packages/core/src/fhir-deduplication/resources/location.ts, packages/core/src/fhir-deduplication/resources/medication-administration.ts, packages/core/src/fhir-deduplication/resources/medication-request.ts, packages/core/src/fhir-deduplication/resources/medication-statement.ts, packages/core/src/fhir-deduplication/resources/medication.ts, packages/core/src/fhir-deduplication/resources/observation-shared.ts, packages/core/src/fhir-deduplication/resources/observation-social.ts, packages/core/src/fhir-deduplication/resources/observation.ts, packages/core/src/fhir-deduplication/resources/organization.ts, packages/core/src/fhir-deduplication/resources/practitioner.ts, packages/core/src/fhir-deduplication/resources/procedure.ts, packages/core/src/fhir-deduplication/resources/related-person.ts, packages/core/src/fhir-deduplication/shared.ts, packages/core/src/fhir-to-cda/cda-templates/components/__tests__/encompassing-enc.test.ts, packages/core/src/fhir-to-cda/cda-templates/components/__tests__/make-composition.ts
- Downstream: https://github.com/metriport/metriport/pull/2699
- Handling dangling links
- Added backup keys as per [this discussion](https://metriport.slack.com/archives/C06CQC7GQG3/p1725060614148579) on Slack
- The blacklisted values checks were added to the following resources with the logic as discussed [here](https://metriport.slack.com/archives/C06CQC7GQG3/p1725063802398999?thread_ts=1725062079.255369&cid=C06CQC7GQG3):
- Condition - condition.code
- Immunization - immunization.vaccineCode
- Medication - medication.code
- Observation - observation.code
- Procedure - procedure.code
- Local
=> feat(core): handling dangling links

package-lock.json, packages/api-sdk/package.json, packages/api-sdk/src/medical/client/metriport.ts, packages/api/package.json, packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/routes/medical/patient.ts, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/core/src/command/consolidated/consolidated-connector-local.ts, packages/core/src/command/consolidated/consolidated-connector.ts, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Ticket: #2064
- Downstream: https://github.com/metriport/metriport-internal/pull/2097
Dedup available for dash
- Local
- Staging
- Production
Check each PR.
=> 2064 dedup from dash

packages/core/src/fhir-deduplication/resources/organization.ts, packages/core/src/fhir-deduplication/resources/practitioner.ts
- adding `validateNpi` for the `Organization` and `Practitioner` deduplication to avoid using fake NPIs as the dedup key
- Local
=> feat(core): adding npi validation

packages/infra/lib/api-stack.ts
Ref. metriport/metriport-internal#2064
Set CORS on medical buckets - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1725649603411619?thread_ts=1725636736.574229&cid=C04DMKE9DME)
- Local
- Staging
- Sandbox
- Production
=> 2064 Set CORS on medical buckets

packages/core/src/fhir-to-cda/cda-templates/components/mental-status.ts, packages/core/src/fhir-to-cda/cda-templates/components/observations.ts, packages/core/src/fhir-to-cda/cda-templates/components/problems.ts, packages/core/src/fhir-to-cda/cda-templates/constants.ts, packages/core/src/fhir-to-cda/cda-templates/create-table-rows-and-entries.ts, packages/core/src/fhir-to-cda/cda-templates/table.ts, packages/core/src/fhir-to-cda/cda-types/sections.ts, packages/core/src/fhir-to-cda/cda-types/shared-types.ts
refs. metriport/metriport-internal#2174
- Split up different mental status tables and added headers to each. Previously, there was just one big table with all the questions and results
- Added support for Problems' Provider status and Clinical status
- Local
=> feat(fhir-to-cda): split up mental status tables

packages/utils/src/fhir-dedup/condition.ts, packages/utils/src/fhir-dedup/medication-administration.ts, packages/utils/src/fhir-dedup/medication-requests.ts, packages/utils/src/fhir-dedup/medication-statement.ts, packages/utils/src/fhir-dedup/medication.ts, packages/utils/src/fhir-dedup/report-dedup.ts, packages/utils/src/fhir-dedup/resource-props.ts, packages/utils/src/fhir-dedup/validate-references.ts
- Upstream: https://github.com/metriport/metriport/pull/2712
Fix missing refs report on dedup script to account for all refs - [context](https://www.notion.so/metriport/Data-Quality-v2-28a69479807a4f9b897921fd77e54d8f?pvs=4#66e201ddd7424d96b58312caad7b2702)
Replicate improvements done from 5th resource onwards to the first resources as well.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2179 Fix missing refs report on dedup script to account for all refs

packages/core/src/fhir-deduplication/deduplicate-fhir.ts
- fix for removed practitioners lingering as dangling references 
- locally ran validate references scripts to confirm that all deduplicated files have no dangling references
=> feat(dedup): practitioner references bug fix

packages/core/src/fhir-deduplication/__tests__/group-same-med-statements.test.ts, packages/core/src/fhir-deduplication/resources/medication-statement.ts
- allow medication statements to not have dates 
- refactoring unit tests
=> 2569 medication statements without dates

packages/utils/src/fhir/process-ndjson-output.ts
none
Add script to process output from healthlake - [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1725984788768939?thread_ts=1725906099.543059&cid=C06CQC7GQG3)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2179 Add script to process output from healthlake

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/error.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/schema.ts, packages/core/src/external/carequality/ihe-gateway-v2/schema.ts
- removing unnessecary fields in zod response schema that cause us to throw zod errors that we dont use anyway for processing
- Local
=> Kno2 and Ehex Zod Schema Issues

packages/core/src/fhir-deduplication/deduplicate-fhir.ts
- fix for removed Practitioners, Organizations, RelatedPersons lingering as dangling references in Compositions
=> feat(dedup): composition references bug fix

packages/core/src/fhir-deduplication/__tests__/group-same-conditions.test.ts, packages/core/src/fhir-deduplication/resources/condition.ts
refs. metriport/metriport-internal#2569
- Sometimes conditions have this useless code that just says "Problem". We shouldn't use those as a key for dedup. 
- Local
=> feat(dedup): condition useless code filter

packages/api/src/external/carequality/document/__tests__/create-outbound-document-retrieval-req.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/gateways.ts
- redox changed system to only accept one docRef per request
- on epic instance Ohio community care physicians randomly only accepts 9 doc refs instead of 10 
- Local
=> fix(ihe): dr errors in prod for redox and ohio physicians too many docs requested

packages/core/src/fhir-deduplication/__tests__/group-same-conditions.test.ts, packages/core/src/fhir-deduplication/__tests__/group-same-medications.test.ts, packages/core/src/fhir-deduplication/__tests__/group-same-observations.test.ts, packages/core/src/fhir-deduplication/__tests__/group-same-procedures.test.ts, packages/core/src/fhir-deduplication/deduplicate-fhir.ts, packages/core/src/fhir-deduplication/resources/condition.ts, packages/core/src/fhir-deduplication/resources/medication.ts, packages/core/src/fhir-deduplication/resources/observation-social.ts, packages/core/src/fhir-deduplication/resources/practitioner.ts, packages/core/src/fhir-deduplication/resources/procedure.ts, packages/core/src/util/constants.ts
- `Object must have some content`. Remove post-processing of codes when all we have is a code without a valid display. Basically, when we use the display as a key, we are removing the code in post processing (the reason we used the display in the first place was because we didnt have a good code) leaving us with no code in the resource. So we need a different post processing function for a few different resources to stop this from happening. 
- `Composition.author: minimum required = 1, but only found 0`. An issue where compositions had no author even though author is a required field 
- more unit tests
=> 2569 healthlake valid fhir v0

packages/core/src/fhir-deduplication/shared.ts
refs. metriport/metriport-internal#2569
- Blacklisting `no data` in `text` field of codeable concepts
- Local
=> feat(dedup): no data text field

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/create/iti55-envelope.ts, packages/core/src/external/fhir/patient/index.ts
- address line 2 is not being used in CQ flow
- Local
=> fix(ihe): address line 2 not used by cq

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts
refs. metriport/metriport-internal#2222
- Dont fail DQ on missing `repositoryUniqueId`
- Local
=> feat(core): dont fail dq on missing repository id

packages/fhir-converter/src/lib/handlebars-converter/__tests__/handlebars-helpers.test.js, packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
refs. metriport/metriport-internal#2107
- Datetimes that are missing `T` and/or `.000Z` get these appended
- Local
- :warning: Points to master
=> PATCH RELEASE 2024_09_13 FHIR Converter datetime

packages/lambdas/src/shared/__tests__/sqs.test.ts, packages/lambdas/src/shared/sqs.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2215
- Upstream: https://github.com/metriport/metriport/pull/2767
Message dedup uses rightmost chars of s3 key.
- Local
- Staging
- none
- Sandbox
- none
- Production
=> PATCH RELEASE 2215 Message dedup uses rightmost chars of s3 key

packages/core/src/command/consolidated/get-snapshot-local.ts, packages/core/src/external/aws/app-config.ts, packages/infra/lib/lambdas-nested-stack/consolidate-patient-data-connector.ts
none
Consolidated from S3 FF from boolean to per cx - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1726687148822529?thread_ts=1726522010.103949&cid=C04DMKE9DME).
Also adjust the threshold for the alert about max age on consolidator SQS - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1726679666129669?thread_ts=1726660494.128789&cid=C04T256DQPQ).
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
```
"cxsWithConsolidatedFromS3": {
"enabled": false,
"values": [
"abc123"
]
},
```
=> 2215 Consolidated from S3 FF from boolean to per cx

packages/core/src/fhir-to-cda/cda-templates/components/medications.ts, packages/lambdas/src/fhir-to-cda-converter.ts
- FHIR to CDA has some scenarios where it errors with `BadRequestError`. We don't want to be notified of those on Sentry. This PR handles that.
- Local
=> fix(core): dont notify us on bad request errors

packages/utils/src/s3/remove-objects.ts
none
Add script to remove objects from s3.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2215 Add script to remove objects from s3

packages/fhir-converter/src/routes.js
refs. metriport/metriport-internal#2107
- When conversion status is `undefined`, we wait until timeout. This fix defaults to 400, so we instantly return if there are errors in the conversion. 
- Local
=> fix(fhir-converter): default 400 status

packages/api/src/external/commonwell/proxy/cw-process-request.ts, packages/core/src/external/carequality/dq/process-inbound-dq.ts, packages/core/src/shareback/ensure-ccd-exists.ts, packages/core/src/shareback/metadata/get-metadata-xml.ts, packages/infra/lib/ihe-stack.ts, packages/lambdas/src/ihe-gateway-v2-inbound-document-query.ts
refs. metriport/metriport-internal#2240
- Before responding to CW DQ requests, we now ensure that a CCD exists (by checking for an existing one, or creating a new one)
- Staging:
=> feat(api): always return CCD to CW

packages/infra/lib/ihe-stack.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2240
- Upstream: https://github.com/metriport/metriport/pull/2787
Add missing env var - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1726869465900829)
None
=> PATCH RELEASE 2240 Add missing env var

packages/core/src/command/consolidated/get-snapshot-local.ts, packages/core/src/external/aws/app-config.ts
none
FF for consolidated on s3 for all customers - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1726932468368799?thread_ts=1726716296.259739&cid=C04DMKE9DME)
- Local
- none
- Staging
- Sandbox
- none
- Production
=> 2215 FF for consolidated on s3 for all customers

packages/api/src/external/commonwell/proxy/cw-process-request.ts, packages/core/src/command/consolidated/consolidated-create.ts, packages/core/src/command/consolidated/get-snapshot-local.ts, packages/core/src/external/fhir/__tests__/reference.ts, packages/core/src/external/fhir/bundle/__tests__/qa.test.ts, packages/core/src/external/fhir/bundle/qa.ts, packages/core/src/external/fhir/consolidated/consolidated.ts, packages/core/src/external/fhir/shared/bundle.ts, packages/utils/src/s3/remove-objects.ts
none
Create new empty bundles on each consolidate create - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1727137104190069?thread_ts=1727121353.235279&cid=C04GEQ1GH9D).
Also added a function to validate the contents of the bundle for mingled data.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2215 Create new empty bundles on each consolidate create

packages/core/src/command/consolidated/consolidated-create.ts, packages/core/src/command/consolidated/consolidated-filter.ts, packages/core/src/command/consolidated/consolidated-get.ts, packages/core/src/command/consolidated/get-snapshot-local.ts, packages/core/src/external/fhir/document/get-documents.ts
none
Add doc refs to consolidated from S3 - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1727188691351699?thread_ts=1726716296.259739&cid=C04DMKE9DME).
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2215 Add doc refs to consolidated from S3

packages/core/src/command/consolidated/consolidated-create.ts, packages/core/src/command/consolidated/consolidated-filter.ts, packages/core/src/domain/consolidated/filename.ts
- Upstream: https://github.com/metriport/metriport/pull/2809
Fix adding doc refs to bundle upon creation - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1727201080532229?thread_ts=1726716296.259739&cid=C04DMKE9DME).
Also storing the original, non-deduped version of the consolidated bundle for debugging purposes.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2215 Fix adding doc refs to bundle upon creation

packages/core/src/command/consolidated/consolidated-create.ts, packages/core/src/command/consolidated/consolidated-filter.ts, packages/core/src/command/consolidated/get-snapshot-local.ts, packages/core/src/command/patient-loader-metriport-api.ts, packages/core/src/external/fhir/consolidated/deduplicate.ts, packages/core/src/fhir-deduplication/__tests__/deduplicate-fhir.test.ts, packages/core/src/fhir-deduplication/deduplicate-fhir.ts, packages/utils/src/fhir-deduplication/dedup-files.ts, packages/utils/src/fhir/consolidate-patient-data.ts
Refs: #2569
- https://github.com/metriport/metriport/pull/2828
- bug fix for patient missing in `createConsolodatedFromConversions`
- local:
- staging
Check each PR.
=> 2569 fix missing patient again

docs/medical-api/more-info/webhooks.mdx
Ticket: #1040
- Update the docs to introduce workflow section for core webhook flows. 
- Emphasize 5 second response timeout
=> fix(api): add webhook flows

packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/external/cda/generate-ccd.ts, packages/core/src/command/consolidated/get-snapshot-local.ts, packages/core/src/command/consolidated/get-snapshot.ts
none
CCD generation uses consolidated from S3 - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1727476915021909?thread_ts=1727121353.235279&cid=C04GEQ1GH9D).
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2215 CCD generation uses consolidated from S3

docs/medical-api/api-reference/document/get-document.mdx, packages/core/src/external/fhir/consolidated/consolidated.ts, packages/core/src/external/fhir/parse-bundle.ts, packages/core/src/external/fhir/shared/extensions/doc-id-extension.ts, packages/lambdas/src/sqs-to-converter.ts, packages/utils/src/fhir-converter/convert.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2261
- The `meta` attribute of the FHIR resources is now populated with the title of the document that was used to generate this resource. This allows for an easier way to download the source document for our customers
- Staging
=> 2261 fhir meta fix

packages/core/src/mpi/__tests__/inbound-epic-match.test.ts, packages/core/src/mpi/inbound-patient-mpi-metriport-api.ts, packages/core/src/mpi/match-patients.ts, packages/lambdas/src/ihe-gateway-v2-inbound-patient-discovery.ts
Refs: #[1766](https://github.com/metriport/metriport-internal/issues/1766)
- use epic similarity algo for patient matching on inbound which is more lenient than exact string matching, which is our current algorithm
- Local
- Staging
Check each PR.
=> feat(inbound): use epic similarity algo for inbound patient matching

packages/api/src/external/ehr/athenahealth/command/get-patient.ts, packages/api/src/external/ehr/athenahealth/command/get-patients-from-appointments.ts, packages/api/src/routes/ehr-internal/athenahealth/internal/patient.ts, packages/core/src/external/athenahealth/index.ts, packages/shared/src/interface/external/athenahealth/appointment.ts, packages/shared/src/interface/external/athenahealth/department.ts, packages/shared/src/interface/external/athenahealth/index.ts, packages/shared/src/interface/external/athenahealth/medication.ts, packages/shared/src/interface/external/athenahealth/subscription.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2170
- Downstream: https://github.com/metriport/metriport-internal/pull/2320
- added response types for Athena (carry-over from https://github.com/metriport/metriport/pull/2812)
- added buildDayjs for dates (carry-over from https://github.com/metriport/metriport/pull/2812)
- added async S3 calls (carry-over from https://github.com/metriport/metriport/pull/2812)
- added getting appointments from subscription endpoint
- added signing up for appointments feed if we get a 403 from the endpoint
- other improvements
- Local
- Staging
- Production
=> 2170 athena appointment subscription endpoint

packages/api/src/command/medical/document/check-doc-queries.ts, packages/api/src/command/medical/document/document-conversion-status.ts, packages/api/src/command/medical/patient/consolidated-delete.ts, packages/api/src/command/medical/patient/consolidated-recreate.ts
Recreate consolidated at end of conversions - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1727978058305349).
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> PATCH RELEASE 799 Recreate consolidated at end of conversions

packages/api/src/routes/medical/internal-patient.ts, packages/api/src/shared/config.ts, packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/config/patient-import.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts, packages/infra/lib/patient-import-nested-stack.ts, packages/infra/lib/shared/sqs.ts, packages/lambdas/src/patient-import-create.ts, packages/lambdas/src/patient-import-file.ts, packages/lambdas/src/patient-import-query.ts, packages/lambdas/src/shared/sqs.ts
- Upstream: https://github.com/metriport/metriport-internal/pull/2334
Infrastructure for Patient Import (bulk operation), to be used originally by Coverage Assessment and later on to be exposed to customers.
This PR only creates the infra with a mocked behavior in the lambdas. It's to be updated by downstream PRs related to the same ticket.
- Local
```json
{
"cxId": "1111",
"jobId":"1234",
"s3BucketName": "bucket-name",
"s3FileName": "file-name",
"amountOfPatients": 4,
}
```
```json
{
"cxId": "2222",
"jobId":"1234",
"s3BucketName": "bucket-name",
"s3FileName": "file-name",
"amountOfPatients": 1,
}
```
- Staging
- Sandbox
- Production
- :warning: Contains infra changes
=> 2330 Patient import infra

packages/core/src/command/patient-import/commands/validate-and-parse-import.ts, packages/core/src/command/patient-import/patient-import-cloud.ts, packages/core/src/command/patient-import/patient-import-local.ts, packages/core/src/command/patient-import/patient-import-shared.ts, packages/shared/src/domain/address/__tests__/normalize-zip.test.ts, packages/shared/src/domain/address/zip.ts, packages/shared/src/domain/patient/patient-import.ts, packages/utils/src/patient-import/validate-file.ts
- Upstream: https://github.com/metriport/metriport/pull/2853
Create new zip normalization and use it for bulk import. The existing implementation is not flexible and fails in many situations that we could normalize the input value.
Didn't replace the existing one because that requires more test across diff use cases. The idea is that on a follow-up PR we would do that so we have a single place to normalize and validate ZIP codes.
It also splits the `validateAndParsePatientImportCsv` in two functions, so we can more easily test the logic that's not dependent on S3.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2330 Create new zip normalization and use it for bulk import

packages/api/src/routes/medical/patient.ts
none
Temporarily return fixed resource count.
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2215 Temporarily return fixed resource count

packages/infra/lib/api-stack/fhir-server-connector.ts, packages/lambdas/src/shared/oss-api.ts, packages/lambdas/src/sqs-to-converter.ts, packages/lambdas/src/sqs-to-fhir.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2215
- Upstream: https://github.com/metriport/metriport/pull/2786
Moves the notification about completed CDA>FHIR conversion from the FHIR server lambda to the Converter lambda.
⚠️ We can only merge this PR when we're ready to move all customers to use consolidated from S3 _permanently_. If we need something temporary and/or that can be toggled, we'll need to tweak this PR so the notification can be moved back/forth between converter and server lambdas.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
- This is important b/c we moved the notification of completed conversion from the FHIR server lambda to the converter lambda;
- If we don't throttle the converter lambda, we could get to a state …
=> 2215 Move "conversion done" notification to the converter lambda

packages/infra/lib/api-stack/fhir-server-connector.ts, packages/infra/lib/shared/lambda.ts
Disable the FHIRServer lambda for outbound ingestion - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1728086552183879?thread_ts=1727883019.543829&cid=C04DMKE9DME)
none
- :warning: This contains infra changes
=> PATCH RELEASE 2330 Disable the FHIRServer lambda for outbound ingestion

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/create/dq-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dq-request.ts, packages/core/src/external/carequality/ihe-gateway-v2/inbound/xca/process/dr-request.ts, packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/constants.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/xmls/xcpd_match.xml, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/xmls/xcpd_match_multi_addr_name.xml, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dq-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/parse-file-from-string.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/process/xcpd-response.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/security/insert-key-info.ts, packages/core/src/external/cda/remove-b64.ts, packages/shared/src/common/xml-parser.ts, packages/utils/src/saml/saml-server.ts
Refs: #[2323](https://github.com/metriport/metriport-internal/issues/2323)
- better parsing 0s in the rest of the IHE gateway 
- Local
=> feat(cq): adding proper leading 0 parsing throughout ihe

packages/core/src/external/fhir/bundle/__tests__/qa.test.ts, packages/core/src/external/fhir/bundle/patient.ts, packages/core/src/external/fhir/bundle/qa.ts
none
Add more checks on get consolidated.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2215 Add more checks on get consolidated

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xcpd/create/iti55-envelope.ts
- fixing bug where we included identifier xml block when we had no identifier, which caused particle to error
- Local
=> fix(cq): not including identifier when empty

packages/core/src/fhir-deduplication/__tests__/deduplicate-fhir.test.ts, packages/core/src/fhir-deduplication/deduplicate-fhir.ts
Refs: #2569
- [context](https://metriport.slack.com/archives/C06CQC7GQG3/p1728510034765019)
- performer not removing duplicates within Observation resources
- Local
=> fix(cq): fix duplicate references for performers

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts, packages/core/src/mpi/normalize-patient.ts, packages/shared/src/domain/contact/email.ts, packages/shared/src/domain/contact/phone.ts
Refs: #[1766](https://github.com/metriport/metriport-internal/issues/1766)
- dont normalize contact info in json extraction phase
- fix email normalization to remove mailto: prefix
- Local
Check each PR.
=> fix(inbound): reordering contact validity and normalization

packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/command/medical/patient/consolidated-recreate.ts, packages/api/src/external/commonwell/document/document-query-sandbox.ts, packages/api/src/external/commonwell/document/document-query.ts, packages/api/src/external/commonwell/document/shared.ts, packages/api/src/external/fhir-converter/converter.ts, packages/api/src/shared/config.ts, packages/api/src/shared/sandbox/sandbox-seed-data-defaults.ts, packages/core/src/command/consolidated/consolidated-create.ts, packages/core/src/external/fhir/parse-bundle.ts, packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/api-service.ts, packages/lambdas/src/sqs-to-fhir.ts
DQ on sandbox prepares conversion bundle - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1728748530937169).
- Local (emulating sandbox)
- Staging
- N/A
- Sandbox
- Production
- none
```json
"cxsWithConsolidatedFromS3": {
"enabled": true
}
```
=> PATCH RELEASE DQ on sandbox prepares conversion bundle

packages/api/src/command/medical/patient/__tests__/validate.test.ts, packages/api/src/command/medical/patient/shared.ts
Ref: #2453
Ticket: https://github.com/metriport/metriport/issues/2453
N/A
Add validation for the `dob` field in the request payload of the Create/Update/Match Patient endpoints. The API will return an error when the `dob` is a future date.
Tested locally with unit tests.
_[How does the changes on this PR impact/interact with the existing environment (database, configs, secrets, FFs, api contracts, etc.)?_
This could be considered a breaking change because a new validation rule is added. I'm not sure if there's any API versioning approach that we can use.
_[This is the release plan for production]_
_[Add and remove items below accordingly]_
=> fix(api): add validation for patient dob

packages/api/src/external/aws/app-config.ts, packages/api/src/external/carequality/document/query-documents.ts, packages/api/src/external/commonwell/document/document-query.ts, packages/core/src/external/aws/app-config.ts
Ref: #1040
- run PD if last PD run was more than 24 hours ago (i.e. always refresh patient links if linking is stale)
- Local
- Staging
- Production
=> feat(pd): run pd on stale patient

packages/api/src/external/aws/app-config.ts, packages/api/src/external/carequality/document/query-documents.ts, packages/api/src/external/commonwell/document/document-query.ts, packages/core/src/external/aws/app-config.ts
Ticket: #1040
- running PD if the HIE data hasn't been present for 24hr or the last PD was more than 24 hours ago
- staging PR https://github.com/metriport/metriport/pull/2903
Check each PR.
=> PATCH stale patients

.github/workflows/_e2e-tests.yml, .github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
none
Add conversion bucket name to CICD to fix E2E test - [context](https://metriport.slack.com/archives/C04CXLSAF7V/p1729025444264769?thread_ts=1729020302.503249&cid=C04CXLSAF7V)
- Local
- none
- Staging
- Sandbox
- none
- Production
- `CONVERSION_RESULT_BUCKET_NAME_STAGING`
- `CONVERSION_RESULT_BUCKET_NAME_PRODUCTION`
=> 2215 Add conversion bucket name to CICD to fix E2E test

.github/workflows/_e2e-tests.yml, .github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
- Upstream: https://github.com/metriport/metriport/pull/2910
Add AWS_REGION to E2E test
- Local
- none
- Staging
- Sandbox
- none
- Production
=> 2215 Add AWS_REGION to E2E test

packages/core/src/external/carequality/ihe-gateway-v2/outbound/xca/process/dr-response.ts, packages/core/src/util/__tests__/urn.test.ts, packages/core/src/util/urn.ts
Ref: #1040
- sure-scripts started sending back doc unqiue ID in brackets as such `"DocumentUniqueId": "[X.XXX.XXXXXXXX.XXXX]",`
- Local
- Production
=> PATCH strip brackets

packages/api/src/__tests__/e2e/mapi/mapi.test.e2e.ts
Temporarily disable E2E tests - [context](https://metriport.slack.com/archives/C04CXLSAF7V/p1729104123253859?thread_ts=1729020302.503249&cid=C04CXLSAF7V)
none
=> 2215 Temporarily disable E2E tests

packages/core/src/external/aws/lambda-logic/__tests__/bundle-to-html-shared.test.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html-adhd.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html-no-dedup.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html-shared.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts, packages/core/src/fhir-to-cda/cda-templates/components/__tests__/make-diagnostic-report.ts
none
Accept non-array `DiagnosticReport.category`, for backwards compatibility - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1729285517248289?thread_ts=1729262903.053189&cid=C0616FCPAKZ)
- Local
- Staging
- none
- Sandbox
- none
- Production
=> PATCH RELEASE 799 Accept non-array DiagnosticReport.category

packages/utils/src/s3/file-history.ts, packages/utils/src/s3/remove-objects.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2215
none
- update remove-objects to work wit larger amount of files 
- add script to list objects' past and present existence in S3
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2215 Add/update S3 file utils

packages/api/src/command/medical/document/document-query.ts, packages/api/src/external/commonwell/document/document-query-sandbox.ts
Recreate consolidated after DQ on sandbox - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1729527314440949).
- Local
- none
- Staging
- none
- Sandbox
- Production
- none
=> PATCH RELEASE Recreate consolidated after DQ on sandbox

packages/core/src/external/carequality/ihe-gateway-v2/gateways.ts, packages/core/src/external/carequality/ihe-gateway-v2/outbound/__tests__/process-dr.test.ts, packages/core/src/external/carequality/ihe-gateway-v2/saml/saml-client.ts
- fixing schema error issue where we would get empty responses and then create MTOM bundles out of those and then throw a schema error downstream, when we should have just thrown an http error and retried. For ehex and athena
- fixing XDSRepositoryErrors where ntst and a few epic facilities each had very specific limits on the number of documents they accept being requested at a time (1,3,9)
- Local
Check each PR.
=> 1667 dr connectivity increase

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package.json
Publish NPM packages
Ref: https://github.com/metriport/metriport/issues/2453
- api@1.22.5
- @metriport/api-sdk@12.2.0
- @metriport/carequality-cert-runner@1.11.5
- @metriport/carequality-sdk@0.13.5
- @metriport/commonwell-cert-runner@1.19.5
- @metriport/commonwell-jwt-maker@1.17.5
- @metriport/commonwell-sdk@5.1.5
- @metriport/core@1.17.5
- @metriport/ihe-gateway-sdk@0.12.5
- infrastructure@1.15.5
- @metriport/react-native-sdk@1.14.5
- @metriport/shared@0.14.0
- utils@1.18.5
=> 2453 Publish NPM packages

package-lock.json, packages/api-sdk/package.json, packages/api-sdk/src/shared.ts, packages/api/package.json, packages/api/src/command/medical/patient/__tests__/validate.test.ts, packages/api/src/command/medical/patient/shared.ts, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/shared/src/common/date.ts, packages/utils/package.json
Ref. metriport/metriport#2453
- Upstream: https://github.com/metriport/metriport/pull/2919
Adjust error message on date validation to indicate it can't be in the future
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2453 Adjust error message on date validation not future

packages/fhir-converter/src/templates/cda/Sections/HealthConcerns.hbs, packages/fhir-converter/src/templates/cda/Utils/ObservationCategoryDisplayFromCode.hbs
refs. metriport/metriport-internal#2360
- Health Concerns section of CDAs is now parsed for observations, which often includes PHQ-9 and PHQ-2 results
- Local
=> feat(fhir-converter): mental health survey mapping

packages/api/src/command/medical/document/check-doc-queries.ts, packages/api/src/command/medical/document/document-conversion-status.ts, packages/api/src/command/medical/patient/consolidated-get.ts, packages/api/src/command/medical/patient/consolidated-recreate.ts, packages/api/src/external/commonwell/document/document-query-sandbox.ts, packages/api/src/routes/medical/internal-patient.ts
none
Get consolidated doesn't need Organization as param, so remove it.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Get consolidated doesn't need Org as param

packages/api-sdk/src/medical/client/__tests__/metriport.test.e2e.ts
none
API SDK E2E test to not filter doc by content.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 1040 API SDK E2E test to not filter doc by content

packages/api/src/@types/custom.d.ts, packages/api/src/routes/medical/document.ts, packages/api/src/routes/medical/facility-root.ts, packages/api/src/routes/medical/facility.ts, packages/api/src/routes/medical/index.ts, packages/api/src/routes/medical/organization.ts, packages/api/src/routes/medical/patient-root.ts, packages/api/src/routes/medical/patient.ts, packages/api/src/routes/middlewares/__tests__/auth.test.ts, packages/api/src/routes/middlewares/auth.ts, packages/api/src/routes/middlewares/facility-authorization.ts, packages/api/src/routes/middlewares/patient-authorization.ts, packages/api/src/routes/util.ts
none
Router-level authorization for patient and facility - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1729799240713459)
- Local
- Staging
- Sandbox
- none
- Production
=> 1040 Router-level authorization for patient and facility

packages/core/src/util/file-type.ts
refs. metriport/metriport-internal#2352
- Added a string detection to classify files as xml (`<?xml-`)
- Local
=> feat(api): added another xml-detection sequence

packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts
- Removing alert for missing patient coordinates, since we don't act on those anyway
- N/A
=> fix(api): removing pt coordinates alert

packages/api/src/command/medical/document/document-webhook.ts, packages/api/src/domain/webhook.ts
Ticket: https://github.com/metriport/metriport-internal/issues/858
- New WH status: `not_sent` for when we query with disabled wh
=> PATCH RELEASE 2024-10-31 WHs

packages/fhir-converter/src/templates/cda/Resources/Practitioner.hbs, packages/fhir-converter/src/templates/cda/Utils/GeneratePractitionerId.hbs, packages/utils/src/fhir-converter/fhir-resource-counts/develop-fhir-resource-count.json
refs. metriport/metriport-internal#2147
- Upstream: https://github.com/metriport/metriport/pull/2982
- Updated Practitioner ID generation to avoid multiple names being attached to the same resource
- Local
=> fix(fhir-converter): corrected practitioner id assignment

packages/api/src/__tests__/e2e/mapi/webhook/webhook-handler.ts, packages/api/src/__tests__/e2e/mapi/webhook/webhook-server.ts, packages/api/src/command/webhook/webhook.ts
Tickets:
- https://github.com/metriport/metriport-internal/issues/2402
- https://github.com/metriport/metriport-internal/issues/2266
- Upstream: https://github.com/metriport/metriport/pull/3004
- Fix E2E test so WH requests don't have the body converted to JSON by default, in order to pass signature verification
- Add `./tmp` folder to repository initialization - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1731619697192249?thread_ts=1731613784.116149&cid=C04GEQ1GH9D)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 2402 Fix E2E for new WH signature verification

packages/utils/src/bulk-insert-patients.ts, packages/utils/src/shared/get-cx-data.ts
none
- bulk-insert w/ better header parsing
- bulk-insert stores the ID mapping on ids.csv
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Bulk-insert w/ better header parsing

packages/api/src/domain/medical/patient-demographics.ts, packages/core/src/mpi/__tests__/normalize-address-lines.test.ts, packages/core/src/mpi/normalize-address.ts
Ticket: #metriport/metriport-internal#799
- Fixing the two places where trim() was called without making sure each item is a string 
- N/A
=> PATCH RELEASE 2024-11-18 Safe Trim

packages/fhir-converter/src/templates/cda/Sections/Results.hbs
refs. metriport/metriport-internal#2485
- Minor update to remove double quotes around the doctors notes
- Local
=> fix(fhir-converter): removing extra quotes

packages/api/src/command/mapping/cx.ts, packages/api/src/command/mapping/facility.ts, packages/api/src/command/mapping/patient.ts, packages/api/src/external/ehr/athenahealth/command/get-patient.ts, packages/api/src/external/ehr/athenahealth/command/get-patients-from-appointments.ts, packages/api/src/routes/internal.ts
Ref: #1040
- updating the default external ID to be practice specific -- this allows us to do facility per practice and gets rid of the constraint conflict of multiple `default / athenahealth` entries.
- REPLACEMENT FOR https://github.com/metriport/metriport/pull/3037
- Local
- Staging
- Production
=> feat(ehr): fixing conflicting external ids

packages/api/src/routes/medical/patient-root.ts, packages/api/src/routes/pagination.ts
Ref. metriport/metriport-internal#483
- Upstream: https://github.com/metriport/metriport/pull/3024
- Downstream: https://github.com/metriport/metriport-internal/pull/2496
Do not paginate by default - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1732824973461689?thread_ts=1731543357.768889&cid=C04DMKE9DME).
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 483 Do not paginate by default

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/react-native-sdk/package.json, packages/shared/package.json, packages/utils/package-lock.json, packages/utils/package.json
Ticket: https://github.com/metriport/metriport-internal/issues/483
- Upstream: https://github.com/metriport/metriport/pull/3043
- Downstream: https://github.com/metriport/metriport-internal/pull/2496
Ref: #000
- api@1.22.10
- @metriport/api-sdk@14.0.3
- @metriport/carequality-cert-runner@1.11.10
- @metriport/carequality-sdk@0.13.10
- @metriport/commonwell-cert-runner@1.19.10
- @metriport/commonwell-jwt-maker@1.17.10
- @metriport/commonwell-sdk@5.1.10
- @metriport/core@1.17.10
- @metriport/ihe-gateway-sdk@0.12.10
- infrastructure@1.15.10
- @metriport/react-native-sdk@1.14.10
- @metriport/shared@0.14.5
- utils@1.18.10
none
=> 483 Publish NPM packages

packages/core/src/external/fhir/consolidated/normalize.ts, packages/core/src/external/fhir/normalization/ normalize-fhir.ts, packages/core/src/external/fhir/normalization/resources/coverage.ts, packages/fhir-converter/src/templates/cda/References/Coverage/identifier.hbs, packages/fhir-converter/src/templates/cda/References/Coverage/subscriberId.hbs, packages/fhir-converter/src/templates/cda/Sections/Payers.hbs, packages/lambdas/src/sqs-to-converter.ts, packages/utils/src/fhir-converter/convert.ts
refs. metriport/metriport-internal#2502
- Adding `subscriberId` field to the `Coverage` resource, which is going to contain policy ID 
- Adding more `Coverage.identifiers` to catch more cases of policy ID being provided in certain areas of the CDAs
- Adding FHIR Normalization into the consolidated data generation flow
- Only `Coverage` resource normalization added for now
- Local
- Staging
=> feat(fhir-converter): improved coverage resource generation

packages/api/src/models/_default.ts
none
Fix mapping of created_at and updated_at on Sequelize - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1733167120266349?thread_ts=1733161624.294379&cid=C0616FCPAKZ)
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Fix mapping of created_at and updated_at on Sequelize

packages/infra/config/env-config.ts
- Upstream: https://github.com/metriport/metriport/pull/3063
Fix EHR config type - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1733356581051329?thread_ts=1733351424.333699&cid=C04FZ9859FZ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> 1040 Fix EHR config type without _ARN

packages/api/src/external/ehr/elation/shared.ts, packages/api/src/external/ehr/shared.ts
Ref: #1040
- adding string to error message on non-prod
- adjusting delay to be non-develop value of 0 seconds
=> feat(elation): logging secrets string on non-prod if bad format

packages/fhir-converter/src/templates/cda/Sections/Medication.hbs, packages/utils/src/fhir-converter/fhir-resource-counts/develop-fhir-resource-count.json
refs. metriport/metriport-internal#2530
- Removing unnecessary MedicationStatement generation if the Medication information is missing in the XML
- Updated the resource counts: 
- ⚠️ Looks like we forgot to update the counts at some point recently. The only real change in the counts based on the changes in this PR is the -6 MedicationStatements, which is expected
- Local
=> fix(fhir-converter): removing unnecessary med stmnt generation

packages/core/src/fhir-deduplication/__tests__/group-same-compositions.test.ts, packages/core/src/fhir-deduplication/deduplicate-fhir.ts, packages/core/src/fhir-deduplication/resources/__tests__/group-same-compositions.test.ts, packages/core/src/fhir-deduplication/resources/composition.ts, packages/core/src/fhir-deduplication/resources/coverage.ts, packages/utils/src/fhir-deduplication/dedup-files.ts
refs. metriport/metriport-internal#2502
- Upstream: https://github.com/metriport/metriport/pull/3101
- Added `Composition` dedup to account for the large files being split into X number of chunks, which results in X number of Compositions
- Local
- Staging
=> fix(core): added composition dedup

packages/core/src/fhir-deduplication/shared.ts
Ticket: #metriport/metriport-internal/issues/799
- We got an error where we tried to trim an attribute that unexpectedly had a number instead of a string in it
- Local
=> PATCH RELEASE Fetch Coding attributes

packages/core/src/fhir-deduplication/__tests__/combine-two-resources.test.ts, packages/core/src/fhir-deduplication/__tests__/examples/condition-examples.ts, packages/core/src/fhir-deduplication/__tests__/group-same-conditions.test.ts, packages/core/src/fhir-deduplication/resources/condition.ts, packages/core/src/fhir-deduplication/shared.ts
Ticket: #metriport/metriport-internal/issues/2525
- Downstream: https://github.com/metriport/metriport/pull/3090
- Reworked the FHIR `Condition` resource deduplication
- Added flag bits to indicate in which cases conditions should use the date for deduplication
- Added the ability to dedup from ICD-10/ICD-9/SNOMED/Name simultaneously, rather than by only one at a time
- Fixed and improved the tests
- Local
=> 2525 improved condition dedup

packages/core/src/fhir-deduplication/__tests__/group-same-diag-reports.test.ts, packages/core/src/fhir-deduplication/deduplicate-fhir.ts, packages/core/src/fhir-deduplication/resources/diagnostic-report.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2533
- Upstream: https://github.com/metriport/metriport/pull/3080
- DiagnosticReport dedup is now dependent on the practitioner that performed it, in addition to the datetime
- Updated unit tests
- Local
=> 2533 improved diagreport dedup

docs/medical-api/api-tools/postman.mdx
n/a
fix broken postman link on docs
n/a - just a link update
=> fix(docs): fix broken postman link

packages/infra/lib/api-stack.ts
Ref: #1040
- Adding CORS to sandbox documents bucket
- NOTE: Added CORS *manually* to the s3 bucket -- copied permissions from `metriport-medical-documents`
- Local
- Staging
- Sandbox
- Production
=> feat(s3): adding cors to sandbox bucket

packages/api/src/command/medical/document/document-webhook.ts, packages/api/src/external/fhir/shared/hydrate-bundle.ts, packages/core/src/external/fhir/document/get-documents.ts, packages/utils/src/fhir/validate/validate-all-bundles.ts
- Fixing bug which caused all documents to be sent on WH for each new DQ that finds no new documents
- Fixing log that printed `[object Object]` on WH settings
- Adding more informative error feedback on missing patient references for data contributions
- Fixing a bug for a local script, where a nanoid containing `-` or `_` would cause the flow to break
- Local
- Production
=> PATCH RELEASE - DQ WH Payload + other misc fixes

packages/core/src/domain/conversion/bundle-modifications/__tests__/post-process-bundle.test.ts, packages/core/src/domain/conversion/bundle-modifications/modifications.ts, packages/core/src/domain/conversion/bundle-modifications/post-process.ts
refs. https://github.com/metriport/metriport-internal/issues/2574
- Once an XML is converted to FHIR, we want to add the document extension. With this extension, the `postProcess` function will make sure each resource ID is replaced with another one - eliminating the possibility of having two resources with the same ID in the collection bundle
_[ Patch PRs ]_:
- ⚠️ [x] Run E2E tests locally
=> PATCH RELEASE Fixing Duplicate IDs on Consolidated Bundle

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/shared/package.json, packages/utils/package.json
Ref: #2998 
- api@1.22.15
- @metriport/api-sdk@14.4.0
- @metriport/carequality-cert-runner@1.11.12
- @metriport/carequality-sdk@0.13.12
- @metriport/commonwell-cert-runner@1.19.12
- @metriport/commonwell-jwt-maker@1.17.12
- @metriport/commonwell-sdk@5.1.12
- @metriport/core@1.17.12
- @metriport/ihe-gateway-sdk@0.12.12
- infrastructure@1.15.12
- @metriport/shared@0.14.7
- utils@1.18.12
- Ticket #2998 
- Upstream: #3137 - Package bumps for release PR
None
=> #2998 npm package updates

packages/api/src/external/carequality/document/query-documents.ts, packages/api/src/external/commonwell/document/document-query.ts
Ref: #1040
- quick fix to refresh the patient right before deciding to schedule
N/A
=> PATCH RELEASE 1040 Refresh patient before scheduling

packages/api/src/external/ehr/athenahealth/command/sync-patient.ts, packages/api/src/external/ehr/athenahealth/shared.ts, packages/core/src/external/athenahealth/index.ts, packages/shared/src/interface/external/athenahealth/patient.ts
Ref: #1040
- allow postalCode to be optional in initial zod schema
- filter addresses along missing zips and only home addresses (new zod schema)
- Local
- Staging
- Sandbox
- Production
=> feat(ehr): use home addresses from athena + check zip separate

packages/api/src/sequelize/migrations/2025-01-15_00-alter-jwt_token-increase-token-length_3.ts
Ref: #1040
- Athena breaking change https://docs.athenahealth.com/api/resources/25-03-release-introducing-json-web-tokens-for-apis recommends supporting tokens up to 8kb
=> feat(ehr): bump token size to support 8kb

packages/core/src/fhir-deduplication/resources/related-person.ts
Ticket: #metriport/metriport-internal/issues/799
- For RelatedPerson dedup, casting name attributes to a string before trying to trim them
_[Patch PRs:]_
- :warning: [x] Run E2E tests locally
=> PATCH RELEASE FHIR Deduplication

packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory-raw-sql.ts, packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts
Ref. metriport/metriport-internal#2553
none
CQ dir rebuild checks for existing entries - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1737321495401769?thread_ts=1737315011.220249&cid=C04T256DQPQ).
- Local
- Staging
- Sandbox
- none
- Production
=> 2553 CQ dir rebuild checks for existing entries

packages/core/src/command/ai-brief/create.ts
refs. metriportmetriport-internal#799
- Updated the target region for Bedrock to `us-west-2`, which is said to have the highest input token limit - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1737378694508219)
- Local
- Production
=> fix(core): changed target region for bedrock

packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory-raw-sql.ts, packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts
Ref. metriport/metriport-internal#2553
- upstream: https://github.com/metriport/metriport/pull/3177
Lighter CQ dir rebuild logic, no PK and only IDs
- Local
- Staging
- Sandbox
- none
- Production
=> 2553 Lighter CQ dir rebuild logic, no PK and only IDs

packages/core/src/command/consolidated/consolidated-create.ts
refs. metriportmetriport-internal#799
- Using the deduped bundle as input for AI Brief generation
- Local
- Production
=> fix(core): updated input bundle for ai brief gen

packages/infra/lib/api-stack.ts, packages/lambdas/src/fhir-to-medical-record.ts
Ref: #1040
- delete temp html / pdf files saved to generate PDFs
- bump fhir to MR lambda memory
- Local
- Staging
- Sandbox
- Production
=> feat(bundle): bumping lambda size + deleting tmp files

packages/lambdas/src/fhir-to-medical-record.ts
Ref: #1040
- remove storing html locally when generating a pdf as it doesn't appear to have any purpose
- Local
- Staging
- Sandbox
- Production
=> feat(bundle): remove storing html locally

packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/fhir-converter-connector.ts
refs. metriportmetriport-internal#2563
- Added AppConfig env vars and permissions to FHIR Converter lambda 
- Staging
- Production
=> fix(core): adding permissions for converter lambda to access app config

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/shared/package.json, packages/utils/package.json
Ref: #000
- api@1.22.19
- @metriport/api-sdk@14.7.0
- @metriport/carequality-cert-runner@1.13.1
- @metriport/carequality-sdk@1.1.1
- @metriport/commonwell-cert-runner@1.21.1
- @metriport/commonwell-jwt-maker@1.19.1
- @metriport/commonwell-sdk@5.3.1
- @metriport/core@1.19.1
- @metriport/ihe-gateway-sdk@0.14.1
- infrastructure@1.17.1
- @metriport/shared@0.17.0
- utils@1.20.1
=> chore(release): publish new versions of packages needed for release

packages/core/src/external/fhir/normalization/resources/observation.ts, packages/core/src/fhir-deduplication/__tests__/examples/observation-examples.ts
refs. metriportmetriport-internal#2551
- Adding more unit conversion mappings
- Local
- Production
=> PATCH RELEASE more unit conversion mappings

packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/schema.ts, packages/core/src/external/carequality/ihe-gateway-v2/inbound/xcpd/process/xcpd-request.ts, packages/terminology/src/operations/codeLookup.ts
refs. metriportmetriport-internal#799
- Adjusting the inbound XCPD schema / Added a Sentry alert for parsing
- Adjusting how the resulting object is handled
- Small tweak to remove a log from the Term Server
_[Patch PRs:]_
- Local
- Production
=> PATCH RELEASE Fixing inbound XCPD schema

package-lock.json, package.json
- Related: https://github.com/metriport/metriport-internal/pull/2569
Currently, when someone clones the repo and runs `install-deps` it doesn't initialize Husky/Githooks. This results in commits being sent without the respective goodies/controls.
This fix repo initialization so it installs husky/hooks when first cloned.
Also
- only installs Husky on local/dev (not on CICD)
- fixes `rimraf` to a version compatible with Node 18.
- Local
- Staging
- Staging EHR App ([Athena Testing Notion](https://www.notion.so/metriport/EHR-Integrations-12fb51bb90408021850cc595b060efc7?pvs=4#12fb51bb90408020a9affff80dc98fac))
- none
- Sandbox
- none
- Production
- none
=> 1040 Fix repo init so it installs husky/hooks

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/shared/package.json, packages/utils/package.json
Ref: https://github.com/metriport/metriport-internal/issues/1040
- Upstream: https://github.com/metriport/metriport/pull/3223
chore(release): publish
- api@1.24.0
- @metriport/api-sdk@14.10.0
- @metriport/carequality-cert-runner@1.15.0
- @metriport/carequality-sdk@1.3.0
- @metriport/commonwell-cert-runner@1.23.0
- @metriport/commonwell-jwt-maker@1.21.0
- @metriport/commonwell-sdk@5.5.0
- @metriport/core@1.21.0
- @metriport/ihe-gateway-sdk@0.16.0
- infrastructure@1.19.0
- @metriport/shared@0.19.0
- utils@1.22.0
none
=> 1040 Publish non-alpha packages for Binary type on filters

docs/_snippets/list-network-entries-response.mdx, packages/api/src/domain/medical/network-entry.ts, packages/api/src/routes/medical/dtos/network-entry-dto.ts
Ticket: #1772
Needs to ship with https://github.com/metriport/metriport/pull/3233
- Local
- Staging
- Sandbox
See https://github.com/metriport/metriport/pull/3222
=> fix(api): use 2 letter state code incl. puerto rico

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/shared/package.json, packages/utils/package.json
- Bump released package off the alpha version
None
=> PATCH 1772 - Update packages to release version

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx, docs/medical-api/fhir/overview.mdx, docs/medical-api/more-info/ai-brief.mdx
- Upstream: https://github.com/metriport/metriport/pull/3226
Add `Binary` resource type to the list of accepted resource types on Start Consolidated Data Query docs - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1738282640546209?thread_ts=1738181709.284669&cid=C0616FCPAKZ).
...
...
- Local
- Production
=> PATCH RELEASE Update docs with Binary resource on consolidated

packages/core/src/command/consolidated/consolidated-shared.ts, packages/core/src/command/consolidated/get-snapshot-local.ts, packages/core/src/domain/consolidated/filename.ts, packages/core/src/external/fhir/codeable-concept.ts, packages/core/src/external/fhir/normalization/__tests__/normalize-coding.test.ts, packages/core/src/external/fhir/normalization/coding.ts, packages/core/src/external/fhir/normalization/normalize-fhir.ts, packages/core/src/external/fhir/shared/__tests__/is-useless-display.test.ts, packages/core/src/external/fhir/shared/__tests__/is-valid-coding.test.ts, packages/core/src/fhir-deduplication/shared.ts, packages/core/src/util/constants.ts, packages/utils/src/fhir-normalization/normalize-files-local.ts
refs. metriportmetriport-internal#2625
- Removing unknown / useless Codings wherever possible (leaving them in, if they're the only element in the coding array)
- Leaving Codings from known systems if they have a non-UNK code, even if missing display
- Leaving Codings from unknown systems as long as they have a non-Unknown display
- Sorting remaining Codings based on their relevance
- Replacing the CodeableConcept.text field with an informative display 
- Local
- Production
=> feat(core): added concept and coding normalization

packages/core/src/command/ai-brief/create.ts, packages/core/src/command/consolidated/consolidated-create.ts, packages/core/src/domain/ai-brief/generate.ts, packages/core/src/domain/ai-brief/modify-resources.ts, packages/utils/src/customer-requests/medical-records-local-with-brief.ts
refs. metriportmetriport-internal#2526
- Small fix for DiagReport processing
- Adding retries for AI brief gen
- Local
- Staging
- Production
=> fix(core): small fixes and improvements

docs/medical-api/api-reference/fhir/consolidated-data-query-post.mdx, docs/medical-api/handling-data/medical-record-summary.mdx, docs/medical-api/handling-data/webhooks.mdx, packages/api/src/command/medical/patient/consolidated-get.ts
none
Store `conversionType` on WH table, and add info to doc about empty MR WH when no content - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1738370386312109?thread_ts=1738354495.517799&cid=C0616FCPAKZ)
No change (need to click on webhook message with a downloadable URL to get to second img and see the note)
updated
updated
- Local
- Staging
- Sandbox
- none
- Production
=> 1040 Store `conversionType` on WH table

package-lock.json, packages/api-sdk/package.json, packages/api/package.json, packages/carequality-cert-runner/package.json, packages/carequality-sdk/package.json, packages/commonwell-cert-runner/package.json, packages/commonwell-jwt-maker/package.json, packages/commonwell-sdk/package.json, packages/core/package.json, packages/ihe-gateway-sdk/package.json, packages/infra/package.json, packages/shared/package.json, packages/utils/package.json
- Upstream: https://github.com/metriport/metriport/pull/3199
- api@1.24.2
- @metriport/api-sdk@14.11.1
- @metriport/carequality-cert-runner@1.15.2
- @metriport/carequality-sdk@1.3.2
- @metriport/commonwell-cert-runner@1.23.2
- @metriport/commonwell-jwt-maker@1.21.2
- @metriport/commonwell-sdk@5.5.2
- @metriport/core@1.21.2
- @metriport/ihe-gateway-sdk@0.16.2
- infrastructure@1.19.2
- @metriport/shared@0.19.2
- utils@1.22.2
none
=> 1040 Publish commonwell-sdk

packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory-raw-sql.ts, packages/api/src/sequelize/migrations/2025-02-01_00_alter-cq-directory-entry-new_recreate-search-criteria.ts
- Fixes an issue where the generated 'search_criteria' column used for FTS has its definition wiped when rebuilding the CQ directory.
✅ Test this 👇  
(1) Check `cq_directory_entry_new` table has incorrect 'search_criteria' generation definition. 
(2) Run migrations 
(3) Ensure generation definition is correct. 
(4) Run CQ directory rebuild 
(5) Ensure generation definition has not returned to NULL
[ ] Test this 👇 
(3) Ensure generation definition is correct. 
(4) Run CQ directory rebuild 
(5) Ensure generation definition has not returned to NULL
=> PATCH - fix(api): ensure generated column for CQ search_criteria is kept when rebuilding the CQ directory

packages/api/src/sequelize/migrations/2025-02-01_01_recreate-hie-directory-view.ts
- Fixes an issue zip and oid columns are not properly loading in production
=> PATCH 1772 - fix(api): fix hie directory view in migrations

packages/api/src/domain/medical/network-entry.ts, packages/api/src/routes/medical/dtos/network-entry-dto.ts
- Fixes an issue where null or invalid state codes would break the network-entries table
=> fix(api): fix invalid us state code

packages/core/src/external/aws/app-config.ts, packages/core/src/external/aws/lambda-logic/bundle-to-html.ts, packages/lambdas/src/fhir-to-medical-record.ts, packages/lambdas/src/fhir-to-medical-record2.ts
- Adding FF to turn off adding Metriport logo to MR summary header
_[Patch PRs:]_
- :warning: [ ] Run E2E tests locally
- Local
- Production
=> PATCH RELEASE: FF for MR Summary without logo

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
- Added whitespaces to keep the expected format
- Local
- Staging
=> PATCH RELEASE: upd whitespace format for mr logo

packages/core/src/external/term-server/index.ts, packages/terminology/README.md, packages/terminology/src/app.ts
refs. metriport/metriport-internal#2599
- Adding some API info for the Term Server
- Removing the `terminology/` from the routes 
- Local
- Staging
=> fix(terminology): updated readme with existing route and supported systems

packages/core/src/domain/conversion/__tests__/cleanup.test.ts, packages/core/src/domain/conversion/__tests__/example.xml, packages/core/src/domain/conversion/cleanup.ts, packages/lambdas/src/cda-to-visualization.ts, packages/lambdas/src/sqs-to-converter.ts, packages/utils/src/fhir-converter/convert.ts
refs. metriport/metriport-internal#2638
- Cleaning up translation.code elements in XMLs during parsing, prior to conversion
- Cleaning up the ampersands 
- Added the cleanup to the visualization lambda
- Updating the fhir integration test to also cleanup the payload
- Local
- Staging
- Production
=> fix(core): xml cleanup escape chars in code

package.json
none
Make build failures more obvious
this
...and
instead of this
...
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 1040 Make build failures more obvious

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
Ticket: metriport/metriport-internal#799
- Removing the Reports section from MR Summaries without logo 
_[Patch PRs:]_
- Local
- Production
=> PATCH RELEASE  remove report from mr

packages/fhir-converter/src/templates/cda/Resources/MedicationRequest.hbs, packages/fhir-converter/src/templates/cda/Sections/Medication.hbs
refs. metriport/metriport-internal#2128
- Added a backup date mapping for the MedicationRequest from its parent XML element
- Local
=> feat(fhir-converter): more thorough date mapping for medication request

packages/infra/config/env-config.ts, packages/infra/lib/lambdas-nested-stack.ts
refs. metriport/metriport-internal#2664
- Upstream: https://github.com/metriport/metriport-internal/pull/2665
- Adding permissions to the FhirToBundle lambda to invoke Bedrock models in an array of active regions
- Supporting docs:
- https://aws.amazon.com/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/?utm_source=chatgpt.com#:~:text=your%20CloudWatch%20dashboard.-,Identity%20and%20Access%20Management,-AWS%20Identity%20and
- https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-prereq.html  
- Staging
- Production
=> fix(lambda): adding bedrock permissions for multiple regions

packages/lambdas/src/patient-import-create.ts, packages/lambdas/src/patient-import-parse.ts, packages/lambdas/src/patient-import-query.ts, packages/lambdas/src/shared/patient-import.ts
Don't require optional params on bulk import parse lambda.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 2330 Don't require optional params on bulk import parse lambda

packages/api/src/external/commonwell/patient.ts
- Upstream: nope
- Downstream: nope
- Change the logic thats causing us to query cw unnecessarily  
- Local
- Production
Check each PR.
=> fix(api): PATCH  cw update patient

packages/fhir-converter/src/lib/workers/worker.js, packages/fhir-converter/src/routes.js
none
Log when get and start processing file - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1739741263242919?thread_ts=1739725444.196009&cid=C04T256DQPQ)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none
=> PATCH RELEASE Log when get and start processing file

packages/core/src/domain/document/upload.ts, packages/core/src/external/cda/process-attachments.ts, packages/utils/src/fhir-converter/convert.ts, packages/utils/src/fhir-converter/integration-test.ts
refs. metriport/metriport-internal#2683
- Added mimetype detection for b64 attachments from xmls 
- Local
- Production
=> feat(core): b64 attachments from xmls undergo mimetype detection

packages/fhir-converter/src/templates/cda/Sections/Encounters.hbs, packages/utils/src/consolidated/create-consolidate-local.ts
refs. metriport/metriport-internal#2357
- Encounter.reasonCode mapping improvements. Previously, we thought that the array of reasonCode was generated from multiple different previous encounters. That assumption was wrong. The `Reasons for Visit` section might contain multiple entries, but they are not in conflict to each other. 
- Some examples:
- Cough
- Runny nose
- Difficulty breathing
- Added a local script to generate a consolidated bundle to allow better local testing for FHIR converter changes / dashboard changes
- Local
- I printed the `reasonCode` from each file into one document, and looked over most of it to make sure nothing crazy is being inserted there
=> fix(fhir-converter): improved reason code mapping for encounters

packages/core/src/domain/conversion/upload-conversion-steps.ts, packages/core/src/external/cda/partition-payload.ts
refs. metriport/metriport-internal#2343
- Smaller chunks for large CDA partitioning - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1739823991376319?thread_ts=1739720279.850789&cid=C04DMKE9DME)
- Fixing the issue where the parts indices were incorrectly implemented, resulting in chunks overwriting one another on s3
- Local
- Production
=> fix(core): smaller partitioning chunks

packages/core/src/domain/conversion/__tests__/cleanup.test.ts, packages/core/src/domain/conversion/cleanup.ts
refs. metriport/metriport-internal#2107
- Replacing some instances of the `<` char to avoid CDA>FHIR conversion failures
- Local
- Production
=> feat(core): replace less than with html code 

packages/core/src/external/cda/process-attachments.ts, packages/core/src/external/cda/remove-b64.ts, packages/infra/lib/api-stack/fhir-converter-connector.ts, packages/infra/lib/api-stack/fhir-converter-service.ts, packages/infra/lib/patient-import-nested-stack.ts, packages/lambdas/src/sqs-to-converter.ts
none
(each change has its own commit to help reviewing)
- fewer lambdas than ECS cores - [context](https://metriport.slack.com/archives/C04DBBJSKGB/p1739719790818809?thread_ts=1739665734.719219&cid=C04DBBJSKGB)
- deal w/ attachments (store on FHIR server and S3) while waiting for (CDA to) FHIR Conversion
- scale out FHIR Converter - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1739721142186769?thread_ts=1739646397.447249&cid=C04T256DQPQ)
- the one linked was 4x b/c of the situation we were were in, this PR 2x so we can process bursts and imports
-  update bulk pt import lambdas's max age thresholds - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1739715092014349?thread_ts=1739666724.121709&cid= …
=> 1040 Fine tune FHIR converter

docs/medical-api/api-reference/document/get-document.mdx, docs/medical-api/handling-data/webhooks.mdx
none
Updates to docs:
- Add URL expiration time
- Fix link on `Get Document URL`
New expiration info
Bug...
...fix
- Local
- Staging
- none
- Sandbox
- none
- Production
=> 1040 Add URL expiration time to docs

packages/core/src/external/cda/process-attachments.ts, packages/core/src/external/cda/remove-b64.ts, packages/infra/lib/api-stack/fhir-converter-connector.ts, packages/infra/lib/api-stack/fhir-converter-service.ts, packages/infra/lib/patient-import-nested-stack.ts, packages/lambdas/src/sqs-to-converter.ts
- Upstream: https://github.com/metriport/metriport/pull/3337
This reintroduces https://github.com/metriport/metriport/pull/3337, reverted on https://github.com/metriport/metriport/pull/3368
- Local
- Staging
- Sandbox
- none
- Production
=> Reintroduce "Fine tune FHIR converter"

docs/medical-api/api-reference/document/get-document.mdx, docs/medical-api/handling-data/webhooks.mdx
- Upstream: https://github.com/metriport/metriport/pull/3194
This reintroduces https://github.com/metriport/metriport/pull/3194, which was rolled-back as part of the patch https://github.com/metriport/metriport/pull/3368.
See https://github.com/metriport/metriport/pull/3194
=> Reintroduce "Add URL expiration time to docs"

packages/infra/lib/api-stack.ts, packages/infra/lib/api-stack/fhir-converter-connector.ts, packages/infra/lib/lambdas-nested-stack.ts
refs. metriport/metriport-internal#2600
- Read access to secrets for the lambdas that need it
- Staging
- Production
=> fix(infra): adding secret read access to lambdas

packages/infra/lib/api-stack/fhir-converter-connector.ts, packages/infra/lib/lambdas-nested-stack.ts
refs. metriport/metriport-internal#2600
- Placing Config read permission prior to actually accessing it
- Staging
- Production
=> fix(infra): Posthog secrets permitted on lambdas

packages/core/src/external/athenahealth/index.ts
Ref: #1040
- hooking into message not status code as handler converts to metriport error
- Local
- Staging
- Sandbox
- Production
=> feat(ehr): patch athena no sub

packages/infra/lib/api-stack/api-service.ts
- Temporarily giving access to the API to call Bedrock methods
- Production
=> PATCH RELEASE API access to Bedrock

packages/api-sdk/src/medical/models/network-entry.ts, packages/api/src/domain/medical/network-entry.ts, packages/api/src/external/hie/command/get-hie-directory-entries.ts, packages/api/src/external/hie/domain/hie-directory-entry.ts, packages/api/src/external/hie/models/hie-directory-view.ts, packages/api/src/routes/medical/dtos/network-entry-dto.ts
refs. metriport/metriport-internal#2790
- Downstream: https://github.com/metriport/metriport-internal/pull/2793
Exposes the 'network' property from the hie_directory_view to our 
Local
✅ Check endpoint w/ postman
Staging
- Check endpoint w/ postman
Sandbox
- Check endpoint w/ postman
Prod
- Check endpoint w/ postman
=> feat(api): surface network type in network entries api response

packages/infra/lib/hl7-notification-stack/index.ts, packages/infra/lib/hl7-notification-stack/mllp.ts, packages/infra/lib/hl7-notification-stack/vpn.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2754
- Upstream: https://github.com/metriport/metriport/pull/3492
This PR pulls a secret containing a pair of preshared keys per partner from secrets manager to establish VPN tunnels.
I've also added some new CFN outputs to simplify the release process for myself.
- Local
- Staging
- Production
=> fix(infra): pull psks from secrets manager

packages/api/src/app.ts, packages/api/src/command/medical/document/document-query.ts, packages/api/src/command/webhook/webhook.ts, packages/api/src/domain/medical/get-patient-limit.ts, packages/api/src/external/aws/app-config.ts, packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts, packages/api/src/external/carequality/document/query-documents.ts, packages/api/src/external/carequality/gateway/index.ts, packages/api/src/external/carequality/patient.ts, packages/api/src/external/carequality/shared.ts, packages/api/src/external/commonwell/__tests__/patient.test.ts, packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts, packages/api/src/external/commonwell/document/document-query.ts, packages/api/src/external/commonwell/link/create.ts, packages/api/src/external/commonwell/link/get.ts, packages/api/src/external/commonwell/link/reset.ts, packages/api/src/external/commonwell/organization.ts, packages/api/src/external/commonwell/patient.ts, packages/api/src/external/commonwell/shared.ts, packages/api/src/external/feature-flags.ts, packages/api/src/external/fhir-to-cda-converter/connector-direct.ts, packages/api/src/external/fhir-to-cda-converter/connector-lambda.ts, packages/api/src/routes/internal/index.ts, packages/api/src/routes/internal/medical/patient.ts, packages/core/src/command/feature-flags/domain-ffs.ts
Ticket: https://github.com/metriport/metriport-internal/issues/2840
- Upstream: https://github.com/metriport/metriport/pull/3550
- Downstream: https://github.com/metriport/metriport/pull/3579
Move FF from api to core.
- Local
- Staging
- Sandbox
- none
- Production
- none
=> 2840 Move FF from api to core

package-lock.json, packages/core/src/util/__tests__/base64-scrambler.test.ts, packages/core/src/util/base64-scrambler.ts, packages/core/src/util/config.ts, packages/infra/config/env-config.ts, packages/infra/config/example.ts, packages/infra/config/hl7-notification-config.ts, packages/infra/lib/hl7-notification-stack/mllp.ts, packages/infra/lib/secrets-stack.ts, packages/mllp-server/.env.example, packages/mllp-server/package.json, packages/mllp-server/src/app.ts, packages/mllp-server/src/utils.ts
Ticket: metriport/metriport-internal#2757
- Upstream: Security utils in core -> https://github.com/metriport/metriport/pull/3596
- Upstream: Configs changes -> https://github.com/metriport/metriport-internal/pull/2852
This PR writes incoming HL7 messages out to S3 using the `cx_id/patient_id/ISO8601_MSGTYPE_MSGCODE.hl7` format.
Have an end to end setup on my machine that passes ADT A01 messages to this server, and verified that the messages were being written to the staging s3 bucket.
=> 2757 write request logs (hl7 messages) to s3

packages/terminology/package-lock.json
- Upstream: https://github.com/metriport/metriport/pull/3706
- [context](https://github.com/metriport/metriport/security/dependabot?q=is%3Aopen+package%3Aaxios+manifest%3Apackages%2Fterminology%2Fpackage-lock.json+has%3Apatch)
none
=> ENG-196 Update terminology's package-lock.json

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
https://github.com/metriport/metriport-internal/issues/2620
- Upstream: https://github.com/metriport/metriport/pull/3823
Fix typo on CICD def.
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> 2620 Fix typo on CICD def

packages/core/src/command/consolidated/search/fhir-resource/ingest-lexical.ts, packages/infra/lib/lambdas-nested-stack.ts
- Upstream: https://github.com/metriport/metriport/pull/3938
- Downstream: 
Add env var to medical bucket - [context](https://metriport.slack.com/archives/C04T5Q9JHFX/p1748733257286879)
- Local
- none
- Staging
- Sandbox
- none
- Production
- none
=> ENG-392 Add env var to medical bucket

packages/api/src/sequelize/migrations/2025-06-09_00_add-patient-settings-patient-id-index.ts
Issues:
- https://linear.app/metriport/issue/ENG-395
None
There was no index on the patient_id column, and we're not querying by cx_id so the (cx_id, patient_id) compound index was not getting hit so the full scans that were happening were absurdly slow (5m+) when querying /internal/patient/hl7v2-subscribers/.
`npx ts-node src/sequelize/cli.ts up` runs my migration successfully and i see the index in my db.
=> feat(api): add patient_id index to patient_settings table

packages/infra/lib/quest/scheduled-lambda.ts
metriport/metriport-internal#3045
Issues:
- https://linear.app/metriport/issue/ENG-864
- Upstream: None
- Downstream: None
Fixes the cron expression for scheduled Lambdas. Apparently you cannot specify both `day` and `weekDay` - good reminder to always run `cdk diff` for infra changes :(
```
Error: Cannot supply both 'day' and 'weekDay', use at most one
at Function.cron (/home/runner/work/***/***/***/node_modules/aws-cdk-lib/aws-events/lib/schedule.js:1:1513)
at createUploadRosterConfig (/home/runner/work/***/***/***/packages/infra/lib/quest/scheduled-lambda.ts:61:16)
at createUploadRosterScheduledLambda (/home/runner/work/***/***/***/packages/infra/lib/quest/scheduled-lambda.ts:79:37)
```
- Local
=> ENG-864: fix(infra) - updates cron expression in scheduled Lambda

packages/api/src/command/hie/unlink-patient-from-organization.ts, packages/commonwell-sdk/src/models/contact.ts
- https://linear.app/metriport/issue/ENG-934/update-low-prio-flows-to-use-cw-v2
- If `cq_patient_data` has no entry for the patient, we fail to unlink even for CW because we use getCqPatientDataOrFail under the hood. This PR fixes that
- Small typo fix
- Small fix for CW SDK - [discussed here](https://metriport.slack.com/archives/C04T256DQPQ/p1756936998496759?thread_ts=1753196698.493009&cid=C04T256DQPQ) 
- Local
=> ENG-934 Minor fix for unlink endpoint

packages/infra/lib/hl7-notification-stack/index.ts, packages/infra/lib/hl7-notification-stack/mllp.ts
None
This PR updates the existing ECR repo with a removal policy so that booting down the stack also wipes the ECR repo. This is fine as cdk should deploy a new ECR repo and part of the process is running a script to publish an image to the repo.
Here's the diff output against production - ignore some of the noise, its due to running diff from dev env as opposed to cloud env.
```
Resources
[~] AWS::ECR::Repository MllpServerRepo MllpServerRepo71CD67DD
├─ [+] EmptyOnDelete
│   └─ true
├─ [~] DeletionPolicy
│   ├─ [-] Retain
│   └─ [+] Delete
└─ [~] UpdateReplacePolicy
├─ [-] Retain
└─ [+] Delete
[~] AWS::CloudFormation::Stack NestedMllpStack.NestedStack/NestedMllpStack.NestedStackResource NestedMllpStack
└─ [~] TemplateURL
└─ [~] .Fn::Join:
└─ @@ -5,6 +5,6 @@
[ ]     {
[ ]       "Ref": …
```
=> feat(infra): update removal policy of mllp server repo to make booting stack up / down easy
