api/app/src/routes/settings.ts

Ticket: #43
- Upstream: https://github.com/metriport/metriport-internal/pull/148
- Downstream: https://github.com/metriport/metriport/pull/10
Removes SettingsDTO unused attribute, was left there for backwards compatibility during the release of the upstream dependency.

Removes old attribute from SettingsDTO

---

api/app/src/command/connected-user/get-connected-user.ts
api/app/src/command/usage/report-usage.ts
api/app/src/command/webhook/webhook.ts
api/app/src/routes/middlewares/usage.ts
api/app/src/sequelize/migrations/20221223020000-alter-connected_user-add-index.ts
api/app/src/shared/types.ts

Ticket: #43
- Upstream: https://github.com/metriport/metriport/pull/9
Report usage on webhook requests

Report usage on webhook requests

---

api/app/src/command/webhook/webhook.ts
api/app/src/mappings/garmin/activity.ts
api/app/src/mappings/garmin/body-composition.ts
api/app/src/mappings/garmin/index.ts
api/app/src/mappings/garmin/sleep.ts
api/app/src/routes/webhook/garmin.ts
api/app/src/shared/date.ts
api/app/src/shared/util.ts
docs/more-info/webhooks.mdx
pkgs/packages/api/src/models/body.ts

- Upstream: https://github.com/metriport/metriport/pull/14
- Downstream: https://github.com/metriport/metriport/pull/18
- Garmin `BodyComposition` mapping.
- Fix issue with sending internal `userId` on the webhook payload instead of `cxUserId`
- Minor typo fix on docs
- anytime

Garmin BodyComposition mapping

---

api/app/src/default-error-handler.ts
api/app/src/mappings/garmin/body-composition.ts
api/app/src/mappings/garmin/index.ts
api/app/src/mappings/garmin/sleep.ts

- Upstream: https://github.com/metriport/metriport/pull/17
- Downstream: https://github.com/metriport/metriport/pull/19
Each Garmin schema determines whether a given property is optional/nullable or not, and not the generic Garmin type.
- anytime

Make garmin schemas optional/null, not types

---

api/app/src/command/webhook/webhook.ts

Ticket: #118
Currently, when there's no Webhook (WH) config on settings, we just skip processing the request. But the logic to re-send/retry WH request on the settings page only processes failed requests - `processing` is supposed to be a temporary state while they are actually being sent to the partner/account.
- anytime

Mark WH request as failed when no WH config

---

infra/lib/api-stack.ts
pkgs/packages/commonwell-jwt-maker/README.md
pkgs/packages/commonwell-jwt-maker/src/index.ts
pkgs/packages/commonwell-sdk/src/common/make-jwt.ts

Ticket: metriport/metriport-internal#274
- Upstream: N/A
- Downstream: https://github.com/metriport/metriport-internal/pull/278
Add support for client keys for mobile clients that will be sending data to the Metriport API.
Updating docs is still a TODO here.

Add support for client keys #274

---

connect-widget/app/src/shared/components/WidgetContainer.tsx

Ref  metriport/metriport-internal#300
- Upstream: https://github.com/metriport/metriport/pull/65
Made widget reset scroll to top for providers page after click-on agreement
Include in update 1.1.0

fix(widget): reset scroll to top after click-on agreement

---

.github/workflows/_reusable_build.yml
.github/workflows/_reusable_deploy.yml
.gitignore
README.md
api/app/package.json
connect-widget/app/package.json
infra/package.json
infra/test/infrastructure.test.ts
package-lock.json
package.json

Ref https://github.com/metriport/metriport-internal/issues/143
- Upstream: https://github.com/metriport/metriport/pull/60
Add NPM workspaces.
With this PR, we can do things like:
- `$metriport> npm install` to run `npm install` on all packages automatically
- likewise for other commands, like `lint` as added on `package.json`
- including commands that are optional on the packages (with `--if-present`)
- to run a command on a package from the root folder, one can issue `npm run <cmd> -w <package-name>`
- anytime

Add NPM workspaces

---

.husky/pre-commit
README.md
api/app/package.json
infra/test/infrastructure.test.ts
package-lock.json
package.json

Ref https://github.com/metriport/metriport-internal/issues/143
- Upstream: https://github.com/metriport/metriport/pull/61
- Downstream: https://github.com/metriport/metriport/pull/63
With this PR, every time we commit Git will automatically run code checks (Lint and Prettier) on the updated files.
- Add [Husky](https://typicode.github.io/husky/), a library that makes Git hooks easier and better
- Add [lint-staged](https://www.npmjs.com/package/lint-staged), which only lints staged files for commit
- anytime

Add Husky and lint-staged

---

.github/workflows/_reusable_release.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.releaserc.yaml
package-lock.json
package.json

Ref https://github.com/metriport/metriport-internal/issues/92
- Upstream: https://github.com/metriport/metriport/pull/64
Adds [semantic release](https://www.npmjs.com/package/semantic-release) to CI/CD.
Upon merge/commit into master, it should create a new tag/release/notes.
Upon merge/commit into develop, it should create a new pre-release (alpha) tag/release.
- anytime

Add semantic versioning

---

packages/.eslintignore
packages/.eslintrc.js
packages/package-lock.json
packages/package.json
packages/packages/api/package.json
packages/packages/commonwell-cert-runner/README.md
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-cert-runner/src/index.ts
packages/packages/commonwell-cert-runner/src/person-management.ts
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json

Ref #227
- Reorganize commonwell-cert-runner's file so we have each group of tests on their own file
- Make the script to run it to be the standard `npm start`
- Install ESLint on `./packages` so `lint-staged` can do its thing
- Fix typo on packages' path on their `package.json`
- Update README
- asap so others can rely on this and minimize code conflicts

Reorganize commonwell-cert-runner

---

packages/packages/commonwell-sdk/src/client/commonwell.ts

Ref: #227
- Upstream: https://github.com/metriport/metriport/pull/73
Commonwell's `findDocument` API is a v2 endpoint: https://specification.commonwellalliance.org/services/data-broker/protocol-operations-data-broker#8781-find-documents
This PR allows our Commonwell SDK to work both with v1 and v2 endpoints.
- asap

Allow Commonwell API v1 and v2

---

.github/workflows/_reusable_build.yml
.github/workflows/_reusable_deploy.yml

Ref #92
- none
Update all CI/CD jobs to use NodeJS latest LTS version.
For reference, a job failing bc of wrong NodeJS version (semantic version requires 18+):
https://github.com/metriport/metriport/actions/runs/4007547608/jobs/6880530895
- asap

Fix nodejs version on build and deploy

---

commitlint.config.js

Ref. metriport/metriport-internal#143
Commitlint to require footer on commit messages.
- A footer is a line after the first one, with at least one empty line between it and the previous line.
- It requires an issue reference, `#123`. 
- The issue reference can include the org/repo, like `metriport/metriport-internal#143` 
To test the configuration local, one can issue this on the command line and play with the contents of `echo`:
```shell
$ echo "build: something\n\nadditional context\n\nRef. metriport/metriport-internal#123" | npx commitlint
```
- anytime

Commitlint to require footer

---

.github/workflows/pull-request_utils.yml
README.md
utils/.eslintignore
utils/.eslintrc.js
utils/package-lock.json
utils/package.json
utils/src/fhir-uploader.ts
utils/tsconfig.json

- Upstream: https://github.com/metriport/hapi-fhir-jpaserver/pull/1
Add FHIR uploader utility.
Add CI configuration so the code under `./utils` gets validated when a PR is opened/updated with those files.
- anytime, no deploy to be done

Add FHIR uploader utility

---

api/app/src/app.ts
utils/src/mock-webhook.ts

Ref. metriport/metriport-internal#334
- none
Set max request body size to 2MB on API.
- asap

fix: set max request body size to 2MB on API

---

api/app/src/default-error-handler.ts

Ref. metriport/metriport-internal#343
⚠️ This is pointing to `master` - see release plan.
Default error handler to have 4 params - we removed the fourth bc of lint issues, and this makes Express to treat it like a regular middleware function, throwing 500 when executed.
- release asap as a patch

fix: default error handler to have 4 params

---

.husky/pre-commit

Ref. metriport/metriport-internal#331
none
#331 updated the Husky hook to execute lint-staged introducing the `-v` parameter - likely to bypass validation?
If needed, one can issue `git commit --no-verify` to skip hooks.
- asap so we bring back lint on commited changes

fix: reenable lint-staged

---

api/app/src/providers/google.ts
api/app/src/providers/oauth2.ts

Ref. metriport/metriport-internal#177
Ref: 177
None
Fixed the google refresh token issue by prompting user to always grant permissions when authenticating
ASAP

fix(api): fix google refresh token issue

---

api/app/src/routes/fhir-proxy.ts
packages/packages/commonwell-sdk/src/models/document.ts

- proxy to http FHIR server instead of https
- fix document parsing to support Document containing Patient
Asap - need this to validate FHIR infra on staging

refactor: proxy to http FHIR server instead of https

---

README.md
api/app/package.json
api/app/src/default-error-handler.ts
api/app/src/routes/fhir-proxy.ts
api/app/src/routes/util.ts
api/app/src/shared/config.ts
infra/lib/api-stack.ts
infra/lib/env-config.ts
packages/packages/commonwell-cert-runner/src/document-consumption.ts
packages/packages/commonwell-cert-runner/src/document-contribution.ts

- Downstream: https://github.com/metriport/metriport-internal/pull/381
- add (final version of) proxy to FHIR server
- add default httpResponseBody() on util
- store document response and contents on cert-runner
STAGING
PRODUCTION
Might need to update the release notes when merging to `master` because there was a [previous commit](https://github.com/metriport/metriport/commit/f07cd23bde6e1e13cd49a4dd3692a21347cfeec5) with `feat: wip fhir server` that shouldn't be `feat`

feat: add proxy to FHIR server

---

infra/config/example.ts
infra/lib/api-stack.ts
infra/lib/env-config.ts
packages/packages/commonwell-cert-runner/src/document-contribution.ts

- Downstream:
- https://github.com/metriport/metriport/pull/122
- https://github.com/metriport/metriport-internal/pull/383
As per discussed and specified on https://github.com/metriport/metriport-internal/issues/228, we want to have a custom authentication subdomain so our setup on Commonwell and other 3rd party applications is not tied to Cognito (see task `create a custom domain for OAuth2`).
This PR introduces this new subdomain.
It adds a new user pool, instead of replacing the previous one. This is so we can validate the creation of the new user pool without impacting CW's authentication on our platform.
STAGING
PRODUCTION
- :warning: Requires updating the repository secret `INFRA_CONFIG_PRODUCTION`

feat: custom cognito user pool subdomain

---

infra/lib/api-stack.ts

- Upstream:
- https://github.com/metriport/metriport/pull/121
- https://github.com/metriport/metriport/pull/123
- https://github.com/metriport/metriport/pull/124
Remove old cognito user pool, left over from upstream PR.
After the upstream PR is merged and tasks from its release plan are done, then we can merge this at any time.

refactor: remove old cognito user pool

---

infra/lib/api-stack.ts

- Upstream: https://github.com/metriport/metriport/pull/122
Keep the new cognito user pool with IDs/names diff than the original ones, the deploy to AWS doesn't work if we try to rename them as we did on the upstream PR.
- asap

chore: keep new user pool's resources names diff than original

---

api/app/src/routes/fhir-proxy.ts

While testing, I noticed we have errors when CW queries for docs for this org, `2.16.840.1.113883.3.3330.8889429.1620.1` - which is not the one being debugged for document retrieval.
The error seems to happen while we're processing the response from the FHIR server. I tried to replicate this local but couldn't. [Link to the log on AWS](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/StagingAPIInfrastructureStack-APIFargateServiceTaskDefAPIServerLogGroup35E9518F-fDzCkr8Zml1k/log-events/APIFargateService$252FAPI-Server$252F6d9e76939c2f42bcbb9696a7d1eb0350$3Fstart$3D1677376451436$26refEventId$3D37406744847719786488407891515299710312535207453298262020)
Since this …

refactor: fhir proxy response transformer w/ try/catch

---

api/app/src/models/db.ts
api/app/src/routes/connect.ts
api/app/src/routes/middlewares/oauth2.ts
api/app/src/sequelize/index.ts
api/app/src/shared/config.ts
api/app/src/shared/log.ts
api/app/src/shared/util.ts

Ref. metriport/metriport-internal#369
Add debug function, so we can have code that's never removed and helpful to debug business logic local. In the future we can make `debug()` parameterized so we can switch it on/on on cloud as well, but not scope of this now.
Improve Util.log params to allow string substitution.
- no specifics

build: add debug function and improve log params

---

api/app/src/routes/middlewares/usage.ts

Ref. metriport/metriport-internal#376
Ref: 376
In debugging the devices api found this bug. The report usage infinitely loads because it wasnt executed

fix(api): report usage bug

---

packages/package-lock.json
packages/packages/api/package.json
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-cert-runner/src/document-consumption.ts
packages/packages/commonwell-cert-runner/src/document-contribution.ts
packages/packages/commonwell-cert-runner/src/link-management.ts
packages/packages/commonwell-cert-runner/src/patient-management.ts
packages/packages/commonwell-cert-runner/src/shared-person.ts
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/commonwell-sdk/src/client/commonwell.ts
packages/packages/commonwell-sdk/src/models/person.ts
packages/packages/react-native-sdk/package.json

Ref. metriport/metriport-internal#369
- Downstream: API TBD
BREAKING CHANGE:
- rename packages/commonwell-sdk's `getPatientsLinks` to `getNetworkLinks`
Regular changes:
- add `reenrollPerson`
- add `getPatientLinks`
- add `addPatientLink`
- deprecate `patientLink`
- (renamed) `getNetworkLinks` returns empty array when nothing found
- release a major update to the `commonwell-sdk` package: `2.0.0`

feat(commonwell-sdk): add new API calls and more

---

api/app/src/routes/medical/dtos/organizationDTO.ts
api/app/src/routes/medical/organization.ts
api/app/src/routes/medical/schemas/organization.ts
packages/package-lock.json
packages/packages/api/package.json
packages/packages/api/src/index.ts
packages/packages/api/src/medical/client/metriport.ts
packages/packages/api/src/medical/models/organization.ts
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/react-native-sdk/package.json

Ref. metriport/metriport-internal#438
- Downstream: https://github.com/metriport/metriport-internal/pull/441
BREAKING CHANGE:
- split org mgmt createOrUpdate in individual create and update endpoints
- anytime along dependencies
- alpha SDK already deployed

feat(sdk): split org mgmt create and update

---

infra/lib/api-stack.ts

Ref. https://github.com/metriport/metriport-internal/issues/474
Allow all headers (CORS).
The main change is on API GW. Left the change at the API's `app.ts` because of [this](https://www.npmjs.com/package/cors#enabling-cors-pre-flight).
Nothing special, asap.

fix(api): allow all headers (CORS)

---

README.md
api/app/docker-compose.dev.yml
api/app/src/command/account-init.ts
api/app/src/command/medical/customer-sequence/create-id.ts
api/app/src/command/medical/facility/create-facility.ts
api/app/src/command/medical/organization/create-organization.ts
api/app/src/command/medical/patient/create-patient.ts
api/app/src/external/commonwell/document.ts
api/app/src/external/commonwell/organization.ts
api/app/src/models/_default.ts
api/app/src/models/connected-user.ts
api/app/src/models/db.ts
api/app/src/models/medical/customer-sequence.ts
api/app/src/models/medical/facility.ts
api/app/src/models/medical/mapi-access.ts
api/app/src/models/medical/organization.ts
api/app/src/models/medical/patient.ts
api/app/src/models/settings.ts
api/app/src/models/webhook-request.ts
api/app/src/routes/index.ts
api/app/src/routes/internal.ts
api/app/src/routes/middlewares/auth.ts
api/app/src/sequelize/migrations/20230324144300_create-customer-sequence.ts
api/app/src/shared/oid.ts
infra/lib/api-stack.ts
utils/src/load-test.sh

Ref. metriport/metriport-internal#366
- Downstream: https://github.com/metriport/metriport-internal/pull/485
- OID generation with sequence per customer
- add account/customer init
- ⚠️ this endpoint doesn't has auth, relies on internal's endpoint `/internal` created on API GW to close public access
- add API DNS entry on private zone
- update README w/ acc init & API Key setup
- ⚠️ Contains DB migration
- ⚠️ Contains Infra update (auto applied upon merge)

refactor(api): rejig OID generation

---

api/app/src/sequelize/migrations/20230324144300_create-customer-sequence.ts

Ref. metriport/metriport-internal#366
- Upstream:https://github.com/metriport/metriport/pull/178
Fix the migration script, the previous version was returning the same customer ID multiple times, leading to error while inserting as that's part of the PK.
Context: https://metriport.slack.com/archives/C04FZ9859FZ/p1680016514274639?thread_ts=1680014828.936219&cid=C04FZ9859FZ
- asap

fix(api): fix OID migration script

---

.github/workflows/_reusable_deploy.yml

Ref. metriport/metriport-internal#156
Temp disable sentry on CI/CD.
Was using CI/CD so we can push source maps; meanwhile, will use the regular Github integration.
More context here: https://metriport.slack.com/archives/C04FZ9859FZ/p1680112432771159?thread_ts=1680110062.829999&cid=C04FZ9859FZ

ci: temp disable sentry

---

api/app/src/command/cx-user/get-user-token.ts
api/app/src/command/webhook/retry-failed.ts
api/app/src/command/webhook/webhook.ts
api/app/src/external/commonwell/link/create.ts
api/app/src/external/commonwell/link/get.ts
api/app/src/external/commonwell/patient-shared.ts
api/app/src/external/commonwell/patient.ts
api/app/src/providers/oauth1.ts
api/app/src/routes/connect.ts
api/app/src/routes/index.ts
api/app/src/routes/internal.ts
api/app/src/routes/medical/organization.ts
api/app/src/routes/medical/patient.ts
api/app/src/routes/util.ts
api/app/src/shared/notifications.ts

Ref. metriport/metriport-internal#156
Send `cxId` to Sentry through auth, so we don't have to pass it around when reporting errors/messages.

refactor: send cxId to Sentry through auth

---

utils/package-lock.json
utils/package.json
utils/src/acc-init.ts

Ref. metriport/metriport-internal#366
Add a script to initialize customers' accounts from Cognito users.
Context: https://metriport.slack.com/archives/C04T5Q9JHFX/p1680185786188569?thread_ts=1680181638.440269&cid=C04T5Q9JHFX
- no release will be done, just merge.
- already executed for `staging`
- included in the [ticket for the release of the next version](https://github.com/metriport/metriport-internal/issues/498), `production`

build(util): add script to initialize customer account

---

api/app/src/external/commonwell/patient-external-data.ts
api/app/src/external/commonwell/patient.ts

Ref. metriport/metriport-internal#156
- setCommonwellId not updating the DB
- create patient @ CW if no CW data found upon update

fix(api): setCommonwellId not updating the DB

---

api/app/src/routes/medical/dtos/linkDTO.ts

Ref. metriport/metriport-internal#504
- Downstream: nont
Use `USA` when no country from CW.
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1680232608751439
- asap

fix(api): use USA when no country from CW

---

packages/package-lock.json
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/commonwell-sdk/src/client/commonwell.ts
packages/packages/commonwell-sdk/src/client/document.ts
utils/package-lock.json
utils/package.json
utils/src/cw-doc-query.ts

Ref. metriport/metriport-internal#506
- Upstream: [none](https://github.com/metriport/metriport/pull/192)
Fix CW SDK building query headers.

fix(cw): fix CW SDK building query headers

---

api/app/src/command/medical/document/create-or-update.ts
api/app/src/command/medical/document/get-documents.ts
api/app/src/command/settings/updateSettings.ts
api/app/src/command/webhook/retry-failed.ts
api/app/src/domain/medical/codeable-concept.ts
api/app/src/domain/medical/document-reference.ts
api/app/src/errors/index.ts
api/app/src/external/commonwell/document.ts
api/app/src/external/commonwell/patient-shared.ts
api/app/src/models/db.ts
api/app/src/models/medical/document-reference.ts
api/app/src/models/medical/patient.ts
api/app/src/routes/medical/document.ts
api/app/src/routes/medical/dtos/codeableDTO.ts
api/app/src/routes/medical/dtos/documentDTO.ts
api/app/src/routes/medical/organization.ts
api/app/src/routes/medical/patient.ts
api/app/src/routes/webhook/garmin.ts
api/app/src/sequelize/migrations-shared.ts
api/app/src/sequelize/migrations/20230404153200-create-document-reference.ts
docs/devices-api/more-info/webhooks.mdx
docs/medical-api/api-reference/document/list-documents.mdx
packages/package-lock.json
packages/packages/api/package.json
packages/packages/api/src/medical/models/document.ts
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/commonwell-sdk/src/common/fileDownload.ts

Ref. metriport/metriport-internal#515
- Downstream: https://github.com/metriport/metriport-internal/pull/523
- fix the issue w/ error on download sending error payload to API response
- create table `document_reference`
- decouple document query from listing
- trigger async doc query w/ CW when doc list is requested
- store doc references from from CW on the `document_reference` table
- update SDK to match `/document` payload
- update async function calls to have a default error handler (found out this makes Express break if not treated/processed)
- add `version` to shared migration code
- update docs
- ⚠️ Contains a DB migration
- nothing on infra
- as soon as possible

feat(api): async document query

---

api/app/src/command/medical/document/document-query.ts
api/app/src/command/medical/document/get-documents.ts
api/app/src/external/commonwell/document.ts
api/app/src/external/commonwell/document/document-download.ts
api/app/src/external/commonwell/document/document-query.ts
api/app/src/external/commonwell/document/shared.ts
api/app/src/routes/medical/document.ts
docs/medical-api/api-reference/document/list-documents.mdx
docs/medical-api/api-reference/document/start-document-query.mdx
docs/mint.json
packages/package-lock.json
packages/packages/api/package.json
packages/packages/api/src/index.ts
packages/packages/api/src/medical/client/metriport.ts
packages/packages/api/src/medical/models/document.ts

Ref: https://github.com/metriport/metriport-internal/issues/522
- Downstream: https://github.com/metriport/metriport-internal/pull/527
- add start doc query endpoint
- update sdk to reflect the API change (⚠️ breaking change)
- update docs
- split document commands in diff files
Note: added two commits so Git recognizes a file renaming/moving, but the diff on the PR shows as deleted/created (`api/app/src/external/commonwell/document.ts`)
- NPM and references to it already updated for `staging`
- note for `prod` release: update version of package SDK/api on `major`, even though this PR increased it on `minor` (there are breaking changes on the SDK - `listDocuments` function)

feat(api): async docs v1

---

api/app/src/external/commonwell/patient.ts
api/app/src/providers/dexcom.ts
api/app/src/providers/oauth2.ts
api/app/src/providers/withings.ts
api/app/tsconfig.json

refs. metriport/metriport-internal#537
N/A
update to proper ts version as per [here](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping) (we were woefully out of date using es2016), fix error rethrows

fix(api): update to proper ts version, fix error rethrows

---

api/app/package.json
api/app/src/external/commonwell/document/document-download.ts
api/app/src/external/commonwell/document/document-query.ts
api/app/src/external/commonwell/link/create.ts
api/app/src/external/commonwell/link/get.ts
api/app/src/external/commonwell/link/shared.ts
api/app/src/external/commonwell/mock.ts
api/app/src/external/commonwell/organization.ts
api/app/src/external/commonwell/patient-shared.ts
api/app/src/external/commonwell/patient.ts
docs/medical-api/getting-started/quickstart.mdx
package-lock.json
packages/package-lock.json
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/commonwell-sdk/src/client/commonwell-api.ts
packages/packages/commonwell-sdk/src/client/commonwell.ts

Ref. metriport/metriport-internal#156
none
- capture CW-Reference header and make it available on SDK
- add CW-Ref to reports to Sentry
- update MAPI docs' quickstart, including info about async doc query
In addition to the info on async doc query, I'm also suggesting a bit more space between sections of the quickstart, it hard to differentiate the sections when scanning the page, and those lines seem to help w/o messing with larger UI changes (left with new lines, right original version):

feat(commonwell-sdk): capture CW-Reference header

---

infra/lib/api-stack.ts
infra/lib/env-config.ts

Ref. metriport/metriport-internal#547
- Downstream: https://github.com/metriport/metriport-internal/pull/548
Allow `prod`'s private zone accessing sandbox's one, so `post-confirmation` lambda in `prod` can initialize the account in `sandbox` as well.

fix: prod private zone accessing sandbox's one

---

infra/lib/api-stack.ts
infra/lib/env-config.ts

Ref. metriport/metriport-internal#547
- Upstream: https://github.com/metriport/metriport/pull/217
- Downstream: https://github.com/metriport/metriport-internal/pull/548
dynamic sandbox vpc name

fix: dynamic sandbox vpc name

---

api/app/src/command/medical/document/create-or-update.ts
api/app/src/domain/base-domain.ts
api/app/src/domain/medical/document-reference.ts
api/app/src/external/commonwell/document/document-query.ts
api/app/src/external/commonwell/document/shared.ts
api/app/src/models/_default.ts
api/app/src/models/medical/document-reference.ts
api/app/src/models/medical/facility.ts
api/app/src/models/medical/organization.ts
api/app/src/models/medical/patient.ts
api/app/src/sequelize/migrations/20230404153200-create-document-reference.ts
api/app/src/sequelize/migrations/20230411144500-alter-document-reference-add-raw.ts
packages/packages/commonwell-sdk/src/models/document.ts

Ref. metriport/metriport-internal#564
- Downstream: https://github.com/metriport/metriport-internal/pull/567
- dedup doc ref by master ID
- store raw doc content from CW
- also changed the interfaces bc the domain was importing the model/DB
- ⚠️ This is pointing to `master` - deploy in `production`
- `select distinct cx_id, patient_id from document_reference order by cx_id, patient_id;`
- `select cx_id, id from facility order by cx_id, id;`
- `CREATE TABLE document_reference_564_20240411 AS  TABLE document_reference;`
- `delete from document_reference`

refactor(api): dedup doc ref by master ID + store raw

---

api/app/src/command/medical/document/create-or-update.ts
api/app/src/domain/base-domain.ts
api/app/src/domain/medical/document-reference.ts
api/app/src/external/commonwell/document/document-query.ts
api/app/src/models/medical/document-reference.ts
api/app/src/sequelize/migrations/20230411221500-alter-document-reference-remove-unique.ts

Ref. metriport/metriport-internal#564
- Upstream: https://github.com/metriport/metriport/pull/221
Recreate CW doc refs on new query.
- ⚠️ This is pointing to `master`, new deployment in `production` upon merge
- ⚠️ This contains a DB migration

refactor(api): recreate CW doc refs on new query

---

infra/lib/api-stack.ts

Ref. metriport/metriport-internal#553
- Downstream: https://github.com/metriport/metriport-internal/pull/575
Allow connections from any IP within VPC

build(api): allow connections from any IP within VPC

---

.github/workflows/_reusable_deploy.yml
.github/workflows/_reusable_release.yml
.github/workflows/branch-to-staging.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/pull-request_api.yml
.github/workflows/pull-request_infra.yml
.github/workflows/pull-request_packages.yml
.github/workflows/pull-request_utils.yml
.github/workflows/pull-request_widget.yml

Ref. metriport/metriport-internal#531
- Upstream:
- https://github.com/metriport/metriport-internal/pull/539
- https://github.com/metriport/metriport-internal/pull/540
- support GH action's `merge_group` trigger
- don't deploy when pr only stuff changed

ci: support GH action's `merge_group` trigger

---

.github/workflows/_reusable_build.yml
.github/workflows/_reusable_deploy.yml
.github/workflows/_reusable_release.yml
.github/workflows/branch-to-staging.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/pull-request_api.yml
.github/workflows/pull-request_infra.yml
.github/workflows/pull-request_packages.yml
.github/workflows/pull-request_utils.yml
.github/workflows/pull-request_widget.yml

Ref. metriport/metriport-internal#553
https://github.com/metriport/metriport-internal/pull/589
- Add login to Docker Hub on CI/CD, like what we did with internal
- Match internal's GH workflow structure/logic
- nothing special, no deploy should be done

553 Add login to Docker Hub

---

.github/workflows/branch-to-staging.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Ref. metriport/metriport-internal#340
- Upstream: https://github.com/metriport/metriport/pull/230
Fix secrets passed to `reusable_deploy`, they need to be customized based on the environment, can't just inherit those. Also, AFAIK, can't override some and inherit the rest.
asap as build is broken

340 fix workflow secrets

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Ref. metriport/metriport-internal#340
none
- fix deploy staging and production, it was pointing to the wrong envs; staging didn't fail bc API and Widget use the same, but in prod they are different
- asap so we can release to prod

340 fix deploy staging and production

---

.github/workflows/deploy-production.yml

Ref. metriport/metriport-internal#594
- Upstream: https://github.com/metriport/metriport/pull/233
Add missing `secrets: inherit` to `deploy-production` when calling `reusable_deploy`
- ⚠️ merging into `master`
- ASAP

594 fix deploy-production

---

api/app/src/mappings/garmin/user.ts
api/app/src/routes/webhook/garmin.ts

Ref. metriport/metriport-internal#608
none
Make vo2Max optional on Garmin.
Don't format log as it breaks CW's log

608 make vo2Max optional on Garmin

---

api/app/src/mappings/garmin/user.ts
api/app/src/routes/webhook/garmin.ts

Ref: https://github.com/metriport/metriport-internal/issues/608
- Upstream: https://github.com/metriport/metriport/pull/243
Release fix garmin vo2 max.
- ⚠️ This is pointing to `master` - DEPLOY in `production`

PATCH 608 release fix garmin vo2 max

---

api/app/package.json
connect-widget/app/package.json
package-lock.json

Ref: https://github.com/advisories/GHSA-f598-mfpv-gmfx
https://github.com/metriport/metriport-internal/pull/613
Update Sequelize to v6.31
Also set connect-widget's `react-scripts` to be automatically updated when a new patch is released.

chore: update sequelize to 6.31

---

README.md

- Upstream: https://github.com/metriport/metriport-internal/pull/616
- update api status badge on GH's repo to come from Checkly
- only merge/deploy this once the upstream is merged **_AND_** http://status.metriport.com is working

135 api status from checkly

---

infra/lib/alarm-slack-chatbot.ts
infra/lib/api-service.ts
infra/lib/api-stack.ts
infra/lib/env-config.ts
infra/lib/shared.ts
infra/lib/util.ts

- Downstream: https://github.com/metriport/metriport-internal/pull/620
- add alarms to API service's ECS
- point all api-stack alarms to Slack
- split api-stack's API ECS code into its own file
- dashboards
- [CW Production dashboard](https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#dashboards:name=PROD;expand=false)
- [CW Staging dashboard](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#dashboards:name=Staging)
- `staging`
- `production`
- once deployed:
- get the SNS Topic's ARN;
- update the downstream's config files
- merge them

153 setup infra alarms to Slack

---

api/app/package.json
api/app/src/external/commonwell/patient-shared.ts
package-lock.json
packages/package-lock.json
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/commonwell-sdk/src/common/util.ts

Ref. metriport/metriport-internal#621
- Upstream: https://github.com/metriport/metriport/pull/260
- Make CW SDK's `getId` accept undefined
- Fix access to array when checking the most recent person

621 accept undefined for getId

---

infra/lib/api-stack.ts

Ref. metriport/metriport-internal#627
- Upstream: https://github.com/metriport/metriport/pull/262
Chatbot channel config per environment
Context: https://metriport.slack.com/archives/C04DBBJSKGB/p1682561953119409?thread_ts=1682559846.204019&cid=C04DBBJSKGB
- following the upstream release plan
- asap

RELEASE - chatbot channel config per environment

---

infra/lib/api-stack.ts
infra/lib/env-config.ts

https://github.com/metriport/metriport-internal/pull/633
Reuse `prod`'s slack SNS topic on `sandbox`
- `develop`
- `master`
- update GH secret `INFRA SANDBOX` w/ base64 from internal

135 reuse slack SNS topic on sandbox

---

infra/lib/api-stack.ts
infra/lib/env-config.ts

https://github.com/metriport/metriport-internal/pull/637
Add slack notif channel for sandbox
- merge/deploy this in staging
- create patch for production
- update GH secrets `INFRA SANDBOX` from base64 of internal
- merge/deploy in prod/staging

135 slack notif channel for sandbox

---

api/app/src/command/usage/report-usage.ts
api/app/src/command/webhook/webhook.ts
api/app/src/external/commonwell/document/document-query.ts
api/app/src/routes/index.ts
api/app/src/routes/medical/document.ts
api/app/src/routes/middlewares/usage.ts
api/app/src/routes/util.ts

Ref. metriport/metriport-internal#649
- Upstream: https://github.com/metriport/metriport-internal/pull/650
- Update report usage to work with MAPI
- only report MAPI on successful doc query
- Remove `forceQuery` from `GET /document`
- Only report successful requests
- update OSS GH secret `INFRA_STAGING`
- merge this

649 update report usage to work with MAPI

---

packages/packages/commonwell-sdk/src/models/identifier.ts

Ref. metriport/metriport-internal#621
none
Add `unspecified` id use.
Additional context: https://metriport.slack.com/archives/C04DBBJSKGB/p1683332701694779

621 add unspecified id use

---

api/app/package.json
api/app/src/external/fhir/document/index.ts
package-lock.json
packages/package-lock.json
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/commonwell-sdk/src/models/document.ts

Ref. metriport/metriport-internal#621
https://github.com/metriport/metriport/pull/292
Deploy CW SDK to NPM and update version at packages and API
- once merged, replicate this to production

621 deploy new version to npm

---

docs/medical-api/api-reference/document/get-document.mdx

N/A
clarify return on document url endpoint - was missing the name of the actual object property, so it made it seem like it returned a string

docs: clarify return on document url endpoint

---

api/app/src/command/settings/updateSettings.ts
api/app/src/command/webhook/webhook.ts
api/app/src/errors/metriport-error.ts
api/app/src/errors/not-found.ts
api/app/src/errors/webhook.ts
api/app/src/external/commonwell/document/document-download.ts
api/app/src/external/commonwell/document/document-query.ts

Ref: https://github.com/metriport/metriport-internal/issues/664
none
Add doc info to sentry.
Also has a [cherry-pick](https://github.com/metriport/metriport/pull/298/commits/5ad4b6b4d73b3e09a0e7cfcda3d2ec7be2f08791) from [this PR](https://github.com/metriport/metriport/pull/298) to support `cause` on `MetriportError` - [context](https://metriport.slack.com/archives/C0553DYC95L/p1683554679386879?thread_ts=1683507833.836849&cid=C0553DYC95L).
- ⚠️ This is pointing to `master`, deployment in `production`
- after merge/deploy, merge `master` into `develop`

664 Add doc info to sentry

---

api/app/src/models/medical/patient.ts

refs. metriport/metriport#327
N/A
filter out empty strings when splitting names
asap

fix(api): filter out empty strings when splitting names

---

api/app/package.json
api/app/src/command/medical/document/document-query.ts
api/app/src/external/commonwell/__tests__/cw-fhir-proxy.test.ts
api/app/src/external/commonwell/api.ts
api/app/src/external/commonwell/cw-fhir-proxy-helpers.ts
api/app/src/external/commonwell/cw-fhir-proxy.ts
api/app/src/external/commonwell/document/document-download.ts
api/app/src/external/commonwell/document/document-query.ts
api/app/src/external/commonwell/document/shared.ts
api/app/src/external/commonwell/tsconfig.json
api/app/src/external/fhir/document/save-document-reference.ts
api/app/tsconfig.json
package-lock.json
packages/package-lock.json
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json

Ref. metriport/metriport-internal#691
https://github.com/metriport/metriport/pull/331
- Add tenant support to Binary on CW proxy
- Add logs when error while processing doc refs/binaries
- Add unit tests for CW FHIR proxy
- Add stricter `tsconfig` for specific path to make safer access to arrays

691 add tenant support to Binary on CW proxy

---

api/app/src/command/medical/patient/consolidate-data.ts
api/app/src/default-error-handler.ts
api/app/src/external/commonwell/cw-fhir-proxy.ts
api/app/src/routes/medical/patient.ts

Ref. metriport/metriport-internal#686
- add patient consolidated endpoint
- adjust defaultHandler for FHIR related errors
- small tweak on `cw-fhir-proxy` when tenant missing
-  update docs
- WIP

686 add patient consolidated endpoint

---

api/app/src/external/index.ts
api/app/src/routes/medical/dtos/documentDTO.ts
api/app/src/shared/__tests__/external.test.ts
api/app/src/shared/external.ts

Ref. metriport/metriport-internal#698
none
(doc) external IDs limit to 64chars
context: https://metriport.slack.com/archives/C04DBBJSKGB/p1684106893571899?thread_ts=1684105959.041439&cid=C04DBBJSKGB
- ⚠️ This is pointing to `master`, deploying in `production`
- re-populate Delfina's data ([here](https://metriport.slack.com/archives/C04DBBJSKGB/p1684105959041439))
- it should re-download doc and re-inserts them on the FHIR DB
- the ones that failed should work now
- just back merge into `develop` once this is merged

698 external IDs limit to 64chars

---

api/app/src/errors/metriport-error.ts
api/app/src/external/commonwell/document/document-query.ts
api/app/src/external/fhir/document/index.ts
api/app/src/external/fhir/shared/index.ts
api/app/src/shared/__tests__/external.test.ts
api/app/src/shared/external.ts

Ref. metriport/metriport-internal#698
- Upstream: https://github.com/metriport/metriport/pull/335
try FHIR id before upload S3
- ⚠️ This is pointing to `master`, deploying in `production`
- re-populate Delfina's data ([here](https://metriport.slack.com/archives/C04DBBJSKGB/p1684105959041439))
- it should re-download doc and re-inserts them on the FHIR DB
- the ones that failed should work now
- just back merge into `develop` once this is merged

698 try FHIR id before upload S3

---

api/app/docker-compose.dev.yml
api/app/src/models/db.ts

Ref. metriport/metriport-internal#696
Increase max DB connections to 300
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1684174050171709?thread_ts=1684171454.512509&cid=C04DMKE9DME
- ⚠️ This is pointing to `master`, deploying in `production`
- back merge into `develop` once this is merged

696 increase max DB connections to 300

---

api/app/src/command/medical/admin-populate-fhir.ts
api/app/src/command/medical/document/document-query.ts
api/app/src/external/commonwell/document/document-query.ts

Ref. metriport/metriport-internal#698
none
Add extra logs to doc query/download
Context: https://metriport.slack.com/archives/C04DBBJSKGB/p1684255094506319?thread_ts=1684251060.218089&cid=C04DBBJSKGB
- ⚠️ This is pointing to `master`, deploying in `production`
- merge `master` into `develop` once this has been merged

698 add extra logs to doc query/download

---

api/app/src/command/medical/__tests__/consolidate-data.test.ts
api/app/src/command/medical/patient/consolidate-data.ts

Ref. metriport/metriport-internal#686
Paginate fhir on consolidated endpoint

PATCH 686 paginate fhir on consolidated endpoint

---

docs/medical-api/fhir/resources/clinicalimpression.mdx

The error that prevented the docs from updating was caused by the use of quotations (`"` and `'`) inside the page's description property while being wrapped in quotations.

[Docs][Hotfix] Fix quotes wrapping

---

infra/lib/api-service.ts
infra/lib/api-stack.ts
infra/lib/fhir-converter-service.ts

Ref. metriport/metriport-internal#706
none
Update FHIR Converter infra
- LB from LB to ALB
- scaling thresholds
- double CPU in prod
- enable container insights
Update API infra
- DB min/max caps prod/staging
- enable container insights

706 move to ALB and update infra

---

fhir-converter/src/templates/cda/Resources/AllergyIntolerance.hbs
fhir-converter/src/templates/cda/Resources/Immunization.hbs
fhir-converter/src/templates/cda/Resources/MedicationRequest.hbs
fhir-converter/src/templates/cda/Resources/Procedure.hbs
fhir-converter/src/templates/cda/ValueSet/AllergySeverity.hbs
fhir-converter/src/templates/cda/ValueSet/EventStatus.hbs
fhir-converter/src/templates/cda/ValueSet/ImmunizationStatus.hbs
fhir-converter/src/templates/cda/ValueSet/MedicationRequestStatus.hbs
fhir-converter/src/templates/cda/ValueSet/MedicationStatementStatus.hbs

N/A
update hbs cda templates for various statuses based on the following observed errors:
```
AllergyIntoleranceSeverity code 'Severe':
Occurrences: 14
AllergyIntoleranceSeverity code 'Unknown':
Occurrences: 1
AllergyIntoleranceSeverity code 'Moderate':
Occurrences: 8
MedicationStatementStatus code 'Completed':
Occurrences: 47
MedicationStatementStatus code 'Discontinued':
Occurrences: 8
MedicationRequestStatus code 'aborted':
Occurrences: 4
ProcedureStatus code 'cancelled':
Occurrences: 1
ImmunizationStatus code 'held':
Occurrences: 1
```
asap

fix(api): update hbs cda templates for various statuses

---

fhir-converter/src/index.js

Ref. metriport/metriport-internal#706
none
Log NODE_OPTIONS on FHIR converter so we can know what's the actual setup we have in `prod` - couldn't get the env var even logging into the ECS task.

706 log NODE_OPTIONS on FHIR converter

---

api/lambdas/sqs-to-converter/index.js
api/lambdas/sqs-to-fhir/index.js
infra/lib/api-stack/fhir-converter-connector.ts
infra/lib/api-stack/fhir-server-connector.ts
infra/lib/fhir-converter-service.ts
infra/lib/shared/lambda.ts
infra/lib/shared/sqs.ts

Ref. metriport/metriport-internal#738
- Upstream: https://github.com/metriport/fhir-server/pull/26
- adj lambda timeout to match LBs, 15min
- adj converter lambda to diff concurrencies in prod/staging
- include 503 on error codes to check on lambdas
- alongside dependencies

build: adj lambda timeout to match LBs, 15min

---

api/app/src/routes/medical/document.ts

refs. metriport/metriport-internal#731
N/A
fix doc ref date filter to not return null
asap
⚠️ this is pointing to master

fix(api): fix doc ref date filter to not return null

---

infra/lib/api-stack.ts
infra/lib/api-stack/fhir-converter-connector.ts
infra/lib/api-stack/fhir-server-connector.ts
infra/lib/connect-widget-stack.ts
infra/lib/shared/lambda.ts
infra/lib/shared/sqs.ts
infra/lib/shared/util.ts

Ref. metriport/metriport-internal#706
none
- Add alarm to DLQ
- Moved `addErrorAlarmToLambdaFunc` to the lambda shared file

706 add alarm to DLQ

---

infra/lib/api-stack/fhir-server-connector.ts

Ref. metriport/metriport-internal#738
none
fhir server lambda timeout to 10min
- asap

738 fhir server lambda timeout to 10min

---

api/lambdas/sqs-to-converter/index.js
infra/lib/api-stack.ts

Ref. metriport/metriport-internal#738
none
- add missing request on FHIR bundle after converting from CDA to FHIR
- increase IOPS alarm from 5,000 to 10,000 IOPS

738 add missing request on FHIR bundle

---

api/app/src/routes/util.ts
fhir-test/.env.example
fhir-test/.gitignore
fhir-test/README.md
fhir-test/package-lock.json
fhir-test/package.json
fhir-test/src/example.js
fhir-test/src/example.yml
fhir-test/src/fhir/fhir-batch-hapi.yml
fhir-test/src/fhir/fhir-batch-medplum.yml
fhir-test/src/fhir/fhir-batch.js
fhir-test/src/fhir/fhir-crud-hapi.yml
fhir-test/src/fhir/fhir-crud-medplum.yml
fhir-test/src/healthcheck-hapi.yml
fhir-test/src/healthcheck-medplum.yml

Ref. metriport/metriport-internal#746
none
Introduces FHIR load test with Artillery.
This does not closes #746, it sets the base for the remaining tests.
- it will lead to a deploy bc of a small change on `api/app/src/routes/util.ts` (log only)

build: add FHIR load test package

---

api/app/src/command/connected-user/get-connected-user.ts
api/app/src/providers/cronometer.ts
api/app/src/providers/dexcom.ts
api/app/src/providers/oauth2.ts
api/app/src/providers/withings.ts

refs. metriport/metriport#421
Modified getProviderDataFromConnectUserOrFail() to include a check for the existence of a token attribute in a providerMap[provider] entry. 
The second part of the issue will be raised separately.

fix(api): provider map token check

---

connect-widget/app/src/pages/connect/components/connect-providers.tsx
connect-widget/app/src/pages/connect/components/error-dialog.tsx
connect-widget/app/src/pages/connect/components/providers.tsx
connect-widget/app/src/pages/connect/index.tsx
connect-widget/app/src/shared/api.ts
connect-widget/app/src/shared/components/WidgetContainer.tsx
connect-widget/app/src/shared/token-errors.ts
connect-widget/app/src/shared/util.ts

refs. metriport/metriport#429
- Created three custom Error classes for the different token situations: no token, demo token, invalid token.
- Error dialog is now displaying the error title, message, and a link (see the image for reference https://imgur.com/a/Z3cyVmk).
- Added isDemoToken function to the util.
- Removed ```token === "demo"``` from everywhere. Also, isDemo is centralized in the api.ts and is exported to all the other files that used it.
- I thought that no token and demo token should both result in the 'demo' behavior, i.e. the Connect buttons become disabled. The error messages and docs links are still unique to each case.
- Cleaned up setupApi to avoid using getApiToken multiple times.
Side note:
The invalid token case will be handled in the next …

feat(widget): docs link for no token

---

connect-widget/app/src/shared/api.ts

refs. metriport/metriport#428
Upon landing on the Connect Widget page, the api will make a request for the redirect link, which will verify the token.
If the token's not valid, Connect buttons will be disabled, a message will pop up and will point the user to docs.

feat(widget): invalid token error handling

---

api/app/src/routes/user.ts
fhir-test/.gitignore

Ref.
- https://metriport.slack.com/archives/C0553DYC95L/p1686159871151379
- https://metriport-inc.sentry.io/issues/4234608505/events/2b9b664c82524cbf9ea8d388749aa3ec/
`sendStatus` sends the status and "closes" the connection, use `status` when we want to also send a body.
- asap

FIX sandbox user count send message along status

---

api/app/src/routes/user.ts
fhir-test/.gitignore

https://github.com/metriport/metriport/pull/457
Fixes the response to `POST /user` when customer reaches the limit of users on sandbox.
- ⚠️ Merging to `master`, deploy to `production`
- nothing fancy, just a deploy on OSS API

fix(api): sandbox user count send message along status

---

connect-widget/app/src/shared/api.ts

refs. metriport/metriport#428
The api wasn't making the request to check the token validity. isTokenValid() needed to be async.

fix(widget): token verification fix

---

api/lambdas/sqs-to-fhir/index.js

none
FHIR server lambda: remove metriport prefix
- asap, code already on lambda console, need this to deploy along next release

785 remove metriport prefix

---

api/lambdas/sqs-to-converter/index.js

- move request to entry
- check entry before using it
- This is pointing to `master`, deploy in `production`
- Update `develop` after this is merged

PATCH RELEASE move request to entry

---

api/lambdas/sqs-to-converter/index.js

n/a
don't replace patient ID in FHIR bundle post-processing
asap

fix(api): don't replace patient ID in FHIR bundle post-processing

---

api/app/src/command/webhook/garmin.ts
docs/devices-api/more-info/webhooks.mdx

refs. metriport/metriport#542
- Garmin now sends Metriport ID instead of cxUserId. The field name has been updated to match the change.
- Webhook docs section updated correspondingly.

fix(api): garmin now sends metriport id

---

api/lambdas/sqs-to-converter/index.js
api/lambdas/sqs-to-fhir/index.js

none
Add retries to FHIR server and converter lambdas.
Some changes are just to keep both the `sqs-to-fhir` and `sqs-to-converter` as similar as possible to make it easier to share code once we have https://github.com/metriport/metriport-internal/issues/715 done
- test on staging

785 add retries to FHIR server and converter lambdas

---

api/app/src/routes/user.ts

refs. metriport/metriport#802
- If a user hasn't connected any providers, using the `/user/:userId/connected-providers` returns an empty array, instead of erroring out.

fix(api): no providers no error ;)

---

api/app/package.json
api/app/src/domain/medical/document-reference.ts
api/app/src/external/fhir/document/get-documents.ts
api/app/src/routes/medical/__tests__/document.test.e2e.ts
api/app/src/routes/medical/document.ts
docs/medical-api/api-reference/document/get-document-query.mdx
docs/medical-api/api-reference/document/list-documents.mdx
docs/mint.json
package-lock.json
packages/package-lock.json
packages/packages/api/package.json
packages/packages/api/src/index.ts
packages/packages/api/src/medical/client/metriport.ts
packages/packages/api/src/medical/models/document.ts
packages/packages/commonwell-cert-runner/package.json
packages/packages/commonwell-jwt-maker/package.json
packages/packages/commonwell-sdk/package.json
packages/packages/react-native-sdk/package.json
utils/package-lock.json
utils/package.json
utils/src/test-sdk.ts

- upstream: none
- downstream: https://github.com/metriport/metriport-internal/pull/818
Add get doc query status
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1687217944864849
- NPM alpha version already deployed
- Need to be updated for prod

785 add get doc query status

---

infra/lib/api-stack.ts
infra/lib/api-stack/fhir-converter-connector.ts
infra/lib/api-stack/fhir-server-connector.ts
infra/lib/api-stack/sidechain-fhir-converter-connector.ts

Ref. metriport/metriport-internal#715
none
Use existing buckets if present. Had to do this so I can branch/deploy `develop` into `staging` again to get `staging` on the current state and afterwards can can merge/deploy the lambda refactoring as we'll do in `production`. Trying to validate the deployment as close to prod as possible. 
asap

715 use existing buckets if present

---

connect-widget/app/src/pages/connect/index.tsx
connect-widget/app/src/shared/api.ts
connect-widget/app/src/shared/token-errors.ts

refs. metriport/metriport#615
- Removed the demo token notification, but kept the sentry reporting. This error is being ignored on Sentry, so we can still see if any new issues arise.

feat(widget): removed demo token notification

---

api/lambdas/cda-to-visualization/index.js
api/lambdas/garmin/index.js
api/lambdas/garmin/package-lock.json
api/lambdas/garmin/package.json
api/lambdas/scheduled/index.js
api/lambdas/tester/index.js
api/lambdas/token-auth/index.js
api/lambdas/token-auth/package-lock.json
api/lambdas/token-auth/package.json
api/lambdas/withings/index.js
api/lambdas/withings/package-lock.json
api/lambdas/withings/package.json
infra/lib/api-stack.ts

Ref. metriport/metriport-internal#715
- Upstream: https://github.com/metriport/metriport/pull/574
- Downstream: https://github.com/metriport/metriport/pull/617
All OSS lambdas to use Sentry, lambda revamp is pointing to this branch.

715 all OSS lambdas to use Sentry

---

connect-widget/app/src/pages/connect/index.tsx
connect-widget/app/src/shared/api.ts
connect-widget/app/src/shared/components/WidgetContainer.tsx

refs. metriport/metriport#624
- Fixed the colorMode query parameter - it is now able to set the color theme again
- Fixed the text color inside widget's buttons

fix(widget): fixed colorMode and button text color

---

connect-widget/app/src/pages/connect/components/error-dialog.tsx

refs. metriport/metriport#533
- Documentation link is now a button instead of an anchor
- The button colour is always grey and becomes light grey on hover (see images: https://imgur.com/a/4wZoRcK)

fix(widget): documentation button instead of anchor

---

api/app/src/external/commonwell/document/document-query.ts
api/app/src/routes/webhook/apple.ts
api/app/src/routes/webhook/withings.ts
api/lambdas/src/withings.ts

Ref. metriport/metriport-internal#693
none
Do not multiline stringify, as it adds too much noise on logs. Also, CW already formats JSON-like logs when we open a log entry.
The ticket's scope is to fix the issue so we can multiline JSON w/o messing with CW logs, but in the meanwhile lets avoid those.

693 do not multiline stringify

---

api/app/src/routes/internal.ts
api/app/src/routes/medical/internal-docs.ts
api/app/src/routes/medical/internal-patient.ts

Ref. metriport/metriport-internal#715
none
- internal patient endpoints get cxId from query
- move delete patient/:id to internal patient routes
- remove duplicated delete patient endpoint

715 internal patient endpoints get cxId from query

---

api/app/src/external/commonwell/document/document-query-sandbox.ts

refs. metriport/metriport#646
- Fixed a mistake that resulted in all of the sandbox documents being described as photographs

fix(mapi): fixed the document type for sandbox patients

---

.github/workflows/_deploy_cdk.yml
.github/workflows/branch-to-staging.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
README.md
packages/infra/bin/infrastructure.ts
packages/infra/cdk.json
packages/infra/config/.gitignore
packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/config/production.ts
packages/infra/config/sandbox.ts
packages/infra/config/staging.ts
packages/infra/lib/api-service.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/doc-query-checker.ts
packages/infra/lib/connect-widget-stack.ts
packages/infra/lib/fhir-converter-service.ts
packages/infra/lib/secrets-stack.ts
packages/infra/lib/shared/config.ts
packages/infra/lib/shared/secrets.ts
packages/infra/lib/shared/util.ts
packages/infra/tsconfig.json

Ref. metriport/metriport-internal#237
- Upstream: https://github.com/metriport/metriport-internal/pull/878
- Symlink configs, pointing to relative `metriport-internal` repo
- Update CI/CD accordingly
With this PR we don't need to update GH actions with the contents of config files from the internal repo, those are symlinks to the actual files.
The only consideration is that we need the respective environment's configs merged on internal before we can merge the respective OSS repo. Example:
- we're working on OSS and need to update the configs
- update those on internal (can edit them on OSS b/c of symlink, but have to commit on internal)
- once all is done, open a PR on each repo (OSS and internal)
- merge internal first (this gets the updated config to internal's …

237 symlink configs + update CICD accordingly

---

docs/devices-api/more-info/react-native.mdx

Ref: 799
None
Update docs to explain how to set up react native with swift template instead of obj-c

feat(api): update docs to fix appdelegate in swift

---

packages/react-native-sdk/metriport-react-native.podspec
packages/react-native-sdk/tsconfig.json

Ref: 799
Remove default pod version and `importsNotUsedAsValues` is causing deploy issues

799 add user agent

---

packages/connect-widget/public/manifest.json

refs. metriport/metriport-internal#881
- For Widget's installation popup, the name was changed from "Create React App Sample" to "Metriport Connect Widget"

fix(widget): installation name change from cra default

---

packages/infra/lib/api-stack.ts

refs. metriport/metriport#363
- Granted the fitbit lambdas access to the secrets

feat(dapi): added secrets access to the fitbit lambdas

---

packages/scripts/restart-api.sh

none
Currently, the script that deploys the API creates a new image on ECR and triggers a restart on ECS, but it doesn't wait for the service to finish restarting (redeploying).
This should fix it. Tested local while there was a deploy in progress and it waited.
- asap

704 wait for API deployment to finish on CICD

---

packages/api/src/mappings/fitbit/body.ts
packages/api/src/providers/fitbit.ts

refs. metriport/metriport#678
- Weight logs are now taking user's timezone into account and convert all entries to UTC. 
- Heart rate data uses the timezone=UTC query parameter as well
- I cross referenced all of the endpoints that we call in [this file](https://github.com/metriport/metriport/blob/b939a32e70d8fe9e45abefd92b4aa3d78b6be777/packages/api/src/providers/fitbit.ts) to Fitbit documentation, and **only** the heart rate data endpoint uses the timezone query parameter.

fix(dapi): user's timezone converted to utc for weight logs and heart rate data

---

packages/api/src/command/connected-user/save-connected-user.ts

Ref. metriport/metriport-internal#695
none
Alter `updateProviderData()` to not use Sequelize's `.save()`, it gave us `OptimisticLockError`.
Context: https://metriport.slack.com/archives/C04GEQ1GH9D/p1690041960129549
- ⚠️ This is pointing to `master`, deploying in `production`.
- asap

fix: revert sequelize .save() to .update()

---

packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/sidechain-fhir-converter-connector.ts

Ref. metriport/metriport-internal#907
none
Fix FHIR converter env var, it was getting the internal address w/o the protocol, and Axios is converting it to `http://localhost/...`
- asap
- merge this
- merge `master` into `develop`

PATCH RELEASE 907 fix converter env var

---

packages/api/src/shared/typescript.ts
packages/api/tsconfig.json
tsconfig.json

Ref. metriport/metriport-internal#699
- Related: https://github.com/metriport/metriport-internal/pull/917
Add Expand and ExpandRecusively util types (for debugging/local purposes only).
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1690069914612819

699 add Expand and ExpandRecusively util types

---

docs/devices-api/getting-started/connect-widget.mdx
packages/connect-widget/src/pages/connect/index.tsx
packages/connect-widget/src/pages/error/index.tsx
packages/connect-widget/src/pages/success/index.tsx
packages/connect-widget/src/shared/constants.ts
packages/connect-widget/src/shared/localStorage/redirect-url.ts
packages/connect-widget/src/shared/util.ts

refs. metriport/metriport#711
- Added the query parameters `redirectUrl` and `failRedirectUrl` to the Widget, allowing the CX to redirect their users to their custom urls based on success/failure during provider connection in the widget.

feat(widget): added success and failure redirect urls to widget localStorage for provider connections

---

packages/api/src/external/commonwell/patient-duplicates.ts
packages/api/src/routes/medical/internal-patient.ts
packages/scripts/restart-api.sh

Ref: https://github.com/metriport/metriport-internal/issues/704
none
Check duplicated persons at CommonWell, returning the patients with duplicated persons per cx, along with when each was enrolled and by whom.
Example response from the endpoint:
Also fixes https://github.com/metriport/metriport-internal/issues/923, based on the work done on [this PR](https://github.com/metriport/metriport-internal/pull/924) for internal.
- nothing major, just a `GET` endpoint and a fix for CI/CD

PATCH RELEASE 704 check duplicated persons at CW

---

packages/api/src/command/connected-user/get-connected-user.ts
packages/api/src/command/webhook/fitbit.ts
packages/api/src/mappings/fitbit/index.ts
packages/api/src/providers/fitbit.ts
packages/api/src/providers/oauth2.ts
packages/api/src/routes/devices/internal-user.ts
packages/api/src/routes/middlewares/oauth2.ts

refs. metriport/metriport#735
- Before we create new WH subscriptions, we now check if they already exist for the Fitbit user
- If other users found to be connected to this Fitbit User, we revoke their tokens and delete their WH subscriptions. Then we re-create the subscriptions based on the new connected user's scopes.
- WH subscription IDs are now built from the Fitbit user ID, instead of the Metriport user ID. 
- Merge this
- Hit this route on prod: `internal/user/resubscribe-fitbit-webhooks`

fix(dapi): fixed the issue of multiple metriport users connecting the same fitbit account

---

packages/api/src/command/connected-user/get-connected-user.ts
packages/api/src/command/webhook/fitbit.ts
packages/api/src/mappings/fitbit/index.ts
packages/api/src/providers/fitbit.ts
packages/api/src/providers/oauth2.ts
packages/api/src/routes/devices/internal-user.ts
packages/api/src/routes/middlewares/oauth2.ts

Ref: #_[735]_(https://github.com/metriport/metriport/issues/735)
Ref: #_[747]_(https://github.com/metriport/metriport/issues/747)
- Multiple users from the same CX connecting to the same Fitbit user is now managed properly
- One user connecting to the same Fitbit user from 2 different CX is now managed properly and WH payloads are now sent to both CX
- New internal route that allows us to create WH subscriptions to existing users who connected to Fitbit before WH were implemented
- THIS IS POINTING TO MASTER!
- Merge this
- Hit the following endpoints on prod:  `internal/user/refresh-tokens` followed by `internal/user/resubscribe-fitbit-webhooks`

PATCH RELEASE 2023 08 06

---

docs/devices-api/sdks/connect-widget/react-native.mdx

Ref: metriport/metriport-internal#940
n/a
update to include expo instructions for dapi
asap

docs: update to include expo instructions for dapi

---

.husky/pre-commit
package.json

Ref. metriport/metriport-internal#934
- related: https://github.com/metriport/metriport-internal/pull/938
Add [gitleaks](https://gitleaks.io/) to prevent secrets on remote.
It runs as a Git hook (pre-commit) triggered by Husky.
We're using the `protect` command to check code that's being pushed to remote (it relies on `git diff`). Other commands, including `detect` that checks code using `git log` or folders, can be seen [here](https://github.com/gitleaks/gitleaks#commands).
We're running it using Docker (slower) so its easier to setup now. If we want we can use the Go version compiled to the local OS, it should be faster (albeit requiring more initial setup). Let's see how this goes and I can adjust if needed.
- nothing special other communicate this to other devs

934 add gitleaks to prevent secrets on remote

---

.github/workflows/_deploy_api.yml
.vscode/settings.json
package-lock.json
package.json
packages/api-sdk/tsconfig.json
packages/api/tsconfig.json
packages/commonwell-cert-runner/tsconfig.json
packages/commonwell-jwt-maker/tsconfig.json
packages/commonwell-sdk/tsconfig.json
packages/connect-widget/tsconfig.json
packages/infra/tsconfig.json
packages/lambdas/tsconfig.json
packages/react-native-sdk/tsconfig.json
packages/utils/tsconfig.json
tsconfig.json

Ref: https://github.com/metriport/metriport-internal/issues/944
- upstream: none
- downstream: TBD
- do not exclude tests on tsconfig 
- typescript only as dev dependency 
- re-enable Sentry's GH Action

944 ts fixes

---

packages/api/src/command/medical/patient/get-patient.ts

refs. metriport/metriport#767
n/a
split patient names before dedup
asap

fix(api): split patient names before dedup

---

packages/connect-widget/public/index.html

refs. metriport/metriport-internal#881
- Widget's meta tag updated from "Web site created using create-react-app" to "Connect Widget for Healthcare Data Providers"

fix(widget): description meta tag updated

---

packages/api/src/mappings/fitbit/index.ts
packages/api/src/providers/fitbit.ts
packages/api/src/providers/oauth2.ts
packages/api/src/routes/devices/internal-user.ts

Ref: #_[ticket-number]_(https://github.com/metriport/metriport/issues/747)
Ref: #_[ticket-number]_(https://github.com/metriport/metriport/issues/735)
- Improved the way we get existing subscriptions 
- Improved how we handle the errors
- Strong typing for more variables
- Error reporting fixed for the internal route
- THIS IS POINTING TO MASTER!
- Merge this
- Run `internal/user/refresh-tokens` followed by `internal/user/resubscribe-fitbit-webhooks`

PATCH RELEASE 2023 08 10

---

packages/api/src/external/commonwell/admin/find-patient-duplicates.ts

Ref. metriport/metriport#704
- Upstream: https://github.com/metriport/metriport/pull/777
Fix after the test on upstream: https://github.com/metriport/metriport/pull/777#issuecomment-1676137636
- nothing special, asap to get to the release train

704 fix find duplicated person display enrolment

---

packages/api/src/command/connected-user/get-connected-user.ts
packages/api/src/command/webhook/fitbit.ts
packages/api/src/providers/fitbit.ts
packages/api/src/providers/provider.ts

refs. metriport/metriport#774
- Instead of getting the access token in `getActivityData` and similar functions, we now get it once for each user in the WH notification and pass it over

fix(dapi): fitbit wh get/refresh access token once per user

---

packages/api/src/command/medical/docref-mapping/get-docref-mapping.ts
packages/api/src/models/db.ts

Ref. metriport/metriport#699
none
Fix docref-mapping sequelize setup and create
Context: https://metriport.slack.com/archives/C04T256DQPQ/p1692050898168939
- asap

PATCH RELEASE 699 fix docref-mapping sequelize setup and create

---

packages/api/src/mappings/fitbit/models/food.ts

refs. metriport/metriport-internal#956
- Made a few food attributes nullish in the schema based on [Fitbit docs](https://dev.fitbit.com/build/reference/web-api/nutrition/create-food-log/#:~:text=logged%2Din%20user.-,Query%20Parameters,-foodId)
- THIS IS POINTING TO MASTER

fix(dapi): fitbit loggedFood.locale nullish

---

packages/api/src/command/webhook/fitbit.ts

refs. metriport/metriport#774
- Added `JSON.stringify` to a log statement for better readability of the processes

fix(dapi): stringified objects in logs

---

.github/workflows/_deploy_widget.yml
.github/workflows/branch-to-staging.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
packages/scripts/deploy-widget.sh

Ref. metriport/metriport-internal#307
- Related: https://github.com/metriport/metriport-internal/pull/927
Add region to deploy script/GH workflow
- `WIDGET_CF_DISTRIB_ID_STAGING`
- `WIDGET_CF_DISTRIB_ID_PRODUCTION`

307 add region to deploy script/GH workflow

---

packages/api/src/routes/helpers/provider-route-helper.ts

Ref: https://github.com/metriport/metriport-internal/issues/963
- Upstream: https://github.com/metriport/metriport/pull/797
Fixes the issue at `getProviderDataForType` - [context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1692231923653749)

963 fix getProviderDataForType

---

packages/api/src/mappings/apple/body.ts

Ref: 799
- Downstream: https://github.com/metriport/metriport-ios-sdk/pull/15
Apple health sends decimals for percentages

fix(api): convert apple decimal to percentage

---

packages/api-sdk/src/devices/client/metriport.ts
packages/api-sdk/src/medical/client/metriport.ts

Ref: 799
We dont want to expose baseaddress in our sdk so i am removing it

fix(packages): remove baseadress from tsdoc

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/connect-widget/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/utils/package.json

Ref. metriport/metriport-internal#968
- Downstream: https://github.com/metriport/metriport-internal/pull/969
Update zod version to 3.22.1
- asap
- `staging`
- `production`

968 update zod version to 3.22.1

---

packages/infra/lib/api-stack.ts
packages/lambdas/src/fitbit-auth.ts
packages/lambdas/src/shared/capture.ts

Ref. metriport/metriport-internal#363
none
- increase fitbit auth timeout
- lower the rate at which we send trace info to Sentry
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1692630919307759

363 increase fitbit auth timeout

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
packages/api/src/routes/webhook/apple.ts

Ref. metriport/metriport-internal#672
Ref: 672
Run e2e script even if all the deploys dont run

fix(ops): run e2e regardless if other deploys do not

---

packages/api/src/mappings/oura/activity.ts
packages/api/src/mappings/whoop/models/cycle.ts
packages/api/src/mappings/whoop/models/recovery.ts

Ref: 799
Certain payloads are throwing zod errors in the console because they come back empty.

fix(api): handle empty payloads

---

packages/api/src/mappings/whoop/models/sleep.ts

Ref: 799
Issue here from zod https://metriport-inc.sentry.io/issues/4421333620/?alert_rule_id=14031188&alert_type=issue&project=4504912884924416&referrer=slack
Zod was throwing errors for whoop sleep because some values came back nullable

fix(api): make values nullable for whoop

---

packages/api/src/providers/tenovi.ts
packages/api/src/routes/middlewares/connect-device.ts
packages/api/src/routes/user.ts
packages/api/src/shared/constants.ts

refs. metriport/metriport#812
- Users can now revoke their token for Tenovi, which disconnects all their devices from the Tenovi Gateway, preventing any future webhooks from coming through
- Users can now delete one device at a time from their user

feat(dapi): added revoke token for tenovi

---

packages/api/src/external/commonwell/document/document-query-sandbox.ts

refs. metriport/metriport-internal#864
- We were lacking the query completion return on Sandbox for non-default patients, resulting in infinite requests to obtain their docs. This fixes the issue.

fix(dash): sandbox non-default patients query completes with no data

---

packages/api/src/routes/settings.ts

Ref. metriport/metriport-internal#1010
- Downstream: https://github.com/metriport/metriport-internal/pull/1011
Don't return empty WH status response

1010 don't return empty WH status response

---

packages/api/src/mappings/garmin/activity.ts
packages/api/src/mappings/garmin/bloodPressure.ts
packages/api/src/mappings/garmin/body-composition.ts
packages/api/src/mappings/garmin/respiration.ts
packages/api/src/mappings/garmin/sleep.ts
packages/api/src/shared/date.ts

Ref: metriport/metriport-internal#118
none
Rename `toISODate` to `secondsToISODate` to be more explicit about unit; especially b/c time is usually represented in milliseconds and not seconds.

118 rename toISODate to be explicit about unit

---

docs/mint.json

Ref: metriport/metriport-internal#895
Re-add "create patient consolidate" to docs menu
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1694022303449149

PATCH RELEASE re-add "create patient consolidate" to docs menu

---

packages/api/src/command/medical/document/document-redownload.ts
packages/api/src/external/commonwell/patient-shared.ts

Ref: https://github.com/metriport/metriport-internal/issues/846
none
Doc reprocess use subjectId for patient instead of contained.id

846 doc reprocess use subjectId for patient

---

packages/api/src/mappings/garmin/index.ts

Ref: metriport/metriport-internal#1035
Make Garmin overallSleepScore.value nullish

PATCH RELEASE make Garmin overallSleepScore.value nullish

---

packages/api/src/mappings/garmin/index.ts

Ref: metriport/metriport-internal#1037
Make Garmin sleepLevelsMap props nullish

PATCH RELEASE make Garmin sleepLevelsMap props nullish

---

packages/api/src/external/commonwell/__tests__/organization.ts

Ref: 799
https://metriport.slack.com/archives/C04DBBJSKGB/p1694284896308459
Issue above but the cwmembername not in prod so move into function

fix(api): move making cw api into functoin

---

packages/lambdas/src/cda-to-visualization.ts

refs. metriport/metriport#598
- The lambda was catching the error, but wasn't rethrowing it, which resulted in a return of broken URLs for doc downloads. 

fix(lambdas): fixed a bug in cda-to-vis lambda 

---

packages/api/src/routes/user.ts

refs. metriport/metriport-internal#1041
- No need to getConnectedUserOrFail on users that have already been fetched from the db
Sentry issue: https://metriport-inc.sentry.io/issues/4473462837/?alert_rule_id=14031188&alert_type=issue&notification_uuid=4c271dfd-663d-41fd-96c7-0fedc29a2ec0&project=4504912884924416&referrer=slack

fix(dapi): fixed a bug causing unnecessary db calls

---

docs/devices-api/sdks/connect-widget/react-native.mdx

Ref: 799
Some customers have issues updating the pod version, add a blurb in the docs to clarify

fix(docs): make clear the pod update for latest version

---

packages/api/src/command/usage/report-usage.ts
packages/api/src/external/commonwell/document/document-query.ts

refs. metriport/metriport-internal#1036
- Upstream: https://github.com/metriport/metriport-internal/pull/1042
- `POST /document/query` reports usage with a flag to indicate a document query for `per-doc-query` billing model
- The usage is reported only if at least 1 document was retrieved with the query
- Merge the upstream PR on internal
- Merge this

feat(mapi): altered usage reporting for post doc query

---

packages/api/src/routes/medical/__tests__/mapi/e2e/shared.ts

Ref: #799
Remove testid to not break prod (not being used now)

fix(api): remove testid

---

packages/api/src/external/fhir/document/index.ts

refs. metriport/metriport-internal#1054
- Now we'll get notified only when a new resource type shows up in CW docs contained, rather than for any ref to another resource without additional context

fix(mapi): updated the scenario for sentry alert

---

packages/infra/lib/api-stack.ts

Ref: 799
Remove alarm sns action for download lambda
Error reference
https://metriport.slack.com/archives/C04T256DQPQ/p1695182213373639

fix(infra): remove alarm for download lambda

---

packages/lambdas/src/document-downloader.ts

Ref: 799
Some doc references use text/xml so need to account for this in the if check
POINTING TO MASTER
ASAP

fix(api): fix doc query check for xml type

---

packages/api-sdk/src/medical/client/__tests__/metriport.test.e2e.ts
packages/api/src/external/fhir/__tests__/api.test.e2e.ts
packages/api/src/routes/__tests__/settings.test.e2e.ts
packages/api/src/routes/medical/__tests__/document.test.e2e.ts
packages/api/src/routes/medical/__tests__/fhir-r4/e2e/document.test.e2e.ts
packages/api/src/routes/medical/__tests__/fhir-r4/e2e/organization.test.e2e.ts
packages/api/src/routes/medical/__tests__/fhir-r4/e2e/patient.test.e2e.ts
packages/connect-widget/src/__tests__/connect.test.e2e.ts

refs. metriport/metriport-internal#1059
- Added jest timeouts of 15 seconds to all existing e2e tests
https://metriport.slack.com/archives/C04DBBJSKGB/p1695282996695729?thread_ts=1695282996.493279&cid=C04DBBJSKGB

fix(test): added 15 sec timeouts to all e2e tests

---

packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/sidechain-fhir-converter-connector.ts

refs. metriport/metriport-internal#1062
- Increasing the memory allocation for the SidechainFHIRConverterLambda to quickly improve coverage 
- Merge this
- Rerun DLQ jobs

fix(mapi): increased the memory capacity of SidechainFHIRConverterLambda

---

packages/infra/dashboards/cw-dashboard-prod.json
packages/infra/lib/api-stack.ts

refs. metriport/metriport-internal#1065
- WriteIOPS alarm threshold on fhir-server dashboards -> 100_000
https://metriport.slack.com/archives/C04DMKE9DME/p1695435636328739
- Update the prod dashboards to reflect the change

fix(mapi): increased iops alarm threshold to 100_000

---

.github/workflows/_e2e-tests.yml

Ref: 799
Quick fix for the e2e test, its not running because its missing the env type variable.

fix(api): add environment as env variable for test to listen too

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/domain/medical/patient-facility.ts

refs. metriport/metriport#923
- Checking if facility ID passed in by the user is in the list of facility IDs that the patient is associated with
- If this check fails, the document query never gets created for the patient and will not be stuck in `processing` state. 

fix(mapi): checkingif patient is associated with given facility

---

packages/api/src/routes/medical/patient.ts
packages/api/src/routes/medical/schemas/patient.ts

refs. metriport/metriport#922
- Fixed a bug introduced earlier that was caught during tests on staging - the patient update thru the dashboard got broken because of a difference in the update schema between the one that was being used on the API vs the one that we have on API-SDK. This PR reverts the change made earlier where I started using the one from API-SDK. 

fix(mapi): fixed a bug with patient update through the dashboard

---

packages/api/src/sequelize/migrations/2023-07-27_00_alter-facility-remove-facilityNumber.ts
packages/api/src/sequelize/migrations/2023-07-27_01_alter-patient-remove-patientNumber.ts

- Upstream: https://github.com/metriport/metriport/pull/681
Remove facility and patient number columns from the DB. They are not being used on code.
- ⚠️ Contains a DB migration
- Planning to merge this no earlier than August 31
- Also remove backup tables:
```sql
drop table "customer_sequence_704_20230720";
drop table "SequelizeMeta_704_20230720";
```

704 remove facility and patient number columns

---

packages/api/src/command/medical/admin/redrive-dlq.ts
packages/api/src/command/medical/admin/upload-doc.ts
packages/api/src/external/aws/sqs.ts
packages/api/src/routes/internal.ts
packages/api/src/shared/config.ts
packages/infra/lib/api-service.ts
packages/infra/lib/api-stack.ts
packages/lambdas/src/shared/sqs.ts
packages/lambdas/src/sqs-to-converter.ts
packages/utils/src/sqs/populate-sqs.ts

Ref: metriport/metriport-internal#1092
none
Add endpoint to redrive sidechain msgs from DLQ to the regular queue.

1092 add endpoint to redrive sidechain msgs from DLQ

---

packages/api/src/command/medical/admin/redrive-dlq.ts
packages/infra/lib/api-service.ts

Ref: metriport/metriport-internal#1092
- Upstream: https://github.com/metriport/metriport/pull/933
- allow API to RW to DLQ
- handle erros from getMessagesFromQueue
- infra changes
- asap

1092 allow API to RW to DLQ and handle errors

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/api/src/sequelize/migrations/2023-07-27_01_alter-patient-remove-patientNumber.ts
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/connect-widget/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/utils/package.json

Ref: https://github.com/metriport/metriport-internal/issues/1092
https://github.com/metriport/metriport/pull/933
https://github.com/metriport/metriport/pull/934
Add endpoint to redrive sidechain msgs from DLQ to the regular queue.
- Contains infra changes

RELEASE 2023-10-01

---

packages/api/src/command/medical/admin/peek-dlq.ts
packages/api/src/command/medical/admin/redrive-dlq.ts
packages/api/src/external/aws/s3.ts
packages/api/src/external/aws/sqs.ts
packages/api/src/models/db-dev.ts
packages/api/src/routes/internal.ts
packages/infra/lib/api-service.ts
packages/utils/src/sqs/populate-sqs.ts

Ref: metriport/metriport-internal#1095
none
- add endpoint to peek into a conversion DLQ
- also return a presigned download URL for easy review of the file
- also send the update for the redrive function so it deals with errors properly and return when no there's no message to process

1095 add endpoint to peek into DLQ

---

packages/infra/lib/api-stack.ts
packages/lambdas/src/cda-to-visualization.ts

Ref: #https://github.com/metriport/metriport-internal/issues/1102
- The CDA-to-Visualization lambda will not pass its timeout to the env vars, and the handler will use that to set the puppeteer timeout 

1102 cda to pdf increase timeout

---

packages/lambdas/src/cda-to-visualization.ts

refs. metriport/metriport-internal#1103
- Looks like the issue is rare enough that we don't need to dive too far into the details at this point
- [This solution](https://github.com/puppeteer/puppeteer/issues/2735#issuecomment-470309033) seems promising based on the popularity in that thread. 
- Using a pipe is arguably better than the default websocket anyway and has no drawbacks based on [this](https://stackoverflow.com/questions/54922756/what-are-the-advantages-and-disadvantages-of-connecting-puppeteer-over-pipe-inst).
- People are reportedly having this issue when converting to PDF some large images
- Merge this
- Monitor if the issue shows up again on Slack

fix(lambda): use pipe instead of websocket for puppeteer connection

---

.github/workflows/_deploy_cdk.yml
packages/infra/lib/api-stack.ts

Ref: https://github.com/metriport/metriport-internal/issues/799
none
Fix `_deploy_cdk` GH workflow, make it use `master` on sandbox too
Context: https://metriport.slack.com/archives/C04DBBJSKGB/p1696433688557939?thread_ts=1696430990.014879&cid=C04DBBJSKGB
- ASAP

build: deploy_cdk GH workflow to use master on sandbox too

---

packages/api/src/command/medical/patient/append-doc-query-progress.ts
packages/api/src/external/commonwell/document/document-query-sandbox.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/fhir-converter/converter.ts

Ref. metriport/metriport-internal#1098
Ref: 1098
There was an issue where when we downloaded a document and extracted b64 we were then also trying to convert that document to fhir. This is an issue as we can only convert xml and the extracted b64 in most instances is a pdf. 
Logic for decreasing total count converted
https://docs.google.com/spreadsheets/d/19B9nGAoJgzlG4hR41NQ-II9qq0Rt94p2VJxIpOaAKP0/edit#gid=0
Sentry error
https://metriport-inc.sentry.io/issues/4326963216/?alert_rule_id=14442454&alert_type=issue&notification_uuid=fb4e5b2c-4cbe-4d61-ada3-8fedfcc60192&project=4505252341153792&referrer=slack

fix(api): fix check for convert by looking at file type

---

packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/api-service.ts
packages/infra/lib/api-stack/ccda-search-connector.ts
packages/infra/lib/shared/open-search-construct.ts

none
Allow ingestion lambda to access OS secret
Context: https://metriport.slack.com/archives/C04T5Q9JHFX/p1696465042642929
- asap

build: allow ingestion lambda to access OS secret

---

packages/api/src/shared/config.ts
packages/core/package.json

none
Fix the script to run E2E tests on core (introduced in one of the last couple PRs). Context [here](https://metriport.slack.com/archives/C04FZ9859FZ/p1696517895400859?thread_ts=1696514103.592759&cid=C04FZ9859FZ).
Also remove a function not being used on API's Config.
- asap

1050 fix core's e2e script

---

packages/api/docker-compose.dev.yml
packages/api/src/external/fhir/document/search-documents.ts
packages/api/src/shared/config.ts
packages/core/package.json
packages/core/src/external/opensearch/file-searcher-direct.ts
packages/core/src/external/opensearch/file-searcher.ts

none
- Filter OpenSearch by cx and patientx
- Fix issue with docker-compose missing `core` package
- asap to fix docker-compose

1050 filter OS by cx and patient

---

packages/api/src/providers/tenovi.ts
packages/infra/dashboards/cw-dashboard-prod.json

Ref: metriport/metriport-internal#1118
none
Return 404 on device not found.
Also update the dashboard's source w/ an additional widget to list API responses.

1118 return 404 on not found

---

packages/infra/lib/api-stack/ccda-search-connector.ts

- Upstream: https://github.com/metriport/metriport/pull/964
Add master node for OS in prod to fix node count vs AZ count
Context: https://metriport.slack.com/archives/C04DBBJSKGB/p1696719838472629?thread_ts=1696719266.048889&cid=C04DBBJSKGB

PATCH RELEASE 1050 add master node for OS in prod

---

packages/lambdas/src/cda-to-visualization.ts

Ref. metriport/metriport-internal#1103
Ref: #1103
Issue with the conversion lambda timeing out and needed to add timeout to navigation and print pdf
https://metriport-inc.sentry.io/issues/4413933361/?alert_rule_id=14442454&alert_type=issue&notification_uuid=d30527ea-0489-4bc9-b6c2-5b1edf3bc5a6&project=4505252341153792&referrer=slack
Tested in staging with a large xml

1103 add timeout navigation and print

---

packages/api/src/external/fhir/patient/count-resources.ts
packages/api/src/routes/internal.ts
packages/api/src/routes/medical/patient.ts

none
Add internal endpoint to count FHIR resources per cx.
Move `/peek-sidechain-dlq` from POST to GET

1050 internal endpoint to count fhir resources per cx

---

packages/lambdas/src/sqs-to-converter.ts
packages/utils/src/sqs/populate-sqs.ts

none
- add dryRun to populate-sqs
- add log to sqs-to-converter when empty XML

1050 add dryRun to populate-sqs

---

packages/lambdas/src/sqs-to-converter.ts

Ref: #https://github.com/metriport/metriport-internal/issues/1145
- Added xml file processing prior to sending it to FHIR converters, which replaces `xsi:type="CD UNK"` with `xsi:type="CD"`. 

1145 cdunk to cd

---

packages/infra/lib/api-stack.ts
packages/infra/lib/shared/lambda.ts

Ref: metriport/metriport-internal#1169
none
- increase the memory of the CDA to Vis lambda from 512 to 1024MB
- add alternative to select architecture while creating a lambda, and test it w/ the tester lambda
- why: https://docs.aws.amazon.com/lambda/latest/dg/foundation-arch.html#foundation-arch-adv
- asap

1169 increase CdaToVisualization lambda memory

---

packages/api/src/command/medical/document/check-doc-queries.ts

Ref: metriport/metriport-internal#801
none
While testing the local document downloader I notices the query for patients to fix for doc query status is using a Postgres function that returns date, not datetime. Moved to `now()` and tested it local, it works better.

801 fix doc query checker to use now()

---

packages/api/src/command/medical/document/check-doc-queries.ts
packages/api/src/routes/medical/internal-patient.ts
packages/core/src/util/__tests__/concurrency.test.ts
packages/core/src/util/concurrency.ts
packages/utils/src/get-medication-list.ts
packages/utils/src/open-search/re-populate.ts

Ref: https://github.com/metriport/metriport-internal/issues/670
- Upstream: https://github.com/metriport/metriport/pull/994
Make `executeAsynchronously()` easier to use.

670 make executeAsync easier to use

---

package-lock.json
packages/api-sdk/package.json
packages/api-sdk/src/medical/client/metriport.ts
packages/api/src/command/medical/document/document-query.ts
packages/api/src/errors/bad-request.ts
packages/api/src/errors/metriport-error.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/patient-shared.ts
packages/api/src/routes/medical/document.ts
packages/api/src/routes/medical/internal-patient.ts
packages/api/src/shared/util.ts
packages/connect-widget/package.json
packages/core/src/util/error/metriport-error.ts
packages/lambdas/package-lock.json
packages/lambdas/package.json
packages/utils/src/bulk-query-patients.ts

Ref: https://github.com/metriport/metriport-internal/issues/1181
- Upstream: https://github.com/metriport/metriport/pull/1016
- Don't load all patients to trigger doc query
- Make facility optional to trigger doc query
- Create internal endpoint to load all patient IDs of a cx
- staging
- production

1181 dont load all patients to trigger doc query

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
packages/infra/dashboards/cw-dashboard-prod.json

Ref: metriport/metriport-internal#1064
none
Update CICD dependencies for packages/libs.
API relies on other packages through the filesystem, so if they change the API needs to be updated as well; but because the dependency is through the FS and not NPM, the actual folder of the API might not have been changes and it still needs to be redeployed.
This is different in the case of lambdas, which rely on a specific NPM version and, thus, need to have its `package.json` updated to make reference to said package's updates. Thus, lambdas/infra don't need to be deployed if there are changes to `core` but no change to lambda's `package.json`, for example.
Also updates the dashboard to include OpenSearch metrics.

1064 update CICD dependencies for packages/libs

---

.github/workflows/_deploy_cdk.yml
.github/workflows/branch-to-staging.yml

Branch to staging to use internal's feature branch instead of the default one (develop).
Currently, when one has a feature branch on OSS and related changes on the internal repo (configs), and wants to branch it to staging, they have to merge internal's change to `develop`, since CI/CD will pull internal repo's `develop` to get the configs.
This is not good since one might be midway through the development and not ready to merge to `develop` - and make a release to `prod`! Before it was not as bad as it its now, since we were grouping multiple PRs in one release …

branch-to-staging to use internal's feature branch

---

.github/workflows/_build.yml
.github/workflows/_check-commits.yml
.github/workflows/pull-request_api-sdk.yml
.github/workflows/pull-request_api.yml
.github/workflows/pull-request_commonwell-cert-runner.yml
.github/workflows/pull-request_commonwell-jwt-maker.yml
.github/workflows/pull-request_commonwell-sdk.yml
.github/workflows/pull-request_infra.yml
.github/workflows/pull-request_lambdas.yml
.github/workflows/pull-request_react-native-sdk.yml
.github/workflows/pull-request_utils.yml
.github/workflows/pull-request_widget.yml
README.md
package.json

none
Remove the commit lint verification from `develop`/`master` based CI/CD jobs. It's fine to check that on the feature PRs, where we can easily rewrite the commit history, but we shouldn’t block deploying once the changes made into the shared repos.
- changes the CI/CD, will test when merged, so it might break and need follow-up PR to fix
- asap
- once done, replicate this to the internal repo

1040 don't run commitlint on master/develop

---

packages/api/src/command/medical/document/__tests__/document-query_calculateAndUpdateDocQuery.test.ts
packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/document/document-redownload.ts
packages/api/src/command/medical/document/document-status.ts
packages/api/src/domain/medical/conversion-progress.ts
packages/api/src/domain/medical/document-query.ts
packages/api/src/routes/medical/__tests__/mapi/e2e/mapi.test.e2e.ts
packages/api/src/routes/medical/patient.ts
packages/utils/.gitignore

Ref: metriport/metriport-internal#1220
- Upstream: https://github.com/metriport/metriport/pull/1085
While testing the upstream PR I realized the internal endpoint was not creating a new doc ref, so I had to update `getOrGenerateRequestId()` to force it if we're skipping validation.
Then I found a bug and refactored the code to minimize the chances of new bugs related to doc query status:
- fix logic to generate new request ID
- concentrate logic to calculate doc query status
- remove circular dependency Patient <> DocumentQuery domain

1220 logic to generate new request ID

---

docs/medical-api/api-reference/document/post-upload-url.mdx
package-lock.json
packages/api-sdk/package.json
packages/api-sdk/src/index.ts
packages/api-sdk/src/medical/client/metriport.ts
packages/api-sdk/src/medical/models/document.ts
packages/api/package.json
packages/api/src/routes/medical/document.ts
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/connect-widget/package.json
packages/core/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/tester-node/package.json
packages/utils/package.json
packages/utils/src/document/document-upload.ts

Ref: https://github.com/metriport/metriport/issues/1088
- Deprecated the `upload-doc` route and corresponding SDK function. Added new corrected functions for replacement.
- Document Upload endpoint now also returns the DocRef ID alongside the upload URL
- Updated the docs accordingly
- Update SDK pkg
- Merge this

Document Upload - New endpoint and documentation updates

---

packages/api/src/command/medical/document/__tests__/document-query.test.ts
packages/api/src/command/medical/document/document-query.ts
packages/api/src/domain/medical/__tests__/document-query.ts

Ref: metriport/metriport-internal#1220
- Upstream: https://github.com/metriport/metriport/pull/1091
Add unit test to getOrGenerateRequestId. I did some tests on staging but thought it would be good to go through all permutations just to be safe.

1220 add unit test to getOrGenerateRequestId

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/routes/medical/internal-docs.ts

Ref: metriport/metriport-internal#1220
Bypass FF on internal doc query trigger
- asap

PATCH RELEASE #1220

---

packages/core/src/external/aws/appConfig.ts

none
Don't log FF contents, its too noisy.
For context, see [this log](https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#logsV2:log-groups/log-group/APIInfrastructureStack-APIFargateServiceTaskDefAPIServerLogGroup35E9518F-7A2oRfufKv3Z/log-events/APIFargateService$252FAPI-Server$252Fbf0406c399044d0c928ea1f6e8f4b98e$3Fstart$3D1698980656752$26refEventId$3D37888534725688643252297167981967795046756001947477016922).

1040 dont log FF contents

---

packages/utils/src/bulk-query-patients.ts

none
Use internal `POST /document/query` to bypass FF for Enhanced Coverage

1195 use internal POST docQuery to bypass FF

---

packages/api/src/external/commonwell/__tests__/organization.ts
packages/api/src/external/commonwell/admin/patch-patient-duplicates.ts
packages/api/src/external/commonwell/organization.ts
packages/api/src/external/commonwell/patient-shared.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/shared/log.ts
packages/core/src/util/__tests__/log.test.ts
packages/core/src/util/config.ts
packages/core/src/util/log.ts
packages/utils/src/commonwell/doc-query-shared.ts

Ref: metriport/metriport-internal#960
none
- delete dup person @ CW if created by us
- update `todo 1106`, enhanced coverage
- update log/debug code to minimize noise on cloud env
- staging

960 delete dup person @ CW

---

packages/api/src/providers/shared/oauth1.ts

None
Deprecate OAuth v1 - see why on the code.
Nothing special, no release should happen from this PR - only comments.

1040 deprecate OAuth v1

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/patient/delete-patient.ts
packages/api/src/domain/medical/patient-facility.ts
packages/api/src/external/commonwell/organization.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/routes/medical/internal-patient.ts
packages/api/src/routes/medical/patient.ts

none
- (Make our lives easier by) make `facilityId` optional on endpoints.
- remove multi-line logs to keep our logs/ops sane (it should be fixed by https://github.com/metriport/metriport-internal/issues/693)

1040 make facilityId optional on endpoints

---

package-lock.json
packages/api-sdk/package.json
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/connect-widget/package.json

Ref: https://github.com/metriport/metriport-internal/issues/1129
- Downstream: https://github.com/metriport/metriport-internal/pull/1238
Release alpha versions due to update on CW SDK
- @metriport/api-sdk@7.5.1-alpha.0
- @metriport/commonwell-cert-runner@1.9.18-alpha.0
- @metriport/commonwell-jwt-maker@1.6.18-alpha.0
- @metriport/commonwell-sdk@4.8.17-alpha.0
- connect-widget@1.6.1-alpha.0
- staging
- production

1129 release NPM packages

---

.github/workflows/fern-check.yml
packages/infra/lib/api-stack/ccda-search-connector.ts

Ref: metriport/metriport-internal#1240
none
Increase memory of CCDAOpenSearchLambda from 512 to 1024 MB
Also renamed the Fern check so we know what's about when we look at the PR's checks - this is what it looked like:

1240 increase memory of CCDAOpenSearchLambda

---

package-lock.json
packages/api/package.json
packages/api/src/command/medical/organization/__tests__/create-organization.test.ts
packages/api/src/domain/__tests__/base-domain.ts
packages/api/src/domain/medical/__tests__/location-address.ts
packages/api/src/domain/medical/__tests__/patient.ts
packages/api/src/external/commonwell/__tests__/error-categories.test.ts
packages/api/src/routes/medical/__tests__/document.test.e2e.ts
packages/api/src/routes/medical/__tests__/fhir-r4/e2e/patient.test.e2e.ts
packages/core/src/external/fhir/__tests__/patient.ts

Tickets:
- https://github.com/metriport/metriport-internal/issues/1096
- https://github.com/metriport/metriport/issues/420
none
- Fix FHIR E2E test
- Remove `@ngneat/falso` - use only one test/mocking library
- nothing special, only unit and E2E tests

1096 fix FHIR E2E test

---

packages/core/src/util/__tests__/env-var.test.ts
packages/core/src/util/env-var.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/ccda-search-connector.ts
packages/infra/lib/api-stack/cw-enhanced-coverage-connector.ts
packages/infra/lib/api-stack/doc-query-checker.ts
packages/infra/lib/api-stack/document-upload.ts
packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/fhir-server-connector.ts
packages/infra/lib/api-stack/sidechain-fhir-converter-connector.ts
packages/infra/lib/ihe-stack.ts
packages/infra/lib/shared/lambda.ts
packages/infra/lib/shared/sqs.ts
packages/lambdas/src/document-downloader.ts
packages/lambdas/src/shared/capture.ts
packages/lambdas/src/shared/env.ts
packages/lambdas/src/sqs-to-fhir.ts

none
While working on #1195 I needed to check if the environment is staging. This should be simple, but it turns out we've been duplicating code over and over again, because we didn't want to create shared functions that would move the acquisition of the `ENV_TYPE` var from the lambda code to some shared code - which increases the chance of runtime error.
So I took the plunge and made `ENV_TYPE` required to create lambdas - and created shared functions to check the environment type.
- infra changes
- validate on staging executing each lambda individually

1195 make envType required to build lambdas

---

packages/api/src/external/commonwell/cq-bridge/coverage-enhancement-init.ts
packages/api/src/routes/medical/internal-patient.ts
packages/api/src/routes/schemas/shared.ts
packages/api/src/routes/schemas/uuid.ts
packages/api/src/shared/config.ts
packages/core/src/domain/auth/cookie-management/cookie-manager-on-secrets.ts
packages/infra/lib/api-stack/api-service.ts
packages/utils/src/commonwell/session-manager.ts

- fix API access to cookie secret
- accept list of patient IDs for EC
- make env var name the same across services
- add stringListFromQuerySchema

PATCH RELESE 1195 fix API access to cookie secret

---

packages/core/src/domain/document-query/trigger-and-query.ts
packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
packages/core/src/external/commonwell/cq-bridge/coverage-enhancer.ts
packages/utils/src/commonwell/enhance-coverage.ts

none
- doc query once on EC - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1699890950486569)
- don't stop EC on error - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1699892625200759)
- asap

PATCH RELEASE 1195 doc query once on EC + dont stop EC on error

---

packages/api/src/command/medical/patient/calculate-patient-similarity.ts
packages/api/src/external/aws/appConfig.ts
packages/api/src/external/commonwell/cq-bridge/coverage-enhancement-check-stale.ts
packages/api/src/external/commonwell/patient.ts
packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts

none
- only set cqLinkStatus=unlinked when FF is set for cx
- log patient IDs on EC flow
- merge/release this
- update patients from cxs not with EC FF enabled so their `cqLinkStatus` is undefined

1195 only set cqLinkStatus=unlinked when FF is set for cx

---

packages/api/src/command/medical/patient/calculate-patient-similarity.ts
packages/api/src/external/aws/appConfig.ts
packages/api/src/external/commonwell/cq-bridge/coverage-enhancement-check-stale.ts
packages/api/src/external/commonwell/patient.ts
packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts

Ref: https://github.com/metriport/metriport-internal/issues/1195
PR: https://github.com/metriport/metriport/pull/1171

RELEASE 1195

---

packages/infra/lib/api-stack.ts

refs. metriport/metriport-internal#1234
n/a
bump fhir to mr lambda to 4gb
asap

PATCH RELEASE - bump fhir to mr lambda to 4gb

---

packages/api/src/external/commonwell/patient-updater-commonwell.ts
packages/infra/dashboards/cw-dashboard-prod.json
packages/infra/lib/api-stack.ts

related: https://github.com/metriport/fhir-server/pull/41
- parallel patient updates @ CW from 10 to 20
- increase API DB's volume IOPS alarms

1195 parallel patient updates @ CW from 10 to 20

---

.github/workflows/_deploy_cdk.yml

none
When building infra, checkout internal from `develop` or feature branch based on whether the feature branch exist on internal or not.
- asap

1195 checkout internal from develop or feature branch

---

.github/workflows/_deploy_cdk.yml

Ref: https://github.com/metriport/metriport/pull/1197
- changing ci/cd to use SERVICE_PAT instead eof GITHUB_TOKEN to check if internal branch exists for branch to staging

feat(cicd): switch for service_pat

---

package-lock.json
packages/api-sdk/package.json
packages/api-sdk/src/index.ts
packages/connect-widget/package.json
packages/tester-node/package.json

Ref: metriport/metriport#1235
none
Just deploy a new version of the SDK so `latest` is not pointing to the alpha version generated by Fern.
- staging
- production

1235 new line to get new version of api-sdk

---

packages/api/src/external/commonwell/__tests__/organization.ts
packages/api/src/external/commonwell/organization.ts
packages/api/src/external/commonwell/patient-shared.ts
packages/api/src/external/commonwell/patient.ts

none
Reverting the change I did a few weeks ago which stopped logging responses from CW. While we don't want to log those multiline to prevent trashing our logs, there's value to having those somewhere in case something goes wrong while integrating with CW.
This re-enables those even on cloud env, but one single line.

1195 log responses from CW

---

docs/medical-api/more-info/webhooks.mdx
packages/api/src/external/commonwell/__tests__/organization.ts
packages/api/src/external/commonwell/organization.ts
packages/api/src/external/commonwell/patient-shared.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/routes/medical/internal-patient.ts
packages/utils/src/bulk-insert-patients.ts
packages/utils/src/commonwell/enhance-coverage.ts
packages/utils/src/customer-requests/get-exams.ts

Ref: metriport/metriport#1040
none
Fix issues found when running AWE last night + add the AWE script itself.
- do not run EC w/o cxId
- local EC do not send WH by default
- bulk insert w/ more flexible column names
- add get-exam script
- update docs so CXs know they should expect more than one WH for requested data - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1699313863011839?thread_ts=1699312935.047899&cid=C04DMKE9DME)

1040 do not run EC w/o cxId + other goodies

---

packages/api/src/external/commonwell/__tests__/organization.test.ts
packages/api/src/external/commonwell/organization.ts
packages/api/src/routes/internal.ts

- Upstream: https://github.com/metriport/metriport/pull/1215
Create endpoint to reset CQ bridge include list 

1195 create endpoint to reset CQ bridge include list

---

packages/core/src/external/commonwell/cq-bridge/coverage-enhancer.ts
packages/core/src/external/commonwell/management/api.ts

none
- add more CQ org chunks to EC from 4 to 6 (300 orgs)
- increase timeout on CW Include List from 3 to 5min
- asap

1195 add more CQ org chunks to EC

---

packages/infra/lib/api-stack/cw-enhanced-coverage-connector.ts

Update EC schedule to run every 15min instead of 30min.
- nothing special other than that

PATCH RELEASE 1195 update ec run schedule

---

packages/api/src/routes/medical/internal-patient.ts

Move `GET /internal/.../states` endpoint from using body to query params

PATCH RELEASE fix /states endpoint

---

packages/core/src/domain/patient/patient-loader-metriport-api.ts
packages/infra/lib/api-stack/cw-enhanced-coverage-connector.ts

Ref: metriport/metriport#1195
none
Fix call to `GET /states`, did this local while running EC and forgot to push with the previous fixes
Increase the EC window so it runs every 20min instead of 15 - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1700791758967409?thread_ts=1700759304.075919&cid=C0616FCPAKZ).

1195 fix call to GET /states

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/external/commonwell/cq-bridge/coverage-enhancer-api-local.ts
packages/api/src/external/commonwell/cq-bridge/cq-link-status.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/patient-external-data.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/external/patient-external.ts
packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
packages/core/src/util/capture.ts
packages/utils/src/commonwell/enhance-coverage.ts

Ref: metriport/metriport#1192
- downstream: https://github.com/metriport/metriport/pull/1243
- retry doc query if patient is not in sync w/ HIE
- enable DQ for cx with EC enabled
- merge this
- merge master into develop

PATCH RELEASE 1192 retry doc query if patient is not in sync w/ HIE

---

package-lock.json
packages/api/src/command/medical/patient/get-patient.ts
packages/utils/.gitignore
packages/utils/package.json
packages/utils/src/bulk-insert-patients.ts
packages/utils/src/bulk-query-patients.ts
packages/utils/src/commonwell/coverage-assessment.ts
packages/utils/src/commonwell/cq-org-builder.ts
packages/utils/src/commonwell/cq-org-grouper.ts
packages/utils/src/commonwell/enhance-coverage.ts
packages/utils/src/customer-requests/get-exams.ts
packages/utils/src/get-medication-list.ts
packages/utils/src/shared/get-cx-data.ts

Ref: metriport/metriport#1040
- related: https://github.com/metriport/metriport-internal/pull/1289
- downstream: https://github.com/metriport/metriport/pull/1233
- move coverage assessment from internal to here
- start getting env data from the API instead of env vars
- bulk insert more reliable to process phone
- add npm script for utils
- update a few API commands to return interface instead of model

1040 move coverage assessment from internal to OSS

---

packages/api/src/routes/internal.ts
packages/utils/src/commonwell/coverage-assessment.ts
packages/utils/src/commonwell/enhance-coverage.ts
packages/utils/src/shared/get-cx-data.ts

Ref: https://github.com/metriport/metriport/issues/1040
- Upstream: https://github.com/metriport/metriport/pull/1232
Get cx data for scripts from internal endpoint instead of env vars
- merge upstrem
- merge this

1040 get cx data for scripts from internal endpoint

---

packages/api/src/command/medical/document/document-download.ts
packages/api/src/external/carequality/api.ts
packages/api/src/external/carequality/organization.ts
packages/api/src/routes/medical/internal-cq.ts

refs. metriport/metriport-internal#1265
refs. https://github.com/metriport/metriport-internal/issues/1297
- Sandbox is failing to initiate Carequality SDK. This makes it so sandbox does not attempt to do so anymore.
- Document download signed url expiration time increased from 1 to 5 min
- ASAP

fix(cq): bug fix for sandbox

---

packages/infra/lib/api-stack/api-service.ts

none
Allow API to access API GW and get usage plan info
Context: https://metriport.slack.com/archives/C04DMKE9DME/p1701189462131629
- asap

1154 allow API to access API GW and get usage plan info

---

packages/api/src/command/medical/admin/api.ts
packages/api/src/shared/config.ts
packages/infra/config/env-config.ts
packages/infra/lib/api-stack/api-service.ts

- Upstream: https://github.com/metriport/metriport-internal/pull/1300
Add API GW usage plan ID to env vars

1154 add API GW usage plan ID to env vars

---

packages/api/src/command/medical/admin/api.ts

Fix api quota checker comparing missing data. Didn't hit this while testing on staging.
- nothing special other than that

PATCH RELASE 1154 fix api quota checker comparing missing data

---

packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/patient-external-data.ts
packages/api/src/shared/log.ts
packages/core/package.json
packages/shared/src/common/__tests__/retry.test.ts
packages/shared/src/common/error.ts
packages/shared/src/common/retry.ts
packages/shared/src/index.ts

none
Don't error when no CW data and EC is on
Why: https://metriport.slack.com/archives/C04T256DQPQ/p1701453114033979?thread_ts=1701440231.797879&cid=C04T256DQPQ

1195 don't error when no CW data and EC is on

---

packages/api/src/app.ts

Refs: #000
- node max payload size going from 2mb to 20mb. Causing issues for cx with lots of patient data on bulk download

PATCH RELEASE bump up max node payload size

---

packages/infra/lib/api-stack/ccda-search-connector.ts

Ref: metriport/metriport-internal#1323
none
Increase memory of the OpenSearch ingestion lambda, CCDAOpenSearchLambda.

1323 increase OS lambda memory

---

packages/infra/lib/api-stack/fhir-converter-connector.ts
packages/infra/lib/api-stack/fhir-server-connector.ts
packages/infra/lib/api-stack/sidechain-fhir-converter-connector.ts

Fix issue with lambdas retying to many times and causing recursion errors - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1702067501378549)
none

PATCH: fix retry count to avoid recursion

---

packages/api-sdk/src/medical/client/metriport.ts

Line 182:21:  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions
_[Document your changes, give context for reviewers, add images/videos of UI changes]_
- Local
- Staging
- Production
_[This is the release plan for production]_
_[You should execute the exact same steps when releasing to staging to validate it works]_
_[Add and remove items below accordingly]_
- _step1_
- _step2_

fixed a linter error

---

package-lock.json
packages/api-sdk/package.json
packages/connect-widget/package.json
packages/tester-node/package.json

none
Publish API SDK after the fix sent by [yuanzhaoYZ](https://github.com/yuanzhaoYZ) [here](https://github.com/metriport/metriport/pull/1310).

799 publish API-SDK

---

.github/workflows/_deploy_cdk.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
packages/api/src/external/aws/address.ts
packages/api/src/shared/config.ts
packages/infra/bin/infrastructure.ts
packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/api-service.ts
packages/infra/lib/location-services-stack.ts

ticket: https://github.com/metriport/metriport-internal/issues/1302
- Upstream: https://github.com/metriport/metriport-internal/pull/1347
- Infra update to allow sandbox to create the place index for prod 
- Prod can now use its own place index from the sandbox region
- Local 
- Staging 
- Production

feat(infra): added sandbox and prod place index generation in cdk

---

packages/utils/src/query-to-s3.ts

Ref: metriport/metriport-internal#1320
none
Update the query-to-s3 script to include num days on name.
Had to update it while running it [here](https://metriport.slack.com/archives/C04DBBJSKGB/p1702170712955579) so we could break the query/file generation in smaller batches.
- nothing special, already executed in prod

1320 update the query-to-s3 script to include num days on name

---

packages/api/src/external/commonwell/patient-conversion.ts

refs. metriport/metriport-internal#1359
Removing everything besides numbers from phone number strings before sending them to CW
- Local
- ASAP

PATCH RELEASE 2023-12-13

---

packages/api/src/external/commonwell/patient-conversion.ts

refs. https://github.com/metriport/metriport-internal/issues/1359
- Removing everything besides numbers from phone number strings before sending them to CW
- Local: The function takes the last 10 digits in longer phone numbers
- Production: Used `PUT /patient/:id` to make sure patients are matched to CW with these 10-digit strictly numeric phone numbers
- ⚠️ Points to master
- ASAP

fix(mapi): phone num 10 digits long

---

packages/core/src/external/commonwell/cq-bridge/coverage-enhancer.ts
packages/infra/lib/api-stack/cw-enhanced-coverage-connector.ts

none
Increase time between ECs from 20 to 25min
none

PATCH RELEASE 1195

---

packages/api/src/app.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/event/index.ts
packages/api/src/event/medical/patient-event.ts
packages/api/src/external/commonwell/cq-bridge/patient-event-listener.ts
packages/api/src/external/commonwell/events.ts
packages/api/src/routes/helpers/request-logger.ts
packages/api/src/shared/notifications.ts
packages/core/src/external/commonwell/cq-bridge/coverage-enhancer-local.ts
packages/core/src/util/concurrency.ts
packages/core/src/util/notifications.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1354
none
- Enable EC upon patient update
- Introduce NodeJS events 🎉 
- Some goodies from a [PR put on hold](https://github.com/metriport/metriport/pull/1344)
- Include req ID on request logger
- Allow `capture.error()` to be passed a string
- Reuse core's capture/notif on API
- Local
- Staging
- Production

1354 enable EC upon patient update

---

packages/infra/lib/shared/open-search-construct.ts

- Upstream: https://github.com/metriport/metriport/pull/1352
Fix FreeStorageSpace alarm on OpenSearchConstruct, adjust the comparison to "lower than".
- Local
- none
- Staging
- Production

1040 fix FreeStorageSpace alarm on OpenSearchConstruct

---

package-lock.json
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/api-service.ts
packages/infra/package.json

- Upstream: https://github.com/metriport/metriport/pull/1350
Fix ACU alarm, it was missing the action when the alarm triggers.
To prevent this from happening again, I created a function to create DB alarms that always adds actions to each alarm created.
While I was there, removed some left-over comments from stuff we were going to do but decided not to.
- Local
- none
- Staging
- Production

1040 add action to ACU RDS alarm

---

packages/infra/bin/infrastructure.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/ihe-stack.ts
packages/infra/lib/shared/lambda-layers.ts
packages/utils/tsconfig.json

none
Lambda layers not shared across stacks
- Local
- Staging
- Production
- none

1040 lambda layers not shared across stacks

---

package.json
packages/core/src/util/capture.ts
packages/core/src/util/notifications.ts

none
Core's notif to use unknown instead of any on `error()`.
Also adjust the color of `Tests passed` to stand out more.
nothing, just expect a new deploy on `staging` to mark the release w/ successful as such

1040 core's notif to use unknown instead of any on error()

---

.github/workflows/branch-to-staging.yml

none
Include ConnectWidget's infra on branch to staging.
Noticed it was not being included when debugging [this run](https://github.com/metriport/metriport/actions/runs/7304072823).
- Local
- Staging
- none
- Production
- none

1040 include ConnectWidget's infra on branch to staging

---

packages/api-sdk/src/medical/client/metriport.ts
packages/api/src/command/medical/patient/add-coordinates.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/routes/medical/internal-patient.ts
packages/utils/src/update-patients.ts

refs. metriport/metriport-internal#1326
- Downstream: https://github.com/metriport/metriport/pull/1323
- Added a script and an internal route to trigger all patient updates, which will add geo coordinates
- Made the facilityId an optional param in the patient update SDK func
- Local
- Staging

fix(mapi): update patient to add coordinates

---

packages/api/src/command/medical/docref-mapping/get-docref-mapping.ts
packages/api/src/command/medical/document/document-query-storage-info.ts
packages/api/src/command/medical/document/document-reconvert.ts
packages/api/src/command/medical/document/document-redownload.ts
packages/api/src/command/medical/patient/consolidated-delete.ts
packages/api/src/command/medical/patient/convert-fhir-bundle.ts
packages/api/src/external/fhir/document/__tests__/get-documents.test.ts
packages/api/src/external/fhir/document/get-documents.ts
packages/api/src/external/fhir/shared/extensions/doc-id-extension.ts
packages/api/src/external/fhir/shared/extensions/metriport.ts
packages/api/src/external/fhir/shared/index.ts
packages/api/src/external/sidechain-fhir-converter/connector-factory.ts
packages/api/src/providers/withings.ts
packages/api/src/routes/medical/dtos/documentDTO.ts
packages/api/src/routes/medical/internal-docs.ts
packages/api/src/routes/util.ts
packages/api/src/shared/types.ts
packages/core/src/util/concurrency.ts
packages/utils/src/open-search/re-populate.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1392
none
- re-convert doc refs 
- fix issue on Withings - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1703911302362379?thread_ts=1703905699.236099&cid=C04T256DQPQ)
- docRef toDTO use new `getMetriportContent`
- Local
- Staging
- Production

1392 re-convert doc refs

---

packages/api/src/command/medical/document/document-reconvert.ts
packages/api/src/command/medical/patient/consolidated-delete.ts
packages/api/src/routes/medical/internal-docs.ts

- Upstream: https://github.com/metriport/metriport/pull/1379
- Add dryRun
- Don't log consolidated after
- Consolidated by doc's patientId (so it logs even if no patient ID is sent)
- Local
- Staging
- upstream
- Production
- upstream

1392 add dryRun + adjust consolidated log

---

packages/api/src/command/medical/patient/consolidated-delete.ts
packages/api/src/command/medical/patient/consolidated-get.ts
packages/api/src/routes/medical/internal-patient.ts

- Upstream: https://github.com/metriport/metriport/pull/1381
- Do not log dryRun for each resource
- Allow to filter resources on getConsolidated by document ID
- Local
- Staging
- none
- Production
- none

1392 do not log dryRun for each resource

---

packages/lambdas/src/sqs-to-converter.ts

refs. metriport/metriport-internal#1392
N/A
make null flavor regex match on only `<id nullFlavor="NA" />` with any permutation of spaces between elements and NA characters
- Local

fix(api): fix null flavor regex

---

packages/api/src/command/medical/document/document-reconvert.ts

Use function to check for XML mime type.
Context: https://metriport.slack.com/archives/C04GEQ1GH9D/p1704063784180129?thread_ts=1703894243.751199&cid=C04GEQ1GH9D

PATCH RELEASE 1392

---

packages/api/src/command/medical/document/document-reconvert.ts
packages/api/src/command/medical/document/document-redownload.ts
packages/api/src/command/medical/document/document-webhook.ts
packages/api/src/command/medical/patient/webhook.ts
packages/api/src/external/fhir/document/get-documents.ts
packages/api/src/external/fhir/patient/index.ts
packages/api/src/external/fhir/shared/index.ts
packages/api/src/routes/medical/internal-docs.ts

none
- disable WH on re-convert
- query docs from FHIR server instead of docRefMappings
- Local
- Staging
- Production

build: disable WH on re-convert + query docs from FHIR server

---

packages/lambdas/src/document-downloader.ts

Ref: metriport/metriport-internal#1394
none
Increase timeout to download docs from CW.
- Local
- none
- Staging
- Production

1394 increase timeout to download docs from CW

---

package-lock.json
packages/api/package.json
packages/api/src/command/webhook/fitbit.ts
packages/api/src/command/webhook/garmin.ts
packages/api/src/command/webhook/tenovi.ts
packages/api/src/command/webhook/webhook.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/providers/fitbit.ts
packages/api/src/providers/shared/analytics.ts
packages/api/src/routes/helpers/request-analytics.ts
packages/api/src/routes/webhook/apple.ts
packages/api/src/shared/analytics.ts

Ref: metriport/metriport-internal#1406
- related: https://github.com/metriport/metriport-internal/pull/1407
Require apiType when sending analytics/posthog.
While working on [this PR](https://github.com/metriport/metriport-internal/pull/1407) and [this escalation](https://metriport.slack.com/archives/C04GEQ1GH9D/p1704761110968329) I checked Posthog and noticed lots of events coming from the API were missing the API Type.
- Local
- Staging
- Production

1406 require apiType when sending analytics/posthog

---

README.md
packages/infra/bin/infrastructure.ts
packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/lib/ihe-stack.ts
packages/infra/lib/shared/lambda.ts
packages/lambdas/src/document-query.ts
packages/lambdas/src/document-retrieval.ts
packages/lambdas/src/patient-discovery.ts

Ref: metriport/metriport-internal#1377
- Upstream: https://github.com/metriport/metriport-internal/pull/1415
- Keep IHE GW Stack separated from API Stack
- Update docs for IHE GW
- Support surfacing Metriport version to lambdas
- Local
- none
- Staging
- Production
- none

1377 keep IHE GW Stack separated from API Stack

---

packages/core/src/external/fhir/document/get-documents.ts

Ticket: 799
Issue where the doc ids where too  many and so the url to search ended up being too large

PATCH - 799 chunk fhir url length

---

packages/lambdas/package.json
packages/lambdas/scripts/build-shared-layer.sh

Refs: #1431
- patching error in cicd caused by dangling symlink to ihe-gateway-sdk repo

feat(symlink): delete dangling symlinks

---

packages/core/src/external/fhir/document/get-documents.ts

Ticket: 799
Issue where the doc ids where too  many and so the url to search ended up being too large

fix(api): chunk the doc ids by 200

---

packages/api/src/external/fhir/document/get-documents.ts
packages/core/src/external/fhir/document/get-documents.ts

Ticket: 799
Issue where the doc ids where too  many and so the url to search ended up being too large

PATCH fix(api): chunk the doc ids by 200

---

packages/api/src/external/fhir/document/get-documents.ts
packages/core/src/external/fhir/document/get-documents.ts

Ticket: 799
Issue where the FHIR docs werent getting queried because we didnt pass doc ids

PATCH: update the fhir get docs with defaults

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/patient/append-doc-query-progress.ts
packages/api/src/external/hie/append-doc-query-progress-with-source.ts
packages/core/src/external/index.ts

Ref:metriport/metriport-internal#799
Ticket: #799
- Upstream: None
- Downstream: None
Bug where the doc query progress within the hies wasnt being reset resulting in subsequent queries counting the aggregate total wrong.
- Local
- Staging
- Sandbox
- Production

fix(api): update the doc query to reset hies when startign

---

packages/fhir-converter/docker-compose.yml

Ticket:  metriport/metriport-internal#1441
n/a
add support for template reload in converter
- Local

chore: add support for template reload in converter

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts

Ticket: #[1441](https://github.com/metriport/metriport-internal/issues/1441)
- fixing social history observation section 
- Local

Update mr observation social history section 

---

packages/fhir-converter/src/lib/cda/cda.js
packages/fhir-converter/src/templates/cda/Resources/DiagnosticReport.hbs

be explicit about where b64 is used in the mapping - will be coded under `_b64` now, not just `_`

feat(api): be explicit about where b64 is used in the mapping

---

packages/api/src/command/medical/document/document-download.ts

refs. metriport/metriport-internal#760
Ticket: #_[ticket-number]_760
- CX uploaded docs will now pick the correct sandbox med docs bucket
- Local
- Sandbox
- Production 

PATCH RELEASE 2024-01-23

---

packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/api-service.ts
packages/infra/lib/shared/waf-rules.ts

refs. metriport/metriport#1525
N/A
Adds a WAF to the API for enhanced security.
- Staging
- Sandbox
- Production

feat(api): add waf

---

packages/api/src/external/fhir/references/get-references.ts
packages/api/src/external/fhir/shared/error-mapping.ts
packages/infra/lib/shared/sqs.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1143
- Upstream: https://github.com/metriport/metriport/pull/1518
- Downstream: https://github.com/metriport/metriport/pull/1522
- SQS' default `maxReceiveCount` from 1 to 5 - [why](https://docs.aws.amazon.com/lambda/latest/operatorguide/sqs-retries.html#:~:text=Set%20the%20maxReceiveCount%20on%20the%20source%20queue%E2%80%99s%20redrive%20policy%20to%20at%20least%205.%20This%20improves%20the%20chances%20of%20messages%20being%20processed%20before%20reaching%20the%20DLQ.)
- we override this in all queues we create, so there shouldn't be any impact
- couple small warning fixes 
- Local
- none
- Staging
- Production

1443 additional fixes

---

packages/api/src/command/medical/docref-mapping/remove-docref-mapping.ts
packages/api/src/command/medical/document/__tests__/document-query.test.ts
packages/api/src/command/medical/document/document-query.ts
packages/api/src/external/commonwell/cw-fhir-proxy.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/fhir/connector/connector-sqs.ts
packages/api/src/external/fhir/connector/connector.ts
packages/api/src/routes/helpers/request-logger.ts
packages/api/src/routes/medical/internal-docs.ts
packages/api/src/routes/medical/internal-patient.ts
packages/api/src/shared/log.ts
packages/core/README.md
packages/core/src/external/aws/lambda-logic/document-uploader.ts
packages/core/src/util/local-storage.ts
packages/core/src/util/log.ts

- Downstream: https://github.com/metriport/metriport/pull/1532
I was hoping to fix https://github.com/metriport/metriport-internal/issues/1455. While debugging I ended up doing some improvements:
- add AsyncLocalStorage and update logs to include the request ID 🤓 
- remove docRefMapping if fails to download docRef
- remove deprecated `updateDocQuery`:tada:
- move jobId create/decompose to single place
https://github.com/metriport/metriport-internal/issues/1455 will be done on another PR, the changes are larger than expected.
- Local
- Staging
- Sandbox
- none
- Production
- none

1040 Miscellaneous improvements/fixes

---

packages/api/src/command/medical/admin/db-maintenance.ts
packages/api/src/routes/internal.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/db-maintenance.ts

- Upstream: https://github.com/metriport/metriport/pull/1531
Add DB maintenance daily job - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1706403600770069).
- Local
- Staging
- Sandbox
- Production

1040 Add DB maintenance daily job

---

packages/fhir-converter/src/templates/cda/ccd.hbs

Ticket: https://github.com/metriport/metriport-internal/issues/1443
- Upstream: https://github.com/metriport/metriport/pull/1523
- harmless update on FHIRConverter to test CD gets triggered
- Staging
- Sandbox
- none
- Production
- none
- nothing special other than follow dependencies

1443 (3/3) harmless update on FHIRConverter

---

packages/api/src/command/medical/admin/upload-doc.ts
packages/api/src/external/commonwell/proxy/process-outbound.ts

- Upstream: https://github.com/metriport/metriport/pull/1539
Fix CW proxy build response
- Local
- Staging
- Sandbox
- none
- Production
- none

1040 fix CW proxy build response

---

packages/api/src/external/commonwell/proxy/process-outbound.ts
packages/lambdas/src/cw-doc-contribution.ts

none
- CW FHIR proxy include other resources
- CW contrib lambda removes leading forward slash for S3 key
- Local
- Staging
- Sandbox
- none
- Production
- none

1040 CW FHIR proxy include other resources

---

packages/api/src/command/medical/patient/add-coordinates.ts
packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/infra/bin/infrastructure.ts
packages/infra/config/env-config.ts
packages/infra/lib/api-stack/api-service.ts
packages/infra/lib/location-services-stack.ts

refs. metriport/metriport-internal#1447
- Upstream: https://github.com/metriport/metriport-internal/pull/1462
- Removed the AWS location service from sandbox
- Adjusted patient create and update to not try to add address coordinates on sandbox
- Local

fix(docs): no location service in sandbox

---

packages/lambdas/src/scheduled.ts

none
Make timeout optional on scheduled lambda - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1706644039383199?thread_ts=1706591878.808909&cid=C04DMKE9DME)
- Staging
- Sandbox
- none
- Production
- none

1040 Make timeout optional on scheduled lambda

---

packages/api/src/external/commonwell/proxy/process-inbound.ts
packages/api/src/external/commonwell/proxy/process-outbound.ts
packages/api/src/external/commonwell/proxy/shared.ts

Remove invalid query param from CW request
- Local
- Production

PATCH RELEASE remove invalid query param from CW request

---

packages/api/src/external/commonwell/proxy/__tests__/cw-fhir-proxy.test.ts
packages/api/src/external/commonwell/proxy/process-inbound.ts
packages/api/src/external/commonwell/proxy/process-outbound.ts
packages/api/src/external/commonwell/proxy/shared.ts

Avoid pagination on CW FHIR proxy - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1706753574921439?thread_ts=1706731392.225699&cid=C0616FCPAKZ)
- Local

PATCH RELEASE avoid pagination on CW FHIR proxy

---

samples/python-fast-api/create_patient_trigger_webhook.py

```
PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
@pydantic.validator("zip", always=True)
PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
content=patient.json(exclude_none=True),
```
A few small fixes for Pydantic warning messages.

Fix Pydantic Deprecations

---

packages/api/src/external/fhir/shared/json-validator.ts
packages/api/src/routes/medical/schemas/fhir.ts

Refs: #443
- customers were getting 500 errors when sending fhir bundles on PUT requests that were missing the resource object. 
- Local

feat(patch): fhir validation bug patch

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js
packages/fhir-converter/src/templates/cda/Resources/RelatedPerson.hbs

Ticket: #[1470](https://github.com/metriport/metriport-internal/issues/1470)
- there was a bug Ramil caught. I didn't rerun the whole 10k load after making small changes because it takes a long time, but should have done it at least without the FHIR insert and I would have easily seen the bug. I was testing with indiv files that happened to be outliers that were not triggering this error. 
- Local
Check each PR.

Patch 1442 bracket

---

.github/workflows/_deploy_cdk.yml
.github/workflows/deploy-production.yml

refs. metriport/metriport-internal#1447
n/a
remove location services from sandbox CI/CD
the release will test it as it's CICD changes

PATCH RELEASE 2024-02-04: remove location services from sandbox CI/CD

---

packages/fhir-converter/src/templates/cda/Sections/Medication.hbs
packages/fhir-converter/src/templates/cda/Sections/Procedures.hbs
packages/fhir-converter/src/templates/cda/Sections/Results.hbs
packages/fhir-converter/src/templates/cda/Utils/GeneratePractitionerId.hbs

Refs: #[1469](https://github.com/metriport/metriport-internal/issues/1469)
- https://github.com/metriport/metriport/pull/1566
- patching hapi 1096 bug
- `"diagnostics":"HAPI-1096: Resource Practitioner/4130df42-2908-3c82-a50b-60abc20f68b9 is deleted, specified in path: Observation.performer"`. Root cause of the bug is we generate a practitioner id for a practitioner that does not exist
- Local

HAPI-1096: Missing Provider Details

---

packages/fhir-converter/src/templates/cda/DataType/Address.hbs
packages/fhir-converter/src/templates/cda/DataType/CodeableConcept.hbs
packages/fhir-converter/src/templates/cda/DataType/Quantity.hbs
packages/fhir-converter/src/templates/cda/Resources/DiagnosticReport.hbs
packages/fhir-converter/src/templates/cda/Resources/DocumentReference.hbs
packages/fhir-converter/src/templates/cda/Resources/MedicationStatement.hbs
packages/fhir-converter/src/templates/cda/Resources/Observation.hbs
packages/fhir-converter/src/templates/cda/Resources/Procedure.hbs
packages/fhir-converter/src/templates/cda/Resources/RelatedPerson.hbs

- triple braces instead of double braces caused malformed json bug with unescaped html i.e `"Pen Needles 5/16"; 31G X 8 MM Miscellaneous"`in CodeableConcept.hbs field text 
- patching remaining triple braces bugs 
- In Handlebars templates, the difference between double braces {{ }} and triple braces {{{ }}} is how they handle HTML encoding.
- Double braces` {{ }}`: This is the standard syntax for Handlebars expressions. It automatically escapes HTML to prevent injection attacks. This means characters like <, >, ", ', and & are converted into their corresponding HTML entities (`&lt;, &gt;, &quot;, &#x27;, and &amp;`, respectively).
- Triple braces `{{{ }}}`: This syntax tells Handlebars to not escape the content. …

Patch: Triple Braces with unescaped quotes

---

packages/api/src/domain/medical/get-patient-limit.ts
packages/api/src/external/aws/appConfig.ts
packages/api/src/routes/medical/patient.ts
packages/api/src/shared/config.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/api-service.ts
packages/infra/lib/app-config-stack.ts

refs. metriport/metriport#1116
- Added feature flags to configure the limits for the number of sandbox patients per cx
- Local
- Staging
- Sandbox

feat(api): added feature flags to configure sandbox patient limits

---

packages/core/src/external/aws/lambda-logic/bundle-to-html.ts
packages/fhir-converter/src/lib/cda/cda.js
packages/utils/src/fhir-converter/convert-and-generate-mr.ts
packages/utils/src/fhir-converter/convert.ts

refs. metriport/metriport-internal#1496
n/a
- preserve formatting on doctor's notes by replacing `<br>` elements with `\n` instead of a space
- fix artifacts by decoding b64 in the MR summary in the same way we encode it, ie `utf-8`, not `binary`
- couple small util pathing fixes
- Local
- Production
```
Inserted 9446 files in 3628908 ms.
Resources:  {
AllergyIntolerance: 737,
Communication: 790,
Composition: 9411,
Condition: 12911,
Consent: 44,
Coverage: 558,
Device: 3830,
DiagnosticReport: 21796,
Encounter: 18460,
FamilyMemberHistory: 725,
Goal: 45,
Immunization: 2117,
MedicationAdministration: 3403,
MedicationRequest: 3261,
MedicationStatement: 4553,
Observation: 78392,
Procedure: 8898,
RelatedPerson: 269,
ServiceRequest: 1
}
Total resources: 170201
Total time: 3636362 ms / …
```

feat(api): preserve correct formatting on doctors notes, clean up arifacts on MR rendering

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/api/src/external/carequality/api.ts
packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts
packages/api/src/routes/medical/internal-cq.ts
packages/carequality-cert-runner/package.json
packages/carequality-sdk/package.json
packages/carequality-sdk/src/client/carequality.ts
packages/carequality-sdk/src/models/address.ts
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/tester-node/package.json
packages/utils/package.json

Ticket: #1350
add production url to carequality sdk
No testing and is only being used by internal routes triggered by us

fix(api): add production url to carequality sdk

---

packages/infra/lib/api-stack.ts

Ticket: #1040
- Upstream: 
MR lambda does not have access to appconfig
- Staging
- Production

fix(api): give mr lambda access to app config

---

packages/lambdas/src/sqs-to-converter.ts

Ticket: #799
Resources without id breaking post processing - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1707410757885269) 
- Local
- Production
Check each PR.

fix(api): 799 only replace if it has id

---

packages/api/src/command/medical/admin/upload-doc.ts
packages/api/src/command/medical/document/document-query-storage-info.ts
packages/api/src/external/carequality/document/process-document-query-results.ts
packages/api/src/external/commonwell/document/document-query-sandbox.ts
packages/api/src/external/commonwell/document/shared.ts
packages/api/src/external/fhir/document/draft-update-document-reference.ts
packages/api/src/routes/internal.ts
packages/api/src/routes/medical/document.ts
packages/api/src/routes/medical/internal-docs.ts
packages/api/src/shared/external.ts
packages/core/src/domain/document/filename.ts
packages/core/src/domain/document/upload.ts
packages/core/src/domain/filename.ts
packages/core/src/domain/medical-record-summary.ts
packages/core/src/external/aws/lambda-logic/document-uploader.ts
packages/core/src/external/aws/s3.ts
packages/core/src/external/fhir/shared/namespaces.ts
packages/core/src/util/mime.ts
packages/lambdas/src/cw-doc-contribution.ts
packages/utils/src/fhir-converter/shared.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1467
- downstream: https://github.com/metriport/metriport/pull/1560
- avoid error when querying empty DQ status - fixes https://github.com/metriport/metriport-internal/issues/1468
- fix duplicate documents on inbound DQs
- refactor code to name/parse file and document names
- now uploaded files also have the a file extension
- Local
- Staging
- Sandbox
- none
- Production
- none

1467 Fix Doc Contribution

---

packages/api/src/domain/medical/get-patient-limit.ts
packages/api/src/external/aws/appConfig.ts
packages/api/src/routes/helpers/default-error-handler.ts
packages/api/src/routes/util.ts
packages/core/src/external/aws/appConfig.ts

- Downstream: https://github.com/metriport/metriport/pull/1598
- FF patient limit not error on invalid number
- stable error messages on getFeatureFlagValue 
- default error logs include request ID 
- Local
- Staging
- none
- Sandbox
- Production
- none

1040 Sandbox patient limit FF doesn't error on invalid number

---

.vscode/launch.json
packages/api/src/app.ts
packages/api/src/external/aws/appConfig.ts
packages/core/src/external/aws/appConfig.ts

Ref. https://github.com/metriport/metriport-internal/issues/1437
- Upstream: https://github.com/metriport/metriport/pull/1597
API fail to start if it fails to load Feature Flags.
- Local
- Staging
- Sandbox
- Production

build: fail to start API if FFs fail

---

packages/fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js

Make these handlebars helpers safer for `undefined`:
- `getFirstCdaSectionsByTemplateId`
- `getAllCdaSectionsByTemplateId`
none

PATCH RELEASE safe handlebars helpers

---

.github/workflows/_ihe-gw-push-config.yml

none
Fix IHE GW push config GH workflow, env vars - [context](https://metriport.slack.com/archives/C04FZ9859FZ/p1707605230923729?thread_ts=1707603824.403399&cid=C04FZ9859FZ).
- Local
- none
- Staging
- Sandbox
- none
- Production
- none

1377 Fix IHE GW push config GH workflow

---

package-lock.json
packages/api/src/command/settings/updateSettings.ts
packages/api/src/command/webhook/webhook.ts
packages/api/src/external/aws/appConfig.ts
packages/core/src/external/aws/appConfig.ts

refs. metriport/metriport#1617
n/a
create ff for setting wh urls with no pong
- Staging
- Sandbox
- Production
add the following to AppConfig on AWS (and add the appropriate cxID on Sandbox + Prod):
```
{
"flags": {
...
"cxsWithNoWebhookPongFeatureFlag": {
"name": "cxsWithNoWebhookPongFeatureFlag",
"attributes": {
"cxIds": {
"type": "string[]"
}
}
}
},
"values": {
...
"cxsWithNoWebhookPongFeatureFlag": {
"enabled": true,
"cxIds": []
}
}
}
```

feat(api): create ff for setting wh urls with no pong

---

package-lock.json
packages/api-sdk/package.json
packages/api/package.json
packages/api/src/external/carequality/api.ts
packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts
packages/api/src/external/carequality/organization.ts
packages/api/src/routes/medical/internal-cq.ts
packages/api/src/shared/config.ts
packages/carequality-cert-runner/package.json
packages/carequality-sdk/README.md
packages/carequality-sdk/package.json
packages/carequality-sdk/src/client/carequality-api.ts
packages/carequality-sdk/src/client/carequality.ts
packages/carequality-sdk/src/index.ts
packages/commonwell-cert-runner/package.json
packages/commonwell-jwt-maker/package.json
packages/commonwell-sdk/package.json
packages/core/package.json
packages/ihe-gateway-sdk/package.json
packages/infra/config/env-config.ts
packages/infra/config/example.ts
packages/infra/package.json
packages/react-native-sdk/package.json
packages/shared/package.json
packages/utils/package.json

- Upstream: https://github.com/metriport/metriport-internal/pull/1514
- Added 2-way-TLS to CQ API as per the [IG requirements](https://carequality.org/healthcare-directory/security.html#tls).
- Local
- Staging
- Production

CQ-API 2-way-TLS

---

packages/api/src/command/medical/admin/upload-doc.ts

refs. metriport/metriport#1623
n/a
set final as docStatus if not set by cx
see thread for context: https://metriport.slack.com/archives/C04DMKE9DME/p1707947387359609
triple checked the logic - low risk change

PATCH RELEASE set final as docStatus if not set by cx

---

packages/fhir-converter/src/lib/cda/cda.js
packages/lambdas/src/sqs-to-converter.ts

refs. metriport/metriport#1629
n/a
don't send nonXMLBody C-CDAs to converter
- Local

PATCH RELEASE - don't send nonXMLBody ccdas to converter

---

packages/api/src/external/commonwell/cq-bridge/cq-link-status.ts
packages/api/src/external/commonwell/patient-updater-commonwell.ts
packages/api/src/routes/medical/internal-patient.ts
packages/utils/src/commonwell/enhance-coverage.ts

refs. [metriport/metriport-internal#799](https://github.com/metriport/metriport-internal/issues/1432)
- Updated the `enhance-coverage` script with a call to an internal route that sets cq link status for patients
- Local

fix(api): added set-cq-link-status to enhance-coverage script

---

packages/api/src/external/commonwell/proxy/cw-process-request.ts

Ref: metriport/metriport-internal#1475
Build new `searchParams` on CW proxy instead of updating existing ones.
- Local
- Staging
- none
- Sandbox
- none
- Production

PATCH RELEASE 1475 Fix CW proxy searchParam processing

---

packages/utils/src/customer-requests/convert-html-to-csv.ts

Ticket: #1040
Temporary function to convert fhir to csv - will eventually be optimized but adding to repo to not lose base logic
- Local

fix(ops): convert html to csv

---

fern/generators.yml

This PR flattens the import hierarchy for the Python SDK.

:herb: Remove `resources` from Python SDK imports

---

packages/api/src/external/commonwell/document/document-query.ts

Ticket: #799
Remove return from doc queries in cw if the patient does not exist.

799 PATCH remove return cw no patient

---

packages/api/src/external/carequality/document/get-non-existent-doc-refs.ts
packages/api/src/external/carequality/outbound-document-query-resp.ts
packages/api/src/external/carequality/outbound-document-retrieval-resp.ts

Ref. metriport/metriport-internal#1413
Ticket:1413
Invalid imports from core with src.

fix(api): remove src from import

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-38 Inbound Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-39 Inbound Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA Inbound Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCPD Inbound Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCPD Inbound Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DQ App Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DQ App Interface/DeployScript.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DR App Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DR App Interface/DeployScript.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DR App Interface/PostprocessingScript.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DR App Interface/PreprocessingScript.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DR App Interface/UndeployScript.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA DR ITI-39 Bulk Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-2-Case 2 - Failure.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD App Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD Bulk Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/index.xml

n/a
Route mirth dr response to the api
- Local

fix(ihe): fix mirth dr channel to send message to api

---

packages/api/src/shared/config.ts

none
Fix API env vars names for IHE GW
none

1377 Fix API env vars names for IHE GW

---

packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/external/commonwell/cq-bridge/patient-event-listener.ts
packages/api/src/routes/medical/internal-patient.ts
packages/api/src/routes/medical/patient.ts
packages/ihe-gateway-sdk/src/models/patient-discovery/patient-discovery-responses.ts

none
- Add CQ PD to patient update
- Fix PD response schema
- Local

1350 Add CQ PD to patient update

---

.github/workflows/deploy-production.yml

- Upstream: 
- https://github.com/metriport/metriport/pull/1590
- https://github.com/metriport/metriport-internal/pull/1546
Add `prod` CICD for IHE GW.
- Sandbox
- Production
- set GH vars

1377 prod CICD for IHE GW

---

packages/api/src/external/carequality/organization-template.ts
packages/api/src/shared/config.ts
packages/infra/lib/api-stack/api-service.ts

- Managing organization fix, now correctly referencing Metriport for all our clients
- Local

fix(api): fixed passing incorrect managing org for cq dir registration

---

packages/api/src/external/carequality/organization.ts
packages/api/src/shared/config.ts

- making `getCQOrgUrls` function return `string | undefined` since it's not used on Sandbox. 
- Local

fix(api): allow getCQOrgUrls return undefined

---

packages/api/src/command/webhook/webhook.ts
packages/api/src/external/aws/appConfig.ts

refs. metriport/metriport#1653
- Fixed a bug in sendTestPayload, ensuring that it always returns a boolean
- Local

PATCH RELEASE 2024-02-23

---

packages/api/src/routes/helpers/request-logger.ts

Remove ihe response logs by blacklisting them.
- Local
- Staging
- Production

fix(ihe): remove ihe url response  logs

---

.github/pull_request_template.md
packages/api/src/routes/medical/internal-docs.ts
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor.xml

- upstream: https://github.com/metriport/metriport-internal/pull/1559
- downstream: none
Increase threads on IHE GW outbound XCPD processor
- Staging
- Already manually set on staging

1350 Increase threads on IHE GW outbound XCPD processor

---

packages/api/src/external/aws/appConfig.ts
packages/api/src/external/carequality/command/update-patient-discovery-status.ts
packages/api/src/external/carequality/patient-shared.ts
packages/api/src/external/carequality/patient-updater-carequality.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/external/carequality/process-outbound-patient-discovery-resps.ts
packages/api/src/external/commonwell/patient-updater-commonwell.ts
packages/api/src/routes/medical/internal-patient.ts
packages/core/src/util/race-control.ts

Add an update-all for cq to be able to link all cx's patients to external GW's
- Local
- Staging
- Production

fix(ihe): update all to rediscover cq patients links

---

packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts
packages/api/src/external/carequality/document/shared.ts
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js
packages/ihe-gateway/server/CodeTemplates/Common Library/Write document to AWS S3 bucket/Write document to AWS S3 bucket.js

- Downstream: https://github.com/metriport/metriport-internal/pull/1569
- Added file size calculation on DR and included it on docRef metadata
- Fixed the issue where we overwrote an existing document description with an undefined string during docRef update
- Local
- Staging

feat(api): updated docref metadata handling

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/routes/medical/document.ts
packages/api/src/routes/medical/patient.ts

refs. metriport/metriport-internal#1572
n/a
add cw/cq flags on pt create, update, and dq so HIE functions need to be explicitly specified to be triggered
🏈 

feat(api): add cw/cq flags on pt create, update, and dq

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js

- Upstream:  none
Dont upload docs to s3 if they werent decoded to string properly 
- Production

fix(ihe): dont uploaded undefined string

---

packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts

Update the doc count after the DR - [context](https://metriport.slack.com/archives/C065BLRBUDQ/p1709502119053989)
- Production

fix(ihe): update doc count after retrieval

---

packages/api/src/external/carequality/document/create-outbound-document-query-req.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/query-documents.ts

We are failing the whole thing if we cant find a cq directory orgs, so we want to log and make sure we continue the processes.
- Production

fix(ihe): dont fail if cant find directory org

---

packages/api/src/external/carequality/patient-updater-carequality.ts

Ticket: #1350
Update all not working because we reference initial patient data

fix(ihe): retrieve patient while checking if race complete

---

packages/api/src/external/carequality/command/update-patient-discovery-status.ts
packages/api/src/external/carequality/document/get-non-existent-doc-refs.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/carequality/document/schedule-document-query.ts
packages/api/src/external/carequality/patient-shared.ts
packages/api/src/external/commonwell/cq-bridge/cq-link-status.ts

none
- Wait for PD before DQ - [context](https://metriport.slack.com/archives/C065BLRBUDQ/p1709600814239239?thread_ts=1709570864.511359&cid=C065BLRBUDQ)
- Updated some logging code that I came across so we can follow what happens for a given request
- Local

RELEASE 1350 Wait for PD before DQ

---

.github/workflows/_deploy-cdk-ihe-gw.yml

Ref: metriport/metriport-internal#1350
- Upstream:  https://github.com/metriport/metriport/pull/1707
Add AWS CLI to `_deploy-cdk-ihe-gw.yml`
- Staging
- Production

1350 Add AWS CLI to _deploy-cdk-ihe-gw.yml

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/external/aws/appConfig.ts
packages/api/src/routes/medical/document.ts
packages/api/src/routes/medical/patient.ts
packages/core/src/external/aws/appConfig.ts

n/a
add network standby mode FF
🏈 
add the following app config to prod:
```
"commonwellFeatureFlag": {
"name": "commonwellFeatureFlag"
}
},
"carequalityFeatureFlag": {
"name": "carequalityFeatureFlag"
}
}
...
"commonwellFeatureFlag": {
"enabled": false
},
"carequalityFeatureFlag": {
"enabled": false
},
```
add the following app config to sandbox:
```
"commonwellFeatureFlag": {
"name": "commonwellFeatureFlag"
}
},
"carequalityFeatureFlag": {
"name": "carequalityFeatureFlag"
}
}
...
"commonwellFeatureFlag": {
"enabled": true
},
"carequalityFeatureFlag": {
"enabled": true
},
```
add the following app config to staging:
```
"commonwellFeatureFlag": {
"name": "commonwellFeatureFlag"
}
},
"carequalityFeatureFlag": {
"name": "carequalityFeatureFlag"
}
} …
```

feat(api): add network standby mode FF

---

packages/api/src/external/hie/set-doc-query-progress.ts

Ticket: #1350
Whats happening is every time we update the doc query progress we are loosing the webhookSent boolean because we dont splat the doc query progress types and so it gets overriden.
[Context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1709695936592569?thread_ts=1709670094.144059&cid=C04GEQ1GH9D)
🏈

fix(ihe): splat doc query progress

---

packages/fhir-converter/src/templates/cda/References/DiagnosticReport/assessment.hbs

- b64 encoded text was being wrapped in {{. This means if there are any special chars, they get escaped as html. So if there were equal signs they were becoming html junk. And HAPI doesnt like HTML in fields that are supposed to be strings
- Fixed by wrapping in {{{ braces, which means we dont do any html escaping. This is ok in this instance since we are removing all single quotes from the text by b64ing it. 
- Local

HAPI-1821 Patch

---

packages/api/src/command/medical/document/process-doc-query-webhook.ts
packages/api/src/external/hie/tally-doc-query-progress.ts

Ticket: #1350
Prevent conversion tallys from sending download webhooks. 
My hypothesis is that we are converting faster than we are sending the download webhook leading to webhookSent still being false and conversion tallys are then sending download webhooks
- Production

fix(ihe): prevent conversion sending download webhooks

---

packages/api/src/models/db.ts

none
Don't log sql on staging - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1709869640585319)
- Local
- none
- Staging
- Sandbox
- Production

1040 Don't log sql on staging

---

packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts

Ticket: #1350
Be able to adjust the progress status if we dont receive any results from IHE GW
- Staging
- Production

fix(ihe): handle progress when there are no results

---

packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts

Ticket: #1350
ref: https://github.com/metriport/metriport/pull/1748
Be able to adjust the progress status if we dont receive any results from IHE GW
Check each PR.

RELEASE: handle no results

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js
packages/ihe-gateway/server/CodeTemplates/Common Library/Write document to AWS S3 bucket/Write document to AWS S3 bucket.js

- patching string conversion issues resulting in messed up pdfs and tiffs. Now, we decode b64 from DocumentReference into bytes and dont touch it and then write it back into the file on s3. 
- file size computed without filtering for utf-8, since tiffs and pdfs raw bytes filled with non utf-8
- preserving the fileType determination logic since it seems like it works 
- Local

Patch pdfs tiffs borked

---

packages/api/src/external/carequality/command/cq-directory/search-cq-directory.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/routes/medical/internal-cq.ts

- Searching for nearby orgs for XCPD now only returns orgs with `url_xcpd`
- Removing post-filtering for this ^
- Local

fix(api): cut out extra cycles on the api for xcpd

---

packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts

Ticket: #1350
- Downstream: none 
There are 2 issues being resolved here:
- First if no results are present we set the progresses to completed but dont update the total 
- The second issue is when we tally the total for download progress were only doing so for results that return success doc refs and not the ones that errored leading to a false total.
- Production
Check each PR.

PATCH: set correct doc total

---

packages/api/src/external/carequality/command/update-patient-discovery-status.ts

Ticket: #1350
[Context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1710264483494489?thread_ts=1710262426.705439&cid=C04GEQ1GH9D) - If there is a doc progress scheduled but xcpd fails it stays in progress
- Production

1350 patch xcpd failed doc progresses

---

packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts

Ticket: #1350
- Downstream: none 
[context](https://metriport.slack.com/archives/C04GEQ1GH9D/p1710363087322519) 
- Production

PATCH: add filename to docpath

---

package-lock.json
packages/api/src/command/settings/updateSettings.ts
packages/api/src/command/webhook/webhook.ts
packages/api/src/models/_default.ts
packages/shared/package.json
packages/shared/src/common/__tests__/string.test.ts
packages/shared/src/common/string.ts
packages/shared/src/index.ts

Limit amount of chars on WH error details - [context](https://metriport.slack.com/archives/C0553DYC95L/p1710447978924019).
- Local
- Production

PATCH RELEASE Limit amount of chars on WH error details

---

packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts
packages/api/src/external/fhir/document/save-document-reference.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1561
Add retries when upserting to FHIR
- Local
- Staging
- Production

fix(api): add retries when upserting to fhir

---

packages/infra/config/env-config.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/api-stack/cq-directory-rebuilder.ts

- Upstream: https://github.com/metriport/metriport-internal/pull/1623
- Added a scheduled lambda to rebuild the CQ directory in Prod on a daily basis (at 10pm)
- Staging

1350 scheduled directory rebuilder

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-38 Inbound Interface/sourceConnector-transformer-step-4-get-query-parameters.js

- regex on xml to remove namespaces was removing more than the namespace, causing invalid xml 
- added logic to get msgId from the header if it doesnt exist where its supposed to be in the body too 
- Local

Patching Regex Issues on Inbound DQ

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-38 Inbound Interface/sourceConnector-transformer-step-4-get-query-parameters.js
packages/ihe-gateway/server/CodeTemplates/XCA Library - Inbound/Process XCA ITI-38 AdhocQueryRequest/Process XCA ITI-38 AdhocQueryRequest.js

- Inbound DQs errored because we weren't replacing all namespaces, and so the AdHocQuery slots werent getting pulled into the lambda request, so the lambda request was missing the patientID, and it was throwing errors. 
- the patient Id also had a newline infront of it causing other errors. 
- [context](https://metriport.slack.com/archives/C04T256DQPQ/p1710977023609959)
- Local

Missing Namespace on Inbound DQ

---

packages/api/src/external/fhir/document/index.ts
packages/api/src/external/fhir/document/search-documents.ts

Ticket: https://github.com/metriport/metriport-internal/issues/1631
none
- Filter out not ready docrefs
- Local

PATCH RELEASE 1631 Filter out not ready docrefs

---

packages/api/src/external/commonwell/patient-loader-local.ts
packages/api/src/sequelize/migrations/2024-03-19_00_alter-patient-add-index-dob-gender.ts
packages/infra/lib/api-stack.ts
packages/infra/lib/ihe-stack/ihe-db-construct.ts

none
- Add index on patient DOB
- Add access log to API GW
- Set param group on DB instances too (was only setting on the cluster)
Amount of records on patient table: `200,025` records
Query
```sql
SELECT "id", "created_at" AS "createdAt", "updated_at" AS "updatedAt", "version", "cx_id" AS "cxId",
"facility_ids" AS "facilityIds", "external_id" AS "externalId", "data", "created_at", "updated_at" 
FROM "patient" AS "PatientModel" WHERE (data->>'dob' = '1999-10-30');
```
Without index
With index
- Local
- Staging
- Sandbox
- Production

1350 Add index on patient DOB

---

packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts
packages/api/src/routes/medical/internal-cq.ts
packages/core/src/external/carequality/ihe-gateway/poll-outbound-results.ts
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD App Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor.xml
packages/infra/dashboards/cw-dashboard-prod.json
packages/infra/lib/api-stack.ts
packages/infra/lib/ihe-stack/ihe-gw-construct.ts

none
- decrease the num of outbound threads on IHE GW 
- increase the timeout of the IHE GW LB
- improve error handling/log on pooling for IHE GW results
- Local
- none
- Staging
- Sandbox
- none
- Production

1350 Tweaks to IHE GW and its outbound Lambdas

---

packages/api/src/external/carequality/command/outbound-resp/get-outbound-patient-discovery-resp.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/external/carequality/process-subsequent-outbound-patient-discovery-resps.ts
packages/api/src/routes/medical/internal-cq.ts

Ticket: #1350
Process the subsequent request again if the discoveryStstus was completed so we  dont lose links
- Local
- Staging
- Production

fix(api): process subsequent pd results

---

packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/external/carequality/command/cq-directory/cq-gateways.ts
packages/api/src/external/carequality/command/cq-directory/get-organizations-for-xcpd.ts
packages/api/src/external/commonwell/admin/patch-patient-duplicates.ts
packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
packages/api/src/external/commonwell/cq-bridge/coverage-enhancer-api-local.ts
packages/api/src/external/commonwell/cq-bridge/coverage-enhancer-factory.ts
packages/api/src/external/commonwell/link/create.ts
packages/api/src/external/commonwell/link/shared.ts
packages/api/src/external/commonwell/patient-updater-commonwell.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/routes/medical/internal-patient.ts

Refs: #[1608](https://github.com/metriport/metriport-internal/issues/1608)
- filter out duplicates with fast DB lookups of CQ directory entries using the id index + downgrading links
- prod

Downgrading CW CQ Duplicates

---

packages/api/src/external/carequality/document/process-outbound-document-retrieval-resps.ts

Ticket: #1350
There is an issue where if we set the conversion progress before the doc retrieval to a certain # but then we dont receive any successful doc entries then since we only change if it has at least one it will stay at the previous #. Now if its 0 we set the total to 0 and mark complete. - [context](https://metriport.slack.com/archives/C04T256DQPQ/p1711459850269839)
- Local
- Staging
- Production

fix(api): set convert 0 if no succ docs

---

packages/api/src/external/commonwell/document/document-query-sandbox.ts
packages/api/src/external/commonwell/document/document-query.ts

Ticket: #1350
In sandbox mode do not check if cw is enabled
- Sandbox

PATCH in sandbox no interrupt

---

packages/ihe-gateway/server/CodeTemplates/XCPD Library - Inbound/Generate HL7v3 Subject from FHIR Patient /Generate HL7v3 Subject from FHIR Patient .js

- every single date we have been returning on inbound patient discovery has been missing the last digit and wrong 🤯 . there are 10 values in a string, and substring(start,end) is exclusive so it misses the 10th digit if we just index (0,9)
- Local
Check each PR.

Patch datetime inbound

---

packages/api/src/command/medical/hie.ts
packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/command/medical/patient/update-patient.ts
packages/api/src/external/carequality/command/cq-directory/cq-gateways.ts
packages/api/src/external/carequality/command/cq-directory/create-cq-directory-entry.ts
packages/api/src/external/carequality/command/cq-directory/get-organizations-for-xcpd.ts
packages/api/src/external/carequality/command/cq-directory/parse-cq-directory-entry.ts
packages/api/src/external/carequality/command/cq-directory/rebuild-cq-directory.ts
packages/api/src/external/commonwell/admin/patch-patient-duplicates.ts
packages/api/src/external/commonwell/admin/recreate-patients-at-hies.ts
packages/api/src/external/commonwell/cq-bridge/coverage-enhancer-api-local.ts
packages/api/src/external/commonwell/cq-bridge/coverage-enhancer-factory.ts
packages/api/src/external/commonwell/index.ts
packages/api/src/external/commonwell/link/create.ts
packages/api/src/external/commonwell/link/get.ts
packages/api/src/external/commonwell/link/reset.ts
packages/api/src/external/commonwell/link/shared.ts
packages/api/src/external/commonwell/patient-updater-commonwell.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/routes/medical/internal-cq.ts
packages/api/src/routes/medical/internal-patient.ts
packages/core/src/external/carequality/ihe-gateway/poll-outbound-results.ts
packages/core/src/external/carequality/pd/get-xcpd-statistics.ts
packages/core/src/util/sequelize.ts

Ref. metriport/metriport-internal#1608
- Upstream: https://github.com/metriport/metriport/pull/1801
- Adjust how we determine/obtain CQ exclude IDs for CW network links
- Fix CQ directory table to keep its structure across rebuilds
- Move get orgs to exclude to be awaited on CW code
- Refactor CW commands so we can use VSCode's `find all references`
Follow up ticket to load the list of CQ org ids in memory: https://github.com/metriport/metriport-internal/issues/1640
- Local
- Staging
- none
- Sandbox
- none
- Production

1608 Adjust how we filter CQ orgs to filter CW links

---

packages/api/src/command/medical/patient/delete-patient.ts
packages/api/src/routes/medical/internal-patient.ts
packages/api/src/routes/medical/patient.ts

Ticket: #[1643](https://github.com/metriport/metriport-internal/issues/1643)
- patient deletion hasn't been working for months? Delete patient always gets passed an empty allEnvs before which means the patient deletion never happens: https://github.com/metriport/metriport/blob/61e55d5885d22000f74328cb88883b81c5f30428/packages/api/src/command/medical/patient/delete-patient.ts#L24
- Local

1643 delete patient

---

packages/api/src/command/medical/document/document-query.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/commonwell/patient-external-data.ts
packages/api/src/external/commonwell/patient-shared.ts
packages/api/src/external/commonwell/patient.ts
packages/api/src/external/hie/schedule-document-query.ts

- Upstream:  none
- Downstream: none 
Trigger a scheduled doc query for when a patient does not have CW data
- Local
- Staging
- Production

fix(api): trigger schedule query no cw links

---

packages/api/src/external/commonwell/document/document-query.ts

Ticket: #1350
- Upstream: https://github.com/metriport/metriport/pull/1821
Left over from upstream PR needed to call doc query progress before schedule doc query
- Local
- Staging
- Production

fix(api): add download progress before schedule doc query

---

packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/commonwell/document/document-query.ts
packages/api/src/external/hie/reset-doc-query-progress.ts

Ticket: #1350
- Upstream: NONE
- Downstream: NONE
Only reset overall doc progress when explicitly passing medicaldatasource all
- Production
- [] monitor logs

PATCH reset only source doc progress

---

packages/api/src/external/commonwell/organization.ts
packages/api/src/routes/internal.ts
packages/utils/src/bulk-insert-patients.ts

- Guardrails on bulk insert
- Don't init CW CQ bridge if EC is not enabled for cx - [context](https://metriport.slack.com/archives/C04DMKE9DME/p1711587454137239)
- Local
- Staging
- none
- Sandbox
- none
- Production
- none

PATCH RELEASE Guardrails on bulk insert

---

packages/core/src/external/carequality/dq/create-metadata-xml.ts

- explicitly adding namespace 
- Local

Explicit Namespace Declaration for Extrinsic Object

---

packages/infra/lib/ihe-stack/ihe-gateway.ts

- misnamed path in cdk. doesnt match CQ directory 🤯

Document Retrieve Wrong URL

---

packages/ihe-gateway/server/CodeTemplates/XCA Library - Inbound/Get XCA ITI-39 RetrieveDocumentSetResponse/Get XCA ITI-39 RetrieveDocumentSetResponse.js

- allow MTOM, but we still respond with regular SOAP
- Local

Allow MTOM on Inbound DR

---

packages/api/src/external/aws/appConfig.ts
packages/core/src/external/aws/appConfig.ts
packages/lambdas/src/fhir-to-medical-record.ts

Simplify FFs. Currently, there's an unnecessary structure of types on the FFs' payload, and a distinction on how we name the property that holds each FF value.
I propose we:
- remove the types from the payload
- have all props to store the value named the same
- Local
- none
- Staging
- Sandbox
- Production
- none

1040 Simplify FFs

---

packages/api/src/command/medical/mapi-access.ts
packages/api/src/routes/internal.ts
packages/utils/package.json
packages/utils/src/make-uuidv7.ts

none
- Add endpoint to get MAPI access.
- Add cli/terminal util to generate UUIDv7
- Local
- Staging
- Sandbox
- none
- Production

1040 Add endpoint to get MAPI access

---

packages/api/src/command/medical/patient/__tests__/append-doc-query-progress.test.ts
packages/api/src/external/carequality/document/process-outbound-document-query-resps.ts
packages/api/src/external/carequality/document/query-documents.ts
packages/api/src/external/hie/__tests__/doc-progress-tests.ts
packages/api/src/external/hie/__tests__/set-doc-query-progress.test.ts
packages/api/src/external/hie/reset-doc-query-progress.ts
packages/api/src/external/hie/set-doc-query-progress.ts
packages/api/src/external/hie/tally-doc-query-progress.ts

2 things fixed:
- When a cx source gets reset and the other source is empty then it wont aggregate the data cause they both are empty
- If we set to processing but then dont download the data then it will be stuck in processing 
- Local
- Staging
- Production

fix(api): doc query stuck processing

---

packages/api/src/external/commonwell/patient.ts

Issue because of the scheduled doc query in CW because when we go to create the patient in CW we have data just not personId so when we go to update its undefined. -[context](https://metriport-inc.sentry.io/issues/4973939488/?alert_rule_id=14031186&alert_type=issue&environment=production&notification_uuid=4aa3c9c8-77f9-4540-92ac-d69e961ec3a0&project=4504912884924416&referrer=slack)
- Production

fix(api): create patient if cw or patient id doesnt exist

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-39 Inbound Interface/destinationConnector-AWS Lambda Interface-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/CodeTemplates/Common Library/Get SOAP Template or Fault message/Get SOAP Template or Fault message.js
packages/ihe-gateway/server/CodeTemplates/XCA Library - Inbound/Get XCA ITI-39 RetrieveDocumentSetResponse/Get XCA ITI-39 RetrieveDocumentSetResponse.js

- invalid xml due to missing namespace in soap body 
- Local

Adding Namespace to Soap Body

---

packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/external/carequality/patient.ts

PD processing sometimes happens after DQ has been started. Need to set it as early as possible.  - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1711741669809139)
- Production

PATCH cq pd processing

---

packages/api/src/command/medical/patient/create-patient.ts
packages/api/src/external/carequality/patient.ts
packages/api/src/external/carequality/shared.ts

revet cw to original state and make CQ async
Check each PR.

fix(api): revert cw back to normal patient create

---

packages/api/src/external/carequality/document/shared.ts

Add creation date to docRef
- Local
- Staging
- Production

PATCH add creation date to docref

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-38 Inbound Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCA ITI-39 Inbound Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Inbound/XCPD Inbound Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DQ App Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA - DR App Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA DQ ITI-38 Bulk Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA DR ITI-39 Bulk Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-1-Case 1 - Success or PartialSuccess.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD App Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD Bulk Interface.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor.xml
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD Interface.xml

none
[context](https://metriport.slack.com/archives/C065BLRBUDQ/p1711733711543549?thread_ts=1711643420.367249&cid=C065BLRBUDQ)
- save some memory/operations on ihe gw outbound code 
- adjust IHE GW channels data retention
- Local
- Staging
- Sandbox
- none
- Production
- just monitor the operation for a while

1350 IHE GW memory management

---

packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-0-Process response.js

- hardcoded looking for fault caused patients with name "fault" to not get processed. Logic was unnessecary fully anyway so just nixing it entirely 

Fault hardcoded issue

---

packages/api/src/external/carequality/document/shared.ts
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-38 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCA ITI-39 Processor/destinationConnector-XCA Endpoint-responseTransformer-step-0-Process response.js
packages/ihe-gateway/server/Channels/CareQuality Document Exchange - Outbound/XCPD ITI-55 Processor/destinationConnector-XCPD Endpoint-responseTransformer-step-0-Process response.js

Ticket: https://github.com/metriport/metriport/pull/1350
- related: https://github.com/metriport/metriport/pull/1859
Merge `master` into `develop` and fix conflicts.
Since `soap` was only used to string search, removing it to save some memory. :) Tested local and it works, `msg` is the actual XML.
- Local
- Staging
- Sandbox
- none
- Production
- none

1040 merge master into develop

---

packages/api/src/external/commonwell/patient-external-data.ts

Current way of setting CW data overrides all previous values. This way we do not ovveride leading to progress not being present when scheduling doc query.
- Production

PATCH pd cw processing

---

packages/api/src/external/commonwell/organization.ts
packages/core/src/external/commonwell/management/api-impl.ts

none
Move some logs to out.log and remove some multi-line logs.
- Local
- none
- Staging
- CW Integration is down
- Sandbox
- CW Integration is down
- Production

1040 Move some logs to out.log and remove multi-lines
